In [1]:
import torch
from torch.nn import *
import torch.nn.functional as F
from pandas_datareader import data as web
import os
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from diebold_mariano import diebold_mariano_test

In [2]:
from utils import *

DEVICE:  cuda

In [3]:
T=30

In [4]:
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib

# Set consistent style for publication-quality plots
sns.set(style="whitegrid", context="talk", palette="colorblind")
matplotlib.rcParams.update({
    "axes.titlesize": 18,
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "legend.fontsize": 10,
    "legend.frameon": True,
    "axes.titleweight": "bold"
})

def customize_ax(ax, title=None, xlabel=None, ylabel=None):
    if title:
        ax.set_title(title, fontsize=20, fontweight="bold")
    if xlabel:
        ax.set_xlabel(xlabel, fontsize=12)
    if ylabel:
        ax.set_ylabel(ylabel, fontsize=12)
    ax.tick_params(axis='both', which='major', labelsize=10)
    ax.grid(False)
    if ax.get_legend():
        ax.legend(fontsize=10, frameon=True)

# Insert your original loop code here afterward, using customize_ax() and matplotlib.rcParams updates
# on all relevant plots to ensure publication-quality formatting.

In [5]:
etfs = ['SPY','XLB','XLE','XLF','XLI','XLK','XLP','XLV','XLY','XLU']
metric2 = "SD_Squared_Returns"
metric3 = "MAD_Returns"
metric4 = "IQR"
metric5 = "SD_Returns"
metrics = ["ATR",metric3,metric4,metric5]
# start = '2001-01-01'
# end = '2020-01-01'
# start_t = '2022-01-02'
# end_t = '2024-01-05'
date_list = [['2023-01-05', '2024-01-05', "2024-01-05", "2025-01-05"], ['2019-01-05', '2024-01-05', "2024-01-05", "2025-01-05"], ['2014-01-05', "2024-01-05", "2024-01-05", "2025-01-05"], ['2004-01-05', '2024-01-05', "2024-01-05", "2025-01-05"], ['1994-01-05', '2024-01-05', "2024-01-05", "2025-01-05"]]
starts,ends = np.array([(f'200{i}-01-01',f'200{i+12}-01-01') for i in range(0,12,4)]).T
models = {}
lrs = [0]
h1 = 50
h2 = 50
hl1s = [20,50,70,100]
hl1s = [20,50,70,100]
models = ["LSTM","RNN"]
b_types = ['ATR' ,'STD']
lr = 0
a_s = np.linspace(1,2,5)
b_s = np.linspace(1,2,5)
A,B = np.meshgrid(a_s,b_s)
pairs = np.column_stack([A.ravel(), B.ravel()])
feat_combos = [['Open','Close','High','Low','Volume','Return','Short_MA','Long_MA'],['Open','Close','High','Low','Volume'],['index','Open','Close','High','Low','Volume']]
sells = np.linspace(1,2,6)
buys = np.linspace(1,2,6)
factors = np.stack((sells,buys),axis=-1)
ini_money=100

In [ ]:
num=30000
for file in os.listdir('../output'):
    if "runtest" in file:
        num+=1
os.mkdir(f'../output/runtest_{num}')
for d,(start,end,start_t,end_t) in enumerate(date_list):
    os.mkdir(f'../output/runtest_{num}/date_config{d}')
    for model_type in models:
        os.mkdir(f'../output/runtest_{num}/date_config{d}/{model_type}')
        root = f'../output/runtest_{num}/date_config{d}/{model_type}'
        with open(os.path.join(root,'run_data.txt'),'w') as f:
            f.write(f'Start Training Date: {start} \n End Training Date: {end} \n Start Sim Date: {start_t} \n End Sim Date: {end_t} \n')
            f.write(f'\n Model Type: {model_type}')
            f.write(f'Look-back window: {T} days')

        for etf in etfs:
            os.mkdir(f'{root}/{etf}')
        for lr in lrs:
            results = pd.DataFrame({"ETF":[],"Metric":[],"Final_Value":[],"Passive_Potential":[],"Relative_MSE":[],"MAPE":[],"DM_stat":[],"DM_p":[]})
            money_df_std = pd.DataFrame()
            money_df_atr = pd.DataFrame()
            money_df_sd_prices = pd.DataFrame()
            money_df_iqr = pd.DataFrame()
            money_df_passive = pd.DataFrame()
            for j,etf in enumerate(etfs):
                #fig,ax = plt.subplots(1,len(metrics),figsize=(26,6))
                fig,ax = plt.subplots(2,2,figsize=(12,9))
                atr_preds = []
                for i,metric in enumerate(metrics):
                    scaler = StandardScaler()
                    scaler_x = StandardScaler()
                    df = get_cleaned_df(etf,start,end)
                    #print(df)
                    model,fig_tr,fig_te = get_trained_model(df,scaler, scaler_x, metric=metric,model_type=model_type)
                    fig_tr.savefig(os.path.join(root,etf,f'training_results_{metric}'))
                    fig_te.savefig(os.path.join(root,etf,f'testing_results_{metric}'))
                    df_test = get_cleaned_df(etf,start_t,end_t)
                    ini_cash = 10000
                    result_best = backtest_strategy_mr(df_test,model,scaler,scaler_x,metric,sell_scale=factors[0][0],buy_scale=factors[0][1],ini_cash=ini_money,buy_max=50)
                    max_val = result_best[0]
                    a_best,b_best = factors[0]
                    for a,b in factors[1:]:
                        res = backtest_strategy_mr(df_test,model,scaler,scaler_x,metric,sell_scale=a,buy_scale=b,ini_cash=ini_money,buy_max=50)
                        if res[0]>max_val:
                            max_val = res[0]
                            result_best = res
                            a_best,b_best = a,b
                    final_value, money, shares,passive_value,buy_points,sell_points,preds, t_money,p_money,lowers,uppers,vols = result_best
                    fig_vol,ax_vol = plt.subplots(figsize=(10,5))
                    sns.lineplot(x = range(0,len(df_test.index)-(T+1)),y=lowers,color = 'blue',ax=ax_vol,label = "Buy")
                    sns.lineplot(x = range(0,len(df_test.index)-(T+1)),y=uppers,color = 'red',ax=ax_vol,label="Sell")
                    sns.lineplot(x = range(0,len(df_test.index)-(T+1)),y=vols,color = 'black',ax=ax_vol,label=f"{metric}")
                    ax_vol.set_title(f"Predicted {metric} and Buy/Sell Signals | a={a_best}, b={b_best}")
                    ax_vol.set_ylabel(f"{metric}")
                    ax_vol.set_xlabel(f"Days after {start_t}")
                    for buy in buy_points:
                        ax_vol.axvline(buy,color = 'Orange',alpha=.5,)
                    for sell in sell_points:
                        ax_vol.axvline(sell,color='Purple',alpha=.5,)
                    #ax_vol.legend()
                    customize_ax(ax_vol)
                    
                    fig_vol.tight_layout()
                    fig_vol.savefig(os.path.join(root,etf,f'{metric}_signals.png'))
                    

                    print(f"{etf} Final Value: {final_value}, Final Money: {money}, Final Shares: {shares}")
                    
                    real_met = np.array(df_test[metric].iloc[T:len(df_test)-1])
                    atr_met = np.array(df_test["ATR"].iloc[T:len(df_test)-1])
                    null_model_error = np.sum((real_met-real_met.mean())**2)
                    mse_error = 1/len(real_met) * np.sum((real_met-preds)**2)/null_model_error
                    mape_error = 1/len(real_met) * np.sum(abs(real_met-preds)/(real_met+1e-8))
                    if metric=="ATR": #atr should go first
                        money_df_atr[etf] = t_money
                        atr_preds = preds
                    elif metric==metric3:
                        money_df_std[etf] = t_money
                        money_df_passive[f"{etf}_Passive"] = p_money
                    elif metric == metric5:
                        money_df_sd_prices[etf] = t_money
                    elif metric == metric4:
                        money_df_iqr[etf] = t_money

                    dm,p = diebold_mariano_test(atr_met,atr_preds,real_met,preds,loss="mae")
                    results.loc[len(results)] = [etf,metric,final_value,passive_value,mse_error,mape_error,dm,p]

                    sns.lineplot(preds,ax=ax[i//2][i%2],label=f"Prediction {metric}",color="Blue",linestyle = '--')
                    sns.lineplot(real_met,ax=ax[i//2][i%2],label = f"True {metric}",color="Orange")
                    sns.despine(ax=ax[i//2][i%2])
                    #for buy in buy_points:
                        #ax[i].axvline(buy,color="Green",alpha=.6)
                    #for sell in sell_points:
                        #ax[i].axvline(sell,color="Red",alpha=.6)
                    ax[i//2][i%2].set_title(f"{etf} - {metric} ",fontsize = 20)
                    ax[i//2][i%2].set_xlabel(f'Total MSE Error {mse_error:.6f} | Total MAPE Error: {mape_error:.3f}')
                    customize_ax(ax[i//2][i%2])
                    #plt.title(f"Performance of LSTM on {etf}")
                fig.supylabel("Volatility Metric")
                fig.supxlabel(f"Days after {start_t}")
                fig.tight_layout()
                fig.savefig(os.path.join(root,etf,'predictions.png'))
                fig_sim,ax_sim = plt.subplots(figsize=(10,6))
                sns.lineplot(x=range(0, len(df_test.index)-(T+1)), y=money_df_atr[etf], label="ATR",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_std[etf],label="SD_Returns",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_sd_prices[etf],label="MAD_Returns",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_passive[f"{etf}_Passive"],label="Passive",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_iqr[etf],label="IQR",ax=ax_sim,palette = 'colorblind')
                sns.despine(ax=ax_sim)
                ax_sim.axhline(ini_money, label = "Initial",color="Black")
                ax_sim.set_xlabel(f"Days after {start_t}")
                ax_sim.set_ylabel(f"Value ($)")
                ax_sim.set_title(f"ETF Performance Over Time for {etf}")
                customize_ax(ax_sim)
                ax_sim.legend(
                    loc='upper left',              # anchor the legend’s corner
                    bbox_to_anchor=(1.02, 1.0),     # (x, y) in axes fraction coordinates
                    borderaxespad=0
                )
                fig_sim.tight_layout()
                fig_sim.savefig(os.path.join(root,etf,'simulation_perf_lr_{lr}'))
                
            fig2,ax2 = plt.subplots(figsize = (8,6))
            sns.barplot(data=results,x="ETF",y="Final_Value",hue="Metric",ax=ax2,palette='colorblind') 
            sns.despine(ax=ax2)   
            plt.legend(loc=(1.1,1))
            fig2.tight_layout()
            customize_ax(ax2)
            fig2.savefig(os.path.join(root,'return_metrics_lr_{lr}.png'))
            results.to_csv(os.path.join(root,'overall_results.csv'),index=False)

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17825237578963055 shares for $106.16889754406185
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 60th day, sold 0.09575609008732956 shares for $48.916998621112306
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09554748710108925 shares for $52.99541372061915
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.174860422392223 shares for $104.59975607080388
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 60th day, sold 0.09636882275846118 shares for $49.230013106159895
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09437879874664956 shares for $52.34720072482918
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17463810735127167 shares for $104.46676943645721
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.1884769619505038 shares for $104.53874694584694
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17582727512007773 shares for $105.17811770407931
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.08226254915187313 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.16468103726712713 shares for $99.02270770872353
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 129th day, sold 0.18867154268899677 shares for $104.48252691031263
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 206th day, sold 0.1759511625304509 shares for $105.25222591409043
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.08226254915187313 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.16468103726712713 shares for $99.02929495021424
On the 225th day, Bought 0.08226254915187313 shares for $50.0
On the 238th day, sold 0.08226254915187313 shares for $49.46776130698739
SPY Final Value: 108.7640477746173, Final Money: 108.7640477746173, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 171th day, Bought 0.08798944126704795 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17555818272909568 shares for $104.56420921527668
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1658128640371508 shares for $98.60725211425321
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.174860422392223 shares for $104.14861618103194
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1656259923094319 shares for $98.49612136649607
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17463810735127167 shares for $104.01620311949092
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 236th day, sold 0.16507664932143729 shares for $98.16943258496555
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.1884769619505038 shares for $104.53874694584694
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 200th day, Bought 0.08792909397861565 shares for $50.0
On the 206th day, sold 0.17413450423016302 shares for $104.16551908544123
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.18867154268899677 shares for $104.64667115245206
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 200th day, Bought 0.08792909397861565 shares for $50.0
On the 206th day, sold 0.17413450423016302 shares for $104.16551908544123

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.81219023789329, Final Money: 108.81219023789329, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0

On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.17825237578963055 shares for $104.4113291187761
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.166739304078092 shares for $97.72590612016972
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1759511625304509 shares for $103.12497635909727
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.17531915484379426 shares for $103.63991838590897
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09457337948514251 shares for $52.45512493143429
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.17334678853326455 shares for $102.47395404143933
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 85th day, Bought 0.09443762394938142 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09443762394938142 shares for $52.379828123524405
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16970156107899426 shares for $100.31907783184745
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.09436989222958307 shares for $50.0
On the 128th day, sold 0.1884680554334373 shares for $104.533806946156
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 105.4630324050886, Final Money: 105.4630324050886, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 60th day, sold 0.09759906304899474 shares for $49.85848135857896
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 151th day, Bought 0.08989248858365395 shares for $50.0
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17883988509335813 shares for $103.13696173333965
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17810733160127143 shares for $102.71449813445324
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 236th day, sold 0.1656259923094319 shares for $98.49612136649607
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1785952662739861 shares for $102.99589006020778
On the 35th day, Bought 0.09712321050484646 shares for $50.0
On the 60th day, sold 0.09712321050484646 shares for $49.61539208640082
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1791071512121006 shares for $103.29109410401843
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 127th day, sold 0.1896456503049435 shares for $104.11356556091094
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
SPY Final Value: 109.21052016948828, Final Money: 109.21052016948828, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0915254873792657 shares for $99.63444648797937
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5343593031954686 shares for $48.428983648605325
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 128th day, sold 0.5442473059758354 shares for $49.205398933275276
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.524824183898394 shares for $47.90595150624541
On the 216th day, Bought 0.5314061005420342 shares for $50.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 229th day, sold 0.5314061005420342 shares for $47.82654904878308
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 128th day, sold 0.5433010974682169 shares for $49.119852222101485
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 229th day, sold 0.5214308061320263 shares for $46.92877255188237
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 128th day, sold 0.5433010974682169 shares for $49.119852222101485
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 229th day, sold 0.5214308061320263 shares for $46.92877255188237
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 128th day, sold 0.5472255663784612 shares for $49.47466345627667
On the 217th day, Bought 0.5259835893120135 shares for $50.00000000000001
On the 230th day, sold 0.5259835893120135 shares for $46.93351567431097

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5614823133071308 shares for $50.02245929253229
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5565449688334817 shares for $51.10752448797862
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1009008637772286 shares for $99.96179843097235
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 175th day, sold 1.0634936048222658 shares for $103.2545940921938
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 214th day, Bought 0.540891389009087 shares for $50.0
On the 217th day, sold 0.540891389009087 shares for $51.417135439203804
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0766472958632796 shares for $91.59038545908919
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5663797009515179 shares for $50.458767557770734
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 0.5471656817684395 shares for $49.78660538411031
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.113275845127881 shares for $101.21903983902695
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.1009008637772286 shares for $106.699311717289
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0766472958632796 shares for $91.59038545908919
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.1186549041658311 shares for $101.70810388675737
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0766472958632796 shares for $91.59038545908919
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.1186549041658311 shares for $101.70810388675737
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 211th day, sold 1.0554195515497262 shares for $96.33869666545901
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.0858983825750537 shares for $92.87688866164434
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 127th day, sold 1.1197107302364473 shares for $100.89713390160627
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 211th day, sold 1.0554195515497262 shares for $96.33869666545901
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.0938814610365155 shares for $93.55968136245318
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.0701677765922009 shares for $91.39232812097396
XLB Final Value: 97.37486764560674, Final Money: 97.37486764560674, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5663797009515179 shares for $50.458767557770734
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 1.0844228128268467 shares for $97.28357053869641
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.5451968160505943 shares for $52.93315887035221
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 202th day, sold 1.0523015578016246 shares for $98.43228771676397
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 240th day, sold 1.0938814610365155 shares for $91.66726643486
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.5253756435851634 shares for $47.956288746453716
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5497526113249038 shares for $45.74491478834524
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 216th day, sold 0.5269259142164612 shares for $49.57845926862684
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5497526113249038 shares for $45.74491478834524
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.5269259142164612 shares for $50.0895774054168
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5603496581867085 shares for $46.626695057716006
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.0563065388855981 shares for $100.41249958646496
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.1257047011536918 shares for $93.66988818299869
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.0554195515497262 shares for $87.82146088445272

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 96.61034976820673, Final Money: 96.61034976820673, Final Shares: 0.0
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0634936048222658 shares for $98.5645872949276
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0766472958632796 shares for $91.59038545908919
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.1197107302364473 shares for $101.80409959309779
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0966471303772733 shares for $100.80380422427896
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0766472958632796 shares for $91.59038545908919
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.1197107302364473 shares for $101.80409959309779
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0966471303772733 shares for $100.80380422427896
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0858983825750537 shares for $92.3773754056598
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 127th day, sold 1.1197107302364473 shares for $100.89713390160627
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 184th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0915254873792657 shares for $100.33302279990211
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0881392947121558 shares for $92.56800980116309
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 128th day, sold 0.5577867023650156 shares for $50.429495760821055
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 139th day, sold 0.5659950192438307 shares for $50.07923930269414
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1072492552135054 shares for $94.1936941410129
XLB Final Value: 95.14941777861725, Final Money: 95.14941777861725, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5804504295333178 shares for $55.27629440445786
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.067180811577654 shares for $96.41978632604103
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0969123538573196 shares for $99.09506204747025
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 163th day, sold 1.1127929289957883 shares for $94.74318997470142
On the 170th day, Bought 0.5620503597122303 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5620503597122303 shares for $49.00517086330936
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5567308762943993 shares for $46.38681661284935
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 61th day, sold 0.5804504295333178 shares for $55.27629440445786
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.0679201308875026 shares for $96.48658382568586
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.0969123538573196 shares for $100.80624531948767
On the 170th day, Bought 0.5620503597122303 shares for $50.0
On the 171th day, Bought 0.5633168093735916 shares for $49.99999999999999
On the 176th day, sold 1.125367169085822 shares for $98.12076347259281
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1137718192470587 shares for $92.79946797966493
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 61th day, sold 0.5804504295333178 shares for $55.27629440445786
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.0679201308875026 shares for $98.1418600285615
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 234th day, sold 1.117517062787762 shares for $93.11152167147632
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 62th day, sold 0.5804504295333178 shares for $54.794520547945204
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 137th day, sold 1.0679201308875026 shares for $94.40413957045523
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 62th day, sold 0.5804504295333178 shares for $54.794520547945204
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 137th day, sold 1.0679201308875026 shares for $94.40413957045523
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 62th day, sold 0.5804504295333178 shares for $54.794520547945204
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 137th day, sold 1.0679201308875026 shares for $94.40413957045523

[*********************100%***********************]  1 of 1 completed

On the 242th day, Bought 0.5769674590353104 shares for $50.0
XLE Final Value: 100.25516256995309, Final Money: 49.19866011840044, Final Shares: 0.5837030119075415
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.5804504295333178 shares for $56.36173670768516
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.067180811577654 shares for $96.85733045878789
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.10678001975448 shares for $101.71308381543672
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 163th day, sold 0.5638249887235002 shares for $48.004059539918806
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0877965532433165 shares for $90.63520881623312
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 53th day, sold 0.5804504295333178 shares for $56.36173670768516
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.067180811577654 shares for $96.85733045878789
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.094935722669386 shares for $100.62459291331659
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0877965532433165 shares for $90.63520881623312
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5567308762943993 shares for $46.38681661284935
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 235th day, sold 0.5569789461958338 shares for $46.86420853291745
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 96th day, sold 0.5343022013250694 shares for $48.028424877110496

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 98.0284248771105, Final Money: 98.0284248771105, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 39th day, Bought 0.5533421868083223 shares for $50.0
On the 57th day, sold 0.5533421868083223 shares for $53.94532979194334
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 99th day, Bought 0.55561729081009 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 133th day, sold 0.55561729081009 shares for $50.78342038004223
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 160th day, sold 1.1127929289957883 shares for $96.92426411553315
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 209th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5538325210456357 shares for $49.98338502436862
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 91th day, Bought 0.5416531253385332 shares for $50.0
On the 96th day, sold 0.5416531253385332 shares for $48.689199436680745
On the 99th day, Bought 0.55561729081009 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.55561729081009 shares for $49.116568507611966
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5538325210456357 shares for $49.98338502436862
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 105th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.1193739853852889 shares for $96.76988103655823
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5538325210456357 shares for $49.98338502436862
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.1193739853852889 shares for $96.76988103655823
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5538325210456357 shares for $50.06645990252547
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.0996959283617667 shares for $95.06871300687473
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5567308762943993 shares for $50.3284712170137
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.5514503143266791 shares for $47.67287967354141
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5567308762943993 shares for $46.843335931410756

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 98.09908351918355, Final Money: 47.63173987736495, Final Shares: 0.5769674590353104
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.5804504295333178 shares for $56.36173670768516
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.067180811577654 shares for $96.85733045878789
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.1222322636675321 shares for $103.13314503104621
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 163th day, sold 1.1127929289957883 shares for $94.74318997470142
On the 169th day, Bought 0.5687635081333182 shares for $50.0
On the 170th day, Bought 0.5620503597122303 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1308138678455486 shares for $99.28545759683917
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.117517062787762 shares for $93.11152167147632
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.5804504295333178 shares for $56.36173670768516
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.067180811577654 shares for $96.85733045878789
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1222322636675321 shares for $103.45859238750978
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 234th day, sold 1.1297548743332761 shares for $94.13117612944856
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.5804504295333178 shares for $56.326909681913165
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1316215290067495 shares for $104.32418875913224
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 61th day, sold 0.5804504295333178 shares for $55.27629440445786
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 96th day, sold 0.5343022013250694 shares for $48.028424877110496
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 96th day, sold 0.5343022013250694 shares for $48.028424877110496
XLE Final Value: 108.10382768713201, Final Money: 6.579981593760749, Final Shares: 1.160670470942852

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 80th day, Bought 1.1953143676786995 shares for $50.0
On the 88th day, Bought 1.0 shares for $41.94
On the 89th day, Bought 0.0 shares for $0.0
On the 101th day, sold 2.1953143676786997 shares for $89.67859191967489
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.2068549360366885 shares for $94.56373400917211
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.276626291211212 shares for $105.36226475725489
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 88th day, Bought 1.0 shares for $41.94
On the 101th day, sold 2.19417243850012 shares for $89.6319441127299
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.2068549360366885 shares for $94.56373400917211
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.247196571777908 shares for $104.00025734188158
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 101th day, sold 1.1853959222380275 shares for $48.42342342342342
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 1.0 shares for $41.91
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.1976047904191613 shares for $94.16736526946107
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 1.1930326890956813 shares for $50.0
On the 128th day, sold 2.390637479514843 shares for $103.01256899229459

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 105.91459068610189, Final Money: 105.91459068610189, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 66th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4935719253583546 shares for $103.13413483282154
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 108th day, sold 2.4292825894470527 shares for $100.40224942184668
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 122th day, sold 2.4029855572570566 shares for $101.83852791655407
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 136th day, Bought 1.1595547309833025 shares for $50.0
On the 137th day, sold 2.3026731580523467 shares for $96.8504330276817
On the 146th day, Bought 1.1507479861910241 shares for $50.0
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.293082918793263 shares for $106.94938733251779
On the 210th day, Bought 1.0072522159548751 shares for $50.0
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 234th day, sold 2.006852375890901 shares for $95.92754356758506
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 66th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4935719253583546 shares for $103.13413483282154
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 109th day, sold 1.21921482565228 shares for $50.70714459887832
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 122th day, sold 2.4029855572570566 shares for $101.83852791655407
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 146th day, Bought 1.1507479861910241 shares for $50.0
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.293082918793263 shares for $106.94938733251779
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 235th day, sold 2.0058388397508775 shares for $97.30324211631506
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 76th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 122th day, sold 2.4935719253583546 shares for $105.67757819668708
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 146th day, Bought 1.1507479861910241 shares for $50.0
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.293082918793263 shares for $106.94938733251779
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 235th day, sold 2.0058388397508775 shares for $97.30324211631506
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4935719253583546 shares for $107.4480142636915
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 202th day, sold 2.2784403631861974 shares for $105.44622000825721
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 235th day, sold 2.0058388397508775 shares for $97.30324211631506
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 129th day, sold 2.4416061852831312 shares for $105.40413901867278
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 202th day, sold 1.142334932602239 shares for $52.86726068083162
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 130th day, sold 1.2382367508667655 shares for $52.724120851906875
On the 213th day, Bought 1.0062386798148522 shares for $50.0
XLF Final Value: 108.27703743078779, Final Money: 108.27703743078779, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 70th day, Bought 1.224889759921607 shares for $50.0
On the 92th day, sold 1.224889759921607 shares for $50.0
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4492271257752813 shares for $105.3167664083371
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2758364540624174 shares for $100.77403818588384
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 1.072271070126528 shares for $49.62470512545571
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 71th day, Bought 1.2266928361138372 shares for $50.0
On the 92th day, sold 1.2266928361138372 shares for $50.073601570166836
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4492271257752813 shares for $105.3167664083371
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2812835348939844 shares for $106.76406943303846
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 106th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.458065172530377 shares for $105.69680241880621
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 106th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.455003258672547 shares for $105.56514012291952
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 123th day, sold 2.455003258672547 shares for $105.56514012291952
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 124th day, sold 2.455003258672547 shares for $106.76809171966907

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.1544374115424, Final Money: 112.1544374115424, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 71th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4935719253583546 shares for $103.13413483282154
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 106th day, Bought 0.0 shares for $0.0
On the 108th day, sold 2.4492271257752813 shares for $101.22655710829237
On the 112th day, Bought 1.22040517451794 shares for $50.0
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4200212973586313 shares for $104.06091578642115
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 200th day, sold 2.2784403631861974 shares for $105.90190808089444
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4935719253583546 shares for $103.13413483282154
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.4492271257752813 shares for $106.51688769996699
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 200th day, sold 2.2758364540624174 shares for $105.78087838482115
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.474550000143869 shares for $107.61817950625688
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 201th day, sold 1.1138338159946535 shares for $51.94920917799064
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 124th day, sold 2.4492271257752813 shares for $106.51688769996699
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 125th day, sold 2.4492271257752813 shares for $107.32513265147283
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 125th day, sold 2.4492271257752813 shares for $107.32513265147283
XLF Final Value: 115.4319009176097, Final Money: 115.4319009176097, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 57th day, sold 0.4132231404958678 shares for $51.71900826446281
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 97th day, sold 0.7973563487023718 shares for $98.01901594598257
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.40264132710581413 shares for $50.78917700112739
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.782632814641483 shares for $104.76322856790893
On the 219th day, Bought 0.34921078362899843 shares for $50.0
On the 220th day, Bought 0.34724633655114934 shares for $49.99999999999999
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.6964571201801477 shares for $92.71237183838127
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 97th day, sold 0.7973563487023718 shares for $98.01901594598257
On the 123th day, Bought 0.39977612536979296 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.39977612536979296 shares for $50.33181418405694
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 237th day, sold 0.7105312176540179 shares for $95.32486816046304
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, sold 0.7991369435960733 shares for $97.65453450744016
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.7966308196124732 shares for $98.13695066806056
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.7983397032568902 shares for $98.3474680442163
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 104.25931579017033, Final Money: 104.25931579017033, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 56th day, sold 0.41145490454246214 shares for $51.617017774851874
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 68th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.82697056674124 shares for $100.24537210037312
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7991369435960733 shares for $97.51868122702884
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.41473125414731254 shares for $51.78749170537492
On the 147th day, Bought 0.3937938095613137 shares for $50.0
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 164th day, sold 0.785213881582607 shares for $100.71938459060101
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 217th day, Bought 0.34833495889647487 shares for $50.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.698843195840043 shares for $93.82668747348416
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 73th day, sold 0.4150410890678177 shares for $50.31128081680087
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7991369435960733 shares for $98.70140390355103
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.41473125414731254 shares for $51.78749170537492
On the 147th day, Bought 0.3937938095613137 shares for $50.0
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.785213881582607 shares for $111.57104043407263
On the 217th day, Bought 0.34833495889647487 shares for $50.0
On the 218th day, Bought 0.34792290028529677 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.6962578591817716 shares for $92.78332231456288
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 74th day, sold 0.4150410890678177 shares for $50.60180957914834
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7966308196124732 shares for $98.39187253033657
On the 147th day, Bought 0.3937938095613137 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3937938095613137 shares for $55.954162400567064
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 74th day, sold 0.4119294776734223 shares for $50.22244191794365
On the 147th day, Bought 0.3937938095613137 shares for $50.0
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.785213881582607 shares for $111.57104043407263
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 95th day, sold 0.4119294776734223 shares for $50.25539627615752
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7839155583232007 shares for $111.3865616821436
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 95th day, sold 0.4119294776734223 shares for $50.25539627615752
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7839155583232007 shares for $111.3865616821436

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 111.79348235201628, Final Money: 111.79348235201628, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 93th day, sold 0.40209087253719344 shares for $49.067149175713716
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.41473125414731254 shares for $51.09074319840743
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 230th day, Bought 0.3638215818962381 shares for $50.0
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 94th day, sold 0.40209087253719344 shares for $49.662243667068765
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.4124731892426992 shares for $50.81257218280812
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7739341331918541 shares for $109.96830098523056
On the 230th day, Bought 0.3638215818962381 shares for $50.0
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 94th day, sold 0.40209087253719344 shares for $49.662243667068765
On the 118th day, Bought 0.4119634176485128 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.4119634176485128 shares for $51.157617203592324
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7741137141045964 shares for $109.9938176371221
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 94th day, sold 0.40209087253719344 shares for $49.662243667068765
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.4137702747434624 shares for $50.782025819265144
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.38711675441313104 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7740537610684475 shares for $109.9852989102157
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.37752944729688914 shares for $50.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 95th day, sold 0.40209087253719344 shares for $49.0550864495376
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 95th day, sold 0.39812086949597897 shares for $48.57074607850944

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 109.22556939988212, Final Money: 10.429568396549612, Final Shares: 0.7443942209413239
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4124731892426992 shares for $51.79013364131331
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 219th day, Bought 0.34921078362899843 shares for $50.0
On the 220th day, Bought 0.34724633655114934 shares for $49.99999999999999
On the 221th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.6964571201801477 shares for $93.50633295538663
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 116th day, Bought 0.4109814236396515 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4109814236396515 shares for $51.60282755219465
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.4062728528479727 shares for $49.24839522223125
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7991369435960733 shares for $97.49470711872095
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7991369435960733 shares for $97.49470711872095
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 96th day, sold 0.3995205753096284 shares for $48.62165401518178
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
XLI Final Value: 111.21906983464346, Final Money: 111.21906983464346, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 60th day, sold 0.24077819512664933 shares for $49.4606568429163
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4446063536548852 shares for $99.55180864686534
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4280507457786669 shares for $99.51751788608227
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 61th day, sold 0.2400729821865847 shares for $48.37950737024055
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44852140323780454 shares for $100.3521787604264
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 234th day, sold 0.20888164765843673 shares for $48.56289426410996
On the 52th day, Bought 0.24173274028234384 shares for $50.0
On the 66th day, sold 0.24173274028234384 shares for $46.956584799845295
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.24211902571304053 shares for $54.32182460897778
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44852140323780454 shares for $100.3521787604264
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 125th day, sold 0.23999232024575212 shares for $53.84467697033695
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.43723461539193853 shares for $97.82687284779233
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 125th day, sold 0.23999232024575212 shares for $53.84467697033695
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 202th day, sold 0.21429795988342193 shares for $47.94702554431682
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 103.83239003897951, Final Money: 103.83239003897951, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 63th day, sold 0.23955538520505942 shares for $47.63558834802606
On the 84th day, Bought 0.23552687361627964 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23552687361627964 shares for $53.285599886947104
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.22360359554581635 shares for $50.73341979339027
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 64th day, sold 0.2400729821865847 shares for $47.193546838238824
On the 85th day, Bought 0.23604947597016335 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23604947597016335 shares for $53.40383344348976
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.21576835109826092 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42613523093669914 shares for $95.61622311757655
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.2229654403567447 shares for $50.5886287625418
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.21392204680614385 shares for $51.48889744577076
On the 52th day, Bought 0.24173274028234384 shares for $50.0
On the 79th day, sold 0.24173274028234384 shares for $49.50203055501837
On the 85th day, Bought 0.23604947597016335 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23604947597016335 shares for $53.40383344348976
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.21576835109826092 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42613523093669914 shares for $95.61622311757655
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.22005105184402782 shares for $49.927383152891466
On the 54th day, Bought 0.2449659497329871 shares for $50.0
On the 112th day, sold 0.2449659497329871 shares for $55.44804272206163
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.21576835109826092 shares for $50.0
On the 126th day, sold 0.42613523093669914 shares for $95.61622311757655
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.22533687863355717 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.4523413279207632 shares for $102.63172389194196
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 127th day, sold 0.21036687983843824 shares for $46.463732749915856
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.21718356354791069 shares for $49.276778733385456
On the 121th day, Bought 0.21576835109826092 shares for $50.0
On the 127th day, sold 0.21576835109826092 shares for $47.65675570707289
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.21429795988342193 shares for $50.0064289387965

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 103.69598973158014, Final Money: 103.69598973158014, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 73th day, Bought 0.2573870071038814 shares for $50.0
On the 76th day, sold 0.2573870071038814 shares for $52.74631936579842
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.4747010467162023 shares for $108.07518730587776
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.43762033266453315 shares for $98.19325024326794
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.45348853112464915 shares for $101.5406170041202
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.4340538421757886 shares for $101.77260437495714
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44301649220077255 shares for $99.19582276867499
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 215th day, Bought 0.21415110501970192 shares for $50.0
On the 240th day, sold 0.43029254797997507 shares for $100.89069372486476
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4316842013032868 shares for $96.86130108843149
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 192th day, Bought 0.215526531316005 shares for $50.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4355775831600328 shares for $97.53017664536294
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 126th day, sold 0.23999232024575212 shares for $53.84947681674186
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 193th day, Bought 0.21574973031283712 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4358007821568649 shares for $97.58015313274362
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 112.32797829402146, Final Money: 112.32797829402146, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22693232877955793 shares for $50.7738392411383
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 76th day, sold 0.23955538520505942 shares for $49.09208509007283
On the 84th day, Bought 0.23552687361627964 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23552687361627964 shares for $53.285599886947104
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 52th day, Bought 0.24173274028234384 shares for $50.0
On the 77th day, sold 0.24173274028234384 shares for $49.37632953007155
On the 85th day, Bought 0.23604947597016335 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23604947597016335 shares for $53.40383344348976
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 92th day, Bought 0.23285055651283007 shares for $50.0
On the 111th day, sold 0.23285055651283007 shares for $52.68010990546268
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.21718356354791069 shares for $48.59265050820954
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 203th day, sold 0.21718356354791069 shares for $49.276778733385456
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 203th day, sold 0.21718356354791069 shares for $49.276778733385456
XLK Final Value: 100.62632542172086, Final Money: 100.62632542172086, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 60th day, sold 0.6693440428380187 shares for $49.11646586345381
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6493506493506493 shares for $50.551948051948045
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6051803437424352 shares for $48.91067538126361
On the 226th day, Bought 0.60790273556231 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.60790273556231 shares for $48.77203647416413
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 60th day, sold 0.6637461834594451 shares for $48.705694942254084
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 156th day, Bought 0.610798924993892 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.610798924993892 shares for $49.36476911800634
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 61th day, sold 0.6637461834594451 shares for $48.50657108721625
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6093102607847916 shares for $49.073848403607116
On the 35th day, Bought 0.6599788806758183 shares for $50.0
On the 62th day, sold 0.6599788806758183 shares for $48.25105596620908
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6093102607847916 shares for $49.073848403607116
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 136th day, sold 0.6431695394906097 shares for $50.5338307177772
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.91505344278146, Final Money: 100.91505344278146, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 82th day, Bought 0.6472491909385113 shares for $50.0
On the 96th day, sold 0.6472491909385113 shares for $50.47249190938511
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, sold 1.2889920939159838 shares for $99.32973075716572
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6227425582264291 shares for $51.718769460704934
On the 177th day, Bought 0.6024096385542169 shares for $50.00000000000001
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 185th day, sold 1.2120170513803568 shares for $98.40366440157116
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.6165988407941793 shares for $49.29091133308669
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 120th day, sold 1.2889920939159838 shares for $99.76798806909716
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6227425582264291 shares for $50.84070245360567
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2181387830463448 shares for $96.13551275801754
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 120th day, sold 0.6518055012384305 shares for $50.449745795854525
On the 135th day, Bought 0.6422607578676943 shares for $50.0
On the 138th day, sold 0.6422607578676943 shares for $49.90366088631985
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 239th day, sold 1.2110226334153902 shares for $96.03409482984044
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6518055012384305 shares for $50.26072220049537
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 121th day, sold 0.6518055012384305 shares for $50.26072220049537
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 208th day, sold 1.2400059548577866 shares for $99.98168014018333
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999

[*********************100%***********************]  1 of 1 completed

On the 240th day, sold 1.2348803404304947 shares for $96.77757227953788
XLP Final Value: 100.2424023406787, Final Money: 100.2424023406787, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 77th day, Bought 0.6514657980456026 shares for $50.0
On the 78th day, Bought 0.6534239414532149 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.3048897394988175 shares for $99.82406507165953
On the 132th day, Bought 0.6370238246910435 shares for $50.0
On the 133th day, Bought 0.0 shares for $0.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6370238246910435 shares for $49.49675117849408
On the 142th day, Bought 0.6317119393556537 shares for $49.99999999999999
On the 143th day, Bought 0.0 shares for $0.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 158th day, sold 0.6317119393556537 shares for $52.48894504106127
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.0 shares for $0.0
On the 183th day, sold 1.2056191664391671 shares for $97.72748963155888
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6065752759917505 shares for $48.435035787941274
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.600817111271329 shares for $47.861091083874065
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 77th day, Bought 0.6514657980456026 shares for $50.0
On the 78th day, Bought 0.6534239414532149 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, sold 1.3048897394988175 shares for $99.1063757149352
On the 132th day, Bought 0.6370238246910435 shares for $50.0
On the 133th day, Bought 0.0 shares for $0.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6370238246910435 shares for $49.49675117849408
On the 142th day, Bought 0.6317119393556537 shares for $49.99999999999999
On the 143th day, Bought 0.0 shares for $0.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 159th day, sold 0.6317119393556537 shares for $52.735312697409974
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.0 shares for $0.0
On the 184th day, sold 1.2056191664391671 shares for $98.31824302311408
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6065752759917505 shares for $48.435035787941274
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.600817111271329 shares for $47.861091083874065
On the 77th day, Bought 0.6514657980456026 shares for $50.0
On the 92th day, sold 0.6514657980456026 shares for $49.47882736156352
On the 132th day, Bought 0.6370238246910435 shares for $50.0
On the 133th day, Bought 0.0 shares for $0.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6370238246910435 shares for $49.49675117849408
On the 143th day, Bought 0.6349206349206349 shares for $50.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 159th day, sold 0.6349206349206349 shares for $53.0031746031746
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 185th day, sold 1.2056191664391671 shares for $97.88422012319597
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 234th day, sold 0.6015399422521656 shares for $47.918671799807505
On the 77th day, Bought 0.6514657980456026 shares for $50.0
On the 95th day, sold 0.6514657980456026 shares for $50.36482084690554
On the 132th day, Bought 0.6370238246910435 shares for $50.0
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.273804262795985 shares for $98.97459121924803
On the 143th day, Bought 0.6349206349206349 shares for $50.0
On the 144th day, Bought 0.0 shares for $0.0
On the 159th day, sold 0.6349206349206349 shares for $53.0031746031746
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 234th day, sold 0.6015399422521656 shares for $47.918671799807505
On the 78th day, Bought 0.6534239414532149 shares for $50.0
On the 171th day, sold 0.6534239414532149 shares for $54.2668583376895
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 171th day, sold 0.6367804381049414 shares for $52.88461538461539

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 104.2668583376895, Final Money: 104.2668583376895, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 122th day, sold 1.3027624078912101 shares for $100.89894849117422
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.2400059548577866 shares for $102.98249455093918
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.6024096385542169 shares for $50.00000000000001
On the 186th day, sold 1.2046741531290182 shares for $98.34959786145305
On the 191th day, Bought 0.6079766536964981 shares for $50.0
On the 192th day, Bought 0.6131207847946045 shares for $50.0
On the 205th day, sold 1.2210974384911026 shares for $97.50463046351454
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.6165988407941793 shares for $48.66198051547663
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.3027624078912101 shares for $101.79785455261916
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2400059548577866 shares for $99.01447549539425
On the 228th day, Bought 0.6096817461285209 shares for $50.0
On the 229th day, Bought 0.60790273556231 shares for $50.0
On the 240th day, sold 1.2175844816908308 shares for $95.42209583011041
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2400059548577866 shares for $99.01447549539425
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 138th day, sold 0.6509569066527796 shares for $50.579351646920976
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2400059548577866 shares for $99.01447549539425
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 139th day, sold 0.6509569066527796 shares for $50.93086837651347
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2348803404304947 shares for $98.60519518337499
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 139th day, sold 0.649772579597141 shares for $50.83820662768031
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 205th day, sold 1.2348803404304947 shares for $98.60519518337499
XLP Final Value: 99.6597629416203, Final Money: 99.6597629416203, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 71th day, Bought 0.3560492772199672 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3560492772199672 shares for $51.52389090650146
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.321646831778707 shares for $47.960759086523005
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6814613955648616 shares for $97.59890107279948
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.32181244770547723 shares for $47.98545407736371
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34055305816646236 shares for $46.996322026971804
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6814613955648616 shares for $97.59890107279948
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.32181244770547723 shares for $47.98545407736371
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 55th day, sold 0.34300610550867805 shares for $49.12533443095287
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.321316110789795 shares for $47.911445279866335
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 55th day, sold 0.34300610550867805 shares for $49.12533443095287
On the 83th day, Bought 0.34199726402188785 shares for $50.0
On the 96th day, sold 0.34199726402188785 shares for $49.63406292749658
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.321316110789795 shares for $48.255253518411415
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 56th day, sold 0.34300610550867805 shares for $48.967551622418874
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.321316110789795 shares for $48.255253518411415
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 94.75720549618484, Final Money: 47.408152749830734, Final Shares: 0.34073872154831675
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 63th day, Bought 0.361167292689974 shares for $50.0
On the 94th day, sold 0.361167292689974 shares for $51.89973995954926
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6849785388796403 shares for $101.56176795968427
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.64628714820769 shares for $99.4571292376814
On the 195th day, Bought 0.33464962184592734 shares for $50.0
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6711460213344528 shares for $100.79270948400813
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.680342388781481 shares for $93.37018943637047
On the 63th day, Bought 0.361167292689974 shares for $50.0
On the 94th day, sold 0.361167292689974 shares for $51.89973995954926
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 122th day, sold 0.6849785388796403 shares for $101.56176795968427
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6446859841239713 shares for $99.21072609683793
On the 195th day, Bought 0.33464962184592734 shares for $50.0
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6711460213344528 shares for $100.79270948400813
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.680342388781481 shares for $93.37018943637047
On the 63th day, Bought 0.361167292689974 shares for $50.0
On the 95th day, sold 0.361167292689974 shares for $52.264518925166136
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 128th day, sold 0.6849785388796403 shares for $101.87000830218011
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6446859841239713 shares for $99.21072609683793
On the 195th day, Bought 0.33464962184592734 shares for $50.0
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6711460213344528 shares for $97.57792004181609
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 241th day, sold 0.680342388781481 shares for $93.59470242466834
On the 64th day, Bought 0.3611933829372246 shares for $50.0
On the 95th day, sold 0.3611933829372246 shares for $52.26829444484577
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 128th day, sold 0.34234851078397804 shares for $50.914070523793214
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6446859841239713 shares for $99.75870918334331
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.672495324291966 shares for $97.77409519880894
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 64th day, Bought 0.3611933829372246 shares for $50.0
On the 95th day, sold 0.3611933829372246 shares for $52.26829444484577
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6446859841239713 shares for $99.75870918334331
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.672495324291966 shares for $97.77409519880894
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 64th day, Bought 0.3611933829372246 shares for $50.0
On the 95th day, sold 0.3611933829372246 shares for $52.26829444484577
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6446859841239713 shares for $99.75870918334331
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 218th day, sold 0.672495324291966 shares for $98.29864155175666
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 97.08153607729355, Final Money: 97.08153607729355, Final Shares: 0.0
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.3584743332377402 shares for $50.770719816461146
On the 118th day, Bought 0.3466204506065858 shares for $50.0
On the 119th day, Bought 0.3449465332873405 shares for $50.0
On the 122th day, sold 0.6915669838939262 shares for $102.53863670195246
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6431285584952722 shares for $98.97105386683742
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 208th day, sold 0.6788695024739367 shares for $99.94316815421297
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3584743332377402 shares for $51.51276168626326
On the 118th day, Bought 0.3466204506065858 shares for $50.0
On the 122th day, sold 0.3466204506065858 shares for $51.39341421143848
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6431285584952722 shares for $98.97105386683742
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6788695024739367 shares for $99.67840904824814
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3584743332377402 shares for $51.51276168626326
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6422609724625596 shares for $99.38346287885649
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3584743332377402 shares for $51.51276168626326
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6422609724625596 shares for $98.16958964090223
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3584743332377402 shares for $51.87482076283339
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6422609724625596 shares for $98.16958964090223
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3538570417551309 shares for $51.20665251238499
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6412113233688959 shares for $98.18868994747902
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 96.89588424862967, Final Money: 2.223578539463972, Final Shares: 0.681291779714779
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 53th day, sold 0.34300610550867805 shares for $49.4031693764149
On the 65th day, Bought 0.35984166966534725 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 68th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.35984166966534725 shares for $52.072688017272405
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6853774917644311 shares for $100.99037341148892
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.64628714820769 shares for $99.06289407727472
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.672495324291966 shares for $95.38673679757247
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6858477175629567 shares for $101.05966118290166
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.6446859841239713 shares for $98.24369712065197
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.672495324291966 shares for $95.38673679757247
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 122th day, sold 0.3431002538941879 shares for $50.871474644891244
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6446859841239713 shares for $98.72076474890372
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6729261485231172 shares for $95.44784490651894
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6446859841239713 shares for $98.72076474890372
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.3359989248034406 shares for $47.691687386600364
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6434592794841842 shares for $98.53291946741314
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 96th day, sold 0.3536067892503536 shares for $51.31895332390382
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6434592794841842 shares for $98.53291946741314
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
XLV Final Value: 96.54228338200308, Final Money: 49.851872791316964, Final Shares: 0.3359989248034406

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.2811041772080733 shares for $53.81739472648563
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5378776536193173 shares for $107.6239397126892
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.44423674848696104 shares for $103.77370444655409
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5612005303535553 shares for $107.44184153618816
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5374235599170535 shares for $107.53308010380323
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.44039044105953584 shares for $102.87520703150757
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 125th day, sold 0.5612005303535553 shares for $107.44184153618816
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5374235599170535 shares for $107.53308010380323
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.43407487791644056 shares for $101.3998914812805
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2811041772080733 shares for $53.26924158092989
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.5374235599170535 shares for $107.16225784746047
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.43407487791644056 shares for $99.72436245252305
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2811041772080733 shares for $53.26924158092989
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 202th day, sold 0.2661414808111992 shares for $53.06861127375312
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.43023815087518835 shares for $97.25533400533634
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2798298634430266 shares for $53.027759122453546
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 240th day, sold 0.2154615185727829 shares for $48.70507627337758
XLY Final Value: 117.85012867149898, Final Money: 117.85012867149898, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 73th day, sold 0.2932379332590464 shares for $51.175884112368784
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5618453338616387 shares for $97.73861427857068
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.2631301968213872 shares for $49.418482265024736
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.26996382484747045 shares for $53.97926677825171
On the 216th day, Bought 0.22925263640531868 shares for $50.0
On the 217th day, Bought 0.22693232877955793 shares for $50.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 73th day, sold 0.2932379332590464 shares for $51.175884112368784
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.5618453338616387 shares for $105.52017215255437
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.5365593993609334 shares for $107.28505190221864
On the 218th day, Bought 0.22611133722244833 shares for $50.0
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 73th day, sold 0.2932379332590464 shares for $51.175884112368784
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.5609340406510999 shares for $105.34902217468307
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.5365593993609334 shares for $107.28505190221864
On the 218th day, Bought 0.22611133722244833 shares for $50.0
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 73th day, sold 0.2932379332590464 shares for $51.175884112368784
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.5609340406510999 shares for $105.34902217468307
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.5378776536193173 shares for $107.54863684118249
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 73th day, sold 0.2932379332590464 shares for $51.175884112368784
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.5609340406510999 shares for $106.51015563883084
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.5378776536193173 shares for $105.90273122110737
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 74th day, sold 0.2932379332590464 shares for $51.82100756553868
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.5609340406510999 shares for $101.29907840118213
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.5374235599170535 shares for $105.81332471206865

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 116.38216846777588, Final Money: 13.981108167141784, Final Shares: 0.4533427496929082
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.28123066539175434 shares for $49.246301816750105
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2814364516492176 shares for $51.910953506698185
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0 shares for $0.0
On the 123th day, Bought 0 shares for $0.0
On the 124th day, Bought 0 shares for $0.0
On the 125th day, Bought 0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.2631301968213872 shares for $47.70550468371751
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 171th day, Bought 0 shares for $0.0
On the 172th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 177th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 208th day, Bought 0 shares for $0.0
On the 209th day, Bought 0 shares for $0.0
On the 210th day, Bought 0 shares for $0.0
On the 211th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 230th day, Bought 0 shares for $0.0
On the 231th day, Bought 0 shares for $0.0
On the 232th day, Bought 0 shares for $0.0
On the 233th day, Bought 0 shares for $0.0
On the 234th day, Bought 0 shares for $0.0
On the 235th day, Bought 0 shares for $0.0
On the 236th day, Bought 0 shares for $0.0
On the 237th day, Bought 0 shares for $0.0
On the 238th day, Bought 0 shares for $0.0
On the 239th day, Bought 0 shares for $0.0
On the 240th day, Bought 0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.2797985450475658 shares for $48.99552322327925
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0 shares for $0.0
On the 123th day, Bought 0 shares for $0.0
On the 124th day, Bought 0 shares for $0.0
On the 125th day, Bought 0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.2814364516492176 shares for $50.82460880333221
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 171th day, Bought 0 shares for $0.0
On the 172th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 177th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 210th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 230th day, Bought 0 shares for $0.0
On the 231th day, Bought 0 shares for $0.0
On the 232th day, Bought 0 shares for $0.0
On the 233th day, Bought 0 shares for $0.0
On the 234th day, Bought 0 shares for $0.0
On the 235th day, Bought 0 shares for $0.0
On the 236th day, Bought 0 shares for $0.0
On the 237th day, Bought 0 shares for $0.0
On the 238th day, Bought 0 shares for $0.0
On the 239th day, Bought 0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 59th day, sold 0.2702410550210788 shares for $48.65149713544482
On the 100th day, Bought 0.28053638556920835 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0 shares for $0.0
On the 123th day, Bought 0 shares for $0.0
On the 124th day, Bought 0 shares for $0.0
On the 125th day, Bought 0 shares for $0.0
On the 131th day, sold 0.28053638556920835 shares for $50.66206586994333
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 171th day, Bought 0 shares for $0.0
On the 172th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 210th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 230th day, Bought 0 shares for $0.0
On the 233th day, Bought 0 shares for $0.0
On the 234th day, Bought 0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 59th day, sold 0.2702410550210788 shares for $48.65149713544482
On the 101th day, Bought 0.2812781278127813 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0 shares for $0.0
On the 123th day, Bought 0 shares for $0.0
On the 124th day, Bought 0 shares for $0.0
On the 125th day, Bought 0 shares for $0.0
On the 137th day, sold 0.2812781278127813 shares for $49.54995499549955
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 171th day, Bought 0 shares for $0.0
On the 172th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 59th day, sold 0.2739425816348893 shares for $49.31788297172913
On the 102th day, Bought 0.2783809364734703 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0 shares for $0.0
On the 123th day, Bought 0 shares for $0.0
On the 124th day, Bought 0 shares for $0.0
On the 125th day, Bought 0 shares for $0.0
On the 138th day, sold 0.2783809364734703 shares for $47.65324870552865
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 171th day, Bought 0 shares for $0.0
On the 172th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 59th day, sold 0.2739425816348893 shares for $49.31788297172913
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 122th day, Bought 0 shares for $0.0
On the 123th day, Bought 0 shares for $0.0
On the 124th day, Bought 0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 171th day, Bought 0 shares for $0.0
On the 172th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 111.23242265451096, Final Money: 49.313563005388154, Final Shares: 0.2741228070175438
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.5608375097990475 shares for $102.41453766440407
On the 148th day, Bought 0.2697162584960621 shares for $49.99999999999999
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5396800833435326 shares for $108.37315753621478
On the 216th day, Bought 0.22925263640531868 shares for $50.0
On the 218th day, Bought 0.22611133722244833 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.45536397362776704 shares for $104.11441893025265
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 126th day, sold 0.5608375097990475 shares for $106.2787081069195
On the 148th day, Bought 0.2697162584960621 shares for $49.99999999999999
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5396800833435326 shares for $108.37315753621478
On the 216th day, Bought 0.22925263640531868 shares for $50.0
On the 218th day, Bought 0.22611133722244833 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.45536397362776704 shares for $103.97325609842805
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2807411566535654 shares for $53.200449185850644
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5365593993609334 shares for $107.74649298566905
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.2807411566535654 shares for $52.72599663110612
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5365593993609334 shares for $107.74649298566905
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 234th day, sold 0.22492127755285649 shares for $51.35627530364373
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 127th day, sold 0.2807411566535654 shares for $52.72599663110612
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5365593993609334 shares for $107.74649298566905
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 127th day, sold 0.2807411566535654 shares for $52.72599663110612
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5365593993609334 shares for $107.74649298566905
XLY Final Value: 118.62512174156235, Final Money: 118.62512174156235, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 54th day, sold 0.8051529790660226 shares for $52.310789049919485
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.3811242047734613 shares for $99.24758535502093
On the 110th day, Bought 0.7237984944991315 shares for $50.0
On the 111th day, Bought 0.7268498328245384 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4506483273236699 shares for $101.64692829556954
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 184th day, sold 1.3360068701989094 shares for $105.27734137167405
On the 193th day, Bought 0.6147037128104254 shares for $50.0
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 1.2275239113641696 shares for $95.90644319488257
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 54th day, sold 0.8051529790660226 shares for $52.310789049919485
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.3811242047734613 shares for $96.83061799666737
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6672894701721607 shares for $52.13532630455091
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 55th day, sold 0.8051529790660226 shares for $52.46376811594203
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.3811242047734613 shares for $96.83061799666737
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6672894701721607 shares for $52.13532630455091
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 55th day, sold 0.8051529790660226 shares for $52.46376811594203
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.3829348252326872 shares for $96.9575605970637
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6687174000267487 shares for $52.24689046408987
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 55th day, sold 0.8051529790660226 shares for $52.46376811594203
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 137th day, sold 1.383509531094396 shares for $102.68407739782606
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 55th day, sold 0.8051529790660226 shares for $52.46376811594203
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 137th day, sold 1.3784824186438849 shares for $102.31096511174914

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 105.14784551376809, Final Money: 105.14784551376809, Final Shares: 0.0
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4124102758916717 shares for $101.53817473385227
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 125th day, sold 0.7228567297961543 shares for $50.67948532600838
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 185th day, sold 0.6149305128520477 shares for $48.30894108965687
On the 209th day, Bought 0.6381620931716656 shares for $50.0
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2785309456306821 shares for $97.24506372466969
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.4124102758916717 shares for $101.49580242557552
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3487087648370697 shares for $108.34177507936181
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 65th day, sold 0.7803964413922273 shares for $51.061339160293436
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4124102758916717 shares for $99.0240844427651
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.348799789227747 shares for $108.34908706866491
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 66th day, sold 0.7803964413922273 shares for $51.529577025128766
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 125th day, sold 1.4024265352120677 shares for $98.32412438371807
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 0.6746727836999056 shares for $54.19646471461341
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 66th day, sold 0.7803964413922273 shares for $51.529577025128766
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 236th day, sold 1.2563839283247926 shares for $95.56056158838373
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 66th day, sold 0.7803964413922273 shares for $51.529577025128766
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 173th day, sold 0.6716818914562064 shares for $53.57334766254702
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 236th day, sold 0.6309148264984227 shares for $47.98738170347003

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 108.38006944539217, Final Money: 57.84906118526368, Final Shares: 0.6555657532450505
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7554011179936546 shares for $54.93276930049856
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 122th day, Bought 0.7016559079427448 shares for $50.0
On the 133th day, sold 1.4084695918556656 shares for $100.69149112176153
On the 137th day, Bought 0.6736728644570197 shares for $50.0
On the 138th day, Bought 0.691945751453086 shares for $50.0
On the 139th day, Bought 0.0 shares for $0.0
On the 140th day, Bought 0.0 shares for $0.0
On the 141th day, Bought 0.0 shares for $0.0
On the 142th day, Bought 0.0 shares for $0.0
On the 143th day, Bought 0.0 shares for $0.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 190th day, sold 1.3656186159101056 shares for $111.2706048243554
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 63th day, sold 0.7827175954915466 shares for $50.15654351909831
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4568087492862052 shares for $104.7299809861853
On the 137th day, Bought 0.6736728644570197 shares for $50.0
On the 138th day, Bought 0.691945751453086 shares for $50.0
On the 139th day, Bought 0.0 shares for $0.0
On the 140th day, Bought 0.0 shares for $0.0
On the 141th day, Bought 0.0 shares for $0.0
On the 143th day, Bought 0.0 shares for $0.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 191th day, sold 1.3656186159101056 shares for $111.91244557383315
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 95th day, sold 0.7452675510508272 shares for $53.57728424504397
On the 138th day, Bought 0.691945751453086 shares for $50.0
On the 139th day, Bought 0.6861534239055852 shares for $50.0
On the 140th day, Bought 0.0 shares for $0.0
On the 141th day, Bought 0.0 shares for $0.0
On the 143th day, Bought 0.0 shares for $0.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, sold 1.3780991753586713 shares for $112.93522742064312
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 95th day, sold 0.7452675510508272 shares for $53.57728424504397
On the 138th day, Bought 0.691945751453086 shares for $50.0
On the 139th day, Bought 0.6861534239055852 shares for $50.0
On the 140th day, Bought 0.0 shares for $0.0
On the 141th day, Bought 0.0 shares for $0.0
On the 143th day, Bought 0.0 shares for $0.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, sold 1.3780991753586713 shares for $112.93522742064312
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, Bought 0.6646284726837698 shares for $50.00000000000001
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 141th day, Bought 0.6815703380588877 shares for $50.0
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 201th day, sold 1.355697343586729 shares for $105.92063345443113
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 201th day, sold 1.3487087648370697 shares for $105.37461579672025

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 120.66151308305976, Final Money: 17.969805930026233, Final Shares: 1.3322743533086863
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 53th day, sold 0.7803964413922273 shares for $50.80380833463399
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 65th day, sold 1.5442838507950172 shares for $101.04249235751799
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4012495930161712 shares for $98.18555898264312
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 133th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.4119643187794981 shares for $104.6265560215608
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 180th day, Bought 0.6139489194499018 shares for $50.0
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 184th day, sold 1.2288794323019494 shares for $96.83569926539361
On the 209th day, Bought 0.6381620931716656 shares for $50.0
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.2785309456306821 shares for $97.71812017455305
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 53th day, sold 0.7803964413922273 shares for $50.80380833463399
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 65th day, sold 1.5442838507950172 shares for $101.04249235751799
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 124th day, sold 1.4012495930161712 shares for $98.18555898264312
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 136th day, sold 1.4119643187794981 shares for $104.6265560215608
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 184th day, sold 0.6149305128520477 shares for $48.45652441274136
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 54th day, sold 0.7803964413922273 shares for $50.70235679725301
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 137th day, sold 1.4119643187794981 shares for $104.79599173981435
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.346354675156112 shares for $107.38524889045149
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 184th day, sold 0.6149305128520477 shares for $48.45652441274136
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 124th day, sold 0.7803964413922273 shares for $54.682378648353364
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 137th day, sold 0.702543206407194 shares for $52.14275677954194
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 185th day, sold 1.346354675156112 shares for $105.76962328026416
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 125th day, sold 0.7803964413922273 shares for $54.71359450600906
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 125th day, sold 0.7803964413922273 shares for $54.71359450600906
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 236th day, sold 0.6309148264984227 shares for $47.98738170347003
On the 242th day, Bought 0.6555657532450505 shares for $50.0
XLU Final Value: 109.81960358979077, Final Money: 59.288595329662286, Final Shares: 0.6555657532450505

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 35th day, Bought 0.09712321050484646 shares for $50.0
On the 40th day, sold 0.09712321050484646 shares for $50.013597249470685
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.19134559053660022 shares for $99.36959207746723
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1791071512121006 shares for $102.05704583216703
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1750799086196722 shares for $100.96858330096497
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17463810735127167 shares for $100.71379650947837
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 204th day, sold 0.1759511625304509 shares for $103.9941751019977
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 60th day, sold 0.09575609008732956 shares for $48.916998621112306
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 204th day, sold 0.1759511625304509 shares for $103.9941751019977
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 204th day, sold 0.08789508842245895 shares for $51.94951306121013
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 103.26397232769021, Final Money: 103.26397232769021, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 35th day, Bought 0.09712321050484646 shares for $50.0
On the 60th day, sold 0.09712321050484646 shares for $49.61539208640082
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 60th day, sold 0.09626306771144183 shares for $49.17598814039006
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.1785952662739861 shares for $105.55694617857672
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 60th day, sold 0.09626306771144183 shares for $49.17598814039006
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17760563979259839 shares for $104.97203734301735
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17334678853326455 shares for $102.45488589470067
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1896456503049435 shares for $104.80956509753008
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17334678853326455 shares for $103.2470807182977
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 234th day, sold 0.08298066550493735 shares for $48.63496805244378
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17202832508608146 shares for $102.46179070452098

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 106.69161386827156, Final Money: 106.69161386827156, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 60th day, sold 0.09749439407234084 shares for $49.80501121185532
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17798507725619608 shares for $106.00969186456295
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.166739304078092 shares for $97.75591919490378
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17726270862194415 shares for $106.03677967056079
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.166739304078092 shares for $97.75591919490378
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.1750799086196722 shares for $104.73105053720172
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.166739304078092 shares for $97.75591919490378
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.1737968507348 shares for $101.89361764879854
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.18867154268899677 shares for $104.27121478250095
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.1693268610481074 shares for $99.27295209528441
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.09409816320385425 shares for $52.00429087624209
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.1693268610481074 shares for $99.27295209528441

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.84454114214051, Final Money: 108.84454114214051, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.19198464209553492 shares for $107.80513607590572
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09598587087980649 shares for $53.458370927799436
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1791071512121006 shares for $102.05704583216703
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17582727512007773 shares for $100.18813963617148
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1759511625304509 shares for $100.25873192147621
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
SPY Final Value: 107.72404346897177, Final Money: 107.72404346897177, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.5710370031978073 shares for $53.140703517587944
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0875484034440523 shares for $98.87990084113324
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0966471303772733 shares for $93.85106141768705
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0875484034440523 shares for $98.87990084113324
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0915254873792657 shares for $93.41275120991756
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.524824183898394 shares for $44.91445365802456
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5184570717544588 shares for $44.36955620074658
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 133th day, sold 0.5433010974682169 shares for $49.706617407367155
On the 189th day, Bought 0.5149860953754248 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5149860953754248 shares for $43.80986713358739
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 133th day, sold 0.5472255663784612 shares for $50.065667067965414
On the 214th day, Bought 0.540891389009087 shares for $50.0
On the 236th day, sold 0.540891389009087 shares for $46.013630463003025
XLB Final Value: 96.07929753096845, Final Money: 96.07929753096845, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5710370031978073 shares for $51.34764732754683
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0844228128268467 shares for $98.67163173911477
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0938814610365155 shares for $93.614375435505
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 60th day, sold 0.5710370031978073 shares for $51.34764732754683
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 1.127982205935974 shares for $99.97306291210538
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0844228128268467 shares for $98.67163173911477
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.0966471303772733 shares for $105.6948504257616
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0938814610365155 shares for $93.614375435505
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5619871866921434 shares for $49.80892435652467
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.0966471303772733 shares for $105.6948504257616
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 96th day, sold 0.5471656817684395 shares for $49.233968045524186
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 0.5451968160505943 shares for $50.11449133137063
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5441288497116117 shares for $46.2890412449668
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 211th day, sold 0.5260389268805892 shares for $48.01683324566018
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5497526113249038 shares for $46.767454645409565
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0945437591716636 shares for $93.11283759273341

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 101.05194950040945, Final Money: 101.05194950040945, Final Shares: 0.0
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 60th day, sold 1.0871888974428363 shares for $97.76002565805985
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5472255663784612 shares for $49.091605559811754
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5441288497116117 shares for $46.46860376537164
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 61th day, sold 0.5397236614853195 shares for $48.29987046632124
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5451968160505943 shares for $52.8404754116236
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5685048322910744 shares for $48.55031267765776
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.5253756435851634 shares for $47.956288746453716
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5685048322910744 shares for $48.55031267765776
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.5253756435851634 shares for $47.956288746453716
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5915059742103396 shares for $50.514610197563
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.0547562682543004 shares for $99.24201728004712
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 237th day, Bought 0.58459020226821 shares for $50.0
On the 238th day, sold 1.1760961764785496 shares for $100.43861347126814
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5253756435851634 shares for $44.86707996217296

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.50167632772275, Final Money: 100.50167632772275, Final Shares: 0.0
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.1274773325509615 shares for $100.44695555696516
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1186549041658311 shares for $100.2762256094251
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.1009008637772286 shares for $106.699311717289
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.0554195515497262 shares for $100.6237000447509
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.078769803289314 shares for $91.77094716582194
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.5619240278714318 shares for $50.370869858395146
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0554195515497262 shares for $96.33869666545901
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5440104450005441 shares for $46.27896855619628
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1197107302364473 shares for $100.37086985839514
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0508631107789832 shares for $89.3969248339681
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.038176589484297 shares for $88.31768246742914
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0966471303772733 shares for $93.29177138119464
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0966471303772733 shares for $93.29177138119464
XLB Final Value: 101.91986116734043, Final Money: 101.91986116734043, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 34th day, Bought 0.573921028466483 shares for $50.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.1430082126230956 shares for $109.87737947945817
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.094935722669386 shares for $98.90554382872564
On the 151th day, Bought 0.5614192679092747 shares for $50.0
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1145778031454734 shares for $94.8951541598056
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5542622769094336 shares for $46.18113291209401
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.1361734946930764 shares for $109.22035804484543
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.0679201308875026 shares for $96.48658382568586
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.094935722669386 shares for $98.90554382872564
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 154th day, Bought 0.5534034311012729 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1016490451363605 shares for $93.79439970290973
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5542622769094336 shares for $46.18113291209401
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.1361734946930764 shares for $109.22035804484543
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0679201308875026 shares for $96.475904624377
On the 154th day, Bought 0.5534034311012729 shares for $50.0
On the 164th day, sold 0.5534034311012729 shares for $46.67957941339237
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.109386069515185 shares for $92.4340473120052
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.0679201308875026 shares for $98.1418600285615
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.108956313651387 shares for $93.3075842306277
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 136th day, sold 0.5336179295624333 shares for $48.42049092849519
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.108956313651387 shares for $93.3075842306277
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.110563397340035 shares for $93.44280425219056

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 96.8947575525947, Final Money: 96.8947575525947, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5737893045673629 shares for $55.15836584806059
On the 65th day, Bought 0.5264820469621986 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0611270426850385 shares for $98.21791907092717
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 129th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.5636978579481398 shares for $51.80383314543405
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 160th day, sold 1.1127929289957883 shares for $96.92426411553315
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5567308762943993 shares for $50.590134728872066
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5730002292000916 shares for $47.74237909695163
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5737893045673629 shares for $55.15836584806059
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.094935722669386 shares for $100.62459291331659
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.1135237493456243 shares for $100.49551837844258
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5737893045673629 shares for $54.64195547394997
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5567308762943993 shares for $50.24496158556954
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5737893045673629 shares for $53.10993803075511
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.1137718192470587 shares for $100.51790668704705
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5737893045673629 shares for $53.10993803075511
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 235th day, sold 0.5569789461958338 shares for $46.86420853291745

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 103.13167872772547, Final Money: 103.13167872772547, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 1.0409737632567437 shares for $96.3525315270442
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5328786102525844 shares for $48.36406266652457
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.548666739822232 shares for $50.422473389663125
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5420641803989593 shares for $50.81851691240244
On the 221th day, Bought 0.528988573846805 shares for $50.00000000000001
On the 227th day, sold 0.528988573846805 shares for $47.74121878967415
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 235th day, sold 0.5948839976204641 shares for $50.05353955978585
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 1.0409737632567437 shares for $96.3525315270442
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.5328786102525844 shares for $47.90045827560481
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.548666739822232 shares for $50.422473389663125
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5387350501023597 shares for $48.62083827173796
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 74th day, sold 0.5222477543346564 shares for $48.3392521412158
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.5336179295624333 shares for $47.96691568836712
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 177th day, sold 0.5526693931690063 shares for $48.52437272023875
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5387350501023597 shares for $48.62083827173796
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 74th day, sold 0.5222477543346564 shares for $48.3392521412158
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 96th day, sold 0.5336179295624333 shares for $47.96691568836712
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5387350501023597 shares for $45.21603275509105
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 236th day, sold 0.5389673385792821 shares for $45.23552872695915
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 236th day, sold 0.5389673385792821 shares for $45.23552872695915

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 94.72226953106522, Final Money: 94.72226953106522, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5737893045673629 shares for $55.15836584806059
On the 66th day, Bought 0.5230672664504655 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 1.041793275372553 shares for $96.4283855684835
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0679201308875026 shares for $96.92443107934974
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.5636978579481398 shares for $51.80383314543405
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 177th day, sold 1.13748262984328 shares for $99.87097490023999
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.117517062787762 shares for $93.11152167147632
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 74th day, sold 0.5187260089220873 shares for $48.013279385828405
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 118th day, Bought 0.5583472920156337 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.5583472920156337 shares for $51.31211613623674
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 177th day, sold 0.5736576411197798 shares for $50.36714089031666
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.117517062787762 shares for $93.11152167147632
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 74th day, sold 0.5187260089220873 shares for $48.013279385828405
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 177th day, sold 0.5736576411197798 shares for $50.36714089031666
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5569789461958338 shares for $46.86420853291745
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.117517062787762 shares for $94.02788566296229
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 235th day, sold 1.1297548743332761 shares for $95.05757512640186
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 235th day, sold 1.1297548743332761 shares for $95.05757512640186
XLE Final Value: 99.25929733214221, Final Money: 99.25929733214221, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 79th day, Bought 1.1999040076793857 shares for $50.0
On the 88th day, Bought 1.0 shares for $41.94
On the 98th day, sold 2.1999040076793857 shares for $90.83403647708184
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 1.0 shares for $41.43
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.2036591237361582 shares for $96.56434280211846
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2812835348939844 shares for $105.5778019948936
On the 225th day, Bought 0.9920634920634921 shares for $50.0
On the 239th day, sold 0.9920634920634921 shares for $48.36309523809524
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 101th day, sold 1.200192030724916 shares for $49.02784445511283
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.276626291211212 shares for $105.36226475725489
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 101th day, sold 1.1941724385001196 shares for $48.78194411272989
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2604395236624435 shares for $104.61314115509789
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 101th day, sold 1.1853959222380275 shares for $48.42342342342342
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 126th day, sold 2.2068549360366885 shares for $95.53475018102824
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 204th day, sold 2.2294092152559086 shares for $110.46722661593027
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 126th day, sold 1.1976047904191616 shares for $51.8443113772455

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.67540022038193, Final Money: 112.67540022038193, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 39th day, Bought 1.2147716229348884 shares for $50.0
On the 54th day, sold 1.2147716229348884 shares for $50.0242954324587
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.4688340557083066 shares for $100.77780615401308
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.418830948492971 shares for $104.22742557056213
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2784403631861974 shares for $105.44622000825721
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.015524105733302 shares for $97.30950382480383
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4029855572570566 shares for $103.54464766220659
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2758364540624174 shares for $105.32571109400868
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4009742248355277 shares for $103.4579793481629
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2530688101629393 shares for $104.27202453434083
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 1.1930326890956813 shares for $50.0
On the 128th day, sold 2.390637479514843 shares for $103.01256899229459
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 129th day, sold 1.2330456226880395 shares for $53.23057953144267
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 130th day, sold 1.2174336498660823 shares for $51.83832481129778
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 1.0604453870625663 shares for $52.54506892895016

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 109.20328107434105, Final Money: 109.20328107434105, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 43th day, Bought 1.2174336498660823 shares for $50.0
On the 57th day, sold 1.2174336498660823 shares for $50.53567080594107
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 2.4688340557083066 shares for $101.59252139239682
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 130th day, sold 2.4070285581525237 shares for $102.49127600613446
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 202th day, sold 2.2784403631861974 shares for $105.44622000825721
On the 212th day, Bought 0 shares for $0.0
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 215th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 217th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 130th day, sold 2.4070285581525237 shares for $102.49127600613446
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 204th day, sold 2.2758364540624174 shares for $112.76769629879277
On the 212th day, Bought 0 shares for $0.0
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 215th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 217th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 130th day, sold 2.4070285581525237 shares for $102.49127600613446
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 204th day, sold 2.2758364540624174 shares for $112.76769629879277
On the 212th day, Bought 0 shares for $0.0
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 215th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 130th day, sold 2.4044597264558503 shares for $102.3818951524901
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 204th day, sold 2.1899305613906623 shares for $108.5110593169073
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 215th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 240th day, sold 1.0501995379122033 shares for $50.703633690401176
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 115.59189462305301, Final Money: 115.59189462305301, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 57th day, sold 2.2330456226880395 shares for $92.69372379778052
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.450479272554122 shares for $100.02856390565925
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4029855572570566 shares for $103.54464766220659
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2784403631861974 shares for $105.44622000825721
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.015524105733302 shares for $97.30950382480383
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 57th day, sold 1.2330456226880395 shares for $51.183723797780516
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.450479272554122 shares for $100.02856390565925
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 129th day, sold 2.4029855572570566 shares for $103.73688650678714
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.2784403631861974 shares for $112.89671999587607
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.015524105733302 shares for $97.30950382480383
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 129th day, sold 2.430650413107201 shares for $104.93117833383786
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.2758364540624174 shares for $112.76769629879277
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 130th day, sold 1.2330456226880395 shares for $52.50308261405672
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 130th day, sold 1.2174336498660823 shares for $51.83832481129778
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 130th day, sold 1.2174336498660823 shares for $51.83832481129778
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 1.0604453870625663 shares for $52.54506892895016
XLF Final Value: 116.74005347800812, Final Money: 67.69887463263063, Final Shares: 1.0092854259184498

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 220th day, Bought 0.34724633655114934 shares for $49.99999999999999
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.6977545734947175 shares for $92.8850888236168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 98th day, sold 0.7973563487023718 shares for $97.43694581142984
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7105312176540179 shares for $94.58591569410287
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.7991369435960733 shares for $100.8031340652087
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7807623283395755 shares for $110.42321609706616
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.7991369435960733 shares for $100.8031340652087
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7773824257425743 shares for $109.9451964727723
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 130th day, sold 0.399616368286445 shares for $49.228740409207155
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 131th day, sold 0.39939292275740873 shares for $49.59661314801502

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 113.06519313748147, Final Money: 113.06519313748147, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 50th day, sold 0.41145490454246214 shares for $51.826859776168526
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 72th day, sold 0.8293256196834445 shares for $100.77964930393217
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7973563487023718 shares for $96.63958946272747
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.41044163519947463 shares for $51.2518469873584
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.782632814641483 shares for $104.73974958346969
On the 201th day, Bought 0.3731064845907022 shares for $50.0
On the 202th day, Bought 0.37352457791722693 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7466310625079291 shares for $105.59603117049642
On the 230th day, Bought 0.3638215818962381 shares for $50.0
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.7273257621943114 shares for $96.92343107001393
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 72th day, sold 0.4142845306156268 shares for $50.343856160410965
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7973563487023718 shares for $96.63958946272747
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.41473125414731254 shares for $51.78749170537492
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39013732833957554 shares for $55.177122347066174
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 239th day, sold 0.7303689539425081 shares for $97.32896680237863
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3995205753096284 shares for $48.421893727526964
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.41473125414731254 shares for $51.78749170537492
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7807623283395755 shares for $110.42321609706616
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 240th day, sold 0.3668647736444347 shares for $48.39680093917382
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3995205753096284 shares for $49.344786256492206
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 128th day, sold 0.4124731892426992 shares for $52.029368091074076
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7773824257425743 shares for $109.9451964727723
On the 151th day, Bought 0.390625 shares for $50.0
On the 204th day, sold 0.390625 shares for $55.24609375
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 204th day, sold 0.3869370066553165 shares for $54.72450085126142

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 111.25344210391083, Final Money: 111.25344210391083, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 72th day, sold 0.4119294776734223 shares for $50.05767012687428
On the 77th day, Bought 0.40209087253719344 shares for $50.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8041817450743869 shares for $97.4668275030157
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.41044163519947463 shares for $51.77310786406173
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 201th day, Bought 0.3731064845907022 shares for $50.0
On the 203th day, Bought 0.36737692872887584 shares for $50.0
On the 204th day, sold 0.7404834133195781 shares for $104.72656914578793
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 228th day, Bought 0.3605422555523507 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.7110504924959189 shares for $93.80178097006161
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 72th day, sold 0.4119294776734223 shares for $50.05767012687428
On the 77th day, Bought 0.40209087253719344 shares for $50.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8041817450743869 shares for $97.4668275030157
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.41044163519947463 shares for $51.67460187161386
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39013732833957554 shares for $52.2120786516854
On the 201th day, Bought 0.3731064845907022 shares for $50.0
On the 203th day, Bought 0.36737692872887584 shares for $50.0
On the 204th day, sold 0.7404834133195781 shares for $104.72656914578793
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.7173730105880028 shares for $94.63584755676932
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 72th day, sold 0.4062728528479727 shares for $49.37027707808564
On the 77th day, Bought 0.40209087253719344 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.40209087253719344 shares for $48.73341375150785
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 129th day, sold 0.4137702747434624 shares for $52.09367759020192
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.7773824257425743 shares for $104.03709003712873
On the 201th day, Bought 0.3731064845907022 shares for $50.0
On the 203th day, Bought 0.36737692872887584 shares for $50.0
On the 204th day, sold 0.7404834133195781 shares for $104.72656914578793
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 237th day, Bought 0.3726893261776983 shares for $50.0
On the 240th day, sold 0.739554099822133 shares for $97.56197684853578
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 72th day, sold 0.4062728528479727 shares for $49.37027707808564
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 92th day, sold 0.40209087253719344 shares for $48.73341375150785
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 130th day, sold 0.4137702747434624 shares for $50.97236014564713
On the 179th day, Bought 0.36965843560550055 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.36965843560550055 shares for $49.471388437084144
On the 201th day, Bought 0.3731064845907022 shares for $50.0
On the 206th day, sold 0.3731064845907022 shares for $53.01470039549288
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 242th day, sold 0.3668647736444347 shares for $48.16934477951428

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 106.52300445124786, Final Money: 106.52300445124786, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 52th day, sold 0.4132231404958678 shares for $51.40909090909091
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8250044961264706 shares for $103.58756453363965
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.7303689539425081 shares for $98.05933575632113
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 55th day, sold 0.41145490454246214 shares for $51.70753785385122
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8272044433900118 shares for $103.86378991204988
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.37752944729688914 shares for $50.0
On the 238th day, sold 0.7443942209413239 shares for $99.94236810358214
On the 33th day, Bought 0.41335978835978837 shares for $50.0
On the 55th day, sold 0.41335978835978837 shares for $51.94692460317461
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7807623283395755 shares for $110.42321609706616
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 73th day, sold 0.4142845306156268 shares for $50.21957080122628
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 95th day, sold 0.7991369435960733 shares for $97.49470711872095
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39013732833957554 shares for $55.177122347066174
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.3995205753096284 shares for $48.741510187774665
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 127th day, sold 0.41473125414731254 shares for $51.78749170537492
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.3995205753096284 shares for $48.741510187774665
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 205th day, sold 0.3869370066553165 shares for $54.3956043956044
XLI Final Value: 115.21378909048528, Final Money: 115.21378909048528, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 38th day, sold 0.24321432045918862 shares for $51.32308590329799
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 107th day, sold 0.24211902571304053 shares for $55.39925427340081
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44852140323780454 shares for $100.3521787604264
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4340538421757886 shares for $100.91317776744908
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 64th day, sold 0.23978515250335697 shares for $47.136965279109916
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44986315601546684 shares for $102.06945146834927
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4340538421757886 shares for $100.91317776744908
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 65th day, sold 0.23978515250335697 shares for $46.16583541147132
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.23999232024575212 shares for $53.84467697033695
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44656903590256103 shares for $101.32204855593207
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 229th day, Bought 0.21005755577028107 shares for $50.0
On the 234th day, sold 0.4189392034287178 shares for $97.39917540514261
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 125th day, sold 0.24077819512664933 shares for $54.020995858615045
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44656903590256103 shares for $101.32204855593207
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.44656903590256103 shares for $104.20688452786261
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 177th day, Bought 0.22147413182140327 shares for $50.0
On the 205th day, sold 0.4435976324877738 shares for $105.31894990524725

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 109.1817241886294, Final Money: 109.1817241886294, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 62th day, sold 0.23819732266209329 shares for $48.05869182030394
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21590810950859313 shares for $50.196476379652815
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 62th day, sold 0.23819732266209329 shares for $48.05869182030394
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2229654403567447 shares for $49.92419175027871
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2229654403567447 shares for $49.92419175027871
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 201th day, sold 0.4314815234313326 shares for $96.61302791150969

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 99.90866704817657, Final Money: 99.90866704817657, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.24211902571304053 shares for $54.91743741223185
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.43762033266453315 shares for $98.19325024326794
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.45094085562377617 shares for $100.97016698271972
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 234th day, sold 0.4340538421757886 shares for $100.91317776744908
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.24211902571304053 shares for $54.91743741223185
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 168th day, Bought 0.228133412419583 shares for $50.0
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4583677910169952 shares for $102.63313208661539
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.23999232024575212 shares for $53.00710377267927
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44301649220077255 shares for $99.19582276867499
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 127th day, sold 0.23999232024575212 shares for $53.00710377267927
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 201th day, sold 0.44301649220077255 shares for $99.19582276867499

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 103.67506438943515, Final Money: 103.67506438943515, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 62th day, sold 0.23819732266209329 shares for $48.05869182030394
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4266667367659256 shares for $95.72694906080307
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22295549808258272 shares for $49.921965575671095
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 65th day, sold 0.23978515250335697 shares for $46.16583541147132
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2132468972576449 shares for $47.84833880667036
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22693232877955793 shares for $50.81241773703081
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.21718356354791069 shares for $48.59265050820954
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 111th day, sold 0.23955538520505942 shares for $54.197010348792645
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.21718356354791069 shares for $48.59265050820954
XLK Final Value: 101.72012830106496, Final Money: 101.72012830106496, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 94th day, Bought 0.6464959917248513 shares for $50.0
On the 97th day, sold 0.6464959917248513 shares for $50.30385311611068
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.227685713783603 shares for $99.2215593879908
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 219th day, sold 0.6232859636000997 shares for $51.60807778608825
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 232th day, sold 0.6069434328720563 shares for $49.44768147608643
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 58th day, sold 1.3424622931916024 shares for $99.75837300706797
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2179045405798123 shares for $98.43104496966042
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.6232859636000997 shares for $50.006232859636
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 60th day, sold 0.6693440428380187 shares for $49.11646586345381
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 189th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.606134076857801 shares for $48.98775609164747
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.6232859636000997 shares for $50.006232859636
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 60th day, sold 0.6693440428380187 shares for $49.11646586345381
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 189th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.606134076857801 shares for $48.98775609164747
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 70th day, sold 0.6637461834594451 shares for $50.17257400769946
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2403224847690706 shares for $100.24286321903628
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.91505344278146, Final Money: 100.91505344278146, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.3027624078912101 shares for $100.45600927249122
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.6422607578676943 shares for $50.0
On the 138th day, sold 1.2833685922054299 shares for $99.7177396143619
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.2400059548577866 shares for $102.98249455093918
On the 178th day, Bought 0.6044487427466151 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.214056155572755 shares for $98.56921927095198
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 205th day, sold 0.616827041697508 shares for $49.253639279546015
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 228th day, Bought 0.6096817461285209 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.214349783376072 shares for $96.2979378217225
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.2400059548577866 shares for $102.98249455093918
On the 228th day, Bought 0.6096817461285209 shares for $50.0
On the 239th day, sold 0.6096817461285209 shares for $48.34776246799171
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2348803404304947 shares for $98.60519518337499
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.227685713783603 shares for $99.2215593879908
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 240th day, sold 0.6126700159294204 shares for $48.01494914838868
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 103.45541901098824, Final Money: 103.45541901098824, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 89th day, Bought 0.6501950585175552 shares for $50.0
On the 95th day, sold 1.2927034111261393 shares for $99.93890071416183
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6443298969072165 shares for $49.90335051546392
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.6210408644888833 shares for $51.937647497205305
On the 180th day, Bought 0.6157635467980296 shares for $50.00000000000001
On the 185th day, sold 0.6157635467980296 shares for $49.99384236453202
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 95th day, sold 0.642508352608584 shares for $49.67232074016963
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6443298969072165 shares for $50.483247422680414
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 138th day, sold 1.2778882724426772 shares for $99.29191876879602
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6189650903689032 shares for $51.15746471898986
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 95th day, sold 0.642508352608584 shares for $49.67232074016963
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6443298969072165 shares for $50.483247422680414
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6159152500615914 shares for $51.151761517615164
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 95th day, sold 0.642508352608584 shares for $49.67232074016963
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 186th day, sold 1.227685713783603 shares for $100.22826167329335
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.642508352608584 shares for $50.34052942688255
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.10968479547452, Final Money: 101.10968479547452, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 71th day, Bought 0.6593696426216538 shares for $50.00000000000001
On the 88th day, sold 0.6593696426216538 shares for $51.31214558881709
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.3027624078912101 shares for $101.79785455261916
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 192th day, Bought 0.6131207847946045 shares for $50.0
On the 205th day, sold 0.6131207847946045 shares for $48.95769466584917
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2205365144262603 shares for $96.78854559400244
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.3027624078912101 shares for $101.79785455261916
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 186th day, sold 1.2400059548577866 shares for $101.2340861545897
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 129th day, sold 0.6518055012384305 shares for $50.7495763264242
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 186th day, sold 1.2400059548577866 shares for $101.2340861545897
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
XLP Final Value: 103.0856680409899, Final Money: 103.0856680409899, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 80th day, Bought 0.3482136639041716 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3482136639041716 shares for $50.38999930357267
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.34220792553555535 shares for $49.41824652658955
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.32379225488926305 shares for $47.87268488537754
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 112th day, Bought 0.34277096044423117 shares for $50.0
On the 117th day, sold 0.34277096044423117 shares for $49.499554397751425
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.32379225488926305 shares for $47.87268488537754
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 83th day, Bought 0.34199726402188785 shares for $50.0
On the 95th day, sold 0.34199726402188785 shares for $49.49042407660739
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 83th day, Bought 0.34199726402188785 shares for $50.0
On the 95th day, sold 0.34199726402188785 shares for $49.49042407660739
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32324799586242564 shares for $47.85363330747349
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 93.28702453021037, Final Money: 45.937971783856284, Final Shares: 0.34073872154831675
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.3550379890648299 shares for $50.28403039125186
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.34234851078397804 shares for $50.44505306401916
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.32324799586242564 shares for $49.74463408326868
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6890405585234674 shares for $97.80930728240618
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3550379890648299 shares for $51.01895902861605
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.34265350877192985 shares for $50.80523574561404
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.32324799586242564 shares for $49.74463408326868
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6446859841239713 shares for $99.75870918334331
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3359989248034406 shares for $47.65808749412002
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6446859841239713 shares for $99.75870918334331
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6780012584497679 shares for $96.16769849851508
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 78th day, Bought 0.3519144144144144 shares for $50.0
On the 95th day, sold 0.3519144144144144 shares for $50.92553490990991
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3375641371860653 shares for $47.880097218471505
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 189th day, sold 0.321646831778707 shares for $49.302026375040214
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.34043712126370257 shares for $48.321644992169944

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 96.74563597140826, Final Money: 96.74563597140826, Final Shares: 0.0
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 63th day, Bought 0.361167292689974 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.361167292689974 shares for $51.12684195319272
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 121th day, sold 0.6839719051540245 shares for $100.78326022444551
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.6470402507516887 shares for $99.13303681766622
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6729261485231172 shares for $101.06004898520175
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 64th day, Bought 0.3611933829372246 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3611933829372246 shares for $51.130535288593514
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.6470402507516887 shares for $99.13303681766622
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6729261485231172 shares for $101.06004898520175
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6470402507516887 shares for $98.11718362398607
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 187th day, sold 0.32303915234526426 shares for $49.98707843390619
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6735630619895059 shares for $95.53818471259152
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 93th day, sold 0.3584743332377402 shares for $50.770719816461146
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6735630619895059 shares for $95.53818471259152

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 96.76581381858132, Final Money: 49.63196943895986, Final Shares: 0.3391900142459806
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6849785388796403 shares for $101.56176795968427
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.64628714820769 shares for $100.00647331365795
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6729261485231172 shares for $98.80574638764931
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.680342388781481 shares for $94.78530160503593
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 109th day, Bought 0.33992793527772114 shares for $50.0
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6809222747716855 shares for $100.68797677048914
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.64628714820769 shares for $100.00647331365795
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 210th day, sold 0.6729261485231172 shares for $97.2512869845609
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 127th day, sold 0.3409943394939644 shares for $50.422832980972515
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 210th day, sold 0.6729261485231172 shares for $97.2512869845609
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3375641371860653 shares for $47.880097218471505
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.6780012584497679 shares for $96.23549862436005
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 54th day, sold 0.34298257648511454 shares for $48.68637673206201
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.3375641371860653 shares for $47.91385363219011
XLV Final Value: 97.3507388863816, Final Money: 97.3507388863816, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 109th day, sold 0.2811041772080733 shares for $51.00354191263282
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.26996382484747045 shares for $53.97926677825171
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.44039044105953584 shares for $100.80977586293835
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.2811041772080733 shares for $53.21302074548828
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.5427999546785756 shares for $108.53285093798118
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.44039044105953584 shares for $100.92427737761382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.2798298634430266 shares for $52.99697783747481
On the 174th day, Bought 0.250388101557414 shares for $50.0
On the 175th day, Bought 0.24932681759250025 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.4997149191499142 shares for $98.38887043142661
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.43407487791644056 shares for $99.47693977211068
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.2798298634430266 shares for $54.48287441235728
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.49849274560048373 shares for $98.14823668127923
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 236th day, sold 0.43023815087518835 shares for $98.59767703606691
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 124th day, sold 0.5595040089152501 shares for $108.93543053579918
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.49849274560048373 shares for $109.39921794948216
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 238th day, sold 0.21477663230240548 shares for $50.17182130584192
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.28123066539175434 shares for $54.755610551774566
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.500089566712886 shares for $109.74965631080995

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 118.50646979112327, Final Money: 118.50646979112327, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 68th day, Bought 0.0 shares for $0.0
On the 71th day, sold 0.2932379332590464 shares for $52.782827986628355
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5592375192127947 shares for $105.9755098908246
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 71th day, sold 0.2897878752752985 shares for $52.161817549553724
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5592375192127947 shares for $105.9755098908246
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5384461385482882 shares for $108.37843876699944
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.43023815087518835 shares for $98.23627698933176
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 71th day, sold 0.2897878752752985 shares for $52.161817549553724
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5592375192127947 shares for $105.9755098908246
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5413167363714689 shares for $108.95623269684927
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 76th day, sold 0.2897878752752985 shares for $52.10675785325142
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.5610292104393202 shares for $105.36689601260872
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5130302364012908 shares for $103.2627259828518
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 77th day, sold 0.2897878752752985 shares for $51.732931494146285
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.5130302364012908 shares for $102.72404423463044
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 235th day, sold 0.25362686415745156 shares for $58.057725474282236

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 117.09356013722758, Final Money: 117.09356013722758, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2711349709885581 shares for $49.18117238761455
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.2897878752752985 shares for $51.53877361771183
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5610292104393202 shares for $97.59664144802414
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.282326369282891 shares for $53.50084697910785
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5413167363714689 shares for $106.86675009445538
On the 227th day, Bought 0.21510927551196007 shares for $50.0
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2711349709885581 shares for $49.18117238761455
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.2897878752752985 shares for $50.411498782890924
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.28028476932563484 shares for $52.64028252704748
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.5199806235127767 shares for $102.21779097014166
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.2797985450475658 shares for $52.54896474538333
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.25889297364469527 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.5191063486121685 shares for $102.0459260101801
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.2814364516492176 shares for $52.85657998423956
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 127th day, sold 0.2814364516492176 shares for $52.85657998423956
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 127th day, sold 0.26452227277536766 shares for $49.6799280499418

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 108.05043894859033, Final Money: 108.05043894859033, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 55th day, sold 0.2808199943836001 shares for $50.22184779556304
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 72th day, sold 0.2897878752752985 shares for $50.89254665584792
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5609340406510999 shares for $105.32658481305702
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 72th day, sold 0.2897878752752985 shares for $50.89254665584792
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5609340406510999 shares for $105.32658481305702
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 72th day, sold 0.2897878752752985 shares for $50.89254665584792
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.561060528834781 shares for $106.320970214191
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5344021379900944 shares for $107.31329332979085
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5130302364012908 shares for $103.2627259828518
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 197th day, sold 0.5130302364012908 shares for $103.2627259828518
XLY Final Value: 114.52681019982975, Final Money: 114.52681019982975, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5665395111523086 shares for $99.64757830439835
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 106th day, sold 1.3829348252326872 shares for $95.69908990610196
On the 111th day, Bought 0.7268498328245384 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.7268498328245384 shares for $50.95944177932839
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.6687174000267487 shares for $53.778253310151136
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 240th day, sold 1.2317703413278247 shares for $93.31892105899601
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5656803264655523 shares for $99.59292556647378
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.3829348252326872 shares for $96.9575605970637
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.6640106241699868 shares for $54.07038512616203
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 240th day, sold 0.651890482398957 shares for $49.38722294654498
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6923289947382997 shares for $51.3846579894766
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6923289947382997 shares for $51.3846579894766
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6861534239055852 shares for $50.92630712227253
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 62th day, sold 0.7793017456359103 shares for $48.91677057356609
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6861534239055852 shares for $50.92630712227253

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 100.8776594536358, Final Money: 100.8776594536358, Final Shares: 0.0
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 53th day, sold 0.7803964413922273 shares for $50.80380833463399
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 62th day, sold 0.772916988715412 shares for $48.51599938166642
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7452675510508272 shares for $52.54881502459383
On the 108th day, Bought 0.7205649228995532 shares for $50.0
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4375135893750337 shares for $100.78407775108361
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2393426438767075 shares for $94.7849254036906
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 66th day, sold 0.7803964413922273 shares for $51.529577025128766
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4461366287071211 shares for $103.96276223775494
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.452026584734816 shares for $101.80158385575794
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 217th day, Bought 0.6127450980392157 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2382141998655856 shares for $94.47574344974417
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 66th day, sold 0.7803964413922273 shares for $51.529577025128766
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4461366287071211 shares for $103.96276223775494
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.7306736811340054 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.465751599393341 shares for $102.76384463346713
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 67th day, sold 0.7803964413922273 shares for $51.77149992196036
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 67th day, sold 0.7803964413922273 shares for $51.77149992196036
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 172th day, sold 1.3360068701989094 shares for $107.32143188307839
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 68th day, sold 0.7803964413922273 shares for $52.083658498517245
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 172th day, sold 0.6672894701721607 shares for $53.603363138929666

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 115.12646393069784, Final Money: 15.81575337595757, Final Shares: 1.2884108790184259
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 76th day, sold 0.7554011179936546 shares for $51.941380873243695
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4124102758916717 shares for $102.71047526284237
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.4377552142113674 shares for $101.33298749761718
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.3487087648370697 shares for $103.90452324304786
On the 186th day, Bought 0.6309148264984227 shares for $50.0
On the 187th day, Bought 0.6230529595015576 shares for $50.0
On the 189th day, sold 1.2539677859999803 shares for $103.08869168705837
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 63th day, sold 0.7803964413922273 shares for $50.007803964413924
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 72th day, Bought 0.7491759065028469 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.494443457553674 shares for $108.67592823330317
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.4346336218846245 shares for $102.5619576285318
On the 187th day, Bought 0.6230529595015576 shares for $50.0
On the 189th day, sold 0.6230529595015576 shares for $51.221183800623045
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 63th day, sold 0.7880220646178092 shares for $50.49645390070921
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 72th day, Bought 0.7491759065028469 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.494443457553674 shares for $108.67592823330317
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 65th day, sold 0.7880220646178092 shares for $51.56028368794326
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 72th day, Bought 0.7491759065028469 shares for $50.0
On the 95th day, sold 1.494443457553674 shares for $107.43554016353363
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 65th day, sold 0.7880220646178092 shares for $51.56028368794326
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 95th day, sold 0.7452675510508272 shares for $53.57728424504397
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 95th day, sold 0.7452675510508272 shares for $53.57728424504397
On the 224th day, Bought 0.6196554715578139 shares for $50.0
XLU Final Value: 108.59232169127557, Final Money: 12.466873626871944, Final Shares: 1.2470867678308721

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 53th day, sold 0.7843137254901961 shares for $51.05882352941176
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 67th day, sold 1.5442838507950172 shares for $102.44779066174145
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, sold 1.4024265352120677 shares for $98.88509499780291
On the 108th day, Bought 0.7205649228995532 shares for $50.0
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4375135893750337 shares for $100.7265772075086
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.346354675156112 shares for $107.81608238650145
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2469731416026284 shares for $94.84477715029593
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 68th day, sold 0.7843137254901961 shares for $52.345098039215685
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4024265352120677 shares for $100.82044361639555
On the 108th day, Bought 0.7205649228995532 shares for $50.0
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4375135893750337 shares for $100.78407775108361
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3389713616283672 shares for $107.22482663919963
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2317703413278247 shares for $94.20579570475203
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 110th day, Bought 0.7237984944991315 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4407471609746119 shares for $101.01078345593004
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 95th day, sold 0.7803964413922273 shares for $56.10270017168722
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 96th day, sold 0.7803964413922273 shares for $56.07928827844545
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 172th day, sold 0.6672894701721607 shares for $53.603363138929666
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 96th day, sold 0.7803964413922273 shares for $56.07928827844545
On the 230th day, Bought 0.6439979392065945 shares for $50.0
XLU Final Value: 112.97298020603421, Final Money: 13.662269651293947, Final Shares: 1.2884108790184259

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 48th day, Bought 0.0963743952506698 shares for $50.0
On the 57th day, sold 0.0963743952506698 shares for $50.04915094157785
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19198464209553492 shares for $106.10223230051832
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17726270862194415 shares for $101.00606399987
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 57th day, sold 0.09557122923715046 shares for $49.63205076743698
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.174860422392223 shares for $99.63721728331258
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 58th day, sold 0.09557122923715046 shares for $49.135080375403795
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.174860422392223 shares for $100.842005593595
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 58th day, sold 0.09558950044927064 shares for $49.14447397097902
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17463810735127167 shares for $100.71379650947837
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 60th day, sold 0.09575609008732956 shares for $48.916998621112306
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 127th day, sold 0.09457337948514251 shares for $51.91983960354839
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
SPY Final Value: 105.17772181752787, Final Money: 105.17772181752787, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.1791071512121006 shares for $105.85949065239994
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 60th day, sold 0.09575609008732956 shares for $48.916998621112306
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17825237578963055 shares for $105.35428418670323
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 61th day, sold 0.09636882275846118 shares for $48.61325264050574
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17582727512007773 shares for $103.92095268697074
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 61th day, sold 0.09636882275846118 shares for $48.61325264050574
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17397879621992118 shares for $102.82842771782221
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 236th day, sold 0.08298066550493735 shares for $49.347771969131195
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 106.14237448352102, Final Money: 106.14237448352102, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17810733160127143 shares for $102.6129769554405
On the 193th day, Bought 0.08571624494274153 shares for $49.99999999999999
On the 194th day, Bought 0.08650668696690254 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17222293190964408 shares for $102.57770047470311
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.166739304078092 shares for $98.56793960576408
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.1791071512121006 shares for $103.18900302782752
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17243352818983582 shares for $103.1480122278779
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.166739304078092 shares for $99.15819674220054
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17825237578963055 shares for $106.6287886735991
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1664768163323842 shares for $99.00209790470556
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 61th day, sold 0.09749439407234084 shares for $49.18104708979234
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17825237578963055 shares for $106.6287886735991
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 238th day, sold 0.1664768163323842 shares for $100.10916873331593
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18867154268899677 shares for $103.57879022083235
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 238th day, sold 0.1664768163323842 shares for $100.10916873331593
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18867154268899677 shares for $103.57879022083235

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.73202122063051, Final Money: 107.73202122063051, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.19153335798089574 shares for $106.67258839388009
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1791071512121006 shares for $102.05704583216703
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17748175238222522 shares for $101.13087732491574
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17582727512007773 shares for $101.39958956174884
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 235th day, sold 0.08298066550493735 shares for $49.05402041324371
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 61th day, sold 0.09636882275846118 shares for $48.61325264050574
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 204th day, sold 0.1759511625304509 shares for $103.9941751019977
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
SPY Final Value: 106.68444591633644, Final Money: 106.68444591633644, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.5710370031978073 shares for $53.140703517587944
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.0966471303772733 shares for $99.38912942609228
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0890283040146238 shares for $99.0144534010096
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.0915254873792657 shares for $98.92495492118285
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 58th day, sold 0.5397236614853195 shares for $49.44408462867012
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5260389268805892 shares for $47.6749079431878
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5260389268805892 shares for $45.01841136244082
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.524824183898394 shares for $44.91445365802456
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.524824183898394 shares for $44.91445365802456

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 101.19579728740513, Final Money: 101.19579728740513, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 47th day, Bought 0.5470459518599562 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 55th day, sold 1.0867696133452758 shares for $100.81961703004123
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.0844228128268467 shares for $99.25722005804128
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0691805544395634 shares for $103.62497933628248
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 47th day, Bought 0.5470459518599562 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, sold 1.0867696133452758 shares for $100.8956909029754
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619240278714318 shares for $51.60148347943358
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0554195515497262 shares for $96.33869666545901
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, sold 1.0871888974428363 shares for $100.93461723859292
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0554195515497262 shares for $96.33869666545901
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 176th day, sold 0.5357334190506804 shares for $51.923282974391945
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0554195515497262 shares for $89.78454125033521
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 176th day, sold 0.5357334190506804 shares for $51.923282974391945
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0554195515497262 shares for $89.78454125033521
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0554195515497262 shares for $89.78454125033521

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 97.4651268750753, Final Money: 97.4651268750753, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5619871866921434 shares for $50.06743846240306
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.089819163774012 shares for $99.18444209507284
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619240278714318 shares for $51.60148347943358
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.0691805544395634 shares for $103.80674003053721
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.0938814610365155 shares for $92.91429130044162
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5425935973955507 shares for $49.38144329896907
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 163th day, sold 0.5514503143266791 shares for $50.07168854086246
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 175th day, sold 1.0691805544395634 shares for $103.80674003053721
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5441288497116117 shares for $46.218304494504295
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5653550429669832 shares for $47.04319312528267
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0547562682543004 shares for $98.69354402055488
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.5851375073142189 shares for $50.00000000000001
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.1536423396052933 shares for $95.99457907855644
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0547562682543004 shares for $98.69354402055488
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 0.5253756435851634 shares for $49.43259430492803

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 99.35694574301522, Final Money: 50.149563748457076, Final Shares: 0.5915059742103396
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 33th day, Bought 0.5673436968115284 shares for $49.99999999999999
On the 35th day, Bought 0.5563591854901524 shares for $50.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.1237028823016808 shares for $104.32457559288805
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1197107302364473 shares for $100.37086985839514
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.078769803289314 shares for $92.32111976549949
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, sold 0.5397236614853195 shares for $50.107944732297064
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 0.5471656817684395 shares for $49.78660538411031
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 154th day, Bought 0.5367686527106816 shares for $50.0
On the 155th day, Bought 0.5390835579514824 shares for $49.99999999999999
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.075852210662164 shares for $104.27159625737693
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.078769803289314 shares for $92.32111976549949
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 155th day, Bought 0.5390835579514824 shares for $49.99999999999999
On the 158th day, Bought 0.5426524853483828 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0817360432998653 shares for $98.7408660324117
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5441288497116117 shares for $46.2890412449668
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0634936048222658 shares for $90.47140096223015
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0651140437198174 shares for $90.60925169924487
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0651140437198174 shares for $90.60925169924487
XLB Final Value: 100.69946955361652, Final Money: 100.69946955361652, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.066726863235409 shares for $96.3787720933192
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.5482456140350876 shares for $49.523026315789465
On the 154th day, Bought 0.5534034311012729 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.5534034311012729 shares for $49.695628112894305
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5534646889528448 shares for $50.29333628514501
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5730002292000916 shares for $48.0919092367637
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.5265374894692503 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.0604403191542475 shares for $95.78957402920318
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5534646889528448 shares for $50.03320788133718
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5730002292000916 shares for $48.0919092367637
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0825695695072293 shares for $97.79933490928309
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5551237926057512 shares for $46.5915399134007
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 118th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5549389567147615 shares for $50.13318534961155
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108956313651387 shares for $93.07470340476091
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 135th day, sold 0.5549389567147615 shares for $51.72586015538291
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108956313651387 shares for $93.07470340476091
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1106253940968607 shares for $93.21478932654952
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 96.52735244246198, Final Money: 44.800563560143814, Final Shares: 0.5913660555884093
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 62th day, sold 0.5130309870716192 shares for $48.430125179560854
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5336179295624333 shares for $48.43116328708645
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5636978579481398 shares for $50.924464487034946
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5526693931690063 shares for $48.52437272023875
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5569789461958338 shares for $46.86420853291745
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5679236710586096 shares for $51.30622444343479
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 137th day, sold 0.5549389567147615 shares for $49.05660377358492
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5569789461958338 shares for $47.14269800601537
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.117517062787762 shares for $94.50841799996103
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 238th day, sold 1.1297548743332761 shares for $95.54336972236516

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 96.43185617433858, Final Money: 45.37535372278592, Final Shares: 0.5837030119075415
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5336179295624333 shares for $49.73319103521878
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5339028296849972 shares for $49.759743726641744
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.546268982847154 shares for $50.917731891183216
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 226th day, sold 1.077702388681642 shares for $97.93081605950081
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.546268982847154 shares for $50.917731891183216
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 226th day, sold 1.077702388681642 shares for $97.93081605950081
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.546268982847154 shares for $50.917731891183216
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 227th day, sold 0.5389673385792821 shares for $48.641802306780214
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608

[*********************100%***********************]  1 of 1 completed

On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
XLE Final Value: 100.85258293442138, Final Money: 49.79608048286872, Final Shares: 0.5837030119075415
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5343022013250694 shares for $48.4932677922633
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5636978579481398 shares for $50.924464487034946
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5490282200505107 shares for $51.130998133304054
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5208875924575477 shares for $43.71809563496198
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5343022013250694 shares for $48.4932677922633
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.5636978579481398 shares for $51.967305524239
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5490282200505107 shares for $51.130998133304054
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 236th day, sold 0.5242189138184106 shares for $43.9976934367792
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.5636978579481398 shares for $51.967305524239
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5490282200505107 shares for $46.46974854507522
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5490282200505107 shares for $46.43131656967169
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 177th day, sold 0.562429696287964 shares for $49.38132733408324
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
XLE Final Value: 96.4850368138649, Final Money: 96.4850368138649, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.228803145736053 shares for $93.05253133448022
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, sold 2.3943644692250357 shares for $98.86330893430171
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.4044597264558503 shares for $104.56995350356493
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.276626291211212 shares for $100.80901217483246
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 101th day, sold 1.200192030724916 shares for $49.02784445511283
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 165th day, sold 2.2604395236624435 shares for $100.31830606013925
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 1.072271070126528 shares for $49.62470512545571
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.391777228919281 shares for $104.8076781712429
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.2379022564825797 shares for $104.53241440030129
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.3830007126571893 shares for $104.42309122863803
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 204th day, sold 1.1133377866844802 shares for $55.165887330215995
On the 85th day, Bought 1.1767474699929394 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.374352260412101 shares for $104.04411605125826
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 1.1976047904191616 shares for $52.47904191616766

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 109.58897855885402, Final Money: 109.58897855885402, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 52th day, sold 2.2330456226880395 shares for $93.05101109741061
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4688340557083066 shares for $102.11097654409556
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 185th day, sold 2.2784403631861974 shares for $103.9652337721862
On the 191th day, Bought 1.0499790004199916 shares for $50.0
On the 192th day, Bought 1.0584250635055037 shares for $50.0
On the 194th day, Bought 0.25 shares for $11.7775
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.3584040639254953 shares for $109.14694007847193
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.015524105733302 shares for $98.25680015449848
On the 39th day, Bought 1.2147716229348884 shares for $50.0
On the 56th day, sold 1.2147716229348884 shares for $50.71671525753159
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 1.1976047904191616 shares for $51.604790419161674
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2294092152559086 shares for $104.33635127397652
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.015524105733302 shares for $98.25680015449848
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.132716457189094 shares for $99.61918571530258
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 107.50163125964536, Final Money: 107.50163125964536, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.422873949388438 shares for $104.4016384791478
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.25 shares for $11.7875
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.3615453243694313 shares for $110.14247392859028
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.0058969467476304 shares for $97.78747615394698
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.020407771722292 shares for $98.49487887146174
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 108.47439130977952, Final Money: 108.47439130977952, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.237623762376238 shares for $93.42079207920793
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4688340557083066 shares for $102.11097654409556
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.3972209132598525 shares for $102.72091613318469
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 185th day, sold 2.2615618513896103 shares for $103.19506727890793
On the 191th day, Bought 1.0499790004199916 shares for $50.0
On the 192th day, Bought 1.0584250635055037 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.1084040639254953 shares for $97.57694007847192
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 239th day, sold 1.0062386798148522 shares for $49.054135640974046
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.2330456226880395 shares for $90.66165228113441
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.235788433020267 shares for $92.47220958971825
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 185th day, sold 2.2294092152559086 shares for $101.72794249212711
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 59th day, sold 1.2330456226880395 shares for $50.06165228113441
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626
XLF Final Value: 107.21882775484207, Final Money: 107.21882775484207, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7959566428887224 shares for $96.86792343955752
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 220th day, Bought 0.34724633655114934 shares for $49.99999999999999
On the 221th day, Bought 0.3498215909885958 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.6970679275397451 shares for $92.79368251409088
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 236th day, sold 0.7105312176540179 shares for $94.58591569410287
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7807623283395755 shares for $109.75956811797754
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7966308196124732 shares for $99.47529044500953
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7739341331918541 shares for $108.79966044411086
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 127th day, sold 0.39701445132602825 shares for $49.57519453708115
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 128th day, sold 0.39939292275740873 shares for $50.37942327661954

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 111.38664124002584, Final Money: 111.38664124002584, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 51th day, sold 0.4132231404958678 shares for $51.64876033057851
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4102732419791581 shares for $51.513908262903094
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.7303689539425081 shares for $98.05933575632113
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4102732419791581 shares for $51.513908262903094
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 239th day, sold 0.3668647736444347 shares for $48.88839973585736
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.82697056674124 shares for $100.24537210037312
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 127th day, sold 0.41473125414731254 shares for $51.78749170537492
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 74th day, sold 0.82697056674124 shares for $100.82425149709199
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 74th day, sold 0.4119294776734223 shares for $50.22244191794365
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 94th day, sold 0.3995205753096284 shares for $49.344786256492206
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 95th day, sold 0.4132231404958678 shares for $50.413223140495866

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 110.45752342399621, Final Money: 110.45752342399621, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 74th day, sold 0.818202330521395 shares for $99.75522813716849
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7999266459299369 shares for $96.95110948670835
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 238th day, sold 0.7173730105880028 shares for $96.31450040154526
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.818202330521395 shares for $99.16612245919308
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 128th day, sold 0.8250044961264706 shares for $104.066067141393
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 155th day, Bought 0.38711675441313104 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7738741801557053 shares for $109.95978225832417
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 239th day, sold 0.7173730105880028 shares for $95.59712739095725
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.8056657756053814 shares for $98.3153945971247
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 179th day, Bought 0.36965843560550055 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7540668310848578 shares for $107.14535602884746
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 239th day, sold 0.3668647736444347 shares for $48.88839973585736
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.8056657756053814 shares for $98.3153945971247
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 199th day, Bought 0.3693034936110496 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.737492006129459 shares for $105.60148035767723
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 93th day, sold 0.4132231404958678 shares for $50.425619834710744
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 199th day, Bought 0.3693034936110496 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.737492006129459 shares for $105.60148035767723
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 93th day, sold 0.4132231404958678 shares for $50.425619834710744
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 204th day, Bought 0.35353178250724737 shares for $50.0
On the 207th day, sold 0.7217202950256567 shares for $103.34312904472378

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 110.62794222507412, Final Money: 110.62794222507412, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8250044961264706 shares for $103.58756453363965
On the 147th day, Bought 0.3937938095613137 shares for $50.0
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.785213881582607 shares for $111.05279927222811
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.3668647736444347 shares for $48.83703866754715
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 126th day, sold 0.8272044433900118 shares for $103.86378991204988
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
XLI Final Value: 115.76585198422075, Final Money: 115.76585198422075, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 61th day, sold 0.24077819512664933 shares for $48.52162188192238
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22472920131241853 shares for $50.280911501640524
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 62th day, sold 0.24077819512664933 shares for $48.57940864875277
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44656903590256103 shares for $99.915356092839
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.42079095047683046 shares for $97.82968807635832
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 65th day, sold 0.24077819512664933 shares for $46.3570259077338
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.23999232024575212 shares for $55.719016991456265
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44656903590256103 shares for $101.32204855593207
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.42079095047683046 shares for $97.82968807635832
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 124th day, sold 0.23955538520505942 shares for $55.921809122269075
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44301649220077255 shares for $105.18097557830741
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 235th day, sold 0.20888164765843673 shares for $49.28771358148473
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 124th day, sold 0.23955538520505942 shares for $55.921809122269075
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.44301649220077255 shares for $105.06579129033521
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.44217455251039833 shares for $104.3355074103536

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 110.9876004126043, Final Money: 110.9876004126043, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 45th day, Bought 0.23827678231033167 shares for $50.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4767240139379725 shares for $96.06942328878021
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23999232024575212 shares for $54.35826053566286
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2299484915378955 shares for $51.48776674025018
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.21614144296027318 shares for $51.45679332555223
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 40th day, sold 0.24321432045918862 shares for $50.778285825469396
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.47664455428973407 shares for $96.16780527349674
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2302343785974122 shares for $51.55177971174656
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 236th day, sold 0.21590810950859313 shares for $51.401243630710766
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 62th day, sold 0.24321432045918862 shares for $49.07092129584589
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2302343785974122 shares for $51.55177971174656
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22360359554581635 shares for $50.029068467420956
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.2229654403567447 shares for $49.88628762541806
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22005105184402782 shares for $49.234222339582786

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 99.87076292331592, Final Money: 99.87076292331592, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0 shares for $0.0
On the 120th day, Bought 0 shares for $0.0
On the 121th day, Bought 0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 161th day, Bought 0.2451941938014908 shares for $50.0
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 201th day, sold 0.4728808968980299 shares for $105.88276162443788
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 215th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0 shares for $0.0
On the 120th day, Bought 0 shares for $0.0
On the 121th day, Bought 0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 168th day, Bought 0.228133412419583 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 201th day, sold 0.4558201155161221 shares for $102.0626820652149
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 119th day, Bought 0 shares for $0.0
On the 120th day, Bought 0 shares for $0.0
On the 121th day, Bought 0 shares for $0.0
On the 168th day, Bought 0.228133412419583 shares for $50.0
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 201th day, sold 0.4583677910169952 shares for $102.63313208661539
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 62th day, sold 0.2415692337423906 shares for $48.739008599864725
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 127th day, sold 0.23470872647045016 shares for $51.84011641552833
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 202th day, sold 0.44656903590256103 shares for $99.915356092839
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 62th day, sold 0.2415692337423906 shares for $48.739008599864725
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.23470872647045016 shares for $51.84011641552833
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 204th day, sold 0.44656903590256103 shares for $104.20688452786261
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 127th day, sold 0.2415692337423906 shares for $53.35539665668181
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 204th day, sold 0.44301649220077255 shares for $103.37789845505027

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 106.73329511173209, Final Money: 106.73329511173209, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.4266667367659256 shares for $99.60108303063767
On the 155th day, Bought 0.22787348464132715 shares for $50.0
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.45782197617922266 shares for $102.43308895033928
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.429830156314737 shares for $101.42272368402534
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.2299484915378955 shares for $51.44867549668874
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.21590810950859313 shares for $51.401243630710766
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22005105184402782 shares for $49.234222339582786
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 236th day, sold 0.21392204680614385 shares for $50.928421683138666
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.22700444928720603 shares for $51.505039498774174
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 92th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.22700444928720603 shares for $52.971488241169524
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 111th day, sold 0.24077819512664933 shares for $54.473658865453146
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.22700444928720603 shares for $53.895396349768454
XLK Final Value: 105.75759351307221, Final Money: 105.75759351307221, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6377551020408163 shares for $49.30484693877551
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 155th day, Bought 0.6077549532028687 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6077549532028687 shares for $48.948583930959046
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 217th day, sold 0.6232859636000997 shares for $51.29020194465221
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 232th day, sold 0.6069434328720563 shares for $49.44768147608643
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 187th day, Bought 0.6099792607051361 shares for $50.00000000000001
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6099792607051361 shares for $49.127729657191665
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 232th day, sold 0.6069434328720563 shares for $49.44768147608643
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.606134076857801 shares for $48.81803855012729
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6238303181534622 shares for $50.24329382407985
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 56th day, sold 0.6693440428380187 shares for $49.67871485943775
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 70th day, sold 0.6693440428380187 shares for $50.595716198125835
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
XLP Final Value: 102.68729852490586, Final Money: 102.68729852490586, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 70th day, Bought 0.6614631565021828 shares for $50.0
On the 73th day, sold 0.6614631565021828 shares for $49.62296600079375
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.2778882724426772 shares for $99.29191876879602
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6210408644888833 shares for $51.577443795801756
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.6024096385542169 shares for $50.00000000000001
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2046741531290182 shares for $97.80749449254498
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3424622931916024 shares for $100.05371471157012
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3027624078912101 shares for $101.7327164322246
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.6422607578676943 shares for $50.0
On the 138th day, sold 1.2833685922054299 shares for $99.7177396143619
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2348803404304947 shares for $100.25993483955186
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 239th day, sold 1.2110226334153902 shares for $96.03409482984044
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 54th day, sold 0.6693440428380187 shares for $49.67202141900937
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 128th day, sold 0.6509569066527796 shares for $50.8657726858482

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.93208186677096, Final Money: 100.93208186677096, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 42th day, sold 0.6637461834594451 shares for $50.086287003849726
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.2778882724426772 shares for $99.29191876879602
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 162th day, sold 1.227685713783603 shares for $102.67135624372271
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 184th day, sold 0.60960741282614 shares for $49.713484515971714
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.215885536776542 shares for $100.05522082134165
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 238th day, sold 1.2062079794997167 shares for $96.12271388633242
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 170th day, sold 1.227685713783603 shares for $101.4682242442148
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.215885536776542 shares for $100.05522082134165
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 238th day, sold 1.2062079794997167 shares for $96.12271388633242
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 170th day, sold 1.2244404796514319 shares for $101.20000564319085
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.69148512698649, Final Money: 102.69148512698649, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 70th day, Bought 0.6614631565021828 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.3215291631028427 shares for $99.14111781597526
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3027624078912101 shares for $101.7327164322246
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 152th day, Bought 0.6109481915933529 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2236182075227733 shares for $99.34556226877396
On the 191th day, Bought 0.6079766536964981 shares for $50.0
On the 192th day, Bought 0.6131207847946045 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2210974384911026 shares for $97.50463046351454
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 70th day, Bought 0.6614631565021828 shares for $50.0
On the 80th day, sold 0.6614631565021828 shares for $51.34277020769943
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.2956839605556736 shares for $101.24474467782034
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 180th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2147877565685752 shares for $97.00080236200073
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 70th day, Bought 0.6614631565021828 shares for $50.0
On the 87th day, sold 0.6614631565021828 shares for $51.680116417515535
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 111th day, Bought 0.6472491909385113 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.2931605718970438 shares for $101.04756708803501
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 180th day, Bought 0.6157635467980296 shares for $50.00000000000001
On the 202th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2253709596241695 shares for $97.84587112598993
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 54th day, sold 0.6693440428380187 shares for $49.67202141900937
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6459113809585325 shares for $50.47151530809973
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 207th day, sold 0.60960741282614 shares for $49.09778102901731
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 139th day, sold 0.6459113809585325 shares for $50.53610644619558
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 207th day, sold 0.60960741282614 shares for $49.09778102901731
XLP Final Value: 100.4664757524169, Final Money: 100.4664757524169, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6827130702820167 shares for $96.91112032653226
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.34220792553555535 shares for $49.03839572924508
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6827130702820167 shares for $96.91112032653226
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 112th day, Bought 0.34277096044423117 shares for $50.0
On the 117th day, sold 0.34277096044423117 shares for $49.499554397751425
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6827130702820167 shares for $96.91112032653226
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.32379225488926305 shares for $47.87268488537754
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6827130702820167 shares for $96.91112032653226
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32324799586242564 shares for $47.85363330747349
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 204th day, sold 0.321316110789795 shares for $47.56763704132125
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 98.14953896480196, Final Money: 98.14953896480196, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3550379890648299 shares for $51.01895902861605
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6839719051540245 shares for $100.78326022444551
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.6446859841239713 shares for $98.4886777946191
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3550379890648299 shares for $51.01895902861605
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6850020195559079 shares for $101.2912486317321
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6434592794841842 shares for $99.02194851982111
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 209th day, sold 0.6788695024739367 shares for $99.67840904824814
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 54th day, sold 0.34298257648511454 shares for $48.68637673206201
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32026646169613116 shares for $49.55803228285934
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.34043712126370257 shares for $49.98638251514945
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 54th day, sold 0.34298257648511454 shares for $48.68637673206201
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.34043712126370257 shares for $49.98638251514945
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 99th day, Bought 0.3414600833162603 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3414600833162603 shares for $50.31414327665096
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.32303915234526426 shares for $49.39268639359091
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 89th day, Bought 0.34504175005175625 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.34504175005175625 shares for $48.844110137326616
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 157th day, Bought 0.31806615776081426 shares for $50.0
On the 181th day, sold 0.31806615776081426 shares for $48.23155216284987
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 89th day, Bought 0.34504175005175625 shares for $50.0
On the 93th day, sold 0.34504175005175625 shares for $48.868263059830234
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 157th day, Bought 0.31806615776081426 shares for $50.0
On the 181th day, sold 0.31806615776081426 shares for $48.23155216284987
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6818288784824503 shares for $100.82203626119993
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6446859841239713 shares for $99.75870918334331
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6729261485231172 shares for $98.80574638764931
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.6789793448609993 shares for $94.59540232603442
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6818288784824503 shares for $100.82203626119993
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6434592794841842 shares for $99.56888890738267
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.6789793448609993 shares for $94.7855165425955
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6821996493935462 shares for $100.87686215582367
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 210th day, sold 0.6735630619895059 shares for $97.3433337187234
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 210th day, sold 0.6780012584497679 shares for $97.98474187116047
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6780012584497679 shares for $96.16769849851508
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
XLV Final Value: 96.30666226872737, Final Money: 49.08953688646438, Final Shares: 0.33978933061501865

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2807411566535654 shares for $51.26614261650759
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.27156202476645663 shares for $54.37486421898761
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 175th day, Bought 0.24932681759250025 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.24932681759250025 shares for $49.92270868654632
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2798298634430266 shares for $51.099731363331095
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.24895439155546703 shares for $53.55506871141207
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.49849274560048373 shares for $107.23575943357606
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 108.2691911038669, Final Money: 108.2691911038669, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 125th day, sold 0.26452227277536766 shares for $50.642789122844135
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2798298634430266 shares for $53.027759122453546
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2794076557697681 shares for $52.94775076837106
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5615154347173892 shares for $106.40717487894526
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5265973015977643 shares for $105.993504865598
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5130302364012908 shares for $103.2627259828518
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 114.07632303176621, Final Money: 114.07632303176621, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2897878752752985 shares for $53.4513735945288
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5413167363714689 shares for $106.86675009445538
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.25257627803596683 shares for $49.99999999999999
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5031902823465277 shares for $106.731690788522
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.21510927551196007 shares for $50.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2702410550210788 shares for $49.019024970273485
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.5269611778992285 shares for $103.59002835143033
On the 192th day, Bought 0.25257627803596683 shares for $49.99999999999999
On the 205th day, sold 0.25257627803596683 shares for $53.57395433420893
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.2176373291546966 shares for $50.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.5199806235127767 shares for $102.21779097014166
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5626111386085259 shares for $106.61481076631564
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5617212209748524 shares for $106.44617137473453
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5617212209748524 shares for $106.44617137473453
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 116.90790081961075, Final Money: 116.90790081961075, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5427999546785756 shares for $108.99965889900476
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 40th day, Bought 0.2780249110320285 shares for $50.0
On the 56th day, sold 0.2780249110320285 shares for $50.19461743772242
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5609340406510999 shares for $105.32658481305702
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 56th day, sold 0.2808199943836001 shares for $50.699241786015165
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5592375192127947 shares for $105.00802898258648
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 59th day, sold 0.2808199943836001 shares for $50.556023588879526
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.561060528834781 shares for $106.320970214191
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2671939293539251 shares for $53.6552129535617
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
XLY Final Value: 115.57880763382519, Final Money: 115.57880763382519, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5786617663397162 shares for $100.41867495686935
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.3890620513572678 shares for $99.85967087207398
On the 112th day, Bought 0.7255840951966334 shares for $50.0
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4593674823407485 shares for $102.31625418690987
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3327280241967356 shares for $106.29838720993165
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 62th day, sold 0.7907638779060573 shares for $49.63624861616322
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6893699158968702 shares for $49.558803253826
On the 112th day, Bought 0.7255840951966334 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.7255840951966334 shares for $50.87070091423596
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.6648052120728627 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.3288158362428495 shares for $106.86336955064996
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 62th day, sold 0.7907638779060573 shares for $49.63624861616322
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6893699158968702 shares for $49.5381221563491
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 62th day, sold 0.7838219156607619 shares for $49.20050164602603
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6861534239055852 shares for $49.306985041855356
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 65th day, sold 0.7838219156607619 shares for $51.285467941683656
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.3805014311268045 shares for $99.20283284077217
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 65th day, sold 0.7793017456359103 shares for $50.98971321695761
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 137th day, sold 1.3805014311268045 shares for $102.46081621823143

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 107.21579164002522, Final Money: 6.929122334875132, Final Shares: 1.3010725130403489
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 63th day, sold 0.7843137254901961 shares for $50.258823529411764
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4461366287071211 shares for $105.16305563958184
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.4616109028568363 shares for $102.38584374512138
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 226th day, Bought 0.6354047528275512 shares for $50.0
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.446825008606601 shares for $105.21311462587202
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 122th day, Bought 0.7016559079427448 shares for $50.0
On the 126th day, sold 1.4084695918556656 shares for $98.66329490948937
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 94th day, sold 1.4031149151115476 shares for $102.03451662691174
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 94th day, sold 0.7015574575557738 shares for $51.01725831345587
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 65th day, sold 0.7803964413922273 shares for $51.061339160293436
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
XLU Final Value: 114.27174971622662, Final Money: 15.960393969405445, Final Shares: 1.275445715449159

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.446268122066912 shares for $103.39370804656353
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 161th day, sold 1.3487087648370697 shares for $102.38048233878196
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.446268122066912 shares for $103.39370804656353
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.3487087648370697 shares for $103.90452324304786
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 164th day, sold 1.3487087648370697 shares for $104.22821334660875
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 62th day, sold 0.7880220646178092 shares for $49.464144996059886
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6741270055278414 shares for $53.98409060266954
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 63th day, sold 0.7880220646178092 shares for $50.49645390070921
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, Bought 0.6646284726837698 shares for $50.00000000000001
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 172th day, sold 1.3487087648370697 shares for $108.34177507936181

[*********************100%***********************]  1 of 1 completed

On the 234th day, Bought 0.6646284726837698 shares for $50.00000000000001
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
XLU Final Value: 112.58834171921777, Final Money: 10.440559993358953, Final Shares: 1.3252177182908513

read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.0 shares for $0.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7015574575557738 shares for $51.01725831345587
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.7306736811340054 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.465751599393341 shares for $102.76384463346713
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 217th day, Bought 0.6127450980392157 shares for $50.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2266186400895533 shares for $93.59100223883291
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4031149151115476 shares for $100.86993124736917
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 125th day, sold 1.4265488213823319 shares for $100.01533786711529
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4031149151115476 shares for $100.86993124736917
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 0.7015574575557738 shares for $50.43496562368458
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 0.7015574575557738 shares for $50.43496562368458
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
XLU Final Value: 108.7425985586799, Final Money: 9.762485652914705, Final Shares: 1.2841218591822159

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 37th day, sold 0.09858432903505658 shares for $50.40419574904372
On the 48th day, Bought 0.0963743952506698 shares for $50.0
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.19194562448782027 shares for $99.68120170901483
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17726270862194415 shares for $101.00606399987
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 58th day, sold 0.09557122923715046 shares for $49.135080375403795
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.174860422392223 shares for $99.63721728331258
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 58th day, sold 0.09557122923715046 shares for $49.135080375403795
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17463810735127167 shares for $99.5105399498281
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17463810735127167 shares for $100.71379650947837
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 104.0176811722084, Final Money: 104.0176811722084, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 59th day, sold 0.09749439407234084 shares for $50.502096129472555
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17798507725619608 shares for $101.41767687135308
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 60th day, sold 0.09749439407234084 shares for $49.80501121185532
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.1791071512121006 shares for $105.85949065239994
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 61th day, sold 0.09858432903505658 shares for $49.73086478173429
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17825237578963055 shares for $106.16889754406185
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1664768163323842 shares for $99.00209790470556
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 61th day, sold 0.09858432903505658 shares for $49.73086478173429
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.1755009281596665 shares for $104.53010782117897
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.1664768163323842 shares for $100.10250966066262
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 205th day, sold 0.17228911804900965 shares for $102.61712160117064
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 237th day, sold 0.08349615082744685 shares for $50.20623549254379
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 238th day, sold 0.08349615082744685 shares for $50.20957533857689

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.12482323957803, Final Money: 107.12482323957803, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.1784969621943106 shares for $102.83745482900817
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17243352818983582 shares for $102.7031337251481
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.1784969621943106 shares for $102.83745482900817
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17243352818983582 shares for $102.7031337251481
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17825237578963055 shares for $102.69654126367985
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 61th day, sold 0.09749439407234084 shares for $49.18104708979234
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 206th day, sold 0.17228911804900965 shares for $103.0616275257371
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 240th day, sold 0.166739304078092 shares for $98.07939344481528
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.09436989222958307 shares for $50.0
On the 126th day, sold 0.1884680554334373 shares for $104.15875551584345
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 240th day, sold 0.08349615082744685 shares for $49.11410583972079

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.67133786825246, Final Money: 107.67133786825246, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 58th day, sold 0.09858432903505658 shares for $50.68417524350329
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.19153335798089574 shares for $106.67258839388009
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09598587087980649 shares for $53.458370927799436
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17825237578963055 shares for $101.56998624868937
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09598587087980649 shares for $53.458370927799436
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17861262232871045 shares for $101.7752583291225
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1755009281596665 shares for $100.00218387465956
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.08349615082744685 shares for $49.358749561645205
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 238th day, sold 0.08349615082744685 shares for $50.20957533857689
SPY Final Value: 106.91386654289077, Final Money: 106.91386654289077, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0890283040146238 shares for $97.99076679523586
On the 114th day, Bought 0.5750431282346176 shares for $50.0
On the 125th day, sold 0.5750431282346176 shares for $52.80621046578493
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.0966471303772733 shares for $104.55433741016924
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0890283040146238 shares for $99.0144534010096
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0890283040146238 shares for $99.0144534010096
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0508631107789832 shares for $97.39399310699618
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0462549900304203 shares for $96.96691247601936
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5214308061320263 shares for $47.25727395974554
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 133th day, sold 0.5433010974682169 shares for $49.706617407367155
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5214308061320263 shares for $47.25727395974554

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 106.83163068978568, Final Money: 106.83163068978568, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.089819163774012 shares for $99.16264571179735
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0881392947121558 shares for $92.56800980116309
On the 31th day, Bought 0.5684402000909504 shares for $49.99999999999999
On the 35th day, Bought 0.5563591854901524 shares for $50.0
On the 59th day, sold 1.124799385581103 shares for $102.96413575609417
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.120521592411536 shares for $99.82726866794374
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0844228128268467 shares for $98.67163173911477
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0958225493695615 shares for $93.22162427486859
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0996844052671673 shares for $93.55015235607792
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0871837333773595 shares for $105.36984743893369
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0996844052671673 shares for $93.55015235607792
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5357334190506804 shares for $45.57484195864138
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.0945437591716636 shares for $93.61632772195239

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 101.6110207094282, Final Money: 101.6110207094282, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 59th day, sold 1.0871888974428363 shares for $99.52127167191725
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5472255663784612 shares for $49.80299879610376
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619240278714318 shares for $51.60148347943358
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.0691805544395634 shares for $103.80674003053721
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.1044785078983201 shares for $94.32246457451654
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 61th day, sold 1.0871888974428363 shares for $97.29253443215941
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5441288497116117 shares for $46.46860376537164
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 176th day, sold 0.5357334190506804 shares for $51.923282974391945
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0523015578016246 shares for $98.463856763498
On the 233th day, Bought 0.5851375073142189 shares for $50.00000000000001
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.1766434815245583 shares for $99.94409732069599
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.0547562682543004 shares for $99.24201728004712
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.0547562682543004 shares for $89.59099742552027
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 101.15319547052519, Final Money: 101.15319547052519, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.5710370031978073 shares for $52.97510278666058
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0877261845762307 shares for $98.97220553459123
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1184689967049135 shares for $102.7090079674122
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.1009008637772286 shares for $106.699311717289
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.0554195515497262 shares for $99.27276301876725
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0881392947121558 shares for $91.98041458201853
On the 35th day, Bought 0.5563591854901524 shares for $50.0
On the 55th day, sold 0.5563591854901524 shares for $51.61344163792143
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 125th day, sold 0.5577867023650156 shares for $51.22155287817938
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.1009008637772286 shares for $106.699311717289
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0881392947121558 shares for $91.98041458201853
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 125th day, sold 0.5577867023650156 shares for $51.22155287817938
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0881392947121558 shares for $91.98041458201853
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0966471303772733 shares for $93.29177138119464
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0966471303772733 shares for $93.29177138119464
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0478710816543884 shares for $89.1423929163388
XLB Final Value: 103.10074033357466, Final Money: 103.10074033357466, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.5424170101974397 shares for $49.99999999999999
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 59th day, sold 1.1095033207339033 shares for $108.42066450211703
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.094935722669386 shares for $100.50414998382296
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1014041492712865 shares for $93.77354926895734
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5542622769094336 shares for $50.105309832612804
On the 232th day, Bought 0.5773005426625101 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5773005426625101 shares for $48.45283454566447
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.066042591472773 shares for $95.81590812157282
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.5549389567147615 shares for $50.93784683684796
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 154th day, Bought 0.5534034311012729 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, sold 1.1016490451363605 shares for $98.92808425324517
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5542622769094336 shares for $46.51923290100877
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.066042591472773 shares for $96.29562728773557
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 118th day, Bought 0.5583472920156337 shares for $50.0
On the 129th day, sold 1.0922501217006308 shares for $98.66295349321798
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 136th day, sold 0.5339028296849972 shares for $48.44634276561665
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 99.37169444557128, Final Money: 2.403459963640884, Final Shares: 1.108588481558596
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5737893045673629 shares for $56.11085609364242
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.0409737632567437 shares for $95.80081543251812
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.5265374894692503 shares for $50.0
On the 92th day, sold 1.0604403191542475 shares for $96.16072814090717
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5679236710586096 shares for $51.30622444343479
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5526693931690063 shares for $48.52437272023875
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5567928730512249 shares for $50.59576837416481
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5730002292000916 shares for $48.0919092367637
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 37th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.579979120751653 shares for $56.71615821830415
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0533710046449274 shares for $96.94173355747267
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.1012079395619154 shares for $99.48312526002344
On the 165th day, Bought 0.5874750323111267 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.148516324950265 shares for $100.83973333063327
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.117517062787762 shares for $94.58664419435617
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 62th day, sold 0.5130309870716192 shares for $48.430125179560854
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 62th day, sold 0.5130309870716192 shares for $48.430125179560854
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.5610412926391383 shares for $50.89766606822262
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 179th day, sold 0.562429696287964 shares for $51.023622047244096
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.117517062787762 shares for $94.50841799996103
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 179th day, sold 0.562429696287964 shares for $51.023622047244096
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.117517062787762 shares for $94.50841799996103

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 98.08091783455271, Final Money: 47.02441538300005, Final Shares: 0.5837030119075415
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, Bought 0.5250446287934474 shares for $49.99999999999999
On the 62th day, sold 1.040296071497487 shares for $98.20394914936277
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5339028296849972 shares for $48.41430859583556
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 218th day, sold 0.5534646889528448 shares for $52.700907682089884
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 237th day, sold 0.5948839976204641 shares for $50.35098155859608
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 94th day, sold 0.5339028296849972 shares for $49.759743726641744
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5420641803989593 shares for $50.189722463139645
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5420641803989593 shares for $50.189722463139645
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
XLE Final Value: 98.40143474278338, Final Money: 47.344932291230734, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 40th day, Bought 0.5477051155657794 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5477051155657794 shares for $53.560083251177566
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 73th day, sold 1.0409737632567437 shares for $95.80081543251812
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5339028296849972 shares for $48.41430859583556
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.5636978579481398 shares for $51.967305524239
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 58th day, sold 0.5130309870716192 shares for $50.16930022573364
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 106th day, Bought 0.5640794223826715 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.5640794223826715 shares for $52.002481949458485
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.5610412926391383 shares for $50.381508078994614
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 174th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
XLE Final Value: 99.1957255343082, Final Money: 49.99999999999999, Final Shares: 0.562429696287964

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 47th day, sold 1.2330456226880395 shares for $50.87546239210851
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2812835348939844 shares for $101.01523492510563
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, sold 2.015524105733302 shares for $98.74052593987447
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 47th day, sold 1.2330456226880395 shares for $50.87546239210851
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.276626291211212 shares for $100.80901217483246
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 96th day, sold 1.1941724385001196 shares for $49.18796274181992
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.2379022564825797 shares for $110.88805680871182
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.391777228919281 shares for $104.8076781712429
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 204th day, sold 2.2294092152559086 shares for $110.46722661593027
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.3830007126571893 shares for $104.42309122863803
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 1.1976047904191616 shares for $52.47904191616766

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 115.27490478717317, Final Money: 115.27490478717317, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.2330456226880395 shares for $92.13546239210851
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4688340557083066 shares for $102.11097654409556
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.4260697616889684 shares for $103.9570892883723
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 239th day, sold 2.002850200644033 shares for $97.63894728139661
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.228803145736053 shares for $91.96041779306955
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 2.4044597264558503 shares for $103.03109927863319
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2530688101629393 shares for $105.44362031562555
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.371791173519794 shares for $109.76649551049607
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 240th day, sold 0.9966115208291807 shares for $48.11640422563285
On the 39th day, Bought 1.2147716229348884 shares for $50.0
On the 52th day, sold 1.2147716229348884 shares for $50.6195335276968
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 1.1976047904191616 shares for $51.604790419161674
On the 157th day, Bought 1.0931351114997814 shares for $50.0
On the 187th day, sold 1.0931351114997814 shares for $51.15872321818976
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 202th day, sold 1.0604453870625663 shares for $49.07741251325557
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 205th day, sold 1.0604453870625663 shares for $51.69671261930011

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 110.45446188905731, Final Money: 110.45446188905731, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 73th day, Bought 1.2388503468780971 shares for $50.0
On the 90th day, sold 1.2388503468780971 shares for $51.54856293359762
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.3615453243694313 shares for $109.29231761181728
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 238th day, sold 2.015524105733302 shares for $98.98238883256246
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.1115453243694313 shares for $97.72231761181729
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 238th day, sold 2.0058969467476304 shares for $98.50959905477613
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 238th day, sold 2.007733866633023 shares for $98.59981019034777
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 206th day, sold 2.121791173519794 shares for $104.37090782543866
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 239th day, sold 0.9966115208291807 shares for $48.58481164042256
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 206th day, sold 2.121791173519794 shares for $104.37090782543866
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 206th day, sold 2.132716457189094 shares for $104.90832252913152

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 108.28308504108111, Final Money: 108.28308504108111, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 31th day, Bought 1.2410027302060065 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2410027302060067 shares for $93.1584834946637
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.418830948492971 shares for $103.64690614292381
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2812835348939844 shares for $106.76406943303846
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 240th day, sold 0.9966115208291807 shares for $48.11640422563285
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.237623762376238 shares for $93.42079207920793
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 2.4044597264558503 shares for $103.03109927863319
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2615618513896103 shares for $105.84109464503375
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.25 shares for $11.8025
On the 202th day, sold 2.382716457189094 shares for $110.27211763871126
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.2330456226880395 shares for $90.66165228113441
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.235788433020267 shares for $93.03115669797332
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 1.1976047904191616 shares for $51.31736526946108
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 38th day, Bought 1.2236906510034264 shares for $50.00000000000001
On the 59th day, sold 1.2236906510034264 shares for $49.681840430739115
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 2.235788433020267 shares for $92.51692535837866
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 1.1976047904191616 shares for $51.31736526946108
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 205th day, sold 1.0590976488032195 shares for $51.631010379156955
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 96th day, sold 1.2357884330202669 shares for $50.90212555610479
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 127th day, sold 1.2330456226880395 shares for $52.8360049321825
XLF Final Value: 112.51688868724464, Final Money: 112.51688868724464, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.8002117420331725 shares for $97.3857690054371
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39142007202129325 shares for $52.383748238609684
On the 221th day, Bought 0.3498215909885958 shares for $50.0
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7003298279321639 shares for $93.22790669432966
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7959566428887224 shares for $96.86792343955752
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39142007202129325 shares for $55.358540785971506
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 236th day, sold 0.35481124042009654 shares for $47.232472324723254
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 236th day, sold 0.35481124042009654 shares for $47.232472324723254
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39013732833957554 shares for $55.177122347066174
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7983397032568902 shares for $99.68867874568788

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 104.14514205026052, Final Money: 104.14514205026052, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7959566428887224 shares for $96.46994511811316
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4102732419791581 shares for $51.513908262903094
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7303689539425081 shares for $97.22671514882668
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4102732419791581 shares for $51.513908262903094
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 240th day, sold 0.3668647736444347 shares for $48.39680093917382
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.390625 shares for $54.91406250000001
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 109.6043201097608, Final Money: 109.6043201097608, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 31th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 53th day, Bought 0 shares for $0.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 92th day, sold 0.818202330521395 shares for $99.16612245919308
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.8250044961264706 shares for $104.066067141393
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 203th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 216th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 232th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 31th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 53th day, Bought 0 shares for $0.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 92th day, sold 0.8041086262407162 shares for $97.45796550037481
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 205th day, sold 0.7831204863019074 shares for $110.09107796432215
On the 216th day, Bought 0 shares for $0.0
On the 232th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 31th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 53th day, Bought 0 shares for $0.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 92th day, sold 0.8056657756053814 shares for $97.64669200337224
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 128th day, sold 0.4137702747434624 shares for $52.19298245614035
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 156th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 232th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 31th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 92th day, sold 0.8056657756053814 shares for $97.64669200337224
On the 156th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 31th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 92th day, sold 0.39939292275740873 shares for $48.40642223819794
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 31th day, Bought 0 shares for $0.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0 shares for $0.0
On the 92th day, sold 0.39939292275740873 shares for $48.40642223819794
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 115.09355365809239, Final Money: 115.09355365809239, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.8293256196834445 shares for $101.25236490715174
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7959566428887224 shares for $96.46994511811316
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4102732419791581 shares for $51.513908262903094
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 184th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 205th day, sold 0.7839155583232007 shares for $110.20284918907556
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 231th day, Bought 0 shares for $0.0
On the 232th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7973563487023718 shares for $96.63958946272747
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 184th day, Bought 0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 62th day, sold 0.4132231404958678 shares for $50.30578512396694
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 69th day, sold 0.4142845306156268 shares for $50.733283619189656
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
XLI Final Value: 112.13382517740496, Final Money: 112.13382517740496, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22472920131241853 shares for $50.280911501640524
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21861746316295744 shares for $50.82637401075598
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 62th day, sold 0.24077819512664933 shares for $48.57940864875277
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44656903590256103 shares for $99.915356092839
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4280507457786669 shares for $99.51751788608227
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 116th day, sold 0.24077819512664933 shares for $55.90147356255417
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44656903590256103 shares for $101.32204855593207
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 234th day, sold 0.42079095047683046 shares for $97.82968807635832
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 124th day, sold 0.23955538520505942 shares for $55.921809122269075
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44301649220077255 shares for $100.51601191543328
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 124th day, sold 0.23955538520505942 shares for $55.921809122269075
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44217455251039833 shares for $104.98108225701877
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 205th day, sold 0.4491279499535765 shares for $106.63195787797814

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 110.90289137928785, Final Money: 110.90289137928785, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.47664455428973407 shares for $96.05341058046722
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.21470285125386465 shares for $48.17502576434215
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.223254152527237 shares for $49.98883729237363
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.21590810950859313 shares for $51.401243630710766
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.4779824751654502 shares for $96.43774418938123
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.21470285125386465 shares for $48.17502576434215
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2302343785974122 shares for $51.55177971174656
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 77th day, sold 0.23819732266209329 shares for $48.65418512695917
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22005105184402782 shares for $49.27163101839627
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22005105184402782 shares for $49.27163101839627
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22005105184402782 shares for $49.27163101839627
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 101.55031097567982, Final Money: 101.55031097567982, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.23819732266209329 shares for $48.00152446286504
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 113th day, Bought 0.22101401228837908 shares for $50.0
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.44036998315790615 shares for $98.81021682097098
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.45094085562377617 shares for $100.97016698271972
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4340538421757886 shares for $100.91317776744908
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 201th day, sold 0.2251339547030483 shares for $50.40974379755955
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 196th day, Bought 0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 103.08183026539784, Final Money: 103.08183026539784, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.4779824751654502 shares for $96.43774418938123
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.21470285125386465 shares for $48.170731707317074
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22295549808258272 shares for $49.921965575671095
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21590810950859313 shares for $50.196476379652815
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.4779824751654502 shares for $96.43774418938123
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.21470285125386465 shares for $48.17502576434215
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22693232877955793 shares for $50.81241773703081
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.22700444928720603 shares for $53.895396349768454
XLK Final Value: 103.8798716476663, Final Money: 103.8798716476663, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 85th day, Bought 0.6393044367727913 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6393044367727913 shares for $49.85295997954226
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.6484243288808196 shares for $50.48631824666061
On the 155th day, Bought 0.6077549532028687 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6077549532028687 shares for $48.52923301324906
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 232th day, sold 0.6069434328720563 shares for $49.44768147608643
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 58th day, sold 1.342552488151616 shares for $99.76507539454659
On the 85th day, Bought 0.6393044367727913 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6393044367727913 shares for $49.85295997954226
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 134th day, sold 0.6455777921239509 shares for $50.34861200774693
On the 187th day, Bought 0.6099792607051361 shares for $50.00000000000001
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6099792607051361 shares for $48.70684396730511
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 233th day, sold 0.6069434328720563 shares for $48.695071619325084
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.3424622931916024 shares for $98.50988307439978
On the 85th day, Bought 0.6393044367727913 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 97th day, sold 0.6393044367727913 shares for $49.74427822529089
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 134th day, sold 0.6455777921239509 shares for $50.34861200774693
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.3403048587263708 shares for $97.94947907572318
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 134th day, sold 0.6455777921239509 shares for $50.34861200774693
On the 197th day, Bought 0.6156877231867997 shares for $49.99999999999999
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6156877231867997 shares for $49.58748922546485
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 61th day, sold 0.6693440428380187 shares for $48.91566265060241
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 134th day, sold 0.6455777921239509 shares for $50.34861200774693
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6238303181534622 shares for $50.24329382407985
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 68th day, sold 0.6637461834594451 shares for $50.39824771007567
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 1.2949284414746003 shares for $100.81017916879763
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.55748155899398, Final Money: 101.55748155899398, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3403048587263708 shares for $101.0053741536193
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, sold 1.2437834227153124 shares for $102.79869988742058
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 185th day, sold 0.60960741282614 shares for $49.4940258473543
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2261373024822997 shares for $97.90706360321163
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2023570535234946 shares for $95.81583359528729
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 53th day, sold 0.6693440428380187 shares for $49.88621151271754
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2348803404304947 shares for $98.60519518337499
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 205th day, sold 1.2285852659910117 shares for $98.10253348938228
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.93208186677096, Final Money: 100.93208186677096, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 41th day, sold 0.6715916722632639 shares for $50.72531900604432
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.2961353981456472 shares for $101.55220844471145
On the 132th day, Bought 0.6370238246910435 shares for $50.0
On the 136th day, Bought 0.6363752068219423 shares for $50.0
On the 138th day, sold 1.2733990315129857 shares for $98.943104748559
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, sold 1.2417076485953324 shares for $103.23557390421594
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 178th day, Bought 0.6044487427466151 shares for $50.0
On the 184th day, sold 1.207803394610981 shares for $98.49636683052549
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.2154443376425925 shares for $99.47196459266978
On the 219th day, Bought 0.6038647342995169 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.2054046765516824 shares for $96.02253653410702
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 41th day, sold 0.6693440428380187 shares for $50.55555555555556
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 170th day, sold 1.227685713783603 shares for $101.4682242442148
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 237th day, sold 1.2062079794997167 shares for $95.82116189145749
On the 35th day, Bought 0.6599788806758183 shares for $50.0
On the 54th day, sold 0.6599788806758183 shares for $48.97703273495247
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 170th day, sold 1.227685713783603 shares for $101.4682242442148
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 238th day, sold 1.2062079794997167 shares for $96.12271388633242
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.227685713783603 shares for $101.95929852972823
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 185th day, sold 0.6117704637220115 shares for $49.66964394959011
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.38749601159896, Final Money: 101.38749601159896, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3403048587263708 shares for $101.0053741536193
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 86th day, sold 0.6600660066006601 shares for $51.26732673267327
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3015780808355715 shares for $101.64023233244978
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 184th day, sold 1.2437834227153124 shares for $101.43053812243372
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 52th day, sold 0.6693440428380187 shares for $50.441767068273094
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 86th day, sold 0.6600660066006601 shares for $51.26732673267327
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.3015780808355715 shares for $101.70531123649155
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2086057108796324 shares for $96.3137890999979
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 52th day, sold 0.6637461834594451 shares for $50.01991238550379
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.3015780808355715 shares for $101.70531123649155
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 130th day, sold 0.6518055012384305 shares for $50.70394994133751
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2386578082880204 shares for $100.56662745490438
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 1.2222774287555604 shares for $97.5988526861315
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
XLP Final Value: 101.2705773962419, Final Money: 101.2705773962419, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3485535029627048 shares for $50.08713837574068
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.3409943394939644 shares for $48.864488849485106
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34055305816646236 shares for $46.996322026971804
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.34220792553555535 shares for $49.41824652658955
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34055305816646236 shares for $46.996322026971804
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.34073872154831675 shares for $47.47171868611149
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152
On the 223th day, Bought 0.34073872154831675 shares for $50.0
XLV Final Value: 95.38801020767457, Final Money: 48.03895746132048, Final Shares: 0.34073872154831675

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.3550379890648299 shares for $50.28403039125186
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32379225488926305 shares for $50.10361352156457
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.33978933061501865 shares for $47.339449541284395
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6850020195559079 shares for $101.56524943955446
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6470402507516887 shares for $100.12300840131631
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.680342388781481 shares for $94.97579747389474
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6829247658074777 shares for $100.98408511995174
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.64628714820769 shares for $99.06289407727472
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3375641371860653 shares for $49.56454226302998
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 189th day, sold 0.321646831778707 shares for $49.302026375040214
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.34043712126370257 shares for $49.98638251514945
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 55th day, sold 0.34525618008562353 shares for $49.447590111863
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.34043712126370257 shares for $48.321644992169944

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.0480321754734, Final Money: 99.0480321754734, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.32379225488926305 shares for $49.50783577256832
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 121th day, sold 0.34234851078397804 shares for $50.44505306401916
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32303915234526426 shares for $48.98565706163587
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 157th day, Bought 0.31806615776081426 shares for $50.0
On the 187th day, sold 0.31806615776081426 shares for $49.2175572519084
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 98.45668673308728, Final Money: 98.45668673308728, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 52th day, sold 0.6890405585234674 shares for $99.35275813349875
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6839719051540245 shares for $101.41251437718722
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6470402507516887 shares for $100.12300840131631
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6729261485231172 shares for $101.06004898520175
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.680342388781481 shares for $93.37018943637047
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 52th day, sold 0.34525618008562353 shares for $49.78248860654605
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6839719051540245 shares for $101.1389256151256
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.64628714820769 shares for $99.06289407727472
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6839719051540245 shares for $101.1389256151256
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.64628714820769 shares for $99.06289407727472
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6780012584497679 shares for $96.16769849851508
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6839719051540245 shares for $101.1389256151256
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 127th day, sold 0.34234851078397804 shares for $50.623074289626835
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 189th day, sold 0.321646831778707 shares for $49.302026375040214
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 222th day, Bought 0.34055305816646236 shares for $50.0
XLV Final Value: 96.69606673114603, Final Money: 96.69606673114603, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2807411566535654 shares for $51.26614261650759
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.26893287435456115 shares for $53.84842943201377
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.27156202476645663 shares for $54.37486421898761
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.43407487791644056 shares for $99.3640803038524
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 109th day, sold 0.2811041772080733 shares for $51.00354191263282
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.24895439155546703 shares for $49.84813782115116
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21929824561403508 shares for $50.19956140350877
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.49849274560048373 shares for $99.67362448281672
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 116th day, sold 0.5595040089152501 shares for $105.05806775401652
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.2794076557697681 shares for $52.89186923721711
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 111.8018542456362, Final Money: 111.8018542456362, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 125th day, sold 0.26452227277536766 shares for $50.642789122844135
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 218th day, Bought 0.22611133722244833 shares for $50.0
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4533427496929082 shares for $103.51175003738174
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 125th day, sold 0.26452227277536766 shares for $50.642789122844135
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.538431859266044 shares for $108.1225016592143
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2798298634430266 shares for $53.027759122453546
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5265973015977643 shares for $105.74600413384705
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.5265973015977643 shares for $105.44057769892034
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5130302364012908 shares for $108.81884344307778
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.2594033722438392 shares for $59.22957198443581

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 113.81933616269642, Final Money: 113.81933616269642, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.2897878752752985 shares for $51.53877361771183
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5022116493566033 shares for $106.52411294502915
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 211th day, sold 0.2309148847734725 shares for $49.28647300604997
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2897878752752985 shares for $53.4513735945288
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.21510927551196007 shares for $50.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.282326369282891 shares for $52.07509881422924
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5242949918070232 shares for $99.3539009474309
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5617212209748524 shares for $106.44617137473453
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 116.73926142802964, Final Money: 116.73926142802964, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.2811041772080733 shares for $50.79833586327093
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.27156202476645663 shares for $54.53237019335216
On the 216th day, Bought 0.22925263640531868 shares for $50.0
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4564840488757786 shares for $104.22900287980653
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44423674848696104 shares for $101.43257678202782
On the 42th day, Bought 0.2792984024131382 shares for $50.0
On the 59th day, sold 0.2792984024131382 shares for $50.282091386437266
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5592375192127947 shares for $105.00802898258648
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5265973015977643 shares for $105.74600413384705
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
XLY Final Value: 113.9698388580293, Final Money: 113.9698388580293, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 61th day, sold 0.7907638779060573 shares for $50.300490273604304
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.3890620513572678 shares for $99.81799901053326
On the 112th day, Bought 0.7255840951966334 shares for $50.0
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4593674823407485 shares for $102.31625418690987
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3327280241967356 shares for $106.29838720993165
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2357984167210918 shares for $94.2914191958193
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 62th day, sold 0.7838219156607619 shares for $49.20050164602603
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.6893699158968702 shares for $48.2145319178271
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.7265329845975008 shares for $50.937227550130785
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.6648052120728627 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, sold 1.3288158362428495 shares for $106.54445374995169
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2636534107644084 shares for $96.41675524132435
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 62th day, sold 0.7838219156607619 shares for $49.20050164602603
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, sold 0.6911805363560962 shares for $47.808957699751176
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.7265329845975008 shares for $50.937227550130785
On the 153th day, Bought 0.6586747464102226 shares for $49.99999999999999
On the 174th day, sold 0.6586747464102226 shares for $52.81254116717165
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2931799698479864 shares for $98.66963169940136
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6923289947382997 shares for $48.553032400996955
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.6491820306413919 shares for $49.5325889379382
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6923289947382997 shares for $50.027693159789536
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6923289947382997 shares for $50.027693159789536

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 107.12701214859315, Final Money: 5.677784837070803, Final Shares: 1.3161549988521322
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 63th day, sold 0.7843137254901961 shares for $50.258823529411764
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4568087492862052 shares for $105.93913224809283
On the 116th day, Bought 0.7306736811340054 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4572066657315061 shares for $102.1647593344359
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 219th day, Bought 0.6031363088057901 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4024265352120677 shares for $101.98445764062156
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4265488213823319 shares for $100.01533786711529
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4024265352120677 shares for $101.98445764062156
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 122th day, Bought 0.7016559079427448 shares for $50.0
On the 127th day, sold 1.4084695918556656 shares for $98.77597247683782
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 94th day, sold 1.4031149151115476 shares for $102.03451662691174
On the 122th day, Bought 0.7016559079427448 shares for $50.0
On the 139th day, sold 0.7016559079427448 shares for $51.12966601178782
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 94th day, sold 0.7015574575557738 shares for $51.01725831345587
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 0.7015574575557738 shares for $50.43496562368458
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 111.35850408471745, Final Money: 12.041399177129826, Final Shares: 1.2884938363724394
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 85th day, sold 0.7452675510508272 shares for $53.91265464301684
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 93th day, sold 0.6861534239055852 shares for $49.03252367229312
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.439698010984607 shares for $102.92401080528954
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 161th day, sold 1.3487087648370697 shares for $102.38048233878196
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 189th day, sold 1.270973978310089 shares for $104.48677075687242
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.439698010984607 shares for $102.92401080528954
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.3487087648370697 shares for $103.90452324304786
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 189th day, sold 1.270973978310089 shares for $104.48677075687242
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 164th day, sold 1.3487087648370697 shares for $104.22821334660875
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 189th day, sold 1.270973978310089 shares for $104.48677075687242
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 164th day, sold 0.6741270055278414 shares for $52.09653498719159
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 191th day, sold 1.270973978310089 shares for $104.1563175225118
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 62th day, sold 0.7827175954915466 shares for $49.131183469004384
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 109.68305669389565, Final Money: 13.557608629492023, Final Shares: 1.2470867678308721
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 53th day, sold 0.7862871520679352 shares for $51.18729359962258
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 90th day, sold 0.7115411982353779 shares for $50.875195673829516
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 116th day, Bought 0.7306736811340054 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4644570682781204 shares for $102.61450677424789
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2317703413278247 shares for $93.98407704331302
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 65th day, sold 0.7862871520679352 shares for $51.446768359805006
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 90th day, sold 1.4124102758916717 shares for $100.98733472625453
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 116th day, Bought 0.7306736811340054 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4644570682781204 shares for $102.61450677424789
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 66th day, sold 0.7862871520679352 shares for $51.91854065104576
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4124102758916717 shares for $102.71047526284237
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 125th day, sold 0.7265329845975008 shares for $50.937227550130785
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 94th day, sold 0.7843137254901961 shares for $57.035294117647055
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 96th day, sold 0.7843137254901961 shares for $56.36078431372549
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
XLU Final Value: 113.91196850484141, Final Money: 14.594863597253784, Final Shares: 1.2884938363724394

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 57th day, sold 0.09575609008732956 shares for $49.72805270415199
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09599877121572843 shares for $53.4655556408878
On the 150th day, Bought 0.08918697156719346 shares for $50.0
On the 151th day, Bought 0.08989248858365395 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1790794601508474 shares for $102.2615349245399
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1658128640371508 shares for $97.18291961217408
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 57th day, sold 0.09575609008732956 shares for $49.72805270415199
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09598587087980649 shares for $53.458370927799436
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.174860422392223 shares for $99.85229560285501
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17463810735127167 shares for $99.5105399498281
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 203th day, sold 0.17582727512007773 shares for $101.39958956174884
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 203th day, sold 0.08789508842245895 shares for $50.68909749323208
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 58th day, sold 0.09636882275846118 shares for $49.54513915658006
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
SPY Final Value: 102.63806288175377, Final Money: 102.63806288175377, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 59th day, sold 0.09636882275846118 shares for $49.91905018888289
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09599877121572843 shares for $53.4655556408878
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 59th day, sold 0.09636882275846118 shares for $49.91905018888289
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17825237578963055 shares for $105.35428418670323
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 60th day, sold 0.09626306771144183 shares for $49.17598814039006
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17531915484379426 shares for $103.62063327887616
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 60th day, sold 0.09626306771144183 shares for $49.17598814039006
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17202832508608146 shares for $101.67562125887758
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 235th day, sold 0.08298066550493735 shares for $49.05402041324371
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17202832508608146 shares for $101.67562125887758
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 205th day, sold 0.17202832508608146 shares for $102.46179070452098

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 106.72746353555354, Final Money: 106.72746353555354, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17810733160127143 shares for $102.6129769554405
On the 193th day, Bought 0.08571624494274153 shares for $49.99999999999999
On the 194th day, Bought 0.08650668696690254 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17222293190964408 shares for $102.57770047470311
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.166739304078092 shares for $97.72590612016972
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 61th day, sold 0.09749439407234084 shares for $49.18104708979234
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.1784969621943106 shares for $106.31457565255334
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.166739304078092 shares for $98.56793960576408
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.166739304078092 shares for $98.56793960576408
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 236th day, sold 0.1664768163323842 shares for $99.00209790470556
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18867154268899677 shares for $103.57879022083235
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 240th day, sold 0.08349615082744685 shares for $49.11410583972079

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 109.04200403898528, Final Money: 109.04200403898528, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 59th day, sold 0.09858432903505658 shares for $51.06668244015931
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19198464209553492 shares for $106.10223230051832
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09599877121572843 shares for $53.05468090008447
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17861262232871045 shares for $101.7752583291225
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17663179810615176 shares for $104.39645795265993
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17582727512007773 shares for $103.92095268697074
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 234th day, sold 0.08349615082744685 shares for $48.9370939999666
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17598826080561075 shares for $104.01610166654817
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
SPY Final Value: 109.06794394322412, Final Money: 109.06794394322412, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 122th day, Bought 0.5524861878453039 shares for $50.0
On the 125th day, sold 0.5524861878453039 shares for $50.73480662983425
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0915254873792657 shares for $101.16258217031036
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, sold 0.5685048322910744 shares for $48.055713473564516
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 152th day, Bought 0.5391998274560552 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0685804521251923 shares for $99.03603630296283
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 127th day, sold 0.5447809980387884 shares for $49.09021573327522
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5260389268805892 shares for $48.75328774329301
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.524824183898394 shares for $47.56481578671145
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.524824183898394 shares for $47.56481578671145
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5214308061320263 shares for $44.358118677651476

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0993826360297, Final Money: 100.0993826360297, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0844228128268467 shares for $98.67163173911477
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.119772962379967 shares for $102.82875113535238
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0915254873792657 shares for $99.11051425403733
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619240278714318 shares for $51.60148347943358
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.5391998274560552 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0855284987847265 shares for $105.2094221022157
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 154th day, Bought 0.5367686527106816 shares for $50.0
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 176th day, sold 1.072502071761362 shares for $103.9469007951112
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1014463109828538 shares for $93.70003767531136
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 176th day, sold 0.5357334190506804 shares for $51.923282974391945
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0554195515497262 shares for $96.33869666545901
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5516936996579499 shares for $46.93258302990179
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5357334190506804 shares for $45.57484195864138
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0554195515497262 shares for $89.78454125033521

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 97.32213923544671, Final Money: 97.32213923544671, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 61th day, sold 1.0871888974428363 shares for $97.29253443215941
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5472255663784612 shares for $49.80299879610376
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 163th day, sold 0.5514503143266791 shares for $50.07168854086246
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5253756435851634 shares for $48.69181464747295
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5441288497116117 shares for $46.46860376537164
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 176th day, sold 1.0691805544395634 shares for $103.62497933628248
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5653550429669832 shares for $48.28132066938037
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5685048322910744 shares for $48.55031267765776
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0547562682543004 shares for $96.27815216625254
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5685048322910744 shares for $48.55031267765776
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 0.529380624669137 shares for $49.809422975119105
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 242th day, sold 0.5915059742103396 shares for $49.21921211404235
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.529380624669137 shares for $44.04976177871889

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 98.32967540125506, Final Money: 98.32967540125506, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 35th day, Bought 0.5563591854901524 shares for $50.0
On the 56th day, sold 0.5563591854901524 shares for $51.65238678090575
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.1274773325509615 shares for $100.44695555696516
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.0886723930838493 shares for $99.64618413896473
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1184689967049135 shares for $100.25956086462845
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1009008637772286 shares for $99.96179843097235
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0788882080003819 shares for $91.19842022227228
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 121th day, sold 0.5619240278714318 shares for $50.370869858395146
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0845119696136738 shares for $91.67379679144385
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0966471303772733 shares for $100.10195006083751
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0966471303772733 shares for $92.69958193079091
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0808309389958162 shares for $92.49751175926194
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0757092959978083 shares for $92.05920155149244
XLB Final Value: 94.12222586846799, Final Money: 94.12222586846799, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.579979120751653 shares for $55.753392877856406
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 151th day, Bought 0.5614192679092747 shares for $50.0
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1145778031454734 shares for $94.8951541598056
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5569169079973267 shares for $50.607039429717084
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.5757052389176742 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5757052389176742 shares for $55.34254461715602
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.067180811577654 shares for $95.91821134459954
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 156th day, Bought 0.5498130635583902 shares for $50.00000000000001
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.102971598794589 shares for $100.0615834426451
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.1103815969501716 shares for $100.21193912475299
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0679201308875026 shares for $96.475904624377
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 179th day, sold 0.5531585352361987 shares for $50.18254231662795
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108588481558596 shares for $100.05011046066329
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 236th day, sold 0.5730002292000916 shares for $48.0919092367637
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 135th day, sold 1.0829689411473016 shares for $100.94353500433998
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108588481558596 shares for $100.05011046066329
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 136th day, sold 1.0829689411473016 shares for $98.26860171970614
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 136th day, sold 0.548666739822232 shares for $49.78601997146933
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 104.95076266302749, Final Money: 104.95076266302749, Final Shares: 0.0
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.579979120751653 shares for $56.67555967985153
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0568927500574965 shares for $97.2658397877914
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 95th day, sold 1.0679201308875026 shares for $96.92443107934974
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.094935722669386 shares for $98.91649318595235
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567308762943993 shares for $51.84834650929741
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 226th day, sold 0.5242189138184106 shares for $47.63577269867897
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 130th day, sold 0.5549389567147615 shares for $50.13318534961155
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 130th day, sold 0.5549389567147615 shares for $50.13318534961155
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 177th day, sold 0.562429696287964 shares for $49.38132733408324
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 98.03901868729304, Final Money: 46.98251623574038, Final Shares: 0.5837030119075415
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5336179295624333 shares for $49.73319103521878
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5534646889528448 shares for $51.24529555014391
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5730002292000916 shares for $48.45862938345174
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.545732372844357 shares for $50.52936040165902
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646

[*********************100%***********************]  1 of 1 completed

On the 241th day, Bought 0.5837030119075415 shares for $50.0
XLE Final Value: 98.98132895466102, Final Money: 47.92482650310838, Final Shares: 0.5837030119075415
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 85th day, Bought 0.5265374894692503 shares for $50.0
On the 95th day, sold 1.0608396907943196 shares for $96.28181033649246
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 106th day, Bought 0.5640794223826715 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1277772803308113 shares for $103.9697874736975
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 157th day, Bought 0.5477651183172656 shares for $50.00000000000001
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1115901070407657 shares for $97.59761139817923
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.117517062787762 shares for $104.07436405742426
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0451065062759581 shares for $87.71578907174117
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 119th day, Bought 0.5633168093735916 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1182557660883532 shares for $103.09199907568528
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 171th day, Bought 0.5633168093735916 shares for $49.99999999999999
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.127141798097092 shares for $98.96304987292467
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1248662813626384 shares for $98.76325950363965
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
XLE Final Value: 101.80689274731098, Final Money: 0.2830466539397207, Final Shares: 1.160670470942852

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.2330456226880395 shares for $92.13546239210851
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.276626291211212 shares for $100.80901217483246
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 1.072271070126528 shares for $49.62470512545571
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 237th day, sold 2.015524105733302 shares for $98.74052593987447
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 96th day, sold 1.200192030724916 shares for $49.43590974555929
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.247196571777908 shares for $99.50586419832577
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 238th day, sold 1.0092854259184498 shares for $49.566007266855074
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.391777228919281 shares for $104.8076781712429
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2379022564825797 shares for $103.57011643001378
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.3830007126571893 shares for $104.42309122863803
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 203th day, sold 2.2294092152559086 shares for $104.13570444460349
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.3830007126571893 shares for $104.42309122863803
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 1.1976047904191616 shares for $52.47904191616766

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 108.55879567324152, Final Money: 108.55879567324152, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.228803145736053 shares for $91.96041779306955
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.403275246576849 shares for $102.98034431581799
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.274804803274146 shares for $106.46086479323002
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 39th day, Bought 1.2147716229348884 shares for $50.0
On the 52th day, sold 1.2147716229348884 shares for $50.6195335276968
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.406471058877379 shares for $103.11728487289571
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2379022564825797 shares for $104.73382560338472
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 2.4044597264558503 shares for $103.03109927863319
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 128th day, sold 1.2357884330202669 shares for $53.2501235788433

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.2326522931034, Final Money: 112.2326522931034, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4105140597728463 shares for $103.86905083561196
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2784403631861974 shares for $106.63100899711402
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 229th day, Bought 1.008471157724889 shares for $50.0
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.017756583643339 shares for $98.36563345261277
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 240th day, sold 2.029452284704046 shares for $97.98195630551135
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 128th day, sold 1.2068549360366885 shares for $52.00337919382091
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 109.7349678715731, Final Money: 109.7349678715731, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2330456226880395 shares for $92.8277065351418
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, sold 2.4688340557083066 shares for $101.59252139239682
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.418830948492971 shares for $103.64690614292381
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2812835348939844 shares for $106.76406943303846
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.2330456226880395 shares for $93.22965474722565
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.4688340557083066 shares for $100.77780615401308
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.406471058877379 shares for $103.11728487289571
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2604395236624435 shares for $105.78856970740235
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.371791173519794 shares for $109.76649551049607
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.2330456226880395 shares for $90.66165228113441
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.235788433020267 shares for $91.2648838358873
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 2.3972209132598525 shares for $102.72091613318469
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 96th day, sold 1.2357884330202669 shares for $50.90212555610479
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 1.0604453870625663 shares for $52.54506892895016
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 127th day, sold 1.2357884330202669 shares for $52.95353435491844
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 127th day, sold 1.2330456226880395 shares for $52.8360049321825
XLF Final Value: 111.82718128866776, Final Money: 62.9340438364641, Final Shares: 1.0062386798148522

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7959566428887224 shares for $97.10671043242412
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4049566696363489 shares for $50.84635943953997
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39142007202129325 shares for $52.383748238609684
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7053194773636646 shares for $93.89212882665103
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 236th day, sold 0.35481124042009654 shares for $47.232472324723254
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.38675742574257427 shares for $54.69910272277228
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.796407374083437 shares for $99.44738880179878

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 104.75647884657614, Final Money: 104.75647884657614, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 69th day, sold 0.82697056674124 shares for $101.27081560313225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8250044961264706 shares for $103.58756453363965
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 237th day, sold 0.7303689539425081 shares for $97.98629886092688
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 69th day, sold 0.82697056674124 shares for $101.27081560313225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 69th day, sold 0.4119294776734223 shares for $50.444883835887296
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7831204863019074 shares for $110.09107796432215
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 112.71797496517846, Final Money: 112.71797496517846, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.8002117420331725 shares for $97.64983888030804
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 241th day, sold 0.7303689539425081 shares for $96.23341337146486
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 74th day, sold 0.4062728528479727 shares for $49.53278621922483
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959566428887224 shares for $97.13058913171079
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 128th day, sold 0.41473125414731254 shares for $52.314200398142006
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.37752944729688914 shares for $50.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 56th day, sold 0.41145490454246214 shares for $51.617017774851874
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 74th day, sold 0.4062728528479727 shares for $49.53278621922483
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7965350266356567 shares for $97.20116930034918
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3844083954793573 shares for $54.62058891366188
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.37752944729688914 shares for $50.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 56th day, sold 0.41145490454246214 shares for $51.617017774851874
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.8056657756053814 shares for $98.3153945971247
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3844083954793573 shares for $54.62058891366188
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 93th day, sold 0.39939292275740873 shares for $48.73791836408659
On the 199th day, Bought 0.3693034936110496 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3693034936110496 shares for $52.47433340719404
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 93th day, sold 0.3994886545222116 shares for $48.749600511345484

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 110.07068860137915, Final Money: 11.27468759804664, Final Shares: 0.7443942209413239
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 52th day, sold 0.4132231404958678 shares for $51.40909090909091
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.8250044961264706 shares for $104.40431898480486
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7839155583232007 shares for $110.86917741365028
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7303689539425081 shares for $97.22671514882668
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 125th day, sold 0.41473125414731254 shares for $52.4842402123424
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.82697056674124 shares for $100.24537210037312
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.390625 shares for $55.24609375
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
XLI Final Value: 114.11408549946013, Final Money: 114.11408549946013, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 31th day, Bought 0.2372366672992978 shares for $50.0
On the 36th day, sold 0.2372366672992978 shares for $49.19102296450939
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.24077819512664933 shares for $48.52162188192238
On the 80th day, Bought 0.24326165223314197 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24326165223314197 shares for $51.35983263598327
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22472920131241853 shares for $50.31911546586363
On the 222th day, Bought 0.21114864864864863 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21114864864864863 shares for $49.08994932432432
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 66th day, sold 0.48033358033170875 shares for $93.30479797943443
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2251339547030483 shares for $50.40974379755955
On the 223th day, Bought 0.20735702732965622 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.20735702732965622 shares for $48.20843528387178
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.47962836739164416 shares for $109.55191539592545
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 223th day, Bought 0.20735702732965622 shares for $50.0
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4192663301480499 shares for $97.47522909612013
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.47962836739164416 shares for $109.87326640207785
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 229th day, Bought 0.21005755577028107 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4189392034287178 shares for $97.39917540514261
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 124th day, sold 0.23955538520505942 shares for $55.921809122269075
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 124th day, sold 0.23955538520505942 shares for $55.921809122269075
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 107.69420398337566, Final Money: 107.69420398337566, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4779824751654502 shares for $96.32302839534154
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.21470285125386465 shares for $48.17502576434215
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2299484915378955 shares for $51.48776674025018
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 40th day, sold 0.24321432045918862 shares for $50.778285825469396
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.4779824751654502 shares for $96.43774418938123
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 40th day, sold 0.24321432045918862 shares for $50.778285825469396
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.4779824751654502 shares for $96.43774418938123
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.2229654403567447 shares for $49.88628762541806
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 111th day, sold 0.23819732266209329 shares for $53.88976227907199
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22005105184402782 shares for $49.234222339582786
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 100.77445078141733, Final Money: 100.77445078141733, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 161th day, Bought 0.2451941938014908 shares for $50.0
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4728808968980299 shares for $105.88276162443788
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.21632847315363649 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.43246991611390967 shares for $101.4012212312284
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 161th day, Bought 0.2451941938014908 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2451941938014908 shares for $54.901431934091804
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 215th day, Bought 0.21415110501970192 shares for $50.0
On the 240th day, sold 0.43029254797997507 shares for $100.89069372486476
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 38th day, sold 0.2415692337423906 shares for $50.975939704319266
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 38th day, sold 0.2415692337423906 shares for $50.975939704319266
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44656903590256103 shares for $99.915356092839
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.44656903590256103 shares for $104.20688452786261
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 204th day, sold 0.2229654403567447 shares for $52.028985507246375

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 107.49273199346176, Final Money: 107.49273199346176, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 40th day, sold 0.24321432045918862 shares for $50.778285825469396
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 45th day, Bought 0.23827678231033167 shares for $50.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4767240139379725 shares for $96.06942328878021
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4279497485115096 shares for $96.01480557604229
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22687054766550208 shares for $50.79858432778257
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 62th day, sold 0.24321432045918862 shares for $49.07092129584589
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22693232877955793 shares for $50.81241773703081
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 236th day, sold 0.21590810950859313 shares for $51.401243630710766
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 77th day, sold 0.24321432045918862 shares for $49.67895709699386
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
XLK Final Value: 100.9301387470271, Final Money: 100.9301387470271, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 155th day, Bought 0.6077549532028687 shares for $50.0
On the 156th day, Bought 0.610798924993892 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2185538781967606 shares for $97.30152717401133
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 218th day, sold 0.6232859636000997 shares for $51.50211917227624
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 231th day, sold 0.6039376736320812 shares for $49.287353545114144
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2154443376425925 shares for $98.23221136827432
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 232th day, sold 0.6069434328720563 shares for $49.44768147608643
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6093102607847916 shares for $49.073848403607116
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 70th day, sold 0.6715014773032502 shares for $50.758796669352684
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
XLP Final Value: 102.85037899613269, Final Money: 102.85037899613269, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.3027624078912101 shares for $100.45600927249122
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.6422607578676943 shares for $50.0
On the 138th day, sold 1.2833685922054299 shares for $99.7177396143619
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.2437834227153124 shares for $103.29621325650669
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.6024096385542169 shares for $50.00000000000001
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2046741531290182 shares for $97.80749449254498
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.6422607578676943 shares for $50.0
On the 138th day, sold 1.2833685922054299 shares for $99.7177396143619
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.2400059548577866 shares for $102.98249455093918
On the 178th day, Bought 0.6044487427466151 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 185th day, sold 1.214056155572755 shares for $98.56921927095198
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2110226334153902 shares for $96.03409482984044
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 53th day, sold 0.6637461834594451 shares for $49.46900305323245
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2348803404304947 shares for $100.25993483955186
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 239th day, sold 1.2110226334153902 shares for $96.03409482984044
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.93208186677096, Final Money: 100.93208186677096, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 53th day, sold 0.6637461834594451 shares for $49.46900305323245
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6399590426212722 shares for $49.47523358505056
On the 99th day, Bought 0.6438320885912954 shares for $49.99999999999999
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6438320885912954 shares for $50.6953386556786
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6227425582264291 shares for $51.46967243741437
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.215885536776542 shares for $100.05522082134165
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.2023570535234946 shares for $95.77976288368158
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.286428337427199 shares for $101.29336728901764
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 170th day, sold 1.227685713783603 shares for $101.4682242442148
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 234th day, sold 1.2062079794997167 shares for $96.08652764694743
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.227685713783603 shares for $101.95929852972823
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 234th day, sold 1.2062079794997167 shares for $96.08652764694743
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 171th day, sold 0.6117704637220115 shares for $50.80753701211305
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.15887513592818, Final Money: 102.15887513592818, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.342552488151616 shares for $101.17475550710579
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3027624078912101 shares for $101.7327164322246
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 137th day, sold 0.6411078343377357 shares for $50.81420694960893
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 191th day, Bought 0.6079766536964981 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2172869144812897 shares for $97.20036012133097
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.239884804394279 shares for $98.80642006218008
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3424622931916024 shares for $100.05371471157012
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3027624078912101 shares for $101.7327164322246
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 239th day, sold 0.6232859636000997 shares for $49.42657691348791
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2437834227153124 shares for $99.31610630381769
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 1.2306482773150234 shares for $98.2672649436046
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
XLP Final Value: 100.84920847120446, Final Money: 100.84920847120446, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 79th day, Bought 0.34891835310537334 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.34891835310537334 shares for $50.13956734124214
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.34220792553555535 shares for $49.03839572924508
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 112th day, Bought 0.34277096044423117 shares for $50.0
On the 116th day, sold 0.34277096044423117 shares for $49.11907863165833
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6827130702820167 shares for $96.91112032653226
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 54th day, sold 0.3442577802258331 shares for $48.867391903057005
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 204th day, sold 0.321316110789795 shares for $47.56763704132125
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.53019972820316, Final Money: 99.53019972820316, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3550379890648299 shares for $51.01895902861605
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6470402507516887 shares for $99.57302418817737
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.3391900142459806 shares for $47.255952784750015
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6877579612666824 shares for $97.62724260180556
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3550379890648299 shares for $51.01895902861605
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.34234851078397804 shares for $50.44505306401916
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32379225488926305 shares for $50.10361352156457
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6890405585234674 shares for $97.80930728240618
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 121th day, sold 0.3409943394939644 shares for $50.24551592443565
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.321646831778707 shares for $49.77163074943712
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6419132934748382 shares for $98.39246962382319
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 55th day, sold 0.34525618008562353 shares for $49.447590111863
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 55th day, sold 0.34525618008562353 shares for $49.447590111863
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 97.90674498828531, Final Money: 97.90674498828531, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6890405585234674 shares for $98.684388791731
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3402054841124039 shares for $50.12927808396272
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32379225488926305 shares for $50.10361352156457
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32324799586242564 shares for $50.019394879751744
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.26090249303772, Final Money: 99.26090249303772, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6839719051540245 shares for $101.1389256151256
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.33978933061501865 shares for $47.14576962283384
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6849785388796403 shares for $101.28777654413241
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6468314072345274 shares for $99.14631810090836
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6877579612666824 shares for $99.05777916124028
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6849785388796403 shares for $101.28777654413241
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6877579612666824 shares for $99.05777916124028
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 209th day, sold 0.6788695024739367 shares for $99.67840904824814
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
XLV Final Value: 100.15616518810998, Final Money: 100.15616518810998, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.26893287435456115 shares for $53.84842943201377
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 175th day, Bought 0.24932681759250025 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.24932681759250025 shares for $49.92270868654632
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.49849274560048373 shares for $105.73529626931861
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2794076557697681 shares for $52.46437552388936
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 110.0436431151654, Final Money: 110.0436431151654, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 125th day, sold 0.26452227277536766 shares for $50.642789122844135
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2798298634430266 shares for $53.027759122453546
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5615154347173892 shares for $106.40717487894526
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5130302364012908 shares for $103.02160177174319
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 126th day, sold 0.28028476932563484 shares for $53.1139637872078
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5130302364012908 shares for $103.02160177174319
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 113.78688773400131, Final Money: 113.78688773400131, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2794076557697681 shares for $51.536742106733726
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5022116493566033 shares for $106.52411294502915
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 210th day, Bought 0.23225566703827574 shares for $50.0
On the 211th day, sold 0.46317055181174827 shares for $98.85912257869956
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 205th day, sold 0.5022116493566033 shares for $106.52411294502915
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 211th day, sold 0.2309148847734725 shares for $49.28647300604997
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.2176373291546966 shares for $50.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5617212209748524 shares for $106.44617137473453
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 116.73926142802964, Final Money: 116.73926142802964, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2807411566535654 shares for $52.71476698483998
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5404948991210178 shares for $108.53678069249158
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5427999546785756 shares for $108.99965889900476
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 58th day, sold 0.2808199943836001 shares for $50.151642796967145
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.561060528834781 shares for $105.35033549930682
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 59th day, sold 0.2808199943836001 shares for $50.556023588879526
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 126th day, sold 0.5610292104393202 shares for $106.31503537825118
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2671939293539251 shares for $53.6552129535617
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
XLY Final Value: 114.61282125149361, Final Money: 114.61282125149361, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 61th day, sold 0.7907638779060573 shares for $50.300490273604304
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, sold 1.3890620513572678 shares for $96.08142209238221
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.7265329845975008 shares for $50.90816623074688
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 172th day, sold 0.6672894701721607 shares for $53.603363138929666
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2348654834504846 shares for $98.67810078252822
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 220th day, Bought 0.6029181237187989 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2241133032442058 shares for $93.62018543211686
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 61th day, sold 0.7838219156607619 shares for $49.858912055181065
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, sold 0.6893699158968702 shares for $47.68371708258652
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 125th day, sold 0.7197351374694113 shares for $50.460630487980424
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3360068701989094 shares for $106.55990796706502
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2348654834504846 shares for $98.67810078252822
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 61th day, sold 0.7838219156607619 shares for $49.858912055181065
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6893699158968702 shares for $48.331724803529575
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 184th day, sold 0.6687174000267487 shares for $52.694931122107796
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 197th day, Bought 0.6172077521293667 shares for $50.0
On the 200th day, sold 1.230027950683111 shares for $98.29153353908741
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6893699158968702 shares for $48.331724803529575
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6640106241699868 shares for $51.87915006640107
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6911805363560962 shares for $51.29941940834946
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6923289947382997 shares for $51.3846579894766

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 105.89450333561368, Final Money: 105.89450333561368, Final Shares: 0.0
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.5006686690444817 shares for $109.1286256129147
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.441891602172256 shares for $101.09102022829687
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.346354675156112 shares for $107.81608238650145
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 218th day, Bought 0.6031363088057901 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2170098508561278 shares for $92.56576925611708
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4124102758916717 shares for $102.71047526284237
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 125th day, sold 0.7068136839129207 shares for $49.55470737913487
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2884108790184259 shares for $97.99653145814148
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4024265352120677 shares for $101.98445764062156
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 125th day, sold 0.7068136839129207 shares for $49.55470737913487
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 237th day, sold 1.2963034222107883 shares for $99.14128573068109
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 94th day, sold 0.7015574575557738 shares for $51.01725831345587
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 238th day, sold 0.6444129398118313 shares for $49.16870730764273
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 0.7015574575557738 shares for $50.43496562368458
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 111.67368221454683, Final Money: 61.14267395441833, Final Shares: 0.6555657532450505
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 75th day, sold 0.7452675510508272 shares for $50.983753167387086
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 85th day, sold 0.7008690776562938 shares for $50.70086907765629
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 93th day, sold 1.3805014311268045 shares for $98.65063226832144
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 0.713165026387106 shares for $50.98416773641421
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.352185047296217 shares for $108.28297858748105
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 62th day, sold 0.7880220646178092 shares for $49.464144996059886
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.428063510802319 shares for $102.09226038725778
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 62th day, sold 0.7880220646178092 shares for $49.464144996059886
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7015574575557738 shares for $50.133295916935595
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 66th day, sold 0.7880220646178092 shares for $52.033096926713945
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 93th day, sold 0.6861534239055852 shares for $49.03252367229312
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 66th day, sold 0.7827175954915466 shares for $51.682842830306825
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 110.21844897858787, Final Money: 59.68744071845937, Final Shares: 0.6555657532450505
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 51th day, sold 0.7862871520679352 shares for $51.30523667243277
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7115411982353779 shares for $51.74327593567668
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4688613054034505 shares for $102.92311166961977
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 139th day, sold 0.7094211123723042 shares for $51.69551645856981
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2466642813517768 shares for $94.82128523961615
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7008690776562938 shares for $50.96719932716569
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 124th day, sold 1.441891602172256 shares for $101.03334456420997
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 139th day, sold 0.7094211123723042 shares for $51.69551645856981
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2317703413278247 shares for $93.68845216139435
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7015574575557738 shares for $50.43496562368458
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.265276076086015 shares for $96.2368983471023
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 173th day, sold 1.346354675156112 shares for $107.38524889045149
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
XLU Final Value: 114.20833418147663, Final Money: 64.53698478078067, Final Shares: 0.6444129398118313

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 37th day, sold 0.09858432903505658 shares for $50.40419574904372
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.19116072968642112 shares for $99.15889370294036
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 173th day, Bought 0.08751969193068442 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17523283486802216 shares for $100.06495802303537
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 37th day, sold 0.09858432903505658 shares for $50.40419574904372
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.19116072968642112 shares for $99.15889370294036
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17463810735127167 shares for $99.72534482187017
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 37th day, sold 0.09858432903505658 shares for $50.40419574904372
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.19116072968642112 shares for $99.15889370294036
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17463810735127167 shares for $99.72534482187017
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 59th day, sold 0.09558950044927064 shares for $49.51536123272219
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17507663733900194 shares for $99.76041872213669
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 59th day, sold 0.09558950044927064 shares for $49.51536123272219
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 202th day, sold 0.17507663733900194 shares for $99.76041872213669
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
SPY Final Value: 99.92104692065574, Final Money: 99.92104692065574, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 59th day, sold 0.09858432903505658 shares for $51.06668244015931
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.19198464209553492 shares for $107.80513607590572
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 59th day, sold 0.09557122923715046 shares for $49.50589674484394
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.09598587087980649 shares for $53.89894607513774
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 59th day, sold 0.09636882275846118 shares for $49.91905018888289
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17711830714665414 shares for $105.49343491961868
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 60th day, sold 0.09636882275846118 shares for $49.230013106159895
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.1751952674334211 shares for $104.34805323601994
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 60th day, sold 0.09626306771144183 shares for $49.17598814039006
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 205th day, sold 0.17202832508608146 shares for $102.46179070452098
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.08349615082744685 shares for $49.358749561645205
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.42892142157243, Final Money: 108.42892142157243, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 37th day, sold 0.09840969925995907 shares for $50.31491103763187
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 54th day, Bought 0.0974525893152981 shares for $50.0
On the 60th day, sold 0.19371565702673993 shares for $98.9596433921101
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.09437879874664956 shares for $49.81312997848163
On the 102th day, Bought 0.0923599822668834 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.0923599822668834 shares for $51.043667799615775
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 184th day, sold 0.17850498203719833 shares for $103.02236533294864
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17243352818983582 shares for $102.7031337251481
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.166739304078092 shares for $97.75591919490378
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.18895217823179206 shares for $104.42631082158219
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17825237578963055 shares for $102.69654126367985
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17202832508608146 shares for $102.46179070452098
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.166739304078092 shares for $97.72590612016972
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 185th day, sold 0.17726270862194415 shares for $102.12636431836069
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 205th day, sold 0.08608370779746224 shares for $51.27231720124649
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.166739304078092 shares for $98.56793960576408
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 185th day, sold 0.08771314293733774 shares for $50.53417304048839
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 205th day, sold 0.08608370779746224 shares for $51.27231720124649
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.08349615082744685 shares for $49.358749561645205
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09409816320385425 shares for $52.00429087624209
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 205th day, sold 0.08608370779746224 shares for $51.27231720124649
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.08349615082744685 shares for $49.358749561645205
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09409816320385425 shares for $52.00429087624209
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.58314377690283, Final Money: 107.58314377690283, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.19198464209553492 shares for $107.5094797270786
On the 149th day, Bought 0.08949346697691068 shares for $50.00000000000001
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17853114772340262 shares for $101.94842659597182
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19198464209553492 shares for $106.10223230051832
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19198464209553492 shares for $106.10223230051832
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17861262232871045 shares for $101.9949518545868
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 201th day, sold 0.17401589449508104 shares for $99.37003639247106
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 61th day, sold 0.09858432903505658 shares for $49.73086478173429
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 202th day, sold 0.08793218669761879 shares for $50.104639302170156
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 234th day, sold 0.08349615082744685 shares for $48.9370939999666
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.08349615082744685 shares for $49.358749561645205
SPY Final Value: 107.39177286301947, Final Money: 107.39177286301947, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 122th day, Bought 0.5524861878453039 shares for $50.0
On the 125th day, sold 0.5524861878453039 shares for $50.73480662983425
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.1009008637772286 shares for $104.00210460103479
On the 212th day, Bought 0.5435373410153278 shares for $50.0
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 1.0782966993040979 shares for $97.72602985793038
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 50th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.0890283040146238 shares for $100.0054691576629
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.0890283040146238 shares for $100.0054691576629
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0508631107789832 shares for $97.39399310699618
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5214308061320263 shares for $48.326207112316204
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5214308061320263 shares for $48.326207112316204
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5184570717544588 shares for $46.987764413106596

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 104.65780057791302, Final Money: 104.65780057791302, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.0870186845035645 shares for $99.49482019261126
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.0554195515497262 shares for $99.27276301876725
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 32th day, Bought 0.5643340857787811 shares for $50.0
On the 59th day, sold 0.5643340857787811 shares for $51.65914221218962
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.1245294249632232 shares for $100.18432646997356
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0844228128268467 shares for $98.67163173911477
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.119772962379967 shares for $102.82875113535238
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0958225493695615 shares for $93.22162427486859
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0977789856553506 shares for $106.39673928971658
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0958225493695615 shares for $93.22162427486859
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5514503143266791 shares for $51.108415131796626
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.115905213742264 shares for $94.9300565330544
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5357334190506804 shares for $45.57484195864138
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 128th day, sold 0.541829215431296 shares for $48.98677936714347
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5357334190506804 shares for $45.57484195864138

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.80348518071861, Final Money: 100.80348518071861, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 59th day, sold 1.0871888974428363 shares for $99.52127167191725
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5472255663784612 shares for $49.80299879610376
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5685048322910744 shares for $48.55031267765776
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 61th day, sold 0.5474652359575167 shares for $48.99266396583817
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5472255663784612 shares for $49.091605559811754
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 163th day, sold 0.5514503143266791 shares for $50.07168854086246
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5334471353888829 shares for $51.701696361890534
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5685048322910744 shares for $48.55031267765776
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 176th day, sold 0.5334471353888829 shares for $51.701696361890534
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0547562682543004 shares for $96.27815216625254
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0547562682543004 shares for $96.27815216625254
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 128th day, sold 0.5619240278714318 shares for $50.80355135985615
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.0547562682543004 shares for $90.07618530891726
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5253756435851634 shares for $44.86707996217296

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.91226042322565, Final Money: 100.91226042322565, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 32th day, Bought 0.5643340857787811 shares for $50.0
On the 55th day, sold 0.5643340857787811 shares for $52.35327313769752
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0877261845762307 shares for $98.97220553459123
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1184689967049135 shares for $102.7090079674122
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1009008637772286 shares for $99.96179843097235
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0958225493695615 shares for $92.62988009820903
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619240278714318 shares for $51.60148347943358
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.1009008637772286 shares for $102.03149205487355
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 125th day, sold 0.5577867023650156 shares for $51.22155287817938
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.1009008637772286 shares for $102.03149205487355
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 126th day, sold 1.0996159177963116 shares for $99.97707924604066
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0977789856553506 shares for $101.7421563905379
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1120433578446582 shares for $94.00102503860896
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0651140437198174 shares for $90.03409011563618
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 228th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0478710816543884 shares for $88.57654253224545
XLB Final Value: 98.00818411272091, Final Money: 98.00818411272091, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 34th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.579979120751653 shares for $55.753392877856406
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 1.116983523959699 shares for $94.2175602460006
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5389673385792821 shares for $48.641802306780214
On the 230th day, Bought 0.5604124635731899 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5604124635731899 shares for $47.15310468504819
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0679201308875026 shares for $95.98466136416873
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 156th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.1014041492712865 shares for $99.91938442189111
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.1103815969501716 shares for $93.42750756738744
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.066042591472773 shares for $95.81590812157282
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 128th day, sold 1.103184570749849 shares for $101.26131174912865
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 156th day, Bought 0.5498130635583902 shares for $50.00000000000001
On the 179th day, sold 1.0980586775934777 shares for $99.6158832312803
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 98.3449361109898, Final Money: 98.3449361109898, Final Shares: 0.0
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5737893045673629 shares for $56.11085609364242
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0568927500574965 shares for $97.2658397877914
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.5265374894692503 shares for $50.0
On the 95th day, sold 1.0604403191542475 shares for $96.24556336643951
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5679236710586096 shares for $51.30622444343479
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.115884169467676 shares for $97.97463007926194
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5567928730512249 shares for $50.59576837416481
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5730002292000916 shares for $47.74237909695163
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.5737893045673629 shares for $54.165710351159056
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0568927500574965 shares for $97.2658397877914
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5569789461958338 shares for $50.61267684081542
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 62th day, sold 0.5130309870716192 shares for $48.430125179560854
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 165th day, Bought 0.5874750323111267 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5874750323111267 shares for $51.58030783691693
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5569789461958338 shares for $50.61267684081542
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 62th day, sold 0.5130309870716192 shares for $48.430125179560854
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.5610412926391383 shares for $50.89766606822262
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 62th day, sold 0.5130309870716192 shares for $48.430125179560854
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 179th day, sold 0.5610412926391383 shares for $50.89766606822262
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 198th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 62th day, sold 0.5130309870716192 shares for $48.430125179560854
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 198th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 101.02955221925774, Final Money: 49.97304976770509, Final Shares: 0.5837030119075415
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.5152514427040396 shares for $48.639736191261335
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5336179295624333 shares for $49.73319103521878
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 219th day, sold 0.5534646889528448 shares for $52.645561213194604
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 237th day, sold 0.5948839976204641 shares for $50.35098155859608
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.545732372844357 shares for $50.52936040165902
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.545732372844357 shares for $50.52936040165902
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 224th day, sold 0.5389673385792821 shares for $49.902985879055734
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 187th day, Bought 0.5389673385792821 shares for $50.0

[*********************100%***********************]  1 of 1 completed

On the 224th day, sold 0.5389673385792821 shares for $49.902985879055734
On the 241th day, Bought 0.5837030119075415 shares for $50.0
XLE Final Value: 100.30942824102027, Final Money: 49.25292578946761, Final Shares: 0.5837030119075415

read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5737893045673629 shares for $56.0706908423227
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 61th day, sold 0.5201289919900135 shares for $49.531883907208986
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 85th day, Bought 0.5265374894692503 shares for $50.0
On the 95th day, sold 1.0608396907943196 shares for $96.28181033649246
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 106th day, Bought 0.5640794223826715 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.132003093441281 shares for $102.26515946148533
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.5874750323111267 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.151300021034627 shares for $101.08414184684024
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.117517062787762 shares for $104.07436405742426
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0451065062759581 shares for $87.71578907174117
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5737893045673629 shares for $56.0706908423227
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 61th day, sold 0.5201289919900135 shares for $49.531883907208986
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 119th day, Bought 0.5633168093735916 shares for $49.99999999999999
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.1182557660883532 shares for $101.02322590842184
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1248662813626384 shares for $98.76325950363965
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 127th day, Bought 0.5413012882970661 shares for $50.0
On the 130th day, sold 1.0962402450118276 shares for $99.0343437343685
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.5610412926391383 shares for $50.381508078994614
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
XLE Final Value: 100.23876969292269, Final Money: 49.18226724137003, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 46th day, sold 2.2312238364934744 shares for $92.41729130755972
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.4105140597728463 shares for $104.8332564595211
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2812835348939844 shares for $101.01523492510563
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 1.072271070126528 shares for $49.62470512545571
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 236th day, sold 2.015524105733302 shares for $97.5916771996065
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 46th day, sold 2.2312238364934744 shares for $92.41729130755972
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 124th day, sold 2.4044597264558503 shares for $104.56995350356493
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2812835348939844 shares for $101.01523492510563
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 96th day, sold 1.1941724385001196 shares for $49.18796274181992
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.2379022564825797 shares for $104.53241440030129
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.391777228919281 shares for $104.8076781712429
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 203th day, sold 2.2294092152559086 shares for $104.13570444460349
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 125th day, sold 1.1853959222380275 shares for $51.94404931247036

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 108.94338261584639, Final Money: 108.94338261584639, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.228803145736053 shares for $91.96041779306955
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.418830948492971 shares for $103.64690614292381
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2784403631861974 shares for $106.63100899711402
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 240th day, sold 2.002850200644033 shares for $96.6976076870939
On the 38th day, Bought 1.2236906510034264 shares for $50.00000000000001
On the 39th day, Bought 1.0 shares for $41.16
On the 52th day, sold 2.2236906510034267 shares for $92.66118942731279
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.406471058877379 shares for $103.11728487289571
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.255802452049888 shares for $105.57155475593474
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 2.4044597264558503 shares for $103.03109927863319
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 1.1976047904191616 shares for $51.31736526946108
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 202th day, sold 1.0604453870625663 shares for $49.07741251325557
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 127th day, sold 1.2357884330202669 shares for $52.95353435491844
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 1.0604453870625663 shares for $52.54506892895016

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 110.77419189933275, Final Money: 61.881054447129074, Final Shares: 1.0062386798148522
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.418830948492971 shares for $104.22742557056213
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 2.2784403631861974 shares for $101.36781175815392
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.015524105733302 shares for $98.25680015449848
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 242th day, sold 2.0173610256186945 shares for $97.25697504507725
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.2758364540624174 shares for $106.14501221747115
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 1.1976047904191616 shares for $51.604790419161674
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 111.17433852842704, Final Money: 111.17433852842704, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.2312238364934744 shares for $92.06029549372074
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4746387798983642 shares for $102.35105993659634
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.418830948492971 shares for $103.64690614292381
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 184th day, sold 2.2784403631861974 shares for $104.28421542303226
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.0058388397508775 shares for $96.84189918317237
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2312238364934744 shares for $92.75197488303374
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4746387798983642 shares for $102.35105993659634
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 1.1976047904191616 shares for $51.31736526946108
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 185th day, sold 2.2758364540624174 shares for $103.84641739886811
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 201th day, sold 2.120443435260447 shares for $98.89748182054726
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 59th day, sold 2.2330456226880395 shares for $90.66165228113441
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.235788433020267 shares for $93.03115669797332
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 127th day, sold 1.2357884330202669 shares for $52.95353435491844
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 127th day, sold 1.2330456226880395 shares for $52.8360049321825
XLF Final Value: 107.28471651240874, Final Money: 107.28471651240874, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7959566428887224 shares for $96.86792343955752
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4049566696363489 shares for $50.84635943953997
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39142007202129325 shares for $52.383748238609684
On the 219th day, Bought 0.34921078362899843 shares for $50.0
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.6997190205725665 shares for $93.14659601862006
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39142007202129325 shares for $52.383748238609684
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7216760140645313 shares for $96.06951099227041
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7973563487023718 shares for $99.56588726246517
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 205th day, sold 0.7768947540821498 shares for $109.21586452886864
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.796407374083437 shares for $99.44738880179878

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 110.7115038574495, Final Money: 110.7115038574495, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.8293256196834445 shares for $101.25236490715174
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7973563487023718 shares for $96.63958946272747
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4102732419791581 shares for $51.513908262903094
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7303689539425081 shares for $97.22671514882668
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7973563487023718 shares for $96.63958946272747
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8250044961264706 shares for $103.58756453363965
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 238th day, sold 0.3668647736444347 shares for $49.2552645095018
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.8262140082890491 shares for $100.15366208479853
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 151th day, Bought 0.390625 shares for $50.0
On the 205th day, sold 0.390625 shares for $54.91406250000001
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 112.90299794980984, Final Money: 112.90299794980984, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 53th day, Bought 0.39984006397441024 shares for $50.0
On the 56th day, sold 0.39984006397441024 shares for $50.159936025589765
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 76th day, Bought 0.40319329086364003 shares for $50.0
On the 77th day, Bought 0.40209087253719344 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8052841634008334 shares for $97.60044060418102
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.782632814641483 shares for $111.20429663240833
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 228th day, Bought 0.3605422555523507 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.7110504924959189 shares for $95.46563912250207
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 53th day, Bought 0.39984006397441024 shares for $50.0
On the 56th day, sold 0.39984006397441024 shares for $50.159936025589765
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.4062728528479727 shares for $49.24839522223125
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7999266459299369 shares for $96.95110948670835
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7831204863019074 shares for $111.27358989863804
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 238th day, sold 0.7173730105880028 shares for $96.31450040154526
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8056657756053814 shares for $97.64669200337224
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 128th day, sold 0.4137702747434624 shares for $52.19298245614035
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 238th day, sold 0.7173730105880028 shares for $96.31450040154526
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8056657756053814 shares for $97.64669200337224
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3844083954793573 shares for $54.62058891366188
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 242th day, sold 0.35050823694356814 shares for $46.0217315106905
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 56th day, sold 0.41145490454246214 shares for $51.617017774851874
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 92th day, sold 0.7988815772796203 shares for $96.82444716628999
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 206th day, sold 0.3681885125184094 shares for $52.31590574374079
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 242th day, sold 0.35050823694356814 shares for $46.0217315106905
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 56th day, sold 0.41145490454246214 shares for $51.617017774851874
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 92th day, sold 0.3994886545222116 shares for $48.418024928092045
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 207th day, sold 0.3681885125184094 shares for $52.72091310751104

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 108.45128671002685, Final Money: 108.45128671002685, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 54th day, sold 0.4132231404958678 shares for $51.219008264462815
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7959566428887224 shares for $96.46994511811316
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4102732419791581 shares for $51.92007877246245
On the 146th day, Bought 0.39323633503735744 shares for $50.0
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.7846564070586507 shares for $105.15180510992977
On the 221th day, Bought 0.3498215909885958 shares for $50.0
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.7133257712866692 shares for $94.35159976808774
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 69th day, sold 0.8262140082890491 shares for $101.17816745507695
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959566428887224 shares for $97.13058913171079
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 120th day, Bought 0.41010498687664043 shares for $50.0
On the 125th day, sold 0.8203782288557986 shares for $103.81886486170131
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7839155583232007 shares for $110.86917741365028
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 69th day, sold 0.8262140082890491 shares for $101.17816745507695
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959566428887224 shares for $97.13058913171079
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959566428887224 shares for $97.13058913171079
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7959566428887224 shares for $97.10671043242412
On the 151th day, Bought 0.390625 shares for $50.0
On the 205th day, sold 0.390625 shares for $54.91406250000001
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
XLI Final Value: 114.92655092825503, Final Money: 114.92655092825503, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 31th day, Bought 0.2372366672992978 shares for $50.0
On the 36th day, sold 0.2372366672992978 shares for $49.19102296450939
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22687054766550208 shares for $50.79858432778257
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21791239921551536 shares for $50.66245369361517
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.4805633476300063 shares for $96.95846101783006
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.48033358033170875 shares for $109.71299308356559
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 234th day, sold 0.21190930281839374 shares for $49.26679381224836
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.48033358033170875 shares for $109.71299308356559
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 234th day, sold 0.21190930281839374 shares for $49.26679381224836
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.47962836739164416 shares for $107.60942050798928
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44572709621218687 shares for $105.8245271826974
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 52th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4794792546309228 shares for $107.58555515408645
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 205th day, sold 0.22700444928720603 shares for $53.895396349768454

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 115.296064584351, Final Money: 115.296064584351, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.2384472316276408 shares for $48.05188611760218
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23999232024575212 shares for $54.35826053566286
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2302343785974122 shares for $51.55177971174656
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 40th day, sold 0.24321432045918862 shares for $50.778285825469396
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.47664455428973407 shares for $96.16780527349674
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 170th day, Bought 0.22359359627940256 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22359359627940256 shares for $50.06484214292103
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 40th day, sold 0.24321432045918862 shares for $50.778285825469396
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.47664455428973407 shares for $96.16780527349674
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2229654403567447 shares for $49.92419175027871
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 111th day, sold 0.24321432045918862 shares for $55.024807860686835
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44996988964395074 shares for $100.752757990177
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 111th day, sold 0.24321432045918862 shares for $55.024807860686835
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 187th day, Bought 0.21383970575656489 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44084415504377095 shares for $98.70941475585074
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 111th day, sold 0.24321432045918862 shares for $55.024807860686835
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4441880128351167 shares for $99.45813795391098

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 101.80093042187636, Final Money: 101.80093042187636, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 44th day, Bought 0.2384472316276408 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.2384472316276408 shares for $48.05188611760218
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.43277581037780777 shares for $97.10623633257251
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.223254152527237 shares for $49.98883729237363
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21791239921551536 shares for $50.66245369361517
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 161th day, Bought 0.2451941938014908 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2451941938014908 shares for $54.901431934091804
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 240th day, sold 0.4340538421757886 shares for $101.77260437495714
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 52th day, Bought 0.24173274028234384 shares for $50.0
On the 61th day, sold 0.4815178927857008 shares for $97.03548575417443
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 103th day, sold 0.23470872647045016 shares for $53.2366333380275
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 101th day, Bought 0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 106.27418841119365, Final Money: 106.27418841119365, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 39th day, sold 0.24321432045918862 shares for $50.768557252651036
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4779824751654502 shares for $96.32302839534154
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.4279497485115096 shares for $100.23439009636577
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4446063536548852 shares for $99.55180864686534
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.429830156314737 shares for $99.9312130416132
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2229654403567447 shares for $49.92419175027871
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21590810950859313 shares for $50.196476379652815
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 76th day, sold 0.23819732266209329 shares for $48.81377733314278
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 110th day, sold 0.23978515250335697 shares for $54.31133704201035
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.21711754744018413 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44412199672739017 shares for $99.44335628722993
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
XLK Final Value: 101.78774562827121, Final Money: 101.78774562827121, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6377551020408163 shares for $49.30484693877551
On the 120th day, Bought 0.6459948320413437 shares for $50.00000000000001
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6459948320413437 shares for $50.2906976744186
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6051803437424352 shares for $48.32365044783345
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, sold 0.606354596167839 shares for $49.39970894979385
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6377551020408163 shares for $49.30484693877551
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.606354596167839 shares for $48.16880911957313
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.606134076857801 shares for $48.81803855012729
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 62th day, sold 1.3424622931916024 shares for $98.14741825523805
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 98th day, sold 0.6377551020408163 shares for $49.77678571428571
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 200th day, Bought 0.6240639041437843 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6240639041437843 shares for $50.26210683974039
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 70th day, sold 0.6715014773032502 shares for $50.758796669352684
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 98th day, sold 0.6377551020408163 shares for $49.77678571428571
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 135th day, sold 1.2949284414746003 shares for $100.81017916879763
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.69481623255669, Final Money: 101.69481623255669, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 137th day, sold 1.2778882724426772 shares for $101.2854244738066
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.2400059548577866 shares for $102.98249455093918
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2118719274009413 shares for $98.39188178568241
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3424622931916024 shares for $100.05371471157012
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2110226334153902 shares for $96.03409482984044
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2348803404304947 shares for $100.25993483955186
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 53th day, sold 0.6693440428380187 shares for $49.88621151271754
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.227685713783603 shares for $98.0307042456207
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 128th day, sold 0.6509569066527796 shares for $50.8657726858482
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 138th day, sold 0.6509569066527796 shares for $50.579351646920976
XLP Final Value: 100.8657726858482, Final Money: 100.8657726858482, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 53th day, sold 0.6637461834594451 shares for $49.46900305323245
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.6399590426212722 shares for $49.4944323563292
On the 99th day, Bought 0.6438320885912954 shares for $49.99999999999999
On the 100th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6438320885912954 shares for $50.6953386556786
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6227425582264291 shares for $51.46967243741437
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 185th day, sold 0.6033546518643659 shares for $48.98636418486787
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2154443376425925 shares for $97.053230360761
On the 219th day, Bought 0.6038647342995169 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6038647342995169 shares for $48.10386473429951
On the 35th day, Bought 0.6599788806758183 shares for $50.0
On the 53th day, sold 0.6599788806758183 shares for $49.18822597676874
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6399590426212722 shares for $50.39037501599897
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6227425582264291 shares for $51.46967243741437
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 205th day, sold 1.2261373024822997 shares for $97.90706360321163
On the 219th day, Bought 0.6038647342995169 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6038647342995169 shares for $48.10386473429951
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 99th day, Bought 0.6438320885912954 shares for $49.99999999999999
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.2837911312125676 shares for $100.58503513050466
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.2348803404304947 shares for $102.55681227275258
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 205th day, sold 1.2261373024822997 shares for $97.90706360321163
On the 219th day, Bought 0.6038647342995169 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 234th day, sold 1.2054046765516824 shares for $96.02253653410702
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.2817251830397036 shares for $100.42316809116078
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.227685713783603 shares for $101.95929852972823
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 234th day, sold 0.6015399422521656 shares for $47.918671799807505
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 126th day, sold 1.2817251830397036 shares for $100.42316809116078
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 171th day, sold 1.227685713783603 shares for $101.95929852972823
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.38246662088903, Final Money: 102.38246662088903, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 73th day, sold 0.6600660066006601 shares for $49.51815181518152
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 204th day, sold 0.6093102607847916 shares for $48.47672434803802
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 204th day, sold 0.6093102607847916 shares for $48.47672434803802
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 239th day, sold 1.2116114701196075 shares for $96.08078958048486
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 53th day, sold 0.6693440428380187 shares for $49.88621151271754
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2285852659910117 shares for $98.10253348938228
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2178503596718557 shares for $97.24535121979767
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 1.2222774287555604 shares for $97.5988526861315
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 138th day, sold 0.649772579597141 shares for $50.487329434697855
XLP Final Value: 100.48732943469786, Final Money: 100.48732943469786, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6867669549229583 shares for $97.48656925131391
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3485535029627048 shares for $50.08713837574068
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.3409943394939644 shares for $48.864488849485106
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6867669549229583 shares for $97.48656925131391
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34055305816646236 shares for $46.996322026971804
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 223th day, Bought 0.34073872154831675 shares for $50.0
XLV Final Value: 96.87925247455726, Final Money: 49.53019972820316, Final Shares: 0.34073872154831675

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3550379890648299 shares for $50.25917773201732
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.32379225488926305 shares for $49.46574277943272
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6850020195559079 shares for $100.93504758156303
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.6470402507516887 shares for $98.84833910733549
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 127th day, sold 0.3409943394939644 shares for $50.422832980972515
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6470402507516887 shares for $100.12300840131631
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 55th day, sold 0.34525618008562353 shares for $49.447590111863
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6764360460671432 shares for $99.32110464403866
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 55th day, sold 0.34525618008562353 shares for $49.447590111863
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 98.78231224075219, Final Money: 98.78231224075219, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 34th day, Bought 0.3424188467333242 shares for $50.0
On the 36th day, sold 0.3424188467333242 shares for $50.14039172716066
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 45th day, Bought 0.3433122768470201 shares for $50.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6862948533321347 shares for $98.29114889422833
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3402054841124039 shares for $50.12927808396272
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.32379225488926305 shares for $49.50783577256832
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.32379225488926305 shares for $49.50783577256832
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32026646169613116 shares for $48.565206251601325
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 157th day, Bought 0.31806615776081426 shares for $50.0
On the 181th day, sold 0.31806615776081426 shares for $48.23155216284987
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 98.45668673308728, Final Money: 98.45668673308728, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6839719051540245 shares for $100.78326022444551
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.33978933061501865 shares for $47.14576962283384
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6877579612666824 shares for $99.05777916124028
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6849785388796403 shares for $101.28777654413241
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6877579612666824 shares for $99.05777916124028
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 109th day, Bought 0.33992793527772114 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.68267539894649 shares for $100.94721124221748
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 127th day, sold 0.3409943394939644 shares for $50.422832980972515
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3375641371860653 shares for $49.56454226302998
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 189th day, sold 0.321646831778707 shares for $49.302026375040214
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 209th day, sold 0.6788695024739367 shares for $99.67840904824814
XLV Final Value: 100.15616518810998, Final Money: 100.15616518810998, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 107th day, sold 0.2807411566535654 shares for $50.83660864682763
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.24895439155546703 shares for $49.84813782115116
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.49849274560048373 shares for $99.81320245158486
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2794076557697681 shares for $52.46437552388936
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.500089566712886 shares for $99.99290886424154
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 116th day, sold 0.2794076557697681 shares for $52.46437552388936
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.500089566712886 shares for $106.07399799547025

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 108.53837351935962, Final Money: 108.53837351935962, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.2756795500909742 shares for $49.99999999999999
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.5468145210795323 shares for $97.79230894986357
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2798298634430266 shares for $51.614618312066256
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 126th day, sold 0.26452227277536766 shares for $50.12697069093217
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.5384461385482882 shares for $105.8477419158225
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5022116493566033 shares for $100.84912130729951
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 126th day, sold 0.26452227277536766 shares for $50.12697069093217
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.538431859266044 shares for $108.1225016592143
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4483236079159607 shares for $102.36572939545131
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2794076557697681 shares for $52.46437552388936
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 126th day, sold 0.26452227277536766 shares for $50.12697069093217
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5265973015977643 shares for $105.74600413384705
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5130302364012908 shares for $103.02160177174319
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5130302364012908 shares for $103.02160177174319

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 111.99498521355444, Final Money: 111.99498521355444, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 47th day, sold 0.2702410550210788 shares for $49.21630094043888
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 78th day, sold 0.2897878752752985 shares for $51.53877361771183
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5610292104393202 shares for $98.72431016100717
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.282326369282891 shares for $52.07509881422924
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.538431859266044 shares for $106.2972176563024
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 192th day, Bought 0.25257627803596683 shares for $49.99999999999999
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5041739230820093 shares for $100.88016026947923
On the 203th day, Bought 0.2463903809195289 shares for $50.0
On the 204th day, sold 0.2463903809195289 shares for $51.59907357216774
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 47th day, sold 0.2739425816348893 shares for $49.89042296734605
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 78th day, sold 0.2897878752752985 shares for $51.53877361771183
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5610292104393202 shares for $98.72431016100717
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5626111386085259 shares for $103.7736245163426
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 126th day, sold 0.5251702862998553 shares for $99.51976925382257
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.2176373291546966 shares for $50.0
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5617212209748524 shares for $103.60947920881152
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 126th day, sold 0.26116479498563594 shares for $49.49072864977801
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 112th day, sold 0.2814364516492176 shares for $51.910953506698185
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 126th day, sold 0.26116479498563594 shares for $49.49072864977801
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 112th day, sold 0.2814364516492176 shares for $51.910953506698185
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
XLY Final Value: 112.20404355999327, Final Money: 112.20404355999327, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2807411566535654 shares for $52.71476698483998
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5404948991210178 shares for $108.53678069249158
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2807411566535654 shares for $52.71476698483998
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4483236079159607 shares for $102.36572939545131
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 41th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.2702410550210788 shares for $48.65149713544482
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 116th day, sold 0.5595040089152501 shares for $105.05806775401652
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5130302364012908 shares for $103.02160177174319
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
XLY Final Value: 113.7598815847712, Final Money: 113.7598815847712, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 60th day, sold 0.7907638779060573 shares for $50.76704096156888
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.4012495930161712 shares for $100.69379575414206
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.443481651072981 shares for $101.14475929068378
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3327280241967356 shares for $106.72486017767459
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 60th day, sold 0.7907638779060573 shares for $50.76704096156888
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.3890620513572678 shares for $99.24848356947679
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.446268122066912 shares for $101.3978580381112
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.6648052120728627 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3288158362428495 shares for $106.7437761253881
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 62th day, sold 0.7838219156607619 shares for $49.20050164602603
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.6893699158968702 shares for $48.2145319178271
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7197351374694113 shares for $50.47502519072981
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 172th day, sold 0.6640106241699868 shares for $53.33997343957504
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.6893699158968702 shares for $48.2145319178271
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 137th day, sold 0.7197351374694113 shares for $53.418741902979704
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6923289947382997 shares for $51.3846579894766
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 62th day, sold 0.7793017456359103 shares for $48.91677057356609
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6923289947382997 shares for $50.027693159789536

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 106.92854905389045, Final Money: 11.98369114434172, Final Shares: 1.2317703413278247
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 63th day, sold 0.7843137254901961 shares for $50.258823529411764
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 1.4568087492862052 shares for $104.10355322399221
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.446268122066912 shares for $101.3978580381112
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.346354675156112 shares for $107.81608238650145
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4568087492862052 shares for $105.93913224809283
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.446268122066912 shares for $101.3978580381112
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.346354675156112 shares for $107.81608238650145
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 218th day, Bought 0.6031363088057901 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4124102758916717 shares for $102.71047526284237
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 122th day, Bought 0.7016559079427448 shares for $50.0
On the 126th day, sold 1.4084695918556656 shares for $98.66329490948937
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 64th day, sold 0.7843137254901961 shares for $50.54117647058823
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4024265352120677 shares for $100.82044361639555
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 127th day, sold 0.7068136839129207 shares for $49.56884365281312
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 1.4024265352120677 shares for $100.82044361639555
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 67th day, sold 0.7843137254901961 shares for $52.03137254901961
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 96th day, sold 1.4024265352120677 shares for $100.77837082033919
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 110.96241442464927, Final Money: 110.96241442464927, Final Shares: 0.0
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 69th day, Bought 0.7471607890017932 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7471607890017932 shares for $53.392109982068135
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.428063510802319 shares for $102.09226038725778
On the 137th day, Bought 0.6736728644570197 shares for $50.0
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.351730906225395 shares for $108.24661097052963
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 182th day, Bought 0.6294058408862034 shares for $50.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, sold 1.2443363537382512 shares for $101.97336418884969
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2377242479976887 shares for $94.43836012222364
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.439698010984607 shares for $102.92401080528954
On the 137th day, Bought 0.6736728644570197 shares for $50.0
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.351730906225395 shares for $108.24661097052963
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 182th day, Bought 0.6294058408862034 shares for $50.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, sold 1.2443363537382512 shares for $101.97336418884969
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2357984167210918 shares for $94.2914191958193
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.352185047296217 shares for $108.6210248493051
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 201th day, sold 1.2494482793495096 shares for $97.61939406557718
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.352185047296217 shares for $108.6210248493051
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 66th day, sold 0.7827175954915466 shares for $51.682842830306825
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3487087648370697 shares for $108.34177507936181

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 112.33247605084603, Final Money: 112.33247605084603, Final Shares: 0.0
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 51th day, sold 0.7862871520679352 shares for $51.30523667243277
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7115411982353779 shares for $51.74327593567668
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4688613054034505 shares for $102.92311166961977
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 139th day, sold 0.7094211123723042 shares for $51.69551645856981
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2317703413278247 shares for $93.68845216139435
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 52th day, sold 0.7862871520679352 shares for $51.391728259160246
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7115411982353779 shares for $51.15269674114131
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4616109028568363 shares for $102.41507596317851
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2244487038527554 shares for $93.13156841504058
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 64th day, sold 0.7862871520679352 shares for $50.66834407925774
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4124102758916717 shares for $101.53817473385227
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 124th day, sold 0.7068136839129207 shares for $49.526434831778346
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2579544386109456 shares for $95.68001460074852
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 95th day, sold 0.7862871520679352 shares for $56.52618336216386
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 96th day, sold 0.7843137254901961 shares for $56.36078431372549
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 96th day, sold 0.7843137254901961 shares for $56.36078431372549
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
XLU Final Value: 114.51345536901596, Final Money: 114.51345536901596, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 58th day, sold 0.09840969925995907 shares for $50.59439458353016
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1899262858477388 shares for $104.96466113661131
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.1750799086196722 shares for $103.47922919057106
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 58th day, sold 0.09840969925995907 shares for $50.59439458353016
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1899262858477388 shares for $104.96466113661131
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.174860422392223 shares for $103.34950405069947
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 58th day, sold 0.09840969925995907 shares for $50.59439458353016
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1899262858477388 shares for $104.96466113661131
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17463810735127167 shares for $104.01620311949092
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.16507664932143729 shares for $98.16943258496555
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 59th day, sold 0.09840969925995907 shares for $50.9762242166588
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18895217823179206 shares for $103.73285632747152
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17507663733900194 shares for $104.27739596548295
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.16507664932143729 shares for $98.16943258496555
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 61th day, sold 0.09749439407234084 shares for $49.18104708979234
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.74469142459795, Final Money: 107.74469142459795, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1896456503049435 shares for $104.80956509753008
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.174860422392223 shares for $104.14861618103194
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1884769619505038 shares for $103.47196734120709
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1884769619505038 shares for $103.47196734120709
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1884769619505038 shares for $103.47196734120709
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.1759511625304509 shares for $104.79827191476187
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18867154268899677 shares for $103.57879022083235
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.88816112583494, Final Money: 108.88816112583494, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 54th day, Bought 0.0974525893152981 shares for $50.0
On the 61th day, sold 0.0974525893152981 shares for $49.15995868010212
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 160th day, Bought 0.0909735994614363 shares for $50.0
On the 161th day, Bought 0.09253090532237768 shares for $50.0
On the 162th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.18350450478381397 shares for $105.72245034109874
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 160th day, Bought 0.0909735994614363 shares for $50.0
On the 161th day, Bought 0.09253090532237768 shares for $50.0
On the 162th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.18350450478381397 shares for $109.77055971662969
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.1664768163323842 shares for $100.10916873331593
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 161th day, Bought 0.09253090532237768 shares for $50.0
On the 162th day, Bought 0.09150637799454622 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.1840372833169239 shares for $110.08926250735072
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.1664768163323842 shares for $100.10916873331593
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1884769619505038 shares for $103.47196734120709
On the 161th day, Bought 0.09253090532237768 shares for $50.0
On the 206th day, sold 0.09253090532237768 shares for $55.351062254793106
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.1664768163323842 shares for $99.05537048593192
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18867154268899677 shares for $103.57879022083235
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18867154268899677 shares for $103.57879022083235

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 114.3621090322321, Final Money: 114.3621090322321, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1791071512121006 shares for $102.05704583216703
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17825237578963055 shares for $101.56998624868937
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17663179810615176 shares for $100.64656487886633
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17582727512007773 shares for $100.18813963617148
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 236th day, sold 0.08349615082744685 shares for $49.65432593557437
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 204th day, sold 0.08793218669761879 shares for $51.97143962576061
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
SPY Final Value: 106.19738633285878, Final Money: 106.19738633285878, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.0890283040146238 shares for $98.77486717412638
On the 122th day, Bought 0.5524861878453039 shares for $50.0
On the 126th day, sold 0.5524861878453039 shares for $50.23204419889503
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 228th day, sold 1.0766472958632796 shares for $97.57654442408902
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.5391998274560552 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0843966435066497 shares for $100.5018809201963
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0462549900304203 shares for $96.96691247601936
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5214308061320263 shares for $48.326207112316204
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 128th day, sold 0.5433010974682169 shares for $49.119852222101485
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5214308061320263 shares for $47.25727395974554
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 133th day, sold 0.5472255663784612 shares for $50.065667067965414
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 188th day, Bought 0.5189952252439277 shares for $50.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0374522969983864 shares for $88.78516757712191

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 101.23578721736055, Final Money: 101.23578721736055, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.0844228128268467 shares for $99.25722005804128
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 31th day, Bought 0.5684402000909504 shares for $49.99999999999999
On the 32th day, Bought 0.5643340857787811 shares for $50.0
On the 33th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 59th day, sold 1.1327742858697314 shares for $103.69415812851521
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.5538938739337543 shares for $50.0
On the 73th day, sold 1.1124282796531468 shares for $99.10623543429885
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0844228128268467 shares for $98.67163173911477
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.119772962379967 shares for $102.82875113535238
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0938814610365155 shares for $93.05649589037637
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 154th day, Bought 0.5367686527106816 shares for $50.0
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.072502071761362 shares for $97.89798911037713
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5555555555555556 shares for $47.26111111111111
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.529380624669137 shares for $48.32186341979883
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5555555555555556 shares for $47.26111111111111
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0554195515497262 shares for $89.78454125033521

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 101.46059624145155, Final Money: 101.46059624145155, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5614823133071308 shares for $50.02245929253229
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.089819163774012 shares for $99.18444209507284
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 154th day, Bought 0.5367686527106816 shares for $50.0
On the 163th day, sold 1.0882189670373608 shares for $98.81028220699235
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 229th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5497526113249038 shares for $45.74491478834524
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5472255663784612 shares for $49.80299879610376
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0547562682543004 shares for $96.27815216625254
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 229th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5497526113249038 shares for $45.74491478834524
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0547562682543004 shares for $96.27815216625254
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5685048322910744 shares for $47.3052870949403
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0547562682543004 shares for $98.69354402055488
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.1600108065014139 shares for $96.52449920898265
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 128th day, sold 0.5619240278714318 shares for $50.80355135985615
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0547562682543004 shares for $98.69354402055488
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 236th day, Bought 0.5877512636652169 shares for $50.0
On the 242th day, sold 1.1792572378755564 shares for $98.12599476362504
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 98.44413572044357, Final Money: 98.44413572044357, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 35th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.1274773325509615 shares for $100.44695555696516
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.089819163774012 shares for $99.16264571179735
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1197107302364473 shares for $100.37086985839514
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.1009008637772286 shares for $106.699311717289
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 202th day, sold 1.0554195515497262 shares for $98.72394485196139
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0881392947121558 shares for $91.98041458201853
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.089819163774012 shares for $99.16264571179735
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.5619240278714318 shares for $50.370869858395146
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 180th day, sold 0.5494505494505495 shares for $52.03846153846154
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.0554195515497262 shares for $100.6237000447509
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1014463109828538 shares for $93.10525666738063
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 121th day, sold 0.5578489345085351 shares for $50.00557848934509
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5514503143266791 shares for $51.108415131796626
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.1072492552135054 shares for $94.75839126117178
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0966471303772733 shares for $93.29177138119464
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0635879769303869 shares for $90.47942919746801
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0635879769303869 shares for $90.47942919746801
XLB Final Value: 99.65686955115382, Final Money: 99.65686955115382, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 33th day, Bought 0.5757052389176742 shares for $50.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.144792423074287 shares for $110.0488956301312
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 151th day, Bought 0.5614192679092747 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.125244256632775 shares for $102.08215896172534
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 190th day, Bought 0.5516328331862312 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108549741183558 shares for $100.04661414181612
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.1036056965369934 shares for $101.29996688513063
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 155th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.1101374814320324 shares for $100.71167231551398
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108588481558596 shares for $100.05011046066329
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0679201308875026 shares for $96.475904624377
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 130th day, sold 0.5343022013250694 shares for $48.26886086770678
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 108.52822222521833, Final Money: 7.004376131847067, Final Shares: 1.160670470942852
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5804504295333178 shares for $56.72161597399582
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.0409737632567437 shares for $95.80081543251812
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0682050310100668 shares for $96.95028861447366
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5636978579481398 shares for $50.924464487034946
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1164943818925064 shares for $98.02820673016205
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5567308762943993 shares for $50.590134728872066
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 234th day, sold 0.5730002292000916 shares for $47.74237909695163
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0568927500574965 shares for $97.2658397877914
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 130th day, sold 1.1012079395619154 shares for $99.48312526002344
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1248662813626384 shares for $98.76325950363965
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 130th day, sold 0.5549389567147615 shares for $50.13318534961155
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 98.05843833429353, Final Money: 47.00193588274087, Final Shares: 0.5837030119075415
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5612932195779076 shares for $54.849573417153124
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0533710046449274 shares for $97.50002018993447
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.0664965398150177 shares for $99.39747751075966
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.094935722669386 shares for $98.91649318595235
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.104728573913182 shares for $96.99516878957738
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5534646889528448 shares for $51.24529555014391
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5152514427040396 shares for $50.35037098103874
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0533710046449274 shares for $97.50002018993447
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5420641803989593 shares for $50.189722463139645
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 1.0339774516261269 shares for $95.70495292251431
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
XLE Final Value: 99.73505304844869, Final Money: 48.678550596896045, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 1.0682050310100668 shares for $96.95028861447366
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.1316215290067495 shares for $102.23068893046975
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 157th day, Bought 0.5477651183172656 shares for $50.00000000000001
On the 165th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1115901070407657 shares for $97.59761139817923
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.117517062787762 shares for $104.07436405742426
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0451065062759581 shares for $87.71578907174117
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 120th day, Bought 0.5595344673231871 shares for $50.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1144734240379486 shares for $102.74330496205847
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1248662813626384 shares for $98.76325950363965
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1248662813626384 shares for $98.76325950363965
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.117517062787762 shares for $94.58664419435617
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.5610412926391383 shares for $50.381508078994614
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
XLE Final Value: 100.79764023826226, Final Money: 49.7411377867096, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.4044597264558503 shares for $105.36342521329536
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, sold 2.276626291211212 shares for $101.03667480395359
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 202th day, sold 2.1313687189297474 shares for $98.63974431206871
On the 216th day, Bought 0.9856100926473488 shares for $50.0
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 237th day, sold 2.003940031547552 shares for $98.17302214551458
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 99th day, sold 2.3943644692250357 shares for $99.31823818345447
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 2.4044597264558503 shares for $104.08906155827376
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.276626291211212 shares for $105.36226475725489
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 55th day, sold 2.228803145736053 shares for $92.65134676824773
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.379568360738147 shares for $101.9645042576296
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.247196571777908 shares for $104.00025734188158
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 56th day, sold 2.228803145736053 shares for $93.05253133448022
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.370791844476055 shares for $101.58843053579896
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.2379022564825797 shares for $104.53241440030129
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 127th day, sold 1.1853959222380275 shares for $50.79421526789948
On the 85th day, Bought 1.1767474699929394 shares for $50.0
On the 127th day, sold 1.1767474699929394 shares for $50.423629089197455

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 111.00410589709915, Final Money: 111.00410589709915, Final Shares: 0.0
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4105140597728463 shares for $103.86905083561196
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 186th day, sold 2.2758364540624174 shares for $105.84915347844303
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 216th day, Bought 0.9856100926473488 shares for $50.0
On the 240th day, sold 1.9822216134765296 shares for $95.70165949864685
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.255802452049888 shares for $105.57155475593474
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 216th day, Bought 0.9856100926473488 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 157th day, Bought 1.0931351114997814 shares for $50.0
On the 187th day, sold 2.2328661349782406 shares for $104.49813511698166
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 92th day, sold 1.2174336498660823 shares for $49.69564158753348

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 106.6881709791214, Final Money: 58.797376577386714, Final Shares: 0.9856100926473488
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 192th day, Bought 1.0584250635055037 shares for $50.0
On the 193th day, Bought 1.0604453870625663 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.11887045056807 shares for $98.0613244522903
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.020407771722292 shares for $97.54528721875225
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.121791173519794 shares for $99.10886571510959
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 241th day, sold 2.020407771722292 shares for $97.64630760733836
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.121791173519794 shares for $99.10886571510959
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 241th day, sold 2.029452284704046 shares for $98.08342891974655
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 242th day, sold 2.029452284704046 shares for $97.83989464558206
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 90th day, sold 1.2330456226880395 shares for $51.30702836004932
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 90th day, sold 1.2330456226880395 shares for $51.30702836004932
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 107.14508403211956, Final Money: 107.14508403211956, Final Shares: 0.0
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.237623762376238 shares for $93.0180198019802
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.406471058877379 shares for $103.11728487289571
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 185th day, sold 2.2604395236624435 shares for $103.1438554647173
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.237623762376238 shares for $93.0180198019802
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 123th day, Bought 1.1627906976744187 shares for $50.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.3603954880935802 shares for $101.14294666480991
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2379022564825797 shares for $104.73382560338472
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.2330456226880395 shares for $93.22965474722565
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 126th day, Bought 1.155001155001155 shares for $50.0
On the 127th day, sold 1.155001155001155 shares for $49.49179949179949
On the 157th day, Bought 1.0931351114997814 shares for $50.0
On the 158th day, Bought 1.1013215859030838 shares for $50.00000000000001
On the 187th day, sold 2.194456697402865 shares for $102.70057343845407
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626
XLF Final Value: 113.241265626397, Final Money: 113.241265626397, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLI

In [13]:
runtest_num = 50000 
for file in os.listdir('../output'):
    if "runtest" in file:
        runtest_num+=1
#get stock
#loop over "metrics"
#loop over "thresholds"
#call bollinger bands method with metric as parameter
#for each point (vertical:m, horizontal:t) -> final portfolio value
os.mkdir(f'../output/runtest_bollinger_{runtest_num}')
root0 = f'../output/runtest_bollinger_{runtest_num}'
start, end = '2019-01-05', '2024-01-05'
metrics = ["sd","atr","mad","iqr"]
    
for etf in etfs:
    root1=os.path.join(root0,f"{etf}")
    os.mkdir(root1)
    df = get_cleaned_df(etf,start,end)
    results_df = pd.DataFrame({"metric":[],"1":[],"1.2":[],"1.4":[],"1.6":[],"1.8":[],"2":[]})
    for metric in metrics:
        final_values = [metric]
        for buy,sell in factors:
            results = bollinger_bands_backtest(df,metric,buy, sell,20)
            final_value = results["final_value"]
            #print(results)
            final_values.append(final_value) # should have n+1 values for metric and number of factors
        print(final_values)
        results_df.loc[len(results_df)] =  final_values # table has n+1 columns
    results_df.to_csv(os.path.join(root1,f"results{etf}.csv"))
df

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  SPY
['sd', 117.54266527842884, 121.73549786607094, 126.0433257221579, 128.98671826684713, 132.03685464678557, 156.42784282708286]
['atr', 124.39313854260224, 130.7082789680004, 116.51008372582844, 124.81051704637999, 137.1453191712022, 143.1503202171475]
['mad', 105.25565176110199, 110.14924352984228, 118.77489142288088, 123.5649344850283, 137.47500154170498, 135.58579792073346]

[*********************100%***********************]  1 of 1 completed

['iqr', 117.216956510824, 123.21999664755505, 145.8736787619094, 159.77367888452687, 173.1839994850421, 158.8808672772966]
read  1258  lines of data for ticker:  XLB

['sd', 113.13044428755849, 106.7475197186633, 116.22992026733883, 123.84978940086422, 130.87516625262447, 118.81494149483427]
['atr', 121.4306432667745, 123.76831104047493, 134.78351103931277, 156.1653906402539, 134.26469461664576, 164.3089072616125]
['mad', 104.35863392583276, 111.00046228139138, 118.57634096414148, 121.1138882688073, 116.28333403053226, 125.56352241035093]

[*********************100%***********************]  1 of 1 completed

['iqr', 118.91282427672506, 118.67544737581247, 122.53710978444573, 150.47377015646103, 128.04449159316678, 131.72638837742244]
read  1258  lines of data for ticker:  XLE

['sd', 70.86398913336946, 56.94961390163529, 64.55765270959735, 87.24700414952322, 100.37754116711412, 129.230630024319]
['atr', 83.57197673019492, 84.72514911460276, 97.87041717583277, 113.8129222315574, 127.36770119335077, 143.06292796743884]
['mad', 67.8015175715597, 68.79617900195751, 64.02926839550106, 64.28620759215893, 72.37696284591986, 92.10558645053476]

[*********************100%***********************]  1 of 1 completed

['iqr', 66.81378740335819, 82.11776076958337, 85.65852351811284, 81.41670838851485, 111.21321163351351, 92.7874267030735]
read  1258  lines of data for ticker:  XLF

['sd', 117.75040058290686, 127.78659931843099, 137.12707070148565, 153.20903447539376, 147.5117222921389, 144.52726273232616]
['atr', 130.56132539887085, 163.63215428137832, 192.70855202965632, 160.09876255474097, 163.64222555506834, 173.1788088088145]
['mad', 109.80584789906912, 120.59753457804192, 127.78659931843099, 142.51092146553685, 154.57834716529922, 133.80031376099302]

[*********************100%***********************]  1 of 1 completed

['iqr', 119.88572038895742, 137.52561331046573, 122.60216300614655, 113.1335896165832, 134.66398611792212, 145.28415553237923]
read  1258  lines of data for ticker:  XLI

['sd', 130.28166344834725, 127.0654236528713, 142.7562950118944, 155.26547888558486, 168.2389016362072, 143.54290267173684]
['atr', 147.106282101117, 142.570669250956, 146.02903796618475, 121.05936570702126, 116.26669577839483, 133.8829975587207]
['mad', 118.84915641207753, 127.58911523969077, 125.86123060019618, 148.26542417640007, 150.23737555527492, 168.97163649612904]

[*********************100%***********************]  1 of 1 completed

['iqr', 141.46942952423282, 158.93765631602793, 170.14091557240104, 152.42648652508225, 142.48553008491342, 135.63251246795218]
read  1258  lines of data for ticker:  XLK

['sd', 109.70778744116767, 123.59766400229964, 144.71406338248465, 137.20950343747268, 158.6777193609677, 182.5160388721641]
['atr', 105.84445046000006, 125.01928908019539, 156.95279551035014, 143.90874422758853, 149.7463200207873, 177.59215282150686]
['mad', 131.200193234034, 122.19333247578302, 127.07782101764832, 155.71665715616354, 144.47875575521024, 143.0294483062618]

[*********************100%***********************]  1 of 1 completed

['iqr', 114.42581909383402, 145.69281248239471, 163.9368073502069, 172.6460685831003, 213.44591453018478, 263.56376078031303]
read  1258  lines of data for ticker:  XLP

['sd', 102.27487002591518, 107.02686420925637, 110.23661087246835, 126.27203344640114, 136.18895310325263, 152.3995260527323]
['atr', 109.7561466164744, 118.6579011893739, 137.05310788085305, 157.08229547541595, 152.4257672392782, 157.2516022920831]
['mad', 98.01029299311905, 99.61622766017994, 106.02148414576227, 108.04525874320403, 121.62867302982603, 124.52177093961865]

[*********************100%***********************]  1 of 1 completed

['iqr', 111.37287824206808, 121.1468580227164, 131.42002872742728, 152.32322410198555, 131.92122350922068, 139.11502089915345]
read  1258  lines of data for ticker:  XLV

['sd', 111.02776456158611, 105.35475606322167, 113.69936133695094, 130.80633200813662, 151.37441756886267, 174.31707276142635]
['atr', 126.11969773888434, 129.06564961885087, 133.5886025271655, 146.15427679761459, 153.67733442550346, 163.16174933568092]
['mad', 118.42275404180339, 110.57365291305727, 108.49632521643096, 111.45593806054706, 120.9302574038689, 134.26898060381833]

[*********************100%***********************]  1 of 1 completed

['iqr', 121.08148934596798, 138.79328112754655, 141.95920946774743, 137.02445456369657, 178.3496036140118, 180.16643003053593]
read  1258  lines of data for ticker:  XLY

['sd', 115.4651299720286, 118.12079528938443, 112.39941838062641, 127.08824588650849, 123.49347659452472, 126.15284112877707]
['atr', 124.48769007682046, 129.5542565088221, 107.8639418663019, 120.65154285726597, 147.65481287045026, 137.93970297521034]
['mad', 109.44436766408361, 119.23524500675518, 137.10893945347638, 112.4461711811554, 125.30732457315949, 127.89653422719962]

[*********************100%***********************]  1 of 1 completed

['iqr', 104.59773318876759, 118.24162478961068, 130.3473594543508, 148.2609790568055, 149.9408157152472, 146.88568122531396]
read  1258  lines of data for ticker:  XLU

['sd', 111.74245874205232, 108.01412367100359, 127.4995792020496, 129.35431543221182, 161.3739222337461, 133.47869566227655]
['atr', 119.00490074188673, 125.30366392118191, 131.64349544204217, 137.23406285394884, 142.99367075435768, 137.56609748744785]
['mad', 106.92083967742913, 111.82145113564818, 115.69657165993412, 120.81288584337742, 125.92327605881799, 137.9769822305908]
['iqr', 114.82986880417528, 131.24967679238696, 139.87803232703135, 143.57951708257627, 150.7541147594477, 130.40389402915972]

Price,index,Date,Open,High,Low,Close,Volume,Adj Close,TR,ATR,Returns,SD_Returns,MAD_Returns,SR,SD_Squared_Returns,IQR
0,0,2019-01-16,52.57,52.88,52.27,52.86,18348200,43.10,0.011582,0.927143,0.003607,0.013141,0.010345,0.000013,0.000177,0.017238
1,1,2019-01-17,52.82,53.20,52.74,53.08,20785900,43.28,0.008702,0.857143,0.004162,0.012324,0.009336,0.000017,0.000184,0.013118
2,2,2019-01-18,53.15,53.32,52.90,53.14,14154700,43.32,0.007913,0.822857,0.001130,0.012022,0.008167,0.000001,0.000187,0.009538
3,3,2019-01-22,53.13,53.53,52.72,53.24,16914400,43.41,0.015243,0.824286,0.001882,0.010857,0.007249,0.000004,0.000191,0.005191
4,4,2019-01-23,53.25,53.81,53.16,53.78,14211100,43.85,0.012209,0.835714,0.010143,0.011411,0.006990,0.000102,0.000187,0.005646
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1246,0,2023-12-28,62.76,63.50,62.76,63.41,8673200,60.60,0.011753,0.787143,0.007147,0.009533,0.006232,0.000051,0.000151,0.005316
1247,1,2023-12-29,63.27,63.46,62.91,63.33,11239000,60.53,0.008674,0.795714,-0.001262,0.009254,0.005868,0.000002,0.000153,0.005665
1248,2,2024-01-02,63.06,64.40,62.93,64.25,15379300,61.41,0.023212,0.805714,0.014527,0.005451,0.004133,0.000208,0.000075,0.006043
1249,3,2024-01-03,64.23,64.61,63.79,64.49,16433200,61.64,0.012763,0.798571,0.003735,0.005341,0.003892,0.000014,0.000074,0.005243
1250,4,2024-01-04,64.56,64.90,64.21,64.29,13311200,61.45,0.010699,0.778571,-0.003101,0.006115,0.004684,0.000010,0.000074,0.007556

In [14]:
results["signals"].iloc[30:40]

     price        ma  metric_value  lower_band  upper_band
30  253.64  249.1820        2.2335    246.9485    251.4155
31  252.72  249.6045        2.3840    247.2205    251.9885
32  252.37  249.9235        2.3180    247.6055    252.2415
33  250.84  250.1145        2.3495    247.7650    252.4640
34  248.74  250.2170        2.4415    247.7755    252.6585
35  248.25  250.4125        2.3485    248.0640    252.7610
36  251.85  250.7730        2.4190    248.3540    253.1920
37  252.80  251.1745        2.4275    248.7470    253.6020
38  254.47  251.5020        2.3770    249.1250    253.8790
39  254.31  251.7810        2.3440    249.4370    254.1250