In [1]:
import torch
from torch.nn import *
import torch.nn.functional as F
from pandas_datareader import data as web
import os
import pandas as pd
import yfinance as yf
import matplotlib.pyplot as plt
import seaborn as sns
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
import numpy as np
import warnings
warnings.filterwarnings("ignore")
from diebold_mariano import diebold_mariano_test

In [2]:
from utils import *

DEVICE:  cuda

In [3]:
T=30

In [7]:
import os
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import matplotlib

# Set consistent style for publication-quality plots
sns.set(style="whitegrid", context="talk", palette="colorblind")
matplotlib.rcParams.update({
    "axes.titlesize": 18,
    "axes.labelsize": 12,
    "xtick.labelsize": 10,
    "ytick.labelsize": 10,
    "legend.fontsize": 10,
    "legend.frameon": True,
    "axes.titleweight": "bold"
})

def customize_ax(ax, title=None, xlabel=None, ylabel=None):
    if title:
        ax.set_title(title, fontsize=20, fontweight="bold")
    if xlabel:
        ax.set_xlabel(xlabel, fontsize=12)
    if ylabel:
        ax.set_ylabel(ylabel, fontsize=12)
    ax.tick_params(axis='both', which='major', labelsize=10)
    ax.grid(False)
    if ax.get_legend():
        ax.legend(fontsize=10, frameon=True)

# Insert your original loop code here afterward, using customize_ax() and matplotlib.rcParams updates
# on all relevant plots to ensure publication-quality formatting.

In [8]:
etfs = ['SPY','XLB','XLE','XLF','XLI','XLK','XLP','XLV','XLY','XLU']
metric2 = "SD_Returns"
metric3 = "SD_Prices"
metric4 = "IQR"
metrics = ["ATR",metric2,metric3,metric4]
# start = '2001-01-01'
# end = '2020-01-01'
# start_t = '2022-01-02'
# end_t = '2024-01-05'
date_list = [['2023-01-05', '2024-01-05', "2024-01-05", "2025-01-05"], ['2019-01-05', '2024-01-05', "2024-01-05", "2025-01-05"], ['2014-01-05', "2024-01-05", "2024-01-05", "2025-01-05"], ['2004-01-05', '2024-01-05', "2024-01-05", "2025-01-05"], ['1994-01-05', '2024-01-05', "2024-01-05", "2025-01-05"]]
starts,ends = np.array([(f'200{i}-01-01',f'200{i+12}-01-01') for i in range(0,12,4)]).T
models = {}
lrs = [0]
h1 = 50
h2 = 50
hl1s = [20,50,70,100]
hl1s = [20,50,70,100]
models = ["LSTM","RNN"]
b_types = ['ATR' ,'STD']
lr = 0
a_s = np.linspace(1,2,5)
b_s = np.linspace(1,2,5)
A,B = np.meshgrid(a_s,b_s)
pairs = np.column_stack([A.ravel(), B.ravel()])
feat_combos = [['Open','Close','High','Low','Volume','Return','Short_MA','Long_MA'],['Open','Close','High','Low','Volume'],['index','Open','Close','High','Low','Volume']]
sells = np.linspace(1,2.5,7)
buys = np.linspace(1,2.5,7)
factors = np.stack((sells,buys),axis=-1)
ini_money=100

In [ ]:
num=30000
for file in os.listdir('../output'):
    if "runtest" in file:
        num+=1
os.mkdir(f'../output/runtest_{num}')
for d,(start,end,start_t,end_t) in enumerate(date_list):
    os.mkdir(f'../output/runtest_{num}/date_config{d}')
    for model_type in models:
        os.mkdir(f'../output/runtest_{num}/date_config{d}/{model_type}')
        root = f'../output/runtest_{num}/date_config{d}/{model_type}'
        with open(os.path.join(root,'run_data.txt'),'w') as f:
            f.write(f'Start Training Date: {start} \n End Training Date: {end} \n Start Sim Date: {start_t} \n End Sim Date: {end_t} \n')
            f.write(f'\n Model Type: {model_type}')
            f.write(f'Look-back window: {T} days')

        for etf in etfs:
            os.mkdir(f'{root}/{etf}')
        for lr in lrs:
            results = pd.DataFrame({"ETF":[],"Metric":[],"Final_Value":[],"Passive_Potential":[],"Relative_MSE":[],"MAPE":[],"DM_stat":[],"DM_p":[]})
            money_df_std = pd.DataFrame()
            money_df_atr = pd.DataFrame()
            money_df_sd_prices = pd.DataFrame()
            money_df_iqr = pd.DataFrame()
            money_df_passive = pd.DataFrame()
            for j,etf in enumerate(etfs):
                #fig,ax = plt.subplots(1,len(metrics),figsize=(26,6))
                fig,ax = plt.subplots(2,2,figsize=(12,9))
                atr_preds = []
                for i,metric in enumerate(metrics):
                    scaler = StandardScaler()
                    scaler_x = StandardScaler()
                    df = get_cleaned_df(etf,start,end)
                    #print(df)
                    model,fig_tr,fig_te = get_trained_model(df,scaler, scaler_x, metric=metric,model_type=model_type)
                    fig_tr.savefig(os.path.join(root,etf,f'training_results_{metric}'))
                    fig_te.savefig(os.path.join(root,etf,f'testing_results_{metric}'))
                    df_test = get_cleaned_df(etf,start_t,end_t)
                    ini_cash = 10000
                    result_best = backtest_strategy_mr(df_test,model,scaler,scaler_x,metric,sell_scale=factors[0][0],buy_scale=factors[0][1],ini_cash=ini_money,buy_max=50)
                    max_val = result_best[0]
                    a_best,b_best = factors[0]
                    for a,b in factors[1:]:
                        res = backtest_strategy_mr(df_test,model,scaler,scaler_x,metric,sell_scale=a,buy_scale=b,ini_cash=ini_money,buy_max=50)
                        if res[0]>max_val:
                            max_val = res[0]
                            result_best = res
                            a_best,b_best = a,b
                    final_value, money, shares,passive_value,buy_points,sell_points,preds, t_money,p_money,lowers,uppers,vols = result_best
                    fig_vol,ax_vol = plt.subplots(figsize=(10,5))
                    sns.lineplot(x = range(0,len(df_test.index)-(T+1)),y=lowers,color = 'blue',ax=ax_vol,label = "Buy")
                    sns.lineplot(x = range(0,len(df_test.index)-(T+1)),y=uppers,color = 'red',ax=ax_vol,label="Sell")
                    sns.lineplot(x = range(0,len(df_test.index)-(T+1)),y=vols,color = 'black',ax=ax_vol,label=f"{metric}")
                    ax_vol.set_title(f"Predicted {metric} and Buy/Sell Signals | a={a_best}, b={b_best}")
                    ax_vol.set_ylabel(f"{metric}")
                    ax_vol.set_xlabel(f"Days after {start_t}")
                    for buy in buy_points:
                        ax_vol.axvline(buy,color = 'Orange',alpha=.5,)
                    for sell in sell_points:
                        ax_vol.axvline(sell,color='Purple',alpha=.5,)
                    #ax_vol.legend()
                    customize_ax(ax_vol)
                    
                    fig_vol.tight_layout()
                    fig_vol.savefig(os.path.join(root,etf,f'{metric}_signals.png'))
                    

                    print(f"{etf} Final Value: {final_value}, Final Money: {money}, Final Shares: {shares}")
                    
                    real_met = np.array(df_test[metric].iloc[T:len(df_test)-1])
                    atr_met = np.array(df_test["ATR"].iloc[T:len(df_test)-1])
                    null_model_error = np.sum((real_met-real_met.mean())**2)
                    mse_error = 1/len(real_met) * np.sum((real_met-preds)**2)/null_model_error
                    mape_error = 1/len(real_met) * np.sum(abs(real_met-preds)/(real_met+1e-8))
                    if metric=="ATR": #atr should go first
                        money_df_atr[etf] = t_money
                        atr_preds = preds
                    elif metric==metric2:
                        money_df_std[etf] = t_money
                        money_df_passive[f"{etf}_Passive"] = p_money
                    elif metric == metric3:
                        money_df_sd_prices[etf] = t_money
                    elif metric == metric4:
                        money_df_iqr[etf] = t_money

                    dm,p = diebold_mariano_test(atr_met,atr_preds,real_met,preds,loss="mae")
                    results.loc[len(results)] = [etf,metric,final_value,passive_value,mse_error,mape_error,dm,p]

                    sns.lineplot(preds,ax=ax[i//2][i%2],label=f"Prediction {metric}",color="Blue",linestyle = '--')
                    sns.lineplot(real_met,ax=ax[i//2][i%2],label = f"True {metric}",color="Orange")
                    sns.despine(ax=ax[i//2][i%2])
                    #for buy in buy_points:
                        #ax[i].axvline(buy,color="Green",alpha=.6)
                    #for sell in sell_points:
                        #ax[i].axvline(sell,color="Red",alpha=.6)
                    ax[i//2][i%2].set_title(f"{etf} - {metric} ",fontsize = 20)
                    ax[i//2][i%2].set_xlabel(f'Total MSE Error {mse_error:.6f} | Total MAPE Error: {mape_error:.3f}')
                    customize_ax(ax[i//2][i%2])
                    #plt.title(f"Performance of LSTM on {etf}")
                fig.supylabel("Volatility Metric")
                fig.supxlabel(f"Days after {start_t}")
                fig.tight_layout()
                fig.savefig(os.path.join(root,etf,'predictions.png'))
                fig_sim,ax_sim = plt.subplots(figsize=(10,6))
                sns.lineplot(x=range(0, len(df_test.index)-(T+1)), y=money_df_atr[etf], label="ATR",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_std[etf],label="SD_Returns",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_sd_prices[etf],label="MAD_Returns",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_passive[f"{etf}_Passive"],label="Passive",ax=ax_sim,palette = 'colorblind')
                sns.lineplot(x=range(0,len(df_test.index)-(T+1)),y=money_df_iqr[etf],label="IQR",ax=ax_sim,palette = 'colorblind')
                sns.despine(ax=ax_sim)
                ax_sim.axhline(ini_money, label = "Initial",color="Black")
                ax_sim.set_xlabel(f"Days after {start_t}")
                ax_sim.set_ylabel(f"Value ($)")
                ax_sim.set_title(f"ETF Performance Over Time for {etf}")
                customize_ax(ax_sim)
                ax_sim.legend(
                    loc='upper left',              # anchor the legend’s corner
                    bbox_to_anchor=(1.02, 1.0),     # (x, y) in axes fraction coordinates
                    borderaxespad=0
                )
                fig_sim.tight_layout()
                fig_sim.savefig(os.path.join(root,etf,'simulation_perf_lr_{lr}'))
                
            fig2,ax2 = plt.subplots(figsize = (8,6))
            sns.barplot(data=results,x="ETF",y="Final_Value",hue="Metric",ax=ax2,palette='colorblind') 
            sns.despine(ax=ax2)   
            plt.legend(loc=(1.1,1))
            fig2.tight_layout()
            customize_ax(ax2)
            fig2.savefig(os.path.join(root,'return_metrics_lr_{lr}.png'))
            results.to_csv(os.path.join(root,'overall_results.csv'),index=False)

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 59th day, sold 0.09858432903505658 shares for $51.06668244015931
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1899262858477388 shares for $104.26763166755012
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17825237578963055 shares for $105.35428418670323
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09554748710108925 shares for $52.99541372061915
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.174860422392223 shares for $103.34950405069947
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.1896456503049435 shares for $105.18695994163691
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17507663733900194 shares for $104.27739596548295
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.08226254915187313 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.16468103726712713 shares for $97.93416605238784
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 128th day, sold 0.09437879874664956 shares for $52.34720072482918
On the 225th day, Bought 0.08226254915187313 shares for $50.0
On the 226th day, Bought 0.08268836409340478 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1649509132452779 shares for $98.09465859783433
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 129th day, sold 0.09457337948514251 shares for $52.37284609128221
On the 226th day, Bought 0.08268836409340478 shares for $50.0
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 237th day, sold 0.1656346149228673 shares for $99.5960939531201

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.63484035526456, Final Money: 108.63484035526456, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1785952662739861 shares for $102.99589006020778
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1899262858477388 shares for $104.96466113661131
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1791071512121006 shares for $103.29109410401843
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1896456503049435 shares for $104.80956509753008
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17825237578963055 shares for $105.35428418670323
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1896456503049435 shares for $104.11356556091094
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17531915484379426 shares for $103.62063327887616
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 127th day, sold 0.1884769619505038 shares for $103.47196734120709
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 204th day, sold 0.08620541025154739 shares for $50.95084567507457
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 127th day, sold 0.09457337948514251 shares for $51.91983960354839

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 110.16384928423331, Final Money: 110.16384928423331, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09506426344208685 shares for $52.83861890638072
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1791071512121006 shares for $103.29109410401843
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.08230994633391499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1652561971633775 shares for $98.27620789108897
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 62th day, sold 0.09749439407234084 shares for $49.09135224724578
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 120th day, sold 0.09443940767603505 shares for $53.010728316712
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17825237578963055 shares for $102.79814511787994
On the 228th day, Bought 0.08230994633391499 shares for $50.0
On the 229th day, Bought 0.08273625337150232 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 62th day, sold 0.09749439407234084 shares for $49.09135224724578
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.09443940767603505 shares for $52.55364158355999
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.09056658455296333 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17926939465798747 shares for $106.77464415224392
On the 230th day, Bought 0.08275268532463878 shares for $50.0
On the 231th day, Bought 0.08240083060037245 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 91th day, Bought 0.09437345463468037 shares for $50.0
On the 92th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.09437345463468037 shares for $50.811611709858255
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.08793218669761879 shares for $52.37328971896873
On the 233th day, Bought 0.08528348229514908 shares for $50.0
SPY Final Value: 106.18226173486009, Final Money: 8.419637983049682, Final Shares: 0.16515351592501124

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17825237578963055 shares for $106.6287886735991
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.1658128640371508 shares for $97.21276592770076
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.17463810735127167 shares for $104.56631315764741
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.1658128640371508 shares for $97.21276592770076
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09457337948514251 shares for $52.45512493143429
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0872630807358023 shares for $50.00000000000001
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.17531915484379426 shares for $102.6931949497525
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 85th day, Bought 0.09443762394938142 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09443762394938142 shares for $52.379828123524405
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 234th day, sold 0.17215002754016662 shares for $100.89713114129165
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09409816320385425 shares for $52.19154622101776
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
SPY Final Value: 105.9389423366132, Final Money: 105.9389423366132, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 112th day, sold 1.0875484034440523 shares for $96.07402596024758
On the 122th day, Bought 0.5524861878453039 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.5524861878453039 shares for $49.950276243093924
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5451968160505943 shares for $50.528840911569084
On the 217th day, Bought 0.5259835893120135 shares for $50.00000000000001
On the 227th day, sold 0.5259835893120135 shares for $47.83820744792763
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 131th day, sold 0.5442473059758354 shares for $48.90606291498857
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 210th day, sold 0.5214308061320263 shares for $47.92991969965586
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 136th day, sold 0.5433010974682169 shares for $49.85874171465826
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.5184570717544588 shares for $47.324761509747
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 136th day, sold 0.5425935973955507 shares for $49.793814432989684
On the 124th day, Bought 0.5433601391001956 shares for $50.0
On the 137th day, sold 0.5433601391001956 shares for $48.92414692458162
On the 124th day, Bought 0.5433601391001956 shares for $50.0
On the 137th day, sold 0.5433601391001956 shares for $48.92414692458162
On the 124th day, Bought 0.5433601391001956 shares for $50.0
On the 137th day, sold 0.5433601391001956 shares for $48.92414692458162

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 99.79381443298968, Final Money: 99.79381443298968, Final Shares: 0.0
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 31th day, Bought 0.5684402000909504 shares for $49.99999999999999
On the 55th day, sold 0.5684402000909504 shares for $52.73419736243747
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 1.1323747201953487 shares for $100.36237145091376
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1186549041658311 shares for $102.72607984954827
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 161th day, sold 1.0966471303772733 shares for $98.5776105496131
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0508631107789832 shares for $97.39399310699618
On the 219th day, Bought 0.5302226935312832 shares for $50.0
On the 221th day, Bought 0.5278716216216216 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0580943151529048 shares for $90.0120833900576
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5663797009515179 shares for $50.19823289533303
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.1186549041658311 shares for $101.70810388675737
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.0966471303772733 shares for $105.6948504257616
On the 221th day, Bought 0.5278716216216216 shares for $50.0
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0574204460232313 shares for $89.95475734319628
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.1186549041658311 shares for $101.70810388675737
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0966471303772733 shares for $100.80380422427896
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0788882080003819 shares for $91.78101985459247
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.5659950192438307 shares for $51.00181118406158
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 211th day, sold 1.0915254873792657 shares for $99.63444648797937
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.1072492552135054 shares for $94.70302879841111
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.5659950192438307 shares for $51.17160968983473
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.1072492552135054 shares for $94.70302879841111
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 139th day, sold 0.5659950192438307 shares for $50.07923930269414
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.1072492552135054 shares for $94.55908639523336
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 142th day, sold 0.5659950192438307 shares for $50.124518904233646
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.1072492552135054 shares for $94.55908639523336
XLB Final Value: 97.55594455104827, Final Money: 97.55594455104827, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5710370031978073 shares for $51.10210141617177
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 112th day, sold 1.1323747201953487 shares for $100.03398278205711
On the 129th day, Bought 0.5508427894678859 shares for $50.0
On the 137th day, sold 0.5508427894678859 shares for $49.59788476368845
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.1229646266142617 shares for $105.51375631667602
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 216th day, Bought 0.5314061005420342 shares for $50.0
On the 218th day, sold 1.0657654037375028 shares for $100.5549658426334
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, sold 1.0643081826903797 shares for $97.799278907419
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 57th day, Bought 0.5372877713303245 shares for $49.99999999999999
On the 61th day, sold 1.0833777669616045 shares for $96.95147636539399
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5663797009515179 shares for $50.033982782057095
On the 129th day, Bought 0.5508427894678859 shares for $50.0
On the 138th day, sold 0.5508427894678859 shares for $48.490690756857994
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5614823133071308 shares for $53.19483436271757
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5343593031954686 shares for $49.102276370631614
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 112th day, sold 0.5663797009515179 shares for $50.033982782057095
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 197th day, sold 1.1229646266142617 shares for $106.38966872543514
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, sold 1.0691186614842387 shares for $98.2413138037867
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 197th day, sold 0.5614823133071308 shares for $53.19483436271757
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 197th day, sold 0.5614823133071308 shares for $53.19483436271757

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 104.30100349743645, Final Money: 54.66496531127893, Final Shares: 0.5966587112171838
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5614823133071308 shares for $50.02245929253229
On the 77th day, Bought 0.5486065393899495 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.0912001367855002 shares for $99.31012444884838
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5567308762943993 shares for $51.12459637011469
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 163th day, sold 0.5451968160505943 shares for $49.503870897393966
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 214th day, Bought 0.540891389009087 shares for $50.0
On the 216th day, sold 0.540891389009087 shares for $50.892470791864994
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 1.1101022695116123 shares for $93.02657018507311
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5663797009515179 shares for $50.458767557770734
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.0844228128268467 shares for $98.69332019537133
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 175th day, sold 1.0691805544395634 shares for $103.80674003053721
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 214th day, Bought 0.540891389009087 shares for $50.0
On the 216th day, sold 0.540891389009087 shares for $50.892470791864994
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.1257047011536918 shares for $93.66988818299869
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 91th day, sold 0.541829215431296 shares for $49.311876896402254
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.0523015578016246 shares for $99.01105357355486
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 128th day, sold 0.5619240278714318 shares for $50.80355135985615
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.5877512636652169 shares for $50.0
XLB Final Value: 99.20738199455815, Final Money: 49.99999999999999, Final Shares: 0.5915059742103396

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.5804504295333178 shares for $56.58811237520315
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0679201308875026 shares for $95.98466136416873
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0969123538573196 shares for $99.09506204747025
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 162th day, sold 1.1127929289957883 shares for $96.40125143890513
On the 170th day, Bought 0.5620503597122303 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5620503597122303 shares for $49.00517086330936
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5567308762943993 shares for $50.24496158556954
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5804504295333178 shares for $55.79869979103784
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0679201308875026 shares for $95.98466136416873
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0969123538573196 shares for $99.09506204747025
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.1137718192470587 shares for $100.68497245993412
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 40th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5804504295333178 shares for $55.27629440445786
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.0679201308875026 shares for $96.48658382568586
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.094935722669386 shares for $100.62459291331659
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.117517062787762 shares for $101.02354247601369
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 38th day, Bought 0.5621767483696875 shares for $50.0
On the 40th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5621767483696875 shares for $53.53609174724534
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.066042591472773 shares for $97.96931415634783
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 234th day, sold 1.117517062787762 shares for $93.11152167147632
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.5621767483696875 shares for $50.0
On the 61th day, sold 0.5621767483696875 shares for $53.53609174724534
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.066042591472773 shares for $92.15938203282123
On the 38th day, Bought 0.5621767483696875 shares for $50.0
On the 62th day, sold 0.5621767483696875 shares for $53.0694850460985

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 104.93485971284524, Final Money: 3.4110136194739766, Final Shares: 1.160670470942852
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 30th day, Bought 0.5804504295333178 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 58th day, sold 1.1495376136899305 shares for $112.4132832427383
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.062820316664879 shares for $96.46157194050443
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.094935722669386 shares for $100.62459291331659
On the 169th day, Bought 0.5687635081333182 shares for $50.0
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 177th day, sold 1.142421149253098 shares for $100.304576904422
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0877965532433165 shares for $90.63520881623312
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5670863105364636 shares for $55.415674265623224
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 118th day, Bought 0.5583472920156337 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1132862487303952 shares for $102.63385927045513
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 199th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1149491305857049 shares for $92.89756156040092
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 101.96307991058569, Final Money: 0.4392338172144292, Final Shares: 1.160670470942852
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 106th day, sold 1.0679201308875026 shares for $94.66044040186823
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 232th day, sold 0.5389673385792821 shares for $46.67996119435163
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 107th day, sold 1.066726863235409 shares for $96.29343394426037
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 163th day, sold 0.5489679402722881 shares for $46.73913043478261
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.5389673385792821 shares for $45.30020480758866
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 107th day, sold 1.0675207592474305 shares for $96.36509893726554
On the 190th day, Bought 0.5516328331862312 shares for $50.0
On the 233th day, sold 0.5516328331862312 shares for $46.36473962930273

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 48th day, Bought 0.5403068943159715 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5403068943159715 shares for $52.83661119515885
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 101th day, Bought 0.5525472427892585 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1039975571159375 shares for $101.77753479051827
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 160th day, sold 1.1016373334412943 shares for $95.95261174273674
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 209th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 226th day, sold 1.110563397340035 shares for $100.916895916289
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1193739853852889 shares for $103.19508771266977
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 160th day, sold 0.5489679402722881 shares for $47.81510759771629
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.110563397340035 shares for $100.22834660993817
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.1193739853852889 shares for $96.76988103655823
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5538325210456357 shares for $49.98338502436862
On the 100th day, Bought 0.5514503143266791 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.0996959283617667 shares for $95.06871300687473
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5567308762943993 shares for $50.24496158556954
On the 113th day, Bought 0.5485463521667581 shares for $50.0
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.0967919662018457 shares for $94.81766547814956
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.0969123538573196 shares for $94.82807299096528
XLE Final Value: 101.48365364470285, Final Money: 101.48365364470285, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 79th day, Bought 1.1999040076793857 shares for $50.0
On the 101th day, sold 1.1999040076793857 shares for $49.0160787137029
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.0 shares for $41.54
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 129th day, Bought 0.0 shares for $0.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 137th day, sold 2.203369434416366 shares for $92.67371841155236
On the 192th day, Bought 1.0584250635055037 shares for $50.0
On the 193th day, Bought 1.0604453870625663 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, sold 2.11887045056807 shares for $98.4850985424039
On the 209th day, Bought 1.0046212577858147 shares for $50.0
On the 210th day, Bought 0.75 shares for $37.230000000000004
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 233th day, sold 1.7546212577858147 shares for $83.57261050833836
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 239th day, Bought 0.75 shares for $36.5625
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 101th day, sold 1.1941724385001196 shares for $48.78194411272989
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.0 shares for $41.54
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 137th day, sold 2.203369434416366 shares for $92.67371841155236
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0 shares for $47.15
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.0613457864572275 shares for $96.1411674803651
On the 209th day, Bought 1.0046212577858147 shares for $50.0
On the 210th day, Bought 0.75 shares for $37.230000000000004
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 233th day, sold 1.7546212577858147 shares for $83.57261050833836
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 239th day, Bought 0.75 shares for $36.5625
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 137th day, sold 2.4009742248355277 shares for $100.9849758965823
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 202th day, sold 1.0604453870625663 shares for $49.07741251325557
On the 209th day, Bought 1.0046212577858147 shares for $50.0
On the 210th day, Bought 1.0072522159548751 shares for $50.0
On the 211th day, Bought 0.0 shares for $0.0
On the 234th day, sold 2.01187347374069 shares for $96.16755204480496
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 137th day, sold 1.203659123736158 shares for $50.62590274434281
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 137th day, sold 1.203659123736158 shares for $50.62590274434281
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 137th day, sold 1.203659123736158 shares for $50.62590274434281

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 100.62590274434281, Final Money: 100.62590274434281, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 64th day, Bought 1.2553351744915893 shares for $50.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 66th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 109th day, sold 2.4935719253583546 shares for $103.70765637565398
On the 113th day, Bought 1.2162490878131842 shares for $50.0
On the 114th day, Bought 1.2135922330097086 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 122th day, sold 2.429841320822893 shares for $102.9766751764742
On the 143th day, Bought 1.1853959222380275 shares for $50.0
On the 144th day, Bought 1.175640724194686 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 171th day, sold 2.3610366464327135 shares for $107.8049332761177
On the 176th day, Bought 1.1074197120708749 shares for $50.0
On the 177th day, Bought 1.1032656663724625 shares for $50.0
On the 178th day, Bought 0.25 shares for $11.27
On the 200th day, sold 2.4606853784433373 shares for $114.37265639004632
On the 237th day, Bought 1.0206164523372117 shares for $50.0
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 239th day, Bought 0.25 shares for $12.1875
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 66th day, Bought 1.223391240518718 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 109th day, sold 2.4616279913854835 shares for $102.37910816172227
On the 114th day, Bought 1.2135922330097086 shares for $50.0
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.4132083558504 shares for $103.40597804818964
On the 143th day, Bought 1.1853959222380275 shares for $50.0
On the 144th day, Bought 1.175640724194686 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 200th day, sold 2.3610366464327135 shares for $109.74098332619252
On the 237th day, Bought 1.0206164523372117 shares for $50.0
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 239th day, Bought 0.25 shares for $12.1875
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 66th day, Bought 1.223391240518718 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 109th day, sold 2.4616279913854835 shares for $102.37910816172227
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 127th day, sold 2.4029855572570566 shares for $102.96793112846488
On the 144th day, Bought 1.175640724194686 shares for $50.0
On the 177th day, Bought 1.1032656663724625 shares for $50.0
On the 200th day, sold 2.2789063905671485 shares for $105.92356903356105
On the 237th day, Bought 1.0206164523372117 shares for $50.0
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 239th day, Bought 0.0 shares for $0.0
On the 65th day, Bought 1.2382367508667655 shares for $49.99999999999999
On the 66th day, Bought 1.223391240518718 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 137th day, sold 2.4616279913854835 shares for $103.53607331767344
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 239th day, Bought 1.0256410256410255 shares for $49.99999999999999
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 106th day, Bought 1.21153380179307 shares for $50.0
On the 137th day, sold 2.43074862744535 shares for $102.23728727035142
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 137th day, sold 1.21921482565228 shares for $51.28017556693489
On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001

[*********************100%***********************]  1 of 1 completed

On the 238th day, Bought 1.018122581958868 shares for $50.00000000000001
XLF Final Value: 116.61425089473869, Final Money: 5.4044212182921925, Final Shares: 2.2887390342960794
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.2394645513138323 shares for $90.9222607833416
On the 97th day, Bought 1.2103606874848705 shares for $50.0
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.4204284512796432 shares for $106.06317473507397
On the 133th day, Bought 1.1534025374855825 shares for $50.00000000000001
On the 134th day, Bought 1.1402508551881414 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 137th day, sold 2.2936533926737237 shares for $96.47106169585682
On the 176th day, Bought 1.1074197120708749 shares for $50.0
On the 177th day, Bought 1.1032656663724625 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, sold 2.2106853784433373 shares for $105.2507308676873
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 2.2394645513138323 shares for $89.71294992563213
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.0 shares for $41.54
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.203369434416366 shares for $96.55164861612515
On the 133th day, Bought 1.1534025374855825 shares for $50.00000000000001
On the 134th day, Bought 1.1402508551881414 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 2.2936533926737237 shares for $93.67280455679489
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 181th day, Bought 1.0 shares for $45.65
On the 182th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.1138338159946537 shares for $104.74046558253508
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.4009742248355277 shares for $105.21069053229283
On the 134th day, Bought 1.1402508551881414 shares for $50.0
On the 138th day, sold 1.1402508551881414 shares for $46.5678449258837
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.186104886121181 shares for $108.32149710730452
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 125th day, sold 1.203659123736158 shares for $52.744342802118446

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 113.99332853567927, Final Money: 113.99332853567927, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 104th day, Bought 1.2300123001230012 shares for $50.0
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 106th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4492271257752813 shares for $105.3167664083371
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 186th day, sold 2.2784403631861974 shares for $105.97026129179004
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 200th day, sold 2.132716457189094 shares for $99.12866093014908
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.422873949388438 shares for $104.18357982370284
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2784403631861974 shares for $106.63100899711402
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 201th day, sold 2.132716457189094 shares for $99.46989556329935
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.4105140597728463 shares for $104.8332564595211
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 78th day, Bought 1.2088974854932302 shares for $50.0
On the 92th day, sold 1.2088974854932302 shares for $49.347195357833655
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 125th day, sold 1.2068549360366885 shares for $52.88438329712769
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 201th day, sold 1.1397310234784592 shares for $53.15705493503534
XLF Final Value: 111.67532482776801, Final Money: 111.67532482776801, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, sold 0.7973563487023718 shares for $98.01901594598257
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.40264132710581413 shares for $50.692543082622
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.390625 shares for $54.91406250000001
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.7105312176540179 shares for $95.32486816046304
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 59th day, sold 0.4132231404958678 shares for $51.33471074380166
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 97th day, sold 0.7991369435960733 shares for $98.2379044762653
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 59th day, sold 0.4132231404958678 shares for $51.33471074380166
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, sold 0.796407374083437 shares for $97.320981112996
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 59th day, sold 0.4132231404958678 shares for $51.33471074380166
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, sold 0.7983397032568902 shares for $97.55711173799199
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3869370066553165 shares for $54.3956043956044
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 59th day, sold 0.4132231404958678 shares for $51.33471074380166
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 60th day, sold 0.4132231404958678 shares for $50.78512396694215
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 60th day, sold 0.4132231404958678 shares for $50.78512396694215

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 103.94297413095805, Final Money: 103.94297413095805, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 68th day, Bought 0.0 shares for $0.0
On the 72th day, sold 0.82697056674124 shares for $100.49346327039548
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 116th day, Bought 0.4109814236396515 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8234546128823508 shares for $103.39296119350797
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7839155583232007 shares for $110.20284918907556
On the 215th day, Bought 0.35539128580567203 shares for $50.0
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 217th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.7058995227492402 shares for $94.70347997203805
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4124731892426992 shares for $51.79013364131331
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7839155583232007 shares for $110.20284918907556
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7991369435960733 shares for $97.49470711872095
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7991369435960733 shares for $97.49470711872095
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 74th day, sold 0.4119294776734223 shares for $50.22244191794365
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 128th day, sold 0.399616368286445 shares for $50.40760869565217
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7807623283395755 shares for $110.93851923377028
On the 151th day, Bought 0.390625 shares for $50.0
On the 206th day, sold 0.390625 shares for $55.50390625

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 111.5685698473661, Final Money: 111.5685698473661, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 43th day, Bought 0 shares for $0.0
On the 62th day, sold 0.4132231404958678 shares for $50.30578512396694
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7983397032568902 shares for $97.42139398843831
On the 120th day, Bought 0.41010498687664043 shares for $50.0
On the 124th day, sold 0.41010498687664043 shares for $52.57135826771653
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 184th day, Bought 0 shares for $0.0
On the 185th day, Bought 0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7739341331918541 shares for $108.79966044411086
On the 241th day, Bought 0.37947783849423194 shares for $50.0
On the 242th day, Bought 0.3808073115003808 shares for $50.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 43th day, Bought 0 shares for $0.0
On the 62th day, sold 0.4132231404958678 shares for $50.30578512396694
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7983397032568902 shares for $97.42139398843831
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 184th day, Bought 0 shares for $0.0
On the 185th day, Bought 0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 62th day, sold 0.4132231404958678 shares for $50.30578512396694
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 94th day, sold 0.7971310601841195 shares for $98.4536572433406
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 184th day, Bought 0 shares for $0.0
On the 185th day, Bought 0 shares for $0.0
On the 205th day, sold 0.3871767074492799 shares for $54.42930153321977
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 62th day, sold 0.4132231404958678 shares for $50.30578512396694
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 95th day, sold 0.3981842796846381 shares for $48.578482121525845
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 184th day, Bought 0 shares for $0.0
On the 205th day, sold 0.3871767074492799 shares for $54.42930153321977
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 63th day, sold 0.4132231404958678 shares for $50.04545454545455
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 124th day, sold 0.3981842796846381 shares for $51.043242812773755
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 63th day, sold 0.4132231404958678 shares for $50.04545454545455
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 63th day, sold 0.4132231404958678 shares for $50.04545454545455

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 110.00324293151765, Final Money: 9.098197824232642, Final Shares: 0.7602851499946127
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.4062728528479727 shares for $49.24839522223125
On the 77th day, Bought 0.40209087253719344 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.40209087253719344 shares for $49.067149175713716
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.4102732419791581 shares for $51.65340116517601
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 194th day, sold 0.38675742574257427 shares for $52.869740099009896
On the 203th day, Bought 0.36737692872887584 shares for $50.0
On the 205th day, sold 0.36737692872887584 shares for $51.64584864070537
On the 230th day, Bought 0.3638215818962381 shares for $50.0
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 93th day, sold 0.40209087253719344 shares for $49.067149175713716
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.4124731892426992 shares for $50.81257218280812
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3871767074492799 shares for $54.42930153321977
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 94th day, sold 0.40209087253719344 shares for $49.662243667068765
On the 116th day, Bought 0.4109814236396515 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.4109814236396515 shares for $51.03567318757193
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.38711675441313104 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7740537610684475 shares for $109.9852989102157
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 237th day, Bought 0.3726893261776983 shares for $50.0
On the 238th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 94th day, sold 0.40209087253719344 shares for $49.662243667068765
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.4137702747434624 shares for $51.381992717643165
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.38711675441313104 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7740537610684475 shares for $109.9852989102157
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 237th day, Bought 0.3726893261776983 shares for $50.0
On the 237th day, Bought 0.3726893261776983 shares for $50.0
XLI Final Value: 109.18315542332112, Final Money: 11.029535294927626, Final Shares: 0.739554099822133

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 61th day, sold 0.24077819512664933 shares for $48.52162188192238
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4446063536548852 shares for $99.55180864686534
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.21632847315363649 shares for $50.0
On the 234th day, sold 0.43246991611390967 shares for $100.54493079732286
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 62th day, sold 0.2400729821865847 shares for $48.43712488596533
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 109th day, sold 0.24211902571304053 shares for $53.852113699094474
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.4446063536548852 shares for $99.47622556674402
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 125th day, sold 0.23940627244433804 shares for $53.713191285611686
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44852140323780454 shares for $100.3521787604264
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 126th day, sold 0.23999232024575212 shares for $53.84947681674186
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 202th day, sold 0.4314815234313326 shares for $96.53967605252636
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 202th day, sold 0.21429795988342193 shares for $47.94702554431682
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 104.06537004603808, Final Money: 104.06537004603808, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 76th day, sold 0.24077819512664933 shares for $49.34267552730425
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 155th day, Bought 0.22787348464132715 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22787348464132715 shares for $50.98441345365054
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 52th day, Bought 0.24173274028234384 shares for $50.0
On the 76th day, sold 0.24173274028234384 shares for $49.53829046606072
On the 84th day, Bought 0.23552687361627964 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23552687361627964 shares for $53.285599886947104
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.22700444928720603 shares for $51.505039498774174
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 238th day, sold 0.21392204680614385 shares for $51.48889744577076
On the 91th day, Bought 0.23137436372049977 shares for $50.0
On the 111th day, sold 0.23137436372049977 shares for $52.34613604812587
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.21718356354791069 shares for $49.276778733385456
On the 92th day, Bought 0.23285055651283007 shares for $50.0
On the 111th day, sold 0.23285055651283007 shares for $52.68010990546268
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.21036687983843824 shares for $47.20212049814877
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.21429795988342193 shares for $48.6220641179496
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 204th day, sold 0.21429795988342193 shares for $50.0064289387965

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 100.90709138456955, Final Money: 100.90709138456955, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 62th day, sold 0.24315518163692068 shares for $49.058989447065116
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 124th day, Bought 0.2141877998629198 shares for $50.0
On the 125th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4324521616579259 shares for $95.5157089453861
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 62th day, sold 0.24315518163692068 shares for $49.058989447065116
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 125th day, Bought 0.22285612408628988 shares for $50.0
On the 127th day, sold 0.22285612408628988 shares for $49.22223212693885
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 62th day, sold 0.23940627244433804 shares for $48.30260952836964
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 62th day, sold 0.23940627244433804 shares for $48.30260952836964
On the 155th day, Bought 0.22787348464132715 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22787348464132715 shares for $51.02315194603956

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 105.19847291103895, Final Money: 53.659405970371736, Final Shares: 0.21861746316295744
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 73th day, Bought 0.2573870071038814 shares for $50.0
On the 78th day, sold 0.2573870071038814 shares for $52.72315453515907
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.4747010467162023 shares for $108.07518730587776
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44934504106442896 shares for $100.61284814473629
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.21632847315363649 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 241th day, sold 0.43246991611390967 shares for $100.55790489480628
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.223254152527237 shares for $49.98883729237363
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.21614144296027318 shares for $50.13833052349457
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 127th day, sold 0.23999232024575212 shares for $53.00710377267927
On the 170th day, Bought 0.22359359627940256 shares for $50.0
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4471971918252189 shares for $100.13192322158476
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.21632847315363649 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.43246991611390967 shares for $100.32004644094363
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 127th day, sold 0.23999232024575212 shares for $53.00710377267927
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 201th day, sold 0.44301649220077255 shares for $99.19582276867499
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 127th day, sold 0.23999232024575212 shares for $53.00710377267927
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 201th day, sold 0.22005105184402782 shares for $49.27163101839627
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 127th day, sold 0.23470872647045016 shares for $51.84011641552833
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 137th day, sold 0.23470872647045016 shares for $48.04957048303056
XLK Final Value: 109.26560238229646, Final Money: 109.26560238229646, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 56th day, sold 0.6693440428380187 shares for $49.67871485943775
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.6455777921239509 shares for $50.67140090380891
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 155th day, Bought 0.6077549532028687 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2129352969453038 shares for $97.68980881597477
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.6069434328720563 shares for $48.695071619325084
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 60th day, sold 0.6637461834594451 shares for $48.705694942254084
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6493506493506493 shares for $50.551948051948045
On the 156th day, Bought 0.610798924993892 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.610798924993892 shares for $49.19374541900807
On the 35th day, Bought 0.6599788806758183 shares for $50.0
On the 62th day, sold 0.6599788806758183 shares for $48.25105596620908
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 191th day, Bought 0.6079766536964981 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6079766536964981 shares for $48.966439688715965
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 136th day, sold 0.6431695394906097 shares for $50.5338307177772
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 136th day, sold 0.6431695394906097 shares for $50.5338307177772
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.628456510809452 shares for $50.0
On the 208th day, sold 1.2466563129855153 shares for $100.51789851602209
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 137th day, sold 0.6431695394906097 shares for $50.97761770002573
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 208th day, sold 0.6181998021760633 shares for $49.845450049455984

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.05172923379928, Final Money: 101.05172923379928, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 94th day, Bought 0.6464959917248513 shares for $50.0
On the 96th day, sold 0.6464959917248513 shares for $50.4137574347039
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.2964676982471979 shares for $99.97062421184143
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, sold 1.2437834227153124 shares for $101.5424786304781
On the 192th day, Bought 0.6131207847946045 shares for $50.0
On the 205th day, sold 0.6131207847946045 shares for $48.95769466584917
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 218th day, sold 1.239884804394279 shares for $102.45168138709927
On the 228th day, Bought 0.6096817461285209 shares for $50.0
On the 229th day, Bought 0.60790273556231 shares for $50.0
On the 239th day, sold 1.2175844816908308 shares for $96.55444939808288
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.3027624078912101 shares for $101.79785455261916
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2400059548577866 shares for $99.01447549539425
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 240th day, sold 0.6165988407941793 shares for $48.32285115303983
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 139th day, sold 0.6509569066527796 shares for $50.93086837651347
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 206th day, sold 1.2400059548577866 shares for $100.21728127160631
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 139th day, sold 0.649772579597141 shares for $50.83820662768031
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 206th day, sold 0.6189650903689032 shares for $50.02475860361476
On the 113th day, Bought 0.6529119874640898 shares for $50.0
On the 207th day, sold 0.6529119874640898 shares for $52.5855314703578
XLP Final Value: 102.58553147035781, Final Money: 102.58553147035781, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 51th day, sold 1.342552488151616 shares for $101.6983509774849
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 61th day, Bought 0.6841817186644773 shares for $50.0
On the 68th day, sold 1.3655662921177343 shares for $103.68744856049958
On the 76th day, Bought 0.6585879873551106 shares for $50.0
On the 77th day, Bought 0.6514657980456026 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 1.3100537854007133 shares for $100.3108183481326
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 153th day, Bought 0.6066488716330988 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2293914298595279 shares for $100.15851979065573
On the 187th day, Bought 0.6099792607051361 shares for $50.00000000000001
On the 200th day, sold 0.6099792607051361 shares for $48.87153836769551
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.2108811065041376 shares for $96.4587889441196
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 52th day, sold 0.6715014773032502 shares for $50.60435132957293
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 68th day, sold 0.6813845734532571 shares for $51.737530662305815
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 1.2964676982471979 shares for $99.27053165478793
On the 156th day, Bought 0.610798924993892 shares for $50.0
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2167860780662467 shares for $99.13156178005713
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 226th day, Bought 0.60790273556231 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.2148461684343663 shares for $96.77464577748162
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6022645145748012 shares for $49.066490002409054
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 181th day, sold 0.6022645145748012 shares for $49.066490002409054
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 115th day, sold 0.6518055012384305 shares for $49.908747229826616

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.18546498858794, Final Money: 101.18546498858794, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 77th day, Bought 0.6514657980456026 shares for $50.0
On the 78th day, Bought 0.6534239414532149 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.3048897394988175 shares for $100.88102576065359
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 119th day, sold 1.3007294862499206 shares for $100.23421421041888
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.2778882724426772 shares for $99.29191876879602
On the 143th day, Bought 0.6349206349206349 shares for $50.0
On the 144th day, Bought 0.6320313487548982 shares for $49.99999999999999
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 159th day, sold 1.2669519836755332 shares for $105.76515159723351
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2056191664391671 shares for $97.88422012319597
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 229th day, Bought 0.0 shares for $0.0
On the 233th day, sold 1.2023570535234946 shares for $96.46510640418998
On the 78th day, Bought 0.6534239414532149 shares for $50.0
On the 121th day, sold 0.6534239414532149 shares for $50.385520125457404
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.2778882724426772 shares for $99.29191876879602
On the 143th day, Bought 0.6349206349206349 shares for $50.0
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 159th day, sold 0.6349206349206349 shares for $53.0031746031746
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2056191664391671 shares for $96.26869044016749
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 121th day, sold 0.6399590426212722 shares for $49.3472417765263
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 144th day, Bought 0.6320313487548982 shares for $49.99999999999999
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6320313487548982 shares for $50.46770319807862
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 121th day, sold 0.642508352608584 shares for $49.54381906964791
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
XLP Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6814613955648616 shares for $97.59890107279948
On the 70th day, Bought 0.35724492712203487 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.35724492712203487 shares for $51.69691340382967
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.321646831778707 shares for $47.960759086523005
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6814613955648616 shares for $97.59890107279948
On the 70th day, Bought 0.35724492712203487 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.35724492712203487 shares for $51.69691340382967
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.321646831778707 shares for $47.960759086523005
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34458993797381116 shares for $47.553411440385936
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 56th day, sold 0.34300610550867805 shares for $48.967551622418874
On the 71th day, Bought 0.3560492772199672 shares for $50.0
On the 95th day, sold 0.3560492772199672 shares for $51.52389090650146
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6434592794841842 shares for $95.94621316388672
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34458993797381116 shares for $47.8118538938663
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.32181244770547723 shares for $47.98545407736371
On the 225th day, Bought 0.34654837815359024 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.32181244770547723 shares for $47.98545407736371
On the 225th day, Bought 0.34654837815359024 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.321316110789795 shares for $47.911445279866335
On the 227th day, Bought 0.3469812630117974 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 205th day, sold 0.32094486167276465 shares for $47.85608832402594

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 97.85608832402593, Final Money: 97.85608832402593, Final Shares: 0.0
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 64th day, Bought 0.3611933829372246 shares for $50.0
On the 65th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.0 shares for $0.0
On the 68th day, Bought 0.0 shares for $0.0
On the 69th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 85th day, sold 0.3611933829372246 shares for $52.846203857545326
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 120th day, sold 0.6853774917644311 shares for $100.28443459497156
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.64628714820769 shares for $99.06289407727472
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.672495324291966 shares for $95.38673679757247
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 64th day, Bought 0.3611933829372246 shares for $50.0
On the 95th day, sold 0.3611933829372246 shares for $52.26829444484577
On the 117th day, Bought 0.34623641022089885 shares for $50.0
On the 121th day, sold 0.34623641022089885 shares for $51.017935046049445
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6446859841239713 shares for $98.72076474890372
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.672495324291966 shares for $95.45398633000165
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 65th day, Bought 0.35984166966534725 shares for $50.0
On the 95th day, sold 0.35984166966534725 shares for $52.072688017272405
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6446859841239713 shares for $98.72076474890372
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6446859841239713 shares for $98.72076474890372
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 96th day, sold 0.3536067892503536 shares for $51.31895332390382
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 96.6507428942479, Final Money: 49.8912032213224, Final Shares: 0.33649639948852544
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 51th day, sold 0.3442577802258331 shares for $50.423437069677775
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 73th day, Bought 0.0 shares for $0.0
On the 74th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.712331374992871 shares for $100.88749264024032
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.6858477175629567 shares for $101.33400026992685
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6412113233688959 shares for $98.00915077693573
On the 192th day, Bought 0.33040375338663847 shares for $50.0
On the 197th day, sold 0.33040375338663847 shares for $49.16738254146567
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3406690740614567 shares for $48.32050146487702
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 93th day, sold 0.3584743332377402 shares for $50.770719816461146
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 123th day, sold 0.6857537626661178 shares for $101.32011843391889
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.31806615776081426 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6383326194569454 shares for $97.56914088399411
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3406690740614567 shares for $48.32050146487702
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 93th day, sold 0.3538570417551309 shares for $50.116772823779186
On the 180th day, Bought 0.32998944033790917 shares for $50.0
On the 181th day, Bought 0.3297283038776049 shares for $50.0
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.659717744215514 shares for $98.17259751671064
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3406690740614567 shares for $48.32050146487702
On the 237th day, Bought 0.3588860178007465 shares for $50.00000000000001
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 93th day, sold 0.3538570417551309 shares for $50.116772823779186
On the 180th day, Bought 0.32998944033790917 shares for $50.0
On the 181th day, Bought 0.3297283038776049 shares for $50.0
On the 198th day, sold 0.659717744215514 shares for $97.90211324158228
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3406690740614567 shares for $48.32050146487702
On the 237th day, Bought 0.3588860178007465 shares for $50.00000000000001
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.32998944033790917 shares for $50.0
On the 198th day, sold 0.32998944033790917 shares for $48.97043294614572
On the 203th day, Bought 0.3381805884342239 shares for $50.0
On the 211th day, sold 0.3381805884342239 shares for $47.967534663510314
On the 238th day, Bought 0.35816618911174786 shares for $50.0
On the 180th day, Bought 0.32998944033790917 shares for $50.0
On the 198th day, sold 0.32998944033790917 shares for $48.97043294614572
On the 203th day, Bought 0.3381805884342239 shares for $50.0
On the 211th day, sold 0.3381805884342239 shares for $47.967534663510314

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3584743332377402 shares for $51.87482076283339
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 117th day, Bought 0.34623641022089885 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.6885849210048769 shares for $102.68178342024724
On the 143th day, Bought 0.33464962184592734 shares for $50.0
On the 157th day, sold 0.33464962184592734 shares for $52.60692055417977
On the 173th day, Bought 0.324485690181063 shares for $50.0
On the 174th day, Bought 0.32767547021429977 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.6521611603953628 shares for $96.59811107776113
On the 203th day, Bought 0.3381805884342239 shares for $50.0
On the 204th day, sold 0.3381805884342239 shares for $50.0642543118025
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3584743332377402 shares for $51.87482076283339
On the 118th day, Bought 0.3466204506065858 shares for $50.0
On the 138th day, sold 0.3466204506065858 shares for $50.894280762564996
On the 173th day, Bought 0.324485690181063 shares for $50.0
On the 174th day, Bought 0.32767547021429977 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.6521611603953628 shares for $96.59811107776113
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.3538570417551309 shares for $51.35527246992214
On the 118th day, Bought 0.3466204506065858 shares for $50.0
On the 138th day, sold 0.3466204506065858 shares for $50.894280762564996
On the 181th day, Bought 0.3297283038776049 shares for $50.0
On the 182th day, Bought 0.3311916274756574 shares for $49.99999999999999
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.6609199313532623 shares for $97.89546023204522
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 138th day, sold 0.3538570417551309 shares for $51.95682944090587
On the 181th day, Bought 0.3297283038776049 shares for $50.0
On the 193th day, Bought 0.3308847859175435 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6606130897951483 shares for $98.50401781935457
On the 193th day, Bought 0.3308847859175435 shares for $50.0
On the 205th day, sold 0.3308847859175435 shares for $49.33823042816491
On the 193th day, Bought 0.3308847859175435 shares for $50.0
On the 205th day, sold 0.3308847859175435 shares for $49.33823042816491
On the 193th day, Bought 0.3308847859175435 shares for $50.0
On the 211th day, sold 0.3308847859175435 shares for $46.93269803454437
XLV Final Value: 103.82589012682405, Final Money: 103.82589012682405, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.2811041772080733 shares for $53.81739472648563
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5374235599170535 shares for $107.53308010380323
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.43407487791644056 shares for $101.3998914812805
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5612005303535553 shares for $107.44184153618816
On the 151th day, Bought 0.2712820791058543 shares for $50.0
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5374235599170535 shares for $107.53308010380323
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.43023815087518835 shares for $97.25533400533634
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 125th day, sold 0.5612005303535553 shares for $107.44184153618816
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.534367434354464 shares for $106.9215799399847
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.2798298634430266 shares for $53.57342735616744
On the 152th day, Bought 0.2661414808111992 shares for $49.99999999999999
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.534367434354464 shares for $106.55286641028012
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.2798298634430266 shares for $53.57342735616744
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2798298634430266 shares for $53.027759122453546
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 126th day, sold 0.2794076557697681 shares for $52.94775076837106

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 114.36342147617287, Final Money: 114.36342147617287, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 108th day, sold 0.5608375097990475 shares for $102.41453766440407
On the 147th day, Bought 0.27303008791568834 shares for $50.00000000000001
On the 148th day, Bought 0.2697162584960621 shares for $49.99999999999999
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5427463464117505 shares for $108.98889382294361
On the 216th day, Bought 0.22925263640531868 shares for $50.0
On the 218th day, Bought 0.22611133722244833 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.45536397362776704 shares for $103.97325609842805
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2807411566535654 shares for $53.200449185850644
On the 147th day, Bought 0.27303008791568834 shares for $50.00000000000001
On the 148th day, Bought 0.2697162584960621 shares for $49.99999999999999
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5427463464117505 shares for $108.98889382294361
On the 216th day, Bought 0.22925263640531868 shares for $50.0
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4564840488757786 shares for $104.22900287980653
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2807411566535654 shares for $53.200449185850644
On the 148th day, Bought 0.2697162584960621 shares for $49.99999999999999
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5396800833435326 shares for $108.37315753621478
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 127th day, sold 0.2807411566535654 shares for $52.72599663110612
On the 148th day, Bought 0.2697162584960621 shares for $49.99999999999999
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5396800833435326 shares for $108.37315753621478
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 127th day, sold 0.2807411566535654 shares for $52.72599663110612
On the 148th day, Bought 0.2697162584960621 shares for $49.99999999999999
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5396800833435326 shares for $108.37315753621478
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 131th day, sold 0.2807411566535654 shares for $50.699045480067376
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5365593993609334 shares for $107.74649298566905
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 131th day, sold 0.2807411566535654 shares for $50.699045480067376
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5365593993609334 shares for $107.74649298566905

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 116.41834588860078, Final Money: 116.41834588860078, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 49th day, Bought 0.2710614767429253 shares for $50.0
On the 50th day, Bought 0.2719016803523846 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.54296315709531 shares for $97.10353101492524
On the 58th day, Bought 0.2799708830281651 shares for $50.0
On the 62th day, sold 0.2799708830281651 shares for $48.48255781398734
On the 68th day, Bought 0.2870428842069005 shares for $50.0
On the 72th day, sold 0.2870428842069005 shares for $50.410471324415866
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 122th day, Bought 0.261110240743642 shares for $50.00000000000001
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.261110240743642 shares for $47.15389837589431
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.26822595354326484 shares for $53.6317794109758
On the 202th day, Bought 0.25075225677031093 shares for $50.0
On the 205th day, sold 0.25075225677031093 shares for $53.187061183550654
On the 211th day, Bought 0.23425787106446777 shares for $50.0
On the 212th day, Bought 0.23211550067313497 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 50th day, Bought 0.2719016803523846 shares for $50.0
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.5458442619872739 shares for $97.61878781380406
On the 58th day, Bought 0.2799708830281651 shares for $50.0
On the 62th day, sold 0.2799708830281651 shares for $48.48255781398734
On the 68th day, Bought 0.2870428842069005 shares for $50.0
On the 72th day, sold 0.2870428842069005 shares for $50.410471324415866
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 122th day, Bought 0.261110240743642 shares for $50.00000000000001
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.261110240743642 shares for $47.15389837589431
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.26893287435456115 shares for $57.04335197934597
On the 212th day, Bought 0.23211550067313497 shares for $50.0
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 68th day, Bought 0.2870428842069005 shares for $50.0
On the 72th day, sold 0.2870428842069005 shares for $50.410471324415866
On the 122th day, Bought 0.261110240743642 shares for $50.00000000000001
On the 131th day, sold 0.261110240743642 shares for $47.15389837589431
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 68th day, Bought 0.2870428842069005 shares for $50.0
On the 72th day, sold 0.2870428842069005 shares for $50.410471324415866
On the 122th day, Bought 0.261110240743642 shares for $50.00000000000001
On the 131th day, sold 0.261110240743642 shares for $47.15389837589431
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 122th day, Bought 0.261110240743642 shares for $50.00000000000001
On the 131th day, sold 0.261110240743642 shares for $47.15389837589431
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 62th day, sold 0.27625835681529365 shares for $47.839659649704394
On the 122th day, Bought 0.261110240743642 shares for $50.00000000000001
On the 131th day, sold 0.261110240743642 shares for $47.15389837589431

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 108.5745746434893, Final Money: 3.2301574353995903, Final Shares: 0.46637337173760274
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 68th day, Bought 0.2870428842069005 shares for $50.0
On the 73th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.2870428842069005 shares for $51.050576956197254
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.28123066539175434 shares for $49.246301816750105
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2814364516492176 shares for $51.910953506698185
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.5242949918070232 shares for $99.10748230128159
On the 158th day, Bought 0.270929287455974 shares for $50.00000000000001
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.270929287455974 shares for $58.28230831752913
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 59th day, sold 0.2711349709885581 shares for $48.812428827070114
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.2797985450475658 shares for $48.99552322327925
On the 100th day, Bought 0.28053638556920835 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.28053638556920835 shares for $49.41928968187174
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 213th day, sold 0.2671939293539251 shares for $57.59899535082563
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 59th day, sold 0.2702410550210788 shares for $48.65149713544482
On the 101th day, Bought 0.2812781278127813 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.2812781278127813 shares for $49.54995499549955
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 213th day, sold 0.2671939293539251 shares for $57.59899535082563
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 59th day, sold 0.2702410550210788 shares for $48.65149713544482
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.26116479498563594 shares for $46.00679028466963
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 213th day, sold 0.2671939293539251 shares for $57.59899535082563
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.26452227277536766 shares for $45.28092265368744
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.25889297364469527 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.25889297364469527 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
XLY Final Value: 117.25574202451662, Final Money: 7.105427357601002e-15, Final Shares: 0.5191063486121685

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 44th day, Bought 0.7828401440425865 shares for $50.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.5666620597033485 shares for $102.08369981027018
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.3811242047734613 shares for $96.77537302847642
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6672894701721607 shares for $52.13532630455091
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2469731416026284 shares for $94.86971661312796
On the 44th day, Bought 0.7828401440425865 shares for $50.0
On the 61th day, sold 0.7828401440425865 shares for $49.79646156254893
On the 84th day, Bought 0.6917542888765911 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6917542888765911 shares for $48.498893193137796
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6687174000267487 shares for $52.24689046408987
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 61th day, sold 0.7793017456359103 shares for $49.57138403990025
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6911805363560962 shares for $48.45866740392591
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6687174000267487 shares for $52.24689046408987
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.7882705344474223 shares for $50.0
On the 62th day, sold 0.7882705344474223 shares for $49.4797414472647
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6923289947382997 shares for $48.49764608141789
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 201th day, sold 0.6640106241699868 shares for $51.87915006640107
On the 48th day, Bought 0.7882705344474223 shares for $50.0
On the 62th day, sold 0.7882705344474223 shares for $49.4797414472647
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6861534239055852 shares for $50.92630712227253
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 138th day, sold 0.6943480072212193 shares for $50.17358700180531

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 100.40604856953723, Final Money: 100.40604856953723, Final Shares: 0.0
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 53th day, sold 0.7843137254901961 shares for $51.05882352941176
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 66th day, sold 1.5442838507950172 shares for $101.96906266799499
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 99th day, Bought 0.7148984844152131 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 123th day, sold 1.416455941970987 shares for $98.48618164524272
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 133th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.4119643187794981 shares for $104.6265560215608
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 179th day, Bought 0.6137228427642077 shares for $50.00000000000001
On the 180th day, Bought 0.6139489194499018 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 184th day, sold 1.2276717622141096 shares for $96.74053486247183
On the 209th day, Bought 0.6381620931716656 shares for $50.0
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, sold 1.2785309456306821 shares for $102.84502926653207
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.2841218591822159 shares for $98.14543369729677
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 53th day, sold 0.7843137254901961 shares for $51.05882352941176
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 67th day, sold 0.772916988715412 shares for $51.275313031380435
On the 99th day, Bought 0.7148984844152131 shares for $50.0
On the 100th day, Bought 0.7058159232072275 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4207144076224405 shares for $99.54945854210439
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 136th day, sold 1.4119643187794981 shares for $104.6265560215608
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 180th day, Bought 0.6139489194499018 shares for $50.0
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 182th day, Bought 0.0 shares for $0.0
On the 184th day, sold 1.2288794323019494 shares for $96.83569926539361
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.271283678957439 shares for $97.16421158271707
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 54th day, sold 0.7803964413922273 shares for $50.70235679725301
On the 100th day, Bought 0.7058159232072275 shares for $50.0
On the 124th day, sold 0.7058159232072275 shares for $49.45652173913043
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 137th day, sold 1.4119643187794981 shares for $104.79599173981435
On the 180th day, Bought 0.6139489194499018 shares for $50.0
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 182th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2288794323019494 shares for $96.54076820164114
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.271283678957439 shares for $96.69383662150283
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 55th day, sold 0.7803964413922273 shares for $50.85063212111753
On the 100th day, Bought 0.7058159232072275 shares for $50.0
On the 124th day, sold 0.7058159232072275 shares for $49.45652173913043
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 137th day, sold 0.702543206407194 shares for $52.14275677954194
On the 180th day, Bought 0.6139489194499018 shares for $50.0
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2288794323019494 shares for $93.46856962088627
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 124th day, sold 0.7803964413922273 shares for $54.682378648353364
On the 180th day, Bought 0.6139489194499018 shares for $50.0
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 210th day, Bought 0.0 shares for $0.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2288794323019494 shares for $93.46856962088627
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 124th day, sold 0.7803964413922273 shares for $54.682378648353364
On the 181th day, Bought 0.6149305128520477 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2458453393504705 shares for $94.75899651099678
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 124th day, sold 0.7803964413922273 shares for $54.682378648353364
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 236th day, sold 1.2884108790184259 shares for $97.99653145814148
XLU Final Value: 113.47352005732375, Final Money: 12.024292745801404, Final Shares: 1.3161549988521322

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 51th day, sold 0.7793017456359103 shares for $50.849438902743145
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 62th day, sold 1.5204614416688504 shares for $95.43936469355374
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6923289947382997 shares for $47.09221822209914
On the 117th day, Bought 0.7293946024799417 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7293946024799417 shares for $51.97665937272065
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 169th day, sold 0.6672894701721607 shares for $52.368877619111174
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.6128201985537443 shares for $48.970462066429704
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.6254691018263698 shares for $48.861646234676016
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 235th day, sold 0.6676458806249166 shares for $51.02817465616238
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6923289947382997 shares for $49.33536416505124
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.6128201985537443 shares for $47.87964211300404
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6861534239055852 shares for $48.89529298751201
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.6128201985537443 shares for $47.30971932834906
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 118th day, Bought 0.728650539201399 shares for $50.0
On the 122th day, sold 0.728650539201399 shares for $51.9236374234917
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.6220452848967405 shares for $48.743468524508586
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.728650539201399 shares for $50.0
On the 123th day, sold 0.728650539201399 shares for $50.663071990673274
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 235th day, sold 0.6220452848967405 shares for $47.54292112465788
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 235th day, sold 0.6220452848967405 shares for $47.54292112465788
On the 242th day, Bought 0.6555657532450505 shares for $50.0

[*********************100%***********************]  1 of 1 completed

On the 242th day, Bought 0.6555657532450505 shares for $50.0
XLU Final Value: 100.53100826012849, Final Money: 50.0, Final Shares: 0.6555657532450505
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.7452675510508272 shares for $50.58130868981964
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7008690776562938 shares for $50.38547799271096
On the 99th day, Bought 0.7148984844152131 shares for $50.0
On the 100th day, Bought 0.7058159232072275 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.4207144076224405 shares for $99.63470140656175
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 240th day, sold 1.2470867678308721 shares for $94.47929353086688
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 74th day, sold 0.7452675510508272 shares for $50.58130868981964
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 96th day, sold 0.6943480072212193 shares for $49.89584779891682
On the 99th day, Bought 0.7148984844152131 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.7148984844152131 shares for $50.55762081784387
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 191th day, sold 1.270973978310089 shares for $104.1563175225118
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 63th day, sold 0.7803964413922273 shares for $50.007803964413924
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 75th day, sold 0.7452675510508272 shares for $50.983753167387086
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.428063510802319 shares for $100.99265148394
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 191th day, sold 1.270973978310089 shares for $104.1563175225118
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.4584325774379332 shares for $104.26334496103783
On the 48th day, Bought 0.7882705344474223 shares for $50.0
On the 66th day, sold 0.7882705344474223 shares for $52.0495033895633
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 173th day, sold 0.7148984844152131 shares for $57.0203031169574
XLU Final Value: 109.0698065065207, Final Money: 109.0698065065207, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 58th day, sold 0.09558950044927064 shares for $49.14447397097902
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09598587087980649 shares for $52.69528325430497
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.174860422392223 shares for $100.842005593595
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17463810735127167 shares for $100.71379650947837
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 60th day, sold 0.09575609008732956 shares for $48.916998621112306
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 204th day, sold 0.17582727512007773 shares for $103.92095268697074
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 205th day, sold 0.08789508842245895 shares for $52.35119361530078
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 127th day, sold 0.09457337948514251 shares for $51.91983960354839
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.1647013436594728 shares for $97.99894649082292

[*********************100%***********************]  1 of 1 completed

On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 240th day, sold 0.08241848811525401 shares for $48.48020307915472
SPY Final Value: 102.23602927837382, Final Money: 102.23602927837382, Final Shares: 0.0

read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 34th day, Bought 0.0980872976949485 shares for $50.0
On the 60th day, sold 0.0980872976949485 shares for $50.10789602746445
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.19153335798089574 shares for $107.55172650701238
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 60th day, sold 0.09626306771144183 shares for $49.17598814039006
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.09598587087980649 shares for $53.89894607513774
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17825237578963055 shares for $101.56998624868937
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.19008403408366076 shares for $107.37086749249661
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1759511625304509 shares for $100.25873192147621
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 234th day, sold 0.1658128640371508 shares for $97.18291961217408
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 125th day, sold 0.09598587087980649 shares for $53.458370927799436
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 203th day, sold 0.1741397819054542 shares for $100.42641222487545
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 235th day, sold 0.08298066550493735 shares for $49.05402041324371
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 106.99705326246722, Final Money: 106.99705326246722, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 61th day, sold 0.09759906304899474 shares for $49.23384735506539
On the 68th day, Bought 0.09892958192358679 shares for $50.0
On the 74th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.09892958192358679 shares for $51.16539047505986
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.1899262858477388 shares for $105.4622680055324
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.08230994633391499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1652561971633775 shares for $96.85665715745556
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 61th day, sold 0.09759906304899474 shares for $49.23384735506539
On the 68th day, Bought 0.09892958192358679 shares for $50.0
On the 78th day, sold 0.09892958192358679 shares for $51.16539047505986
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.1899262858477388 shares for $105.56482819989019
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.09437879874664956 shares for $52.51991392653555
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17819761583805918 shares for $101.53878348068449
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 121th day, sold 0.09443940767603505 shares for $52.55364158355999
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.72203257818076, Final Money: 107.72203257818076, Final Shares: 0.0
read  251  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17798507725619608 shares for $106.00969186456295
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.166739304078092 shares for $97.75591919490378
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 176th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17726270862194415 shares for $105.57944188231616
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.166739304078092 shares for $97.75591919490378
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.1737968507348 shares for $103.96353814105002
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.166739304078092 shares for $97.75591919490378
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 206th day, sold 0.17228911804900965 shares for $103.0616275257371
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.166739304078092 shares for $98.56793960576408
On the 86th day, Bought 0.09432894389314418 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.18842710709699845 shares for $104.13612500822715
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.08349615082744685 shares for $49.358749561645205
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 235th day, sold 0.08608370779746224 shares for $50.8883838644698
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 235th day, sold 0.08608370779746224 shares for $50.8883838644698
SPY Final Value: 109.89103154813867, Final Money: 109.89103154813867, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.5710370031978073 shares for $53.140703517587944
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 118th day, sold 1.0875484034440523 shares for $95.87826724762765
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5514503143266791 shares for $47.1931179000772
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0875484034440523 shares for $98.87990084113324
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0915254873792657 shares for $93.41275120991756
On the 31th day, Bought 0.5684402000909504 shares for $49.99999999999999
On the 60th day, sold 0.5684402000909504 shares for $51.114142792178264
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.524824183898394 shares for $44.91445365802456
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 133th day, sold 0.5433010974682169 shares for $49.706617407367155
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5214308061320263 shares for $44.62404838877881
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 134th day, sold 0.5433010974682169 shares for $49.5436270781267
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 134th day, sold 0.5472255663784612 shares for $49.901499398051875

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5614823133071308 shares for $50.02245929253229
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 0.5471656817684395 shares for $49.78660538411031
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.5567308762943993 shares for $49.90535575102996
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0766472958632796 shares for $91.59038545908919
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5614823133071308 shares for $49.764177428411
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5567308762943993 shares for $51.12459637011469
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.038176589484297 shares for $94.76475908812662
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0766472958632796 shares for $91.59038545908919
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0700493718811332 shares for $91.02910006592799
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 126th day, sold 1.1197107302364473 shares for $101.80409959309779
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0903391163292153 shares for $92.75514862612634
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.1344998515349052 shares for $97.03377230178044
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.1344998515349052 shares for $97.03377230178044
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.1344998515349052 shares for $96.88628732108091
XLB Final Value: 100.30331485528697, Final Money: 100.30331485528697, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, Bought 0.0 shares for $0.0
On the 57th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0913564946715506 shares for $97.66549270815706
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5663797009515179 shares for $50.033982782057095
On the 119th day, Bought 0.5730002292000916 shares for $50.0
On the 121th day, sold 0.5730002292000916 shares for $51.36374054549621
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 166th day, Bought 0.5394325169921242 shares for $49.99999999999999
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 1.0642567008905184 shares for $100.8276798423677
On the 201th day, Bought 0.5368839256952647 shares for $49.99999999999999
On the 210th day, sold 0.5368839256952647 shares for $49.35037044990873
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 216th day, Bought 0.5314061005420342 shares for $50.0
On the 218th day, sold 1.0657654037375028 shares for $100.5549658426334
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 226th day, sold 1.0643081826903797 shares for $97.799278907419
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 241th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.5515719801434087 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0901329452446582 shares for $97.55599726994446
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5659950192438307 shares for $49.30382612633009
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 163th day, sold 0.5614823133071308 shares for $50.98259404828748
On the 166th day, Bought 0.5394325169921242 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5394325169921242 shares for $51.10583665983385
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5295488244016098 shares for $48.66024147426392
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 241th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.5515719801434087 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0901329452446582 shares for $97.55599726994446
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5659950192438307 shares for $49.30382612633009
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 166th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5614823133071308 shares for $53.19483436271757
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 197th day, sold 0.5614823133071308 shares for $53.19483436271757
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 233th day, sold 0.5347593582887701 shares for $45.69518716577541
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 233th day, sold 0.5347593582887701 shares for $45.69518716577541

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  251  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5619871866921434 shares for $49.80892435652467
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.0966471303772733 shares for $106.47346988832948
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 202th day, sold 1.0523015578016246 shares for $98.43228771676397
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.1101022695116123 shares for $94.29208677231634
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5451968160505943 shares for $52.8404754116236
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5653550429669832 shares for $48.02125734961555
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5253756435851634 shares for $44.62540716612378
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.0554195515497262 shares for $89.64733670863374
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.529380624669137 shares for $44.362096347273685
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.0945437591716636 shares for $91.07698620067411
On the 236th day, Bought 0.5877512636652169 shares for $50.0
On the 242th day, sold 0.5877512636652169 shares for $48.906782649582695
XLB Final Value: 99.76049331761979, Final Money: 99.76049331761979, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.1361734946930764 shares for $109.22035804484543
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.0969123538573196 shares for $99.08409292393168
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1014041492712865 shares for $93.77354926895734
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5389673385792821 shares for $48.72264740756711
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.1361734946930764 shares for $108.19780189962167
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.067180811577654 shares for $95.91821134459954
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.094935722669386 shares for $98.90554382872564
On the 154th day, Bought 0.5534034311012729 shares for $50.0
On the 155th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 163th day, sold 1.1103823772971066 shares for $94.53795560307566
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 190th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5542622769094336 shares for $46.18113291209401
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5670863105364636 shares for $54.003629352387435
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.067180811577654 shares for $96.41978632604103
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 118th day, Bought 0.5583472920156337 shares for $50.0
On the 131th day, sold 1.1046162748627877 shares for $101.51423565989019
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.109386069515185 shares for $92.4340473120052
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.0679201308875026 shares for $96.90307267673198
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.110563397340035 shares for $92.53214226637171
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 137th day, sold 0.5343022013250694 shares for $47.232314597136146
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 235th day, sold 1.1137718192470587 shares for $93.71276087144751
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 38th day, Bought 0.5621767483696875 shares for $50.0
On the 62th day, sold 0.5621767483696875 shares for $53.0694850460985

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 103.45195330040414, Final Money: 103.45195330040414, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5737893045673629 shares for $54.64195547394997
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0679201308875026 shares for $96.92443107934974
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1316215290067495 shares for $104.32418875913224
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 158th day, Bought 0.5617346365576901 shares for $49.99999999999999
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1255596252811904 shares for $98.8241350996885
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.117517062787762 shares for $93.11152167147632
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5737893045673629 shares for $54.64195547394997
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0679201308875026 shares for $96.92443107934974
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 1.122862627773371 shares for $103.51670565442708
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.117517062787762 shares for $94.02788566296229
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 177th day, sold 0.5736576411197798 shares for $50.36714089031666
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.117517062787762 shares for $94.02788566296229
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.117517062787762 shares for $94.02788566296229
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 235th day, sold 1.1297548743332761 shares for $95.05757512640186
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 235th day, sold 1.1297548743332761 shares for $95.05757512640186

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 63th day, sold 0.5201289919900135 shares for $48.959742016019966
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5201831044527674 shares for $48.14814814814815
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5299417064122947 shares for $48.91891891891892
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 111th day, sold 0.5636978579481398 shares for $51.06538895152198
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 161th day, sold 0.5489679402722881 shares for $47.21673254281951
On the 168th day, Bought 0.5698655117392296 shares for $50.0
On the 171th day, sold 0.5698655117392296 shares for $50.58126282197402
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5387350501023597 shares for $50.50641094709622
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 226th day, sold 0.5208875924575477 shares for $47.33305552661736
On the 239th day, Bought 0.5912961210974456 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 68th day, Bought 0.5198045534878886 shares for $50.0
On the 74th day, sold 0.5198045534878886 shares for $48.113109470838964
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.5299417064122947 shares for $48.00741918388977
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 161th day, sold 0.5489679402722881 shares for $47.21673254281951
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5389673385792821 shares for $50.5281879918077
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 103th day, Bought 0.0 shares for $0.0
On the 111th day, sold 1.062820316664879 shares for $96.2808924866714
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5482456140350876 shares for $51.200657894736835
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 163th day, sold 0.5489679402722881 shares for $46.73913043478261
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5567928730512249 shares for $52.19933184855234
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 126th day, sold 0.5328786102525844 shares for $49.76553341148886
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5567928730512249 shares for $52.19933184855234
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 126th day, sold 0.5328786102525844 shares for $49.76553341148886
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.5567928730512249 shares for $46.391982182628055
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 234th day, sold 0.5569789461958338 shares for $46.40748579703686

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 101.9648652600412, Final Money: 101.9648652600412, Final Shares: 0.0
read  251  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 1.0409737632567437 shares for $96.3525315270442
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5328786102525844 shares for $48.36406266652457
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5387350501023597 shares for $50.50641094709622
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 235th day, sold 0.5948839976204641 shares for $50.05353955978585
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 74th day, sold 0.5222477543346564 shares for $48.3392521412158
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.5328786102525844 shares for $47.90045827560481
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 219th day, sold 0.5387350501023597 shares for $51.24447796573646
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 236th day, sold 0.5948839976204641 shares for $49.92861392028556
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 74th day, sold 0.5222477543346564 shares for $48.3392521412158
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.5328786102525844 shares for $47.90045827560481
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5387350501023597 shares for $48.62083827173796
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 236th day, sold 0.5948839976204641 shares for $49.92861392028556
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 96th day, sold 0.5336179295624333 shares for $47.96691568836712
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5387350501023597 shares for $45.59853464066372
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 237th day, sold 0.5389673385792821 shares for $45.61819553735044
XLE Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 80th day, Bought 1.1953143676786995 shares for $50.0
On the 88th day, Bought 1.0 shares for $41.94
On the 98th day, sold 2.1953143676786997 shares for $90.64453024145351
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 2.2068549360366885 shares for $95.53475018102824
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2812835348939844 shares for $105.5778019948936
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 238th day, sold 2.015524105733302 shares for $98.98238883256246
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 101th day, sold 1.200192030724916 shares for $49.02784445511283
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 2.2068549360366885 shares for $95.53475018102824
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.2812835348939844 shares for $106.558753914898
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 239th day, sold 1.0092854259184498 shares for $49.20266451352443
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 101th day, sold 1.1853959222380275 shares for $48.42342342342342
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 1.0 shares for $41.91
On the 127th day, sold 2.1976047904191613 shares for $94.16736526946107
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.2379022564825797 shares for $110.88805680871182
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 130th day, sold 2.3830007126571893 shares for $101.46817034494312

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 111.56884550159631, Final Money: 111.56884550159631, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 57th day, sold 2.2330456226880395 shares for $92.69372379778052
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.450479272554122 shares for $100.02856390565925
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4029855572570566 shares for $103.54464766220659
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2784403631861974 shares for $105.44622000825721
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.015524105733302 shares for $98.25680015449848
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 57th day, sold 1.2330456226880395 shares for $51.183723797780516
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.450479272554122 shares for $100.02856390565925
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4029855572570566 shares for $103.54464766220659
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.2784403631861974 shares for $112.89671999587607
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.015524105733302 shares for $97.30950382480383
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 96th day, sold 1.2330456226880395 shares for $50.78914919852034
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 1.1930326890956813 shares for $50.0
On the 128th day, sold 2.390637479514843 shares for $103.01256899229459
On the 191th day, Bought 1.0499790004199916 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.110424387482558 shares for $104.57152839976075
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 129th day, sold 1.2330456226880395 shares for $53.23057953144267
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 2.119543035865786 shares for $105.02335742714969
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 130th day, sold 1.2174336498660823 shares for $51.83832481129778
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 130th day, sold 1.2174336498660823 shares for $51.83832481129778
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 130th day, sold 1.200192030724916 shares for $51.10417666826692

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 114.96315918632624, Final Money: 114.96315918632624, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 123th day, sold 1.2388503468780971 shares for $53.27056491575818
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 188th day, sold 2.247196571777908 shares for $105.39351921638388
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 212th day, Bought 0.9996001599360256 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.25 shares for $12.385
On the 215th day, Bought 0.0 shares for $0.0
On the 235th day, sold 2.2558388397508775 shares for $109.43074211631506
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 124th day, sold 1.2388503468780971 shares for $53.87760158572845
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 189th day, sold 2.2379022564825797 shares for $106.25559913779287
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 235th day, sold 2.015524105733302 shares for $97.77307436912248
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 189th day, sold 1.121830827911151 shares for $53.26452770922145
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 2.17427920305722 shares for $107.73553451148523
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 204th day, sold 1.1138338159946535 shares for $55.190465582535076

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 113.0410277405496, Final Money: 113.0410277405496, Final Shares: 0.0
read  251  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 43th day, Bought 1.2174336498660823 shares for $50.0
On the 57th day, sold 1.2174336498660823 shares for $50.53567080594107
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 2.4688340557083066 shares for $101.59252139239682
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 2.4070285581525237 shares for $102.49127600613446
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 204th day, sold 2.2784403631861974 shares for $112.89671999587607
On the 210th day, Bought 0 shares for $0.0
On the 212th day, Bought 0 shares for $0.0
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 215th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 217th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 116th day, Bought 1.203369434416366 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 130th day, sold 2.4070285581525237 shares for $102.49127600613446
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 204th day, sold 2.2758364540624174 shares for $112.76769629879277
On the 212th day, Bought 0 shares for $0.0
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 215th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 131th day, sold 2.4044597264558503 shares for $102.76660870872304
On the 135th day, Bought 1.1431184270690442 shares for $49.99999999999999
On the 137th day, sold 1.1431184270690442 shares for $48.079561042524
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 190th day, Bought 0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 204th day, sold 1.1397310234784592 shares for $56.47367221335765
On the 212th day, Bought 0 shares for $0.0
On the 213th day, Bought 0 shares for $0.0
On the 214th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 78th day, Bought 1.2088974854932302 shares for $50.0
On the 92th day, sold 1.2088974854932302 shares for $49.347195357833655
On the 190th day, Bought 0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 212th day, Bought 0 shares for $0.0
On the 213th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 79th day, Bought 1.1999040076793857 shares for $50.0
On the 92th day, sold 1.1999040076793857 shares for $48.98008159347252
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
XLF Final Value: 115.59574924287242, Final Money: 115.59574924287242, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 220th day, Bought 0.34724633655114934 shares for $49.99999999999999
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.6977545734947175 shares for $92.8850888236168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 98th day, sold 0.7991369435960733 shares for $97.65453450744016
On the 123th day, Bought 0.39977612536979296 shares for $50.0
On the 127th day, sold 0.39977612536979296 shares for $49.92004477492605
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 236th day, sold 0.7105312176540179 shares for $94.58591569410287
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 57th day, sold 0.4132231404958678 shares for $51.71900826446281
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.7991369435960733 shares for $100.8031340652087
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7807623283395755 shares for $110.42321609706616
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 57th day, sold 0.4132231404958678 shares for $51.71900826446281
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.7966308196124732 shares for $100.48701158591737
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 204th day, sold 0.38675742574257427 shares for $54.69910272277228
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 131th day, sold 0.39701445132602825 shares for $49.30125456566619

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 112.94535842673767, Final Money: 112.94535842673767, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7973563487023718 shares for $96.63958946272747
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4102732419791581 shares for $51.92007877246245
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 238th day, sold 0.7303689539425081 shares for $98.05933575632113
On the 33th day, Bought 0.41335978835978837 shares for $50.0
On the 55th day, sold 0.41335978835978837 shares for $51.94692460317461
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8272044433900118 shares for $103.86378991204988
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 239th day, sold 0.3668647736444347 shares for $48.88839973585736
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7807623283395755 shares for $110.42321609706616
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.390625 shares for $55.24609375
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.3995205753096284 shares for $48.741510187774665

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 114.39920747208389, Final Money: 114.39920747208389, Final Shares: 0.0
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 100th day, Bought 0.4074647542987532 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.4074647542987532 shares for $50.96161682014505
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.38675742574257427 shares for $51.50835396039604
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 180th day, Bought 0.3715538381511481 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.7407209970406934 shares for $102.35282737108302
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 235th day, sold 0.7053194773636646 shares for $94.3858524608056
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.40913182227313644 shares for $50.0
On the 46th day, sold 0.40913182227313644 shares for $51.22739546681941
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 118th day, Bought 0.4119634176485128 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.4119634176485128 shares for $51.524264645299496
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 235th day, sold 0.35481124042009654 shares for $47.480840193017315
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.37947783849423194 shares for $50.0
On the 42th day, Bought 0.4102395799146702 shares for $50.0
On the 46th day, sold 0.4102395799146702 shares for $51.36609780111585
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7983397032568902 shares for $97.42139398843831
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.37947783849423194 shares for $50.0
On the 42th day, Bought 0.4102395799146702 shares for $50.0
On the 46th day, sold 0.4102395799146702 shares for $51.36609780111585
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7983397032568902 shares for $98.60293674925852
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 205th day, sold 0.3871767074492799 shares for $54.42930153321977
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.37947783849423194 shares for $50.0
On the 42th day, Bought 0.4102395799146702 shares for $50.0
On the 47th day, sold 0.4102395799146702 shares for $51.03380374138497
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 94th day, sold 0.7976729342068497 shares for $98.52058410388801
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 105.0658488776814, Final Money: 4.398336083594131, Final Shares: 0.7584954249102417
read  251  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 72th day, sold 0.4119294776734223 shares for $50.05767012687428
On the 77th day, Bought 0.40209087253719344 shares for $50.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8041817450743869 shares for $97.4668275030157
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.41044163519947463 shares for $51.77310786406173
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 228th day, Bought 0.3605422555523507 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.7110504924959189 shares for $93.80178097006161
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 77th day, Bought 0.40209087253719344 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.40209087253719344 shares for $48.73341375150785
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.41473125414731254 shares for $52.214664897146655
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 230th day, Bought 0.3638215818962381 shares for $50.0
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.7273257621943114 shares for $95.94881454867355
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.4062728528479727 shares for $49.24839522223125
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.40209087253719344 shares for $48.73341375150785
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 130th day, sold 0.4137702747434624 shares for $50.97236014564713
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.390625 shares for $55.50390625
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 240th day, sold 0.3668647736444347 shares for $48.39680093917382
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 92th day, sold 0.3994886545222116 shares for $48.418024928092045
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 206th day, sold 0.3681885125184094 shares for $52.31590574374079
On the 232th day, Bought 0.3668647736444347 shares for $50.0
XLI Final Value: 107.2892533546627, Final Money: 107.2892533546627, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 61th day, sold 0.24321432045918862 shares for $49.01254985893569
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44852140323780454 shares for $101.76502118062547
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4340538421757886 shares for $100.91317776744908
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 61th day, sold 0.24321432045918862 shares for $49.01254985893569
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.24211902571304053 shares for $54.32182460897778
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44873755024886464 shares for $101.81406277596489
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.4280507457786669 shares for $101.00285397393425
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 65th day, sold 0.24077819512664933 shares for $46.3570259077338
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.23999232024575212 shares for $53.84467697033695
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44656903590256103 shares for $101.32204855593207
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.44301649220077255 shares for $103.37789845505027
On the 52th day, Bought 0.24173274028234384 shares for $50.0
On the 125th day, sold 0.24173274028234384 shares for $54.235157609746665
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 177th day, Bought 0.22147413182140327 shares for $50.0
On the 205th day, sold 0.4435976324877738 shares for $105.31894990524725
On the 84th day, Bought 0.23552687361627964 shares for $50.0
On the 125th day, sold 0.23552687361627964 shares for $52.8428093645485

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 109.55410751499392, Final Money: 109.55410751499392, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 62th day, sold 0.23819732266209329 shares for $48.05869182030394
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4266667367659256 shares for $95.72694906080307
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22295549808258272 shares for $49.921965575671095
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 65th day, sold 0.23819732266209329 shares for $45.86013053213282
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2132468972576449 shares for $47.84833880667036
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22693232877955793 shares for $50.7738392411383
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.21718356354791069 shares for $48.59265050820954
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 111th day, sold 0.24077819512664933 shares for $54.473658865453146
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.21718356354791069 shares for $49.276778733385456
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 100.57139828369147, Final Money: 100.57139828369147, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 63th day, sold 0.23955538520505942 shares for $47.63558834802606
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, sold 0.23999232024575212 shares for $50.835173274455215
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, sold 0.2323528044983503 shares for $52.28867512430875
On the 125th day, Bought 0.22285612408628988 shares for $50.0
On the 127th day, sold 0.22285612408628988 shares for $49.22223212693885
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 239th day, sold 0.4325395099691013 shares for $102.72380822256187
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 63th day, sold 0.2400729821865847 shares for $47.73851250780237
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 85th day, sold 0.23999232024575212 shares for $50.835173274455215
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, sold 0.2323528044983503 shares for $52.28867512430875
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 63th day, sold 0.2400729821865847 shares for $47.73851250780237
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.4508200898496105 shares for $100.86648690295185
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 64th day, sold 0.2400729821865847 shares for $47.193546838238824
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22609088853719195 shares for $50.58557540131133
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 64th day, sold 0.2400729821865847 shares for $47.193546838238824
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22609088853719195 shares for $50.58557540131133
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 64th day, sold 0.2400729821865847 shares for $47.193546838238824
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 202th day, sold 0.22472920131241853 shares for $50.280911501640524
On the 52th day, Bought 0.24173274028234384 shares for $50.0
On the 64th day, sold 0.24173274028234384 shares for $47.51982208470316

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 103.3294879486534, Final Money: 103.3294879486534, Final Shares: 0.0
read  251  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.43762033266453315 shares for $98.19325024326794
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.45094085562377617 shares for $100.97016698271972
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 234th day, sold 0.4340538421757886 shares for $100.91317776744908
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.23999232024575212 shares for $53.84947681674186
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.23999232024575212 shares for $53.84947681674186
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 201th day, sold 0.2229654403567447 shares for $49.92419175027871
XLK Final Value: 103.39667852755369, Final Money: 103.39667852755369, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.3424622931916024 shares for $99.7852222529318
On the 85th day, Bought 0.6393044367727913 shares for $50.0
On the 97th day, sold 0.6393044367727913 shares for $49.74427822529089
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.6455777921239509 shares for $50.26468689477082
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6117704637220115 shares for $49.443288878012964
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 219th day, sold 0.6232859636000997 shares for $51.60807778608825
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 226th day, Bought 0.60790273556231 shares for $50.0
On the 231th day, sold 1.2148461684343663 shares for $99.14359580592864
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2127093528495516 shares for $98.01116989730075
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, sold 0.6232859636000997 shares for $50.77910745450012
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 61th day, sold 0.6693440428380187 shares for $48.91566265060241
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6065752759917505 shares for $49.02341380565328
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.6232859636000997 shares for $50.006232859636
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 61th day, sold 0.6637461834594451 shares for $48.50657108721625
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6238303181534622 shares for $50.417966313162815
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 207th day, sold 0.6221226825930073 shares for $50.10576085604081
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 207th day, sold 0.6221226825930073 shares for $50.10576085604081
XLP Final Value: 100.91505344278146, Final Money: 100.91505344278146, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 94th day, Bought 0.6464959917248513 shares for $50.0
On the 96th day, sold 0.6464959917248513 shares for $50.4137574347039
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.2964676982471979 shares for $101.24116255612368
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 191th day, Bought 0.6079766536964981 shares for $50.0
On the 192th day, Bought 0.6131207847946045 shares for $50.0
On the 205th day, sold 1.2210974384911026 shares for $97.50463046351454
On the 215th day, Bought 0.6165988407941793 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.6165988407941793 shares for $48.896288074978415
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 53th day, sold 0.6715916722632639 shares for $50.053727333781055
On the 94th day, Bought 0.6464959917248513 shares for $50.0
On the 97th day, sold 0.6464959917248513 shares for $50.30385311611068
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.2964676982471979 shares for $101.30598594103604
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 186th day, sold 1.2400059548577866 shares for $101.2340861545897
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2400059548577866 shares for $99.01447549539425
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 205th day, sold 1.2348803404304947 shares for $98.60519518337499
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 206th day, sold 0.6189650903689032 shares for $50.02475860361476
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.89765254551747, Final Money: 102.89765254551747, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 63th day, sold 0.6813845734532571 shares for $50.0
On the 73th day, Bought 0.6664889362836577 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.6664889362836577 shares for $51.54625433217809
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 1.2964676982471979 shares for $99.27053165478793
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 127th day, sold 1.2925201888412592 shares for $100.93290154661393
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 158th day, Bought 0.6017571308220002 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.207744283894355 shares for $98.39492680887311
On the 187th day, Bought 0.6099792607051361 shares for $50.00000000000001
On the 200th day, sold 0.6099792607051361 shares for $48.87153836769551
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6039376736320812 shares for $48.109675081531584
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 54th day, sold 0.6715014773032502 shares for $49.83212463067419
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 63th day, sold 0.6813845734532571 shares for $50.0
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 127th day, sold 0.6431695394906097 shares for $50.22510933882172
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 218th day, sold 0.6201165819174005 shares for $51.2402331638348
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.2108811065041376 shares for $96.4587889441196
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 127th day, sold 0.6446621970087674 shares for $50.34167096441465
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.595734540688669 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.1956865445283618 shares for $97.41258278272564
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6039376736320812 shares for $48.109675081531584
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 127th day, sold 0.6446621970087674 shares for $50.34167096441465
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.595734540688669 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.1956865445283618 shares for $97.41258278272564
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 182th day, sold 1.2469267115835687 shares for $100.57710855633064
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 182th day, sold 1.202216518414494 shares for $96.97078437531307

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.57710855633064, Final Money: 100.57710855633064, Final Shares: 0.0
read  251  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 42th day, sold 0.6715916722632639 shares for $50.67830758898589
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 95th day, sold 1.2824673952298562 shares for $99.14755432522018
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6443298969072165 shares for $49.90335051546392
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6227425582264291 shares for $51.46967243741437
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 184th day, sold 0.6033546518643659 shares for $49.20357185953903
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6065752759917505 shares for $49.91507946136115
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.600817111271329 shares for $47.879115597212206
On the 35th day, Bought 0.6599788806758183 shares for $50.0
On the 54th day, sold 0.6599788806758183 shares for $48.97703273495247
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6399590426212722 shares for $49.47523358505056
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6443298969072165 shares for $50.483247422680414
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6210408644888833 shares for $51.32902745000621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 95th day, sold 0.6399590426212722 shares for $49.47523358505056
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.227685713783603 shares for $101.95929852972823
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.642508352608584 shares for $50.34052942688255
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 185th day, sold 1.2244404796514319 shares for $99.41232254289976
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
XLP Final Value: 101.06896102203103, Final Money: 101.06896102203103, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6890405585234674 shares for $97.80930728240618
On the 79th day, Bought 0.34891835310537334 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.34891835310537334 shares for $50.491974877878576
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.34220792553555535 shares for $49.41824652658955
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.34055305816646236 shares for $46.76474594741861
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 112th day, Bought 0.34277096044423117 shares for $50.0
On the 118th day, sold 0.34277096044423117 shares for $49.44471104408034
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6814378665412981 shares for $97.59553124604471
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32324799586242564 shares for $47.85363330747349
On the 226th day, Bought 0.34554250172771256 shares for $50.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 56th day, sold 0.34300610550867805 shares for $48.967551622418874

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.30459928394382, Final Money: 99.30459928394382, Final Shares: 0.0
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6853774917644311 shares for $100.99037341148892
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.64628714820769 shares for $100.00647331365795
On the 196th day, Bought 0.33649639948852544 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.672495324291966 shares for $98.74248846578938
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.680342388781481 shares for $94.78530160503593
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 109th day, Bought 0.33992793527772114 shares for $50.0
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6809222747716855 shares for $100.68797677048914
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.33692722371967654 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6729261485231172 shares for $95.44784490651894
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3359989248034406 shares for $47.65808749412002
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.6735630619895059 shares for $95.60554101879046
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.6735630619895059 shares for $95.60554101879046
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, sold 0.6780012584497679 shares for $96.23549862436005
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 96.23549862436005, Final Money: 96.23549862436005, Final Shares: 0.0
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 59th day, Bought 0.35458478122119 shares for $50.0
On the 61th day, sold 0.35458478122119 shares for $49.15608822069357
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 74th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.3426300280956623 shares for $50.623586651134104
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 184th day, sold 0.6431285584952722 shares for $98.61733315966504
On the 192th day, Bought 0.33040375338663847 shares for $50.0
On the 194th day, sold 0.33040375338663847 shares for $49.69272450935043
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3406690740614567 shares for $48.32050146487702
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.34458993797381116 shares for $47.31909028256374
On the 237th day, Bought 0.3588860178007465 shares for $50.00000000000001
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.6858477175629567 shares for $101.33400026992685
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6412113233688959 shares for $98.00915077693573
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.3381805884342239 shares for $50.0
On the 205th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.6788496624956806 shares for $96.28803612838733
On the 237th day, Bought 0.3588860178007465 shares for $50.00000000000001
On the 238th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 93th day, sold 0.3538570417551309 shares for $50.116772823779186
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 180th day, Bought 0.32998944033790917 shares for $50.0
On the 188th day, sold 0.6502559020340404 shares for $99.39161462590307
On the 203th day, Bought 0.3381805884342239 shares for $50.0
On the 211th day, sold 0.3381805884342239 shares for $47.967534663510314
On the 237th day, Bought 0.3588860178007465 shares for $50.00000000000001
On the 238th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 93th day, sold 0.3538570417551309 shares for $50.116772823779186
On the 180th day, Bought 0.32998944033790917 shares for $50.0
On the 188th day, sold 0.32998944033790917 shares for $50.43888595564941
On the 237th day, Bought 0.3588860178007465 shares for $50.00000000000001

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.42645981302033, Final Money: 50.55565877942859, Final Shares: 0.3588860178007465
read  251  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.3538570417551309 shares for $50.116772823779186
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.32379225488926305 shares for $49.608211371584
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.33978933061501865 shares for $46.30648997621474
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 78th day, Bought 0.3519144144144144 shares for $50.0
On the 93th day, sold 0.3519144144144144 shares for $49.84163851351351
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 133th day, sold 0.34234851078397804 shares for $51.36939404313591
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.32379225488926305 shares for $49.608211371584
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32379225488926305 shares for $50.10361352156457
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32324799586242564 shares for $50.019394879751744
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 149th day, Bought 0.26996382484747045 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.26996382484747045 shares for $53.97926677825171
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.43407487791644056 shares for $99.3640803038524
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 109th day, sold 0.5599262165885086 shares for $101.593012737819
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.537833504425582 shares for $105.89403868635283
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 235th day, sold 0.43023815087518835 shares for $98.48581511683936
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.5599262165885086 shares for $106.04442615969764
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.49849274560048373 shares for $98.14823668127923
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 236th day, sold 0.43023815087518835 shares for $98.59767703606691
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 118th day, sold 0.5595040089152501 shares for $105.96446424845921
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.500089566712886 shares for $100.06292140358136
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 238th day, sold 0.21477663230240548 shares for $50.17182130584192
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 124th day, sold 0.5613270185372363 shares for $109.2903705091999
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 208th day, sold 0.500089566712886 shares for $108.2843938803412

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 117.57476438954112, Final Money: 117.57476438954112, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 72th day, sold 0.2897878752752985 shares for $50.89254665584792
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.2811041772080733 shares for $50.79833586327093
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 72th day, sold 0.2897878752752985 shares for $50.89254665584792
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5592375192127947 shares for $105.9755098908246
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5592375192127947 shares for $105.9755098908246
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.561060528834781 shares for $106.320970214191
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5265973015977643 shares for $105.993504865598
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 197th day, sold 0.25362686415745156 shares for $51.05001521761185

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 115.25110371462436, Final Money: 115.25110371462436, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 54th day, sold 0.2739425816348893 shares for $48.72068814376507
On the 58th day, Bought 0.2799708830281651 shares for $50.0
On the 59th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.2799708830281651 shares for $48.48255781398734
On the 68th day, Bought 0.2870428842069005 shares for $50.0
On the 72th day, sold 0.2870428842069005 shares for $50.410471324415866
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 123th day, Bought 0.26141057144350915 shares for $50.0
On the 129th day, sold 0.26141057144350915 shares for $49.41444031996654
On the 144th day, Bought 0.2808988764044944 shares for $50.0
On the 145th day, Bought 0.28240609997175936 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5633049763762538 shares for $112.71169272312461
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 54th day, sold 0.27625835681529365 shares for $49.13254875959997
On the 58th day, Bought 0.2799708830281651 shares for $50.0
On the 59th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.2799708830281651 shares for $48.48255781398734
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 144th day, Bought 0.2808988764044944 shares for $50.0
On the 145th day, Bought 0.28240609997175936 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5633049763762538 shares for $119.48261853916719
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 54th day, sold 0.27625835681529365 shares for $49.13254875959997
On the 59th day, Bought 0.2777314891962451 shares for $50.0
On the 62th day, sold 0.2777314891962451 shares for $48.09476198411376
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 117th day, sold 0.2798298634430266 shares for $52.97179314976494
On the 144th day, Bought 0.2808988764044944 shares for $50.0
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.5335900372676874 shares for $113.17978280484918
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.252691160863193 shares for $53.59832213069187
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 119.64137857145161, Final Money: 119.64137857145161, Final Shares: 0.0
read  251  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2702410550210788 shares for $49.019024970273485
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.2897878752752985 shares for $51.53877361771183
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5610292104393202 shares for $97.59664144802414
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28028476932563484 shares for $51.69852570211334
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.2631301968213872 shares for $49.86317229765288
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.2671939293539251 shares for $52.524982632394604
On the 192th day, Bought 0.25257627803596683 shares for $49.99999999999999
On the 193th day, Bought 0.2536011361330899 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5061774141690567 shares for $107.36529131939862
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.28123066539175434 shares for $52.81793126722538
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.5269611778992285 shares for $103.59002835143033
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.21510927551196007 shares for $50.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.2797985450475658 shares for $52.54896474538333
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.2814364516492176 shares for $52.85657998423956
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.25889297364469527 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5191063486121685 shares for $110.10764760412708
On the 100th day, Bought 0.28053638556920835 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.28053638556920835 shares for $52.68753857375302
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 212th day, sold 0.5196167472113125 shares for $111.93064351678882
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 127th day, sold 0.26452227277536766 shares for $49.6799280499418
XLY Final Value: 114.61818209054184, Final Money: 114.61818209054184, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5665395111523086 shares for $99.64757830439835
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.383509531094396 shares for $99.4189949044433
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.7169486664754804 shares for $50.26527100659593
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.3327280241967356 shares for $106.12513256678605
On the 197th day, Bought 0.6172077521293667 shares for $50.0
On the 199th day, sold 0.6172077521293667 shares for $48.814961115911615
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5656803264655523 shares for $99.59292556647378
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.3784824186438849 shares for $96.64540237112277
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6923289947382997 shares for $51.3846579894766
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6861534239055852 shares for $50.92630712227253
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 62th day, sold 0.7793017456359103 shares for $48.91677057356609
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6861534239055852 shares for $50.92630712227253
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 137th day, sold 0.6943480072212193 shares for $51.53450909595889

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 101.5345090959589, Final Money: 101.5345090959589, Final Shares: 0.0
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 68th day, sold 1.5442838507950172 shares for $103.06550420205944
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 92th day, sold 1.4024265352120677 shares for $98.88509499780291
On the 108th day, Bought 0.7205649228995532 shares for $50.0
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4375135893750337 shares for $100.78407775108361
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3389713616283672 shares for $107.22482663919963
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2469731416026284 shares for $94.84477715029593
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 53th day, sold 0.7843137254901961 shares for $51.05882352941176
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.772916988715412 shares for $50.0
On the 68th day, sold 1.5442838507950172 shares for $103.06550420205944
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 1.4031149151115476 shares for $100.86993124736917
On the 108th day, Bought 0.7205649228995532 shares for $50.0
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4375135893750337 shares for $100.78407775108361
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2469731416026284 shares for $95.36850586976902
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 96th day, sold 0.7803964413922273 shares for $56.07928827844545
On the 109th day, Bought 0.7169486664754804 shares for $50.0
On the 125th day, sold 0.7169486664754804 shares for $50.26527100659593
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3360068701989094 shares for $107.32143188307839
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 96th day, sold 0.7803964413922273 shares for $56.07928827844545
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3360068701989094 shares for $106.55990796706502
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 96th day, sold 0.7803964413922273 shares for $56.07928827844545
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 139th day, sold 0.7803964413922273 shares for $56.867488684251605
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 139th day, sold 0.7803964413922273 shares for $56.867488684251605

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 112.97670172286004, Final Money: 13.665991168119781, Final Shares: 1.2884108790184259
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 51th day, sold 0.7907638779060573 shares for $51.59734303337024
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 61th day, sold 0.7581501137225171 shares for $48.22592873388931
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6861534239055852 shares for $48.89529298751201
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 168th day, sold 0.6716818914562064 shares for $53.1166039763568
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2216852740530135 shares for $97.6248702495763
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6403688524590164 shares for $52.25409836065574
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 235th day, sold 0.6676458806249166 shares for $51.02817465616238
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 51th day, sold 0.7829627309740056 shares for $51.08831819605386
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 122th day, sold 1.3805014311268045 shares for $98.37453198209609
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.6128201985537443 shares for $48.970462066429704
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.6403688524590164 shares for $48.94339139344263
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 123th day, sold 0.6861534239055852 shares for $47.70824756415534
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.6128201985537443 shares for $46.83784777546268
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 123th day, sold 0.6943480072212193 shares for $48.27801694209138
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.6128201985537443 shares for $46.83784777546268
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.7268498328245384 shares for $50.0
On the 123th day, sold 0.7268498328245384 shares for $50.537868876290155
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.6553079947575361 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 103.91065517770284, Final Money: 2.742311997522762, Final Shares: 1.3125109390267264
read  251  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7554011179936546 shares for $54.93276930049856
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 131th day, sold 1.428063510802319 shares for $100.64991624134744
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.3487087648370697 shares for $103.90452324304786
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 186th day, Bought 0.6309148264984227 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 189th day, sold 1.26737103831105 shares for $104.19057305955141
On the 220th day, Bought 0.6029181237187989 shares for $50.0
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 63th day, sold 0.7803964413922273 shares for $50.007803964413924
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 94th day, sold 1.5006686690444817 shares for $109.1286256129147
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.428063510802319 shares for $102.09226038725778
On the 186th day, Bought 0.6309148264984227 shares for $50.0
On the 187th day, Bought 0.6230529595015576 shares for $50.0
On the 189th day, sold 1.2539677859999803 shares for $103.08869168705837
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 63th day, sold 0.7880220646178092 shares for $50.49645390070921
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 133th day, sold 0.7148984844152131 shares for $51.10809265084358
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 66th day, sold 0.7880220646178092 shares for $52.033096926713945
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 95th day, sold 0.7452675510508272 shares for $53.57728424504397
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 95th day, sold 0.7452675510508272 shares for $53.57728424504397
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
XLU Final Value: 110.44282971604841, Final Money: 14.31738165164478, Final Shares: 1.2470867678308721

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 38th day, sold 0.09858432903505658 shares for $50.94640955873654
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.19116072968642112 shares for $98.27955434638282
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1791071512121006 shares for $102.05704583216703
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.174860422392223 shares for $99.63721728331258
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17463810735127167 shares for $100.71379650947837
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09554748710108925 shares for $52.454614943626986
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 204th day, sold 0.08789508842245895 shares for $51.94951306121013
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 60th day, sold 0.09636882275846118 shares for $49.230013106159895
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 235th day, sold 0.08228285554421881 shares for $48.64151005496495

[*********************100%***********************]  1 of 1 completed

On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 236th day, sold 0.08241848811525401 shares for $49.01345069726041
SPY Final Value: 101.59084391644146, Final Money: 101.59084391644146, Final Shares: 0.0

read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.19153335798089574 shares for $107.55172650701238
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09598587087980649 shares for $53.458370927799436
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1791071512121006 shares for $102.05704583216703
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1759511625304509 shares for $101.47103543131104
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1658128640371508 shares for $98.02027457556169
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 61th day, sold 0.09636882275846118 shares for $48.61325264050574
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.08805607410799196 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.1759511625304509 shares for $103.9941751019977
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.25096172256143, Final Money: 107.25096172256143, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.19116072968642112 shares for $96.43103009031513
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09554748710108925 shares for $53.107204280527434
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 211th day, Bought 0.08536064874093043 shares for $50.0
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.16830689957039294 shares for $98.64467383820731
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.09506426344208685 shares for $52.90136132025249
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1791071512121006 shares for $102.27734762815793
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.09506426344208685 shares for $52.90136132025249
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 201th day, sold 0.08714445064138315 shares for $49.76296709425543
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09443940767603505 shares for $52.38081746751284
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 202th day, sold 0.08714445064138315 shares for $49.65577941996653

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 104.32276516547074, Final Money: 104.32276516547074, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17798507725619608 shares for $102.54254255961224
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17243352818983582 shares for $102.7031337251481
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.166739304078092 shares for $99.15819674220054
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 61th day, sold 0.09749439407234084 shares for $49.18104708979234
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17825237578963055 shares for $102.69654126367985
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17202832508608146 shares for $102.46179070452098
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17202832508608146 shares for $102.90562378324307
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.1664768163323842 shares for $100.10916873331593
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.18867154268899677 shares for $104.27121478250095
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 240th day, sold 0.1664768163323842 shares for $97.92499290303505
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.09436989222958307 shares for $50.0
On the 127th day, sold 0.1884680554334373 shares for $103.46707775240274
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 127th day, sold 0.09409816320385425 shares for $51.65895061728395
SPY Final Value: 106.76577908763636, Final Money: 106.76577908763636, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.0915254873792657 shares for $98.92495492118285
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, sold 0.5685048322910744 shares for $48.055713473564516
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0875484034440523 shares for $98.87990084113324
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.0508631107789832 shares for $95.23972372989924
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0875484034440523 shares for $98.87990084113324
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.0508631107789832 shares for $95.23972372989924
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.524824183898394 shares for $44.91445365802456
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 192th day, Bought 0.5161023947151115 shares for $50.00000000000001
On the 235th day, sold 0.5161023947151115 shares for $44.16804293971924

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 55th day, sold 1.0871888974428363 shares for $100.85851401577192
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1197107302364473 shares for $100.37086985839514
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.078769803289314 shares for $92.32111976549949
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 0.5471656817684395 shares for $49.78660538411031
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0554195515497262 shares for $96.33869666545901
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0788882080003819 shares for $92.33125284067268
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0820620903793516 shares for $92.60287369466491
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0651140437198174 shares for $90.60925169924487
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0945437591716636 shares for $93.11283759273341
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1201985319490242 shares for $95.29528911290348
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 236th day, sold 1.1201985319490242 shares for $95.29528911290348
XLB Final Value: 97.99112738845315, Final Money: 97.99112738845315, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, Bought 0.0 shares for $0.0
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0858136571165995 shares for $97.16946417536448
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 69th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.5663797009515179 shares for $51.38196647032171
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.541829215431296 shares for $49.003034243606415
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.5567308762943993 shares for $49.16490368555841
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 173th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.052751541094044 shares for $98.91653480119636
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5295488244016098 shares for $48.66024147426392
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 69th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 193th day, Bought 0.5208875924575477 shares for $50.0
On the 196th day, sold 1.042318398589574 shares for $97.93623673147637
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5295488244016098 shares for $48.66024147426392
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 196th day, sold 0.5214308061320263 shares for $48.99363854416519
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5295488244016098 shares for $48.16246557932641
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 197th day, sold 0.5443065534509035 shares for $51.5676028739386
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5619871866921434 shares for $49.80892435652467
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5425935973955507 shares for $49.38144329896907
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 163th day, sold 0.5514503143266791 shares for $50.07168854086246
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.0691805544395634 shares for $103.80674003053721
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 1.0938814610365155 shares for $91.66726643486
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 175th day, sold 0.5357334190506804 shares for $52.01435765563056
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0547562682543004 shares for $96.27815216625254
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.0938814610365155 shares for $91.02187637284845
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0547562682543004 shares for $98.69354402055488
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.1257047011536918 shares for $93.66988818299869
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 0.529380624669137 shares for $49.809422975119105
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 47th day, Bought 0.536135535063264 shares for $50.0
On the 53th day, sold 0.536135535063264 shares for $52.05876045464293
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.066042591472773 shares for $95.82656854748755
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.548666739822232 shares for $49.56106660814222
On the 154th day, Bought 0.5534034311012729 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 0.5534034311012729 shares for $47.11676812396237
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5534646889528448 shares for $50.03320788133718
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.5325948018747337 shares for $50.0
On the 97th day, sold 0.5325948018747337 shares for $47.86962079250107
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 129th day, sold 0.548666739822232 shares for $49.56106660814222
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5534646889528448 shares for $50.03320788133718
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5534646889528448 shares for $46.45229134381227
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 135th day, sold 0.5549389567147615 shares for $51.72586015538291
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108956313651387 shares for $93.07470340476091
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5551237926057512 shares for $46.5915399134007
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 97.74921748204554, Final Money: 7.105427357601002e-15, Final Shares: 1.117517062787762
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 65th day, Bought 0.5264820469621986 shares for $50.0
On the 66th day, sold 0.5264820469621986 shares for $50.326418869116566
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 73th day, sold 1.0409737632567437 shares for $95.80081543251812
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5343022013250694 shares for $48.4932677922633
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5636978579481398 shares for $50.924464487034946
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 190th day, sold 0.5490282200505107 shares for $49.76391786537829
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5569789461958338 shares for $51.871449259218
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5208875924575477 shares for $43.71809563496198
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 95th day, sold 0.5336179295624333 shares for $48.43116328708645
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.5636978579481398 shares for $51.967305524239
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5569789461958338 shares for $51.871449259218
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5242189138184106 shares for $44.36988886559027
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.5692167577413478 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 99.03026905829596, Final Money: 50.0, Final Shares: 0.5605381165919282
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 64th day, sold 0.5201289919900135 shares for $48.80890460834287
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5299417064122947 shares for $48.91891891891892
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 103th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5585344057193924 shares for $51.100312779267206
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5420641803989593 shares for $50.482437120555076
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, sold 1.0623663683226343 shares for $96.23976930634744
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5389673385792821 shares for $50.194028241888546
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5299417064122947 shares for $49.40116587175411
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5299417064122947 shares for $49.491255961844196
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 101.25528613901469, Final Money: 101.25528613901469, Final Shares: 0.0
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5187260089220873 shares for $48.013279385828405
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5339028296849972 shares for $49.759743726641744
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
XLE Final Value: 100.08400113381074, Final Money: 49.0274986822581, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 47th day, sold 1.228803145736053 shares for $50.70041779306955
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 2.276626291211212 shares for $101.28710369598681
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.132716457189094 shares for $99.46989556329935
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 237th day, sold 2.015524105733302 shares for $98.74052593987447
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 101th day, sold 1.200192030724916 shares for $49.02784445511283
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2604395236624435 shares for $100.092262107773
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.391777228919281 shares for $104.8076781712429
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.247196571777908 shares for $104.96655186774608
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.3830007126571893 shares for $104.42309122863803
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 1.1976047904191616 shares for $52.47904191616766

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 109.77423003898897, Final Money: 109.77423003898897, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 31th day, Bought 1.2410027302060065 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.2410027302060067 shares for $93.56186398610078
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4688340557083066 shares for $102.11097654409556
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.3972209132598525 shares for $103.29624915236705
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 185th day, sold 2.2379022564825797 shares for $102.11547996330012
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.2312238364934744 shares for $93.15359517360255
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 126th day, Bought 1.155001155001155 shares for $50.0
On the 128th day, sold 1.155001155001155 shares for $49.76899976899977
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 156th day, Bought 1.1035091591260207 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.216846945810501 shares for $103.74843706393143
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 60th day, sold 1.2330456226880395 shares for $49.395807644882865
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.0 shares for $41.07
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 2.2330456226880395 shares for $91.88982737361282
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 128th day, sold 1.2174336498660823 shares for $52.45921597272949

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 111.0175055627559, Final Money: 111.0175055627559, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 45th day, sold 2.2379301807378065 shares for $93.76927457291409
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4562839967441796 shares for $105.62021185999973
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 199th day, Bought 1.0608953957139826 shares for $50.0
On the 205th day, sold 1.0608953957139826 shares for $51.718650541056654
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 35th day, Bought 0.0 shares for $0.0
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.434057971873108 shares for $104.66449279054363
On the 167th day, Bought 1.1088933244621866 shares for $50.0
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.225213931740597 shares for $104.14001200545992
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 46th day, sold 1.2379301807378065 shares for $51.27506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.434057971873108 shares for $104.66449279054363
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.224231088111559 shares for $104.09401492362096
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 46th day, sold 1.2379301807378065 shares for $51.27506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 123th day, sold 2.434057971873108 shares for $104.66449279054363
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.224231088111559 shares for $104.09401492362096
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 188th day, sold 2.230154423273064 shares for $104.59424245150669

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 115.87693653317652, Final Money: 115.87693653317652, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4260697616889684 shares for $104.53934603117766
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.25 shares for $11.7875
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.3615453243694313 shares for $109.29231761181728
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.0058969467476304 shares for $97.78747615394698
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 1.1397310234784592 shares for $53.33941189879189
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 239th day, sold 2.029452284704046 shares for $98.93579887932225
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
XLF Final Value: 107.76194254503636, Final Money: 107.76194254503636, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.8002117420331725 shares for $97.3857690054371
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4049566696363489 shares for $50.84635943953997
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.782632814641483 shares for $104.73974958346969
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7053194773636646 shares for $93.89212882665103
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7959566428887224 shares for $96.86792343955752
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 236th day, sold 0.35481124042009654 shares for $47.232472324723254
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39013732833957554 shares for $52.2120786516854
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 127th day, sold 0.399616368286445 shares for $49.90009590792839
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 127th day, sold 0.39701445132602825 shares for $49.57519453708115

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 101.30588766253415, Final Money: 101.30588766253415, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8250044961264706 shares for $103.58756453363965
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7303689539425081 shares for $97.22671514882668
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.8250044961264706 shares for $103.58756453363965
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7807623283395755 shares for $109.75956811797754
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 74th day, sold 0.8293256196834445 shares for $101.11137955180556
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.3995205753096284 shares for $48.741510187774665
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.38711675441313104 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7740537610684475 shares for $108.81647773100235
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 74th day, sold 0.4132231404958678 shares for $50.3801652892562
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.3995205753096284 shares for $48.741510187774665
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.3995205753096284 shares for $48.741510187774665

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 114.19830987308089, Final Money: 114.19830987308089, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 46th day, sold 0.41145490454246214 shares for $51.51826859776168
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 102th day, Bought 0.40594300560201346 shares for $50.0
On the 123th day, sold 0.40594300560201346 shares for $50.77129171064382
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.38675742574257427 shares for $49.43533415841584
On the 165th day, Bought 0.38681726752282225 shares for $50.0
On the 171th day, sold 0.38681726752282225 shares for $51.51632368868947
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 178th day, Bought 0.36897645930189654 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.7381436181914418 shares for $100.23990335039781
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 234th day, sold 0.7053194773636646 shares for $93.29260727089192
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 46th day, sold 0.41145490454246214 shares for $51.51826859776168
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7976729342068497 shares for $97.34002816126187
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 205th day, sold 0.3691671588895452 shares for $51.89751919669227
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 47th day, sold 0.40997048212528703 shares for $51.000327976385705
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 93th day, sold 0.3981842796846381 shares for $48.590427649916386
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 47th day, sold 0.40997048212528703 shares for $51.000327976385705
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 47th day, sold 0.40997048212528703 shares for $51.000327976385705

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 103.32299069745252, Final Money: 53.01977662831972, Final Shares: 0.37901758641600974
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 47th day, sold 0.4132231404958678 shares for $51.404958677685954
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.818202330521395 shares for $99.16612245919308
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.8207148771786328 shares for $103.52497460731274
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7831204863019074 shares for $110.09107796432215
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 229th day, Bought 0.36287103563393575 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.7133792725775039 shares for $93.66669848942627
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.818202330521395 shares for $99.16612245919308
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.8250044961264706 shares for $104.066067141393
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7988815772796203 shares for $97.48751887543206
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3844083954793573 shares for $54.62058891366188
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 56th day, sold 0.41145490454246214 shares for $51.617017774851874
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 89th day, Bought 0.4037793749495276 shares for $50.0
On the 93th day, sold 0.8032680294717391 shares for $98.02279763643632
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 206th day, sold 0.3681885125184094 shares for $52.31590574374079
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 93th day, sold 0.3994886545222116 shares for $48.749600511345484
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 206th day, sold 0.3681885125184094 shares for $52.31590574374079
XLI Final Value: 113.25649054642608, Final Money: 64.56619778833671, Final Shares: 0.3668647736444347

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2216508555723025 shares for $49.62984307119425
On the 210th day, Bought 0.21319234213107066 shares for $50.0
On the 211th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21319234213107066 shares for $49.56508762205262
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 61th day, sold 0.24077819512664933 shares for $48.52162188192238
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 65th day, sold 0.23955538520505942 shares for $46.12159831353009
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.24211902571304053 shares for $56.52026536245218
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44301649220077255 shares for $99.19582276867499
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 234th day, sold 0.20888164765843673 shares for $48.56289426410996
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 124th day, sold 0.2400729821865847 shares for $56.04263696163633
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44301649220077255 shares for $99.12050996500085
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 234th day, sold 0.22005105184402782 shares for $51.15966904321803
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 125th day, sold 0.23940627244433804 shares for $53.713191285611686
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 125th day, sold 0.23470872647045016 shares for $52.6592498709102

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 105.16314692663718, Final Money: 105.16314692663718, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.4266667367659256 shares for $99.60108303063767
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.4568808203174535 shares for $102.22251473782704
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.429830156314737 shares for $101.42272368402534
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22693232877955793 shares for $50.7738392411383
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.21392204680614385 shares for $50.928421683138666
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.22700444928720603 shares for $51.505039498774174
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 92th day, Bought 0.23285055651283007 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23285055651283007 shares for $52.68010990546268
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.22700444928720603 shares for $51.505039498774174
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 111th day, sold 0.24077819512664933 shares for $54.473658865453146
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.4441880128351167 shares for $105.4591180073134
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 111th day, sold 0.23955538520505942 shares for $54.197010348792645
On the 198th day, Bought 0.21429795988342193 shares for $50.0
On the 205th day, sold 0.21429795988342193 shares for $50.87862163552203

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 109.93277687276655, Final Money: 109.93277687276655, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 37th day, Bought 0.2418028822903569 shares for $50.0
On the 62th day, sold 0.2418028822903569 shares for $48.78614953090241
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, sold 0.2323528044983503 shares for $52.28867512430875
On the 109th day, Bought 0.22479992806402302 shares for $50.0
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4441558989335501 shares for $99.65970060270998
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44934504106442896 shares for $100.61284814473629
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 224th day, sold 0.21861746316295744 shares for $52.44851558742512
On the 37th day, Bought 0.2418028822903569 shares for $50.0
On the 63th day, sold 0.2418028822903569 shares for $48.08250314343747
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 109th day, Bought 0.22479992806402302 shares for $50.0
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 126th day, sold 0.4441558989335501 shares for $99.65970060270998
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44934504106442896 shares for $100.61284814473629
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 234th day, sold 0.21861746316295744 shares for $50.82637401075598
On the 37th day, Bought 0.2418028822903569 shares for $50.0
On the 63th day, sold 0.2418028822903569 shares for $48.08250314343747
On the 109th day, Bought 0.22479992806402302 shares for $50.0
On the 126th day, sold 0.22479992806402302 shares for $50.44060785900548
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 40th day, Bought 0.23948654085640386 shares for $50.0
On the 63th day, sold 0.23948654085640386 shares for $47.62189864929591
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.22609088853719195 shares for $53.61971512548044
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 206th day, sold 0.22609088853719195 shares for $53.61971512548044
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 103.79588899008255, Final Money: 103.79588899008255, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 161th day, Bought 0.2451941938014908 shares for $50.0
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4728808968980299 shares for $105.88276162443788
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.21632847315363649 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.43246991611390967 shares for $101.4012212312284
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 168th day, Bought 0.228133412419583 shares for $50.0
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4583677910169952 shares for $102.63313208661539
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 62th day, sold 0.2415692337423906 shares for $48.739008599864725
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 202th day, sold 0.44656903590256103 shares for $99.915356092839
On the 84th day, Bought 0.23552687361627964 shares for $50.0
On the 127th day, sold 0.23552687361627964 shares for $52.02082057562768
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.44656903590256103 shares for $104.20688452786261
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 204th day, sold 0.2229654403567447 shares for $52.028985507246375
XLK Final Value: 107.55738487354886, Final Money: 107.55738487354886, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.3424622931916024 shares for $99.7852222529318
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 120th day, Bought 0.6459948320413437 shares for $50.00000000000001
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6459948320413437 shares for $50.2906976744186
On the 187th day, Bought 0.6099792607051361 shares for $50.00000000000001
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6099792607051361 shares for $49.29852385018909
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 233th day, sold 0.6069434328720563 shares for $48.695071619325084
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 85th day, Bought 0.6393044367727913 shares for $50.0
On the 96th day, sold 0.6393044367727913 shares for $49.85295997954226
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.606134076857801 shares for $48.98775609164747
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 56th day, sold 0.6693440428380187 shares for $49.67871485943775
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6238303181534622 shares for $50.417966313162815
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 56th day, sold 0.6693440428380187 shares for $49.67871485943775
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 70th day, sold 0.6693440428380187 shares for $50.595716198125835
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 70th day, sold 0.6637461834594451 shares for $50.17257400769946
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 0.6493506493506493 shares for $51.01948051948052
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.23381676808613, Final Money: 102.23381676808613, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 70th day, Bought 0.6614631565021828 shares for $50.0
On the 73th day, sold 0.6614631565021828 shares for $49.62296600079375
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3027624078912101 shares for $101.7327164322246
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 205th day, sold 0.6221226825930073 shares for $49.67649620505163
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2110226334153902 shares for $96.03409482984044
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 70th day, Bought 0.6614631565021828 shares for $50.0
On the 86th day, sold 0.6614631565021828 shares for $51.37584336552454
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3015780808355715 shares for $101.64023233244978
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 152th day, Bought 0.6109481915933529 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2236182075227733 shares for $99.34556226877396
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 53th day, sold 0.6693440428380187 shares for $49.88621151271754
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6459113809585325 shares for $50.47151530809973
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 0.60960741282614 shares for $48.67715191416727
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 138th day, sold 0.6459113809585325 shares for $50.18731430047798
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 0.60960741282614 shares for $48.67715191416727
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 207th day, sold 0.60960741282614 shares for $49.09778102901731

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.2047344413555, Final Money: 100.2047344413555, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 62th day, sold 0.6813845734532571 shares for $49.81602616516763
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 93th day, sold 0.6377551020408163 shares for $48.56505102040816
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6455777921239509 shares for $50.58102001291155
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6069434328720563 shares for $48.349113862588005
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 54th day, sold 0.6693440428380187 shares for $49.67202141900937
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 164th day, Bought 0.6036460219727152 shares for $50.0
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2035980258124082 shares for $98.0571311629369
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 228th day, Bought 0.6096817461285209 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6096817461285209 shares for $48.56724789659797
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 54th day, sold 0.6637461834594451 shares for $49.25660427452542
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 164th day, Bought 0.6036460219727152 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6036460219727152 shares for $49.17904141011711
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 149th day, sold 0.6446621970087674 shares for $52.33367715317174
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2033066557040586 shares for $98.03339324020965
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 149th day, sold 0.6446621970087674 shares for $52.33367715317174
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2033066557040586 shares for $98.03339324020965
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 149th day, sold 0.6446621970087674 shares for $52.33367715317174

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.33367715317175, Final Money: 102.33367715317175, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 42th day, sold 0.6693440428380187 shares for $50.508701472556886
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.3027624078912101 shares for $102.57951199735388
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 161th day, sold 1.227685713783603 shares for $101.88563738690121
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.215885536776542 shares for $100.05522082134165
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2062079794997167 shares for $96.12271388633242
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 54th day, sold 0.6637461834594451 shares for $49.25660427452542
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 170th day, sold 1.227685713783603 shares for $101.4682242442148
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 171th day, sold 0.6117704637220115 shares for $50.80753701211305
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
XLP Final Value: 102.69262816203971, Final Money: 102.69262816203971, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 78th day, Bought 0.3519144144144144 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3519144144144144 shares for $50.92553490990991
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.34220792553555535 shares for $49.03839572924508
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34055305816646236 shares for $46.996322026971804
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6827130702820167 shares for $96.91112032653226
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.321646831778707 shares for $47.61659697651978
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.321316110789795 shares for $47.56763704132125
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 83th day, Bought 0.34199726402188785 shares for $50.0
On the 96th day, sold 0.34199726402188785 shares for $49.63406292749658
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 55th day, sold 0.34300610550867805 shares for $49.12533443095287
On the 48th day, Bought 0.34300610550867805 shares for $50.0
On the 55th day, sold 0.34300610550867805 shares for $49.12533443095287

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.12533443095288, Final Money: 99.12533443095288, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6818288784824503 shares for $100.82203626119993
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.6446859841239713 shares for $99.21072609683793
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.3391900142459806 shares for $47.255952784750015
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 109th day, Bought 0.33992793527772114 shares for $50.0
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 127th day, sold 0.6809222747716855 shares for $100.68797677048914
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3375641371860653 shares for $49.56454226302998
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 127th day, sold 0.3409943394939644 shares for $50.422832980972515
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.31806615776081426 shares for $50.0
On the 189th day, sold 0.6383326194569454 shares for $97.84362391036059
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3375641371860653 shares for $49.56454226302998
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 98.76535741990541, Final Money: 98.76535741990541, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, sold 0.6838510315018442 shares for $100.16366058407512
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7086447783151835 shares for $100.31575481829738
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6858477175629567 shares for $101.6906410830596
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 183th day, sold 0.6422609724625596 shares for $97.48879301009192
On the 190th day, Bought 0.32810551873482513 shares for $50.0
On the 193th day, sold 0.32810551873482513 shares for $49.58002493601943
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.3406690740614567 shares for $50.861892757375486
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6838510315018442 shares for $98.49506406721062
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 92th day, sold 0.3550379890648299 shares for $50.25917773201732
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.34274746366876885 shares for $50.6409377570606
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32094486167276465 shares for $49.6630078952436
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 53th day, sold 0.3400666530640005 shares for $48.979800040807994
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 123th day, sold 0.34057625502349975 shares for $50.32014167972209
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.32094486167276465 shares for $49.6630078952436
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 99th day, Bought 0.3414600833162603 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3414600833162603 shares for $50.31414327665096
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.6470402507516887 shares for $98.9324543399332
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 157th day, Bought 0.31806615776081426 shares for $50.0
On the 181th day, sold 0.31806615776081426 shares for $48.23155216284987
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6735630619895059 shares for $101.15570064958399
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 211th day, sold 0.3359989248034406 shares for $47.65808749412002
XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2807411566535654 shares for $51.26614261650759
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.27156202476645663 shares for $54.37486421898761
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.49849274560048373 shares for $99.81320245158486
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 123th day, sold 0.2794076557697681 shares for $53.44230231908355
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.5021488577139117 shares for $110.20158831389507
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 207th day, sold 0.2505512126678693 shares for $54.985969132090595

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 111.0215699103596, Final Money: 111.0215699103596, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2807411566535654 shares for $52.71476698483998
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5427999546785756 shares for $108.99965889900476
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 59th day, sold 0.2808199943836001 shares for $50.556023588879526
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.561060528834781 shares for $105.35033549930682
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2671939293539251 shares for $53.6552129535617
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 114.60817291894102, Final Money: 114.60817291894102, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 52th day, Bought 0.2780403714619363 shares for $50.00000000000001
On the 55th day, sold 0.5519829530968257 shares for $98.7166313318363
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.537158827897826 shares for $107.480109874076
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5427999546785756 shares for $115.13329838687267
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5387559541203817 shares for $114.27552542847417
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5609340406510999 shares for $105.32658481305702
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.252691160863193 shares for $53.59832213069187
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 62th day, sold 0.27625835681529365 shares for $47.839659649704394
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 62th day, sold 0.27625835681529365 shares for $47.839659649704394

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 117.38604799810668, Final Money: 117.38604799810668, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2702410550210788 shares for $49.019024970273485
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 68th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2932379332590464 shares for $54.08773678963111
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5022116493566033 shares for $106.52411294502915
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.21510927551196007 shares for $50.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2702410550210788 shares for $49.019024970273485
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.28123066539175434 shares for $52.806682040609715
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5242949918070232 shares for $99.3539009474309
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 192th day, Bought 0.25257627803596683 shares for $49.99999999999999
On the 205th day, sold 0.25257627803596683 shares for $53.57395433420893
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.2176373291546966 shares for $50.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5626111386085259 shares for $106.61481076631564
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 186th day, sold 0.5199806235127767 shares for $102.21779097014166
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5617212209748524 shares for $106.44617137473453
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
XLY Final Value: 111.64003033908531, Final Money: 111.64003033908531, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 44th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5745857935668193 shares for $100.15940232878538
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.3890620513572678 shares for $99.81799901053326
On the 112th day, Bought 0.7255840951966334 shares for $50.0
On the 118th day, Bought 0.728650539201399 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.4542346343980324 shares for $101.95639021764605
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 174th day, sold 1.3327280241967356 shares for $106.85813298009427
On the 220th day, Bought 0.6029181237187989 shares for $50.0
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2190610688820769 shares for $93.01435955570247
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 62th day, sold 0.7907638779060573 shares for $49.63624861616322
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6893699158968702 shares for $49.5381221563491
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.7265329845975008 shares for $50.937227550130785
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.6648052120728627 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.3288158362428495 shares for $105.8136050400181
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2653249758046696 shares for $96.54429565389628
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 62th day, sold 0.7838219156607619 shares for $49.20050164602603
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6893699158968702 shares for $48.331724803529575
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 62th day, sold 0.7838219156607619 shares for $49.20050164602603
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.6861534239055852 shares for $50.92630712227253
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 65th day, sold 0.7793017456359103 shares for $50.98971321695761
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 137th day, sold 1.3805014311268045 shares for $102.46081621823143
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 65th day, sold 0.7793017456359103 shares for $50.98971321695761
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 137th day, sold 0.6943480072212193 shares for $51.53450909595889
On the 48th day, Bought 0.7882705344474223 shares for $50.0
On the 138th day, sold 0.7882705344474223 shares for $56.960428819170744

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 106.96042881917074, Final Money: 106.96042881917074, Final Shares: 0.0
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 59th day, Bought 0.0 shares for $0.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7008690776562938 shares for $50.96719932716569
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.7306736811340054 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.465751599393341 shares for $102.70521456949139
On the 132th day, Bought 0.702543206407194 shares for $50.0
On the 139th day, sold 0.702543206407194 shares for $51.194323450892234
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7015574575557738 shares for $51.01725831345587
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 1.4031149151115476 shares for $100.86993124736917
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 1.4031149151115476 shares for $100.86993124736917
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 96th day, sold 0.7843137254901961 shares for $56.36078431372549
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 173th day, sold 0.6716818914562064 shares for $53.57334766254702
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 126th day, sold 0.7803964413922273 shares for $54.66677071952552

[*********************100%***********************]  1 of 1 completed

On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
XLU Final Value: 112.4977744365564, Final Money: 13.180669528968771, Final Shares: 1.2884938363724394

read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 50th day, sold 0.7827175954915466 shares for $51.38541014402004
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7063144511936713 shares for $50.33196779206102
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2348654834504846 shares for $98.67810078252822
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 226th day, sold 1.2658379542853861 shares for $99.60878862271703
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 0.6676458806249166 shares for $50.22699959941248
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7148984844152131 shares for $50.94366599942809
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2348654834504846 shares for $98.67810078252822
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.6254691018263698 shares for $48.861646234676016
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 1.2348654834504846 shares for $96.48004022198636
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 202th day, sold 0.6220452848967405 shares for $48.02189599402837
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 63th day, sold 0.7623113279463333 shares for $48.84890989480103
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.6605892456070815 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 101.38159331583162, Final Money: 0.21325013565154904, Final Shares: 1.3125109390267264
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.7554011179936546 shares for $53.95830185828675
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.428063510802319 shares for $102.09226038725778
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 161th day, sold 1.3487087648370697 shares for $102.38048233878196
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.446268122066912 shares for $103.39370804656353
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.3487087648370697 shares for $103.90452324304786
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 62th day, sold 0.7880220646178092 shares for $49.464144996059886
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 63th day, sold 0.7890168849613381 shares for $50.56020198832255
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 171th day, sold 0.6741270055278414 shares for $53.98409060266954
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 67th day, sold 0.7793017456359103 shares for $51.69887780548629
XLU Final Value: 108.32015752396691, Final Money: 12.194709459563285, Final Shares: 1.2470867678308721

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 37th day, sold 0.09858432903505658 shares for $50.40419574904372
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.19116072968642112 shares for $99.27359014075222
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17726270862194415 shares for $101.22409713147498
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 58th day, sold 0.09558950044927064 shares for $49.14447397097902
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17463810735127167 shares for $99.5105399498281
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17463810735127167 shares for $99.5105399498281
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 204th day, sold 0.17582727512007773 shares for $103.92095268697074
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.1647013436594728 shares for $99.034917942441
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.08228285554421881 shares for $49.47668103873877

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 103.31954724825394, Final Money: 103.31954724825394, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 58th day, sold 0.09858432903505658 shares for $50.68417524350329
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.19198464209553492 shares for $108.44444493408386
On the 149th day, Bought 0.08949346697691068 shares for $50.00000000000001
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17853114772340262 shares for $101.94842659597182
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.19153335798089574 shares for $106.67258839388009
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1791071512121006 shares for $102.27734762815793
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09598587087980649 shares for $53.458370927799436
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1755009281596665 shares for $100.00218387465956
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 61th day, sold 0.09557122923715046 shares for $48.21090658868055
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 202th day, sold 0.08793218669761879 shares for $50.104639302170156
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 235th day, sold 0.08349615082744685 shares for $49.358749561645205
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.64910882596936, Final Money: 108.64910882596936, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.19134559053660022 shares for $99.19929450188964
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.1899262858477388 shares for $105.4622680055324
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 211th day, Bought 0.08536064874093043 shares for $50.0
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.16830689957039294 shares for $98.64467383820731
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 53th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.19212491284579075 shares for $96.91741228505914
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09554748710108925 shares for $53.107204280527434
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 211th day, Bought 0.08536064874093043 shares for $50.0
On the 234th day, sold 0.08536064874093043 shares for $50.029876227059326
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 47th day, sold 0.09759906304899474 shares for $50.72906500097599
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 62th day, sold 0.19212491284579075 shares for $96.740657365241
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.09506426344208685 shares for $52.90136132025249
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17871752061906143 shares for $102.05485297430883
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09443940767603505 shares for $52.38081746751284
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 201th day, sold 0.08714445064138315 shares for $49.76296709425543

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 105.93381054556122, Final Money: 105.93381054556122, Final Shares: 0.0
read  1258  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17850498203719833 shares for $102.84207530109107
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0 shares for $0.0
On the 206th day, sold 0.17229443768099278 shares for $103.06480967639308
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 206th day, sold 0.1784969621943106 shares for $106.77509781501468
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 206th day, sold 0.17406296332971133 shares for $104.12272403420003
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.09436989222958307 shares for $50.0
On the 127th day, sold 0.1884680554334373 shares for $103.46707775240274
On the 197th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 127th day, sold 0.09409816320385425 shares for $51.65895061728395
On the 197th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
SPY Final Value: 108.57725752202438, Final Money: 108.57725752202438, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.0966471303772733 shares for $103.60025440674102
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 50th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0890283040146238 shares for $99.0144534010096
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.5391998274560552 shares for $50.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0843966435066497 shares for $100.5018809201963
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0875484034440523 shares for $98.87990084113324
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.0462549900304203 shares for $94.822089746457
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5214308061320263 shares for $47.25727395974554
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5184570717544588 shares for $46.987764413106596
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 133th day, sold 0.5425935973955507 shares for $49.64188822571893

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 103.74653476906158, Final Money: 103.74653476906158, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.5710370031978073 shares for $52.97510278666058
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0905266638466782 shares for $99.22702114340925
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1184689967049135 shares for $102.7090079674122
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1009008637772286 shares for $99.96179843097235
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.0554195515497262 shares for $99.27276301876725
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0881392947121558 shares for $91.98041458201853
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 35th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 125th day, sold 0.5577867023650156 shares for $51.22155287817938
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.1009008637772286 shares for $102.03149205487355
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0881392947121558 shares for $91.98041458201853
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 126th day, sold 0.5577867023650156 shares for $50.71396697902722
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.095704144658494 shares for $93.77036069987392
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0966471303772733 shares for $93.29177138119464
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0478710816543884 shares for $89.1423929163388
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 236th day, sold 1.1288544904777829 shares for $96.03165150494497

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, Bought 0.0 shares for $0.0
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0913564946715506 shares for $97.66549270815706
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 69th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.5663797009515179 shares for $50.01699139102855
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 166th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.053966284076239 shares for $99.0306720518034
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, sold 1.0643081826903797 shares for $97.799278907419
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0901937982874808 shares for $97.56144300874665
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.524824183898394 shares for $49.3124803190931
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5295488244016098 shares for $48.66024147426392
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 106th day, Bought 0.5584096493187402 shares for $50.0
On the 115th day, sold 0.5584096493187402 shares for $48.64306455215545
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 186th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5443065534509035 shares for $51.14304376224689
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5295488244016098 shares for $47.99300995551789
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 186th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5443065534509035 shares for $51.5676028739386
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 234th day, sold 0.5347593582887701 shares for $45.20320855614973
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 98.86959370904324, Final Money: 98.86959370904324, Final Shares: 0.0
read  1258  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 59th day, sold 1.0871888974428363 shares for $99.52127167191725
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5619871866921434 shares for $49.80892435652467
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5425935973955507 shares for $49.38144329896907
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619240278714318 shares for $51.60148347943358
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5441288497116117 shares for $46.218304494504295
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5585344057193924 shares for $50.106121537086686
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0691805544395634 shares for $103.62497933628248
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.1338598752580578 shares for $96.31005780441943
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5685048322910744 shares for $48.288800454803855
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 1.0547562682543004 shares for $87.76626908144033
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 184th day, Bought 0.5260389268805892 shares for $50.0
XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 58th day, sold 1.1361734946930764 shares for $111.10640604603594
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.094935722669386 shares for $100.50414998382296
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 1.116983523959699 shares for $100.30512045158098
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 189th day, Bought 0.5542622769094336 shares for $50.00000000000001
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1111791849067605 shares for $93.26126898922442
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5670863105364636 shares for $55.415674265623224
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0679201308875026 shares for $95.98466136416873
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.1036056965369934 shares for $99.68870256818661
On the 154th day, Bought 0.5534034311012729 shares for $50.0
On the 155th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 179th day, sold 1.1103823772971066 shares for $100.73388926839351
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.066042591472773 shares for $96.29562728773557
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 102.69613212951315, Final Money: 1.1722860361418839, Final Shares: 1.160670470942852
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 40th day, Bought 0.5477051155657794 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5477051155657794 shares for $53.560083251177566
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 61th day, sold 0.5201289919900135 shares for $49.531883907208986
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0533710046449274 shares for $96.94173355747267
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 92th day, sold 0.5339028296849972 shares for $48.41430859583556
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.5636978579481398 shares for $51.967305524239
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 157th day, Bought 0.5477651183172656 shares for $50.00000000000001
On the 165th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1115901070407657 shares for $97.59761139817923
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 106th day, Bought 0.5640794223826715 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 0.5640794223826715 shares for $52.002481949458485
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5638249887235002 shares for $49.50383400992332
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5569789461958338 shares for $47.14269800601537
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5569789461958338 shares for $47.14269800601537
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.5610412926391383 shares for $50.381508078994614
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 179th day, sold 0.562429696287964 shares for $51.023622047244096
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 197th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 197th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 99.1957255343082, Final Money: 49.99999999999999, Final Shares: 0.562429696287964
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 59th day, Bought 0.511665984445354 shares for $50.0
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 63th day, sold 1.0317949764353676 shares for $97.12286113186114
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5201831044527674 shares for $48.14814814814815
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5299417064122947 shares for $48.91891891891892
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 110th day, sold 0.5585344057193924 shares for $51.100312779267206
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 180th day, sold 0.5736576411197798 shares for $52.96007342817806
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567308762943993 shares for $51.84834650929741
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 40th day, sold 0.5737893045673629 shares for $52.38122561395456
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, sold 1.0642439077373642 shares for $96.40985560192783
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5299417064122947 shares for $49.40116587175411
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 181th day, sold 0.5489679402722881 shares for $51.15283267457181
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.1137718192470587 shares for $103.72556952647857
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5299417064122947 shares for $49.491255961844196
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 234th day, sold 0.5567928730512249 shares for $46.391982182628055
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 234th day, sold 0.5567928730512249 shares for $46.391982182628055
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 234th day, sold 0.5567928730512249 shares for $46.391982182628055

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 104.2795680728045, Final Money: 104.2795680728045, Final Shares: 0.0
read  1258  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.5152514427040396 shares for $48.639736191261335
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.5339028296849972 shares for $48.41430859583556
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 218th day, sold 0.5420641803989593 shares for $51.615351257588905
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5152514427040396 shares for $47.41859027205276
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5420641803989593 shares for $50.189722463139645
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5152514427040396 shares for $47.41859027205276
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 73th day, sold 0.5152514427040396 shares for $47.41859027205276
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
XLE Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.2330456226880395 shares for $92.13546239210851
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2812835348939844 shares for $101.01523492510563
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 0.0 shares for $0.0
On the 237th day, sold 2.0173610256186945 shares for $98.83051664505984
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 47th day, sold 1.2330456226880395 shares for $50.87546239210851
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 125th day, sold 2.2068549360366885 shares for $96.70438329712769
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 165th day, sold 2.276626291211212 shares for $101.03667480395359
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.391777228919281 shares for $104.8076781712429
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 203th day, sold 2.2294092152559086 shares for $104.13570444460349
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 126th day, sold 2.3830007126571893 shares for $103.16010085092972
On the 85th day, Bought 1.1767474699929394 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 126th day, sold 2.374352260412101 shares for $102.78570935323984

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 108.94338261584639, Final Money: 108.94338261584639, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.2394645513138323 shares for $93.4976450173525
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4688340557083066 shares for $102.11097654409556
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.3972209132598525 shares for $102.72091613318469
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 185th day, sold 2.2784403631861974 shares for $103.9652337721862
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 191th day, Bought 1.0499790004199916 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.100178538332195 shares for $97.19626275401399
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 238th day, sold 2.015524105733302 shares for $98.98238883256246
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.237623762376238 shares for $90.84752475247527
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.235788433020267 shares for $93.03115669797332
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 123th day, Bought 1.1627906976744187 shares for $50.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.3603954880935802 shares for $101.70944158195238
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.2294092152559086 shares for $110.46722661593027
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.002850200644033 shares for $96.6976076870939
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.237623762376238 shares for $90.84752475247527
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 2.235788433020267 shares for $92.00269401878398
On the 126th day, Bought 1.155001155001155 shares for $50.0
On the 128th day, sold 1.155001155001155 shares for $49.76899976899977
On the 157th day, Bought 1.0931351114997814 shares for $50.0
On the 158th day, Bought 1.1013215859030838 shares for $50.00000000000001
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 2.194456697402865 shares for $106.97976399838967
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 60th day, sold 1.2312238364934744 shares for $49.32282688992859
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.0 shares for $40.55
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.235788433020267 shares for $91.2648838358873
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 128th day, sold 1.2357884330202669 shares for $53.2501235788433
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 111.34295733542514, Final Money: 111.34295733542514, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 34th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 45th day, sold 2.2379301807378065 shares for $93.76927457291409
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4562839967441796 shares for $105.62021185999973
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 199th day, Bought 0.25 shares for $11.7825
On the 205th day, sold 2.382716457189094 shares for $116.15742728796833
On the 211th day, Bought 1.0026067776218168 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.25 shares for $12.385
On the 234th day, sold 2.258845457436669 shares for $107.97281286547278
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.44891811067287 shares for $105.30347875893341
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 167th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 211th day, Bought 1.0026067776218168 shares for $50.0
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 46th day, sold 1.2379301807378065 shares for $51.27506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.434057971873108 shares for $104.66449279054363
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.224231088111559 shares for $104.09401492362096
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 181th day, Bought 0.0 shares for $0.0
On the 189th day, sold 2.230154423273064 shares for $105.88773201700506
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 189th day, sold 1.1138338159946535 shares for $52.884829583426146

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 114.12102614556098, Final Money: 114.12102614556098, Final Shares: 0.0
read  1258  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4260697616889684 shares for $104.53934603117766
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.25 shares for $11.7875
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.3615453243694313 shares for $110.14247392859028
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.015524105733302 shares for $98.25680015449848
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 1.1397310234784592 shares for $53.33941189879189
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.0058969467476304 shares for $97.78747615394698
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 207th day, sold 2.132716457189094 shares for $106.4012240491639
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 207th day, sold 2.132716457189094 shares for $106.4012240491639
XLF Final Value: 109.08142286236085, Final Money: 109.08142286236085, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7959566428887224 shares for $96.86792343955752
On the 120th day, Bought 0.41010498687664043 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.41010498687664043 shares for $51.49278215223097
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.7839155583232007 shares for $104.91141917039396
On the 219th day, Bought 0.34921078362899843 shares for $50.0
On the 220th day, Bought 0.34724633655114934 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.6964571201801477 shares for $92.71237183838127
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 236th day, sold 0.35481124042009654 shares for $47.232472324723254
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7966308196124732 shares for $99.47529044500953
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 137th day, sold 0.39939292275740873 shares for $49.017493410016776

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 104.33194859231043, Final Money: 104.33194859231043, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 69th day, sold 0.8293256196834445 shares for $101.55921538643462
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.8250044961264706 shares for $104.40431898480486
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7303689539425081 shares for $97.22671514882668
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.8250044961264706 shares for $103.58756453363965
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 240th day, sold 0.3668647736444347 shares for $48.39680093917382
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.8262140082890491 shares for $100.15366208479853
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 96th day, sold 0.4132231404958678 shares for $50.28925619834711
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 126th day, sold 0.4132231404958678 shares for $51.88429752066116

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 113.01824670216817, Final Money: 113.01824670216817, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 46th day, sold 0.41145490454246214 shares for $51.51826859776168
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 102th day, Bought 0.40594300560201346 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.40594300560201346 shares for $50.77129171064382
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.390625 shares for $52.0234375
On the 175th day, Bought 0.3713606654783126 shares for $50.0
On the 176th day, Bought 0.3708373507379663 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 205th day, sold 0.7421980162162789 shares for $104.3381971196845
On the 222th day, Bought 0.3520383017672323 shares for $50.0
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.7025465387108004 shares for $92.92583067527758
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 46th day, sold 0.41145490454246214 shares for $51.51826859776168
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 234th day, sold 0.35050823694356814 shares for $46.36172450052576
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 46th day, sold 0.41145490454246214 shares for $51.51826859776168
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 62th day, sold 0.41145490454246214 shares for $50.09052007899934
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 193th day, Bought 0 shares for $0.0
On the 205th day, sold 0.3691671588895452 shares for $51.89751919669227
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 62th day, sold 0.40997048212528703 shares for $49.90980649393244
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.39701445132602825 shares for $48.44767349531523
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 205th day, sold 0.3691671588895452 shares for $51.89751919669227
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 62th day, sold 0.40997048212528703 shares for $49.90980649393244
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 93th day, sold 0.3981842796846381 shares for $48.590427649916386
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 124th day, sold 0.40997048212528703 shares for $52.554116103640546

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 103.01977662831972, Final Money: 103.01977662831972, Final Shares: 0.0
read  1258  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 53th day, Bought 0.39984006397441024 shares for $50.0
On the 56th day, sold 0.39984006397441024 shares for $50.159936025589765
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 74th day, sold 0.818202330521395 shares for $99.75522813716849
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.796407374083437 shares for $96.52457373891257
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 205th day, sold 0.7831204863019074 shares for $110.09107796432215
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 232th day, Bought 0 shares for $0.0
On the 240th day, sold 0.35050823694356814 shares for $46.239046617595505
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.818202330521395 shares for $99.16612245919308
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.8250044961264706 shares for $104.066067141393
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 232th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8056657756053814 shares for $97.64669200337224
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 151th day, Bought 0.390625 shares for $50.0
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 197th day, Bought 0 shares for $0.0
On the 203th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 205th day, sold 0.7750333954793573 shares for $108.95419473648806
On the 232th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 89th day, Bought 0.4037793749495276 shares for $50.0
On the 93th day, sold 0.8032680294717391 shares for $98.02279763643632
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 197th day, Bought 0 shares for $0.0
On the 203th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 205th day, sold 0.3844083954793573 shares for $54.040132236488056
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 93th day, sold 0.3994886545222116 shares for $48.749600511345484
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 93th day, sold 0.4132231404958678 shares for $50.425619834710744
XLI Final Value: 114.35545398668381, Final Money: 114.35545398668381, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 99th day, sold 0.24211902571304053 shares for $52.20086194373154
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22472920131241853 shares for $50.280911501640524
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21791239921551536 shares for $50.66245369361517
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 65th day, sold 0.4805633476300063 shares for $92.52286131920512
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 99th day, sold 0.24211902571304053 shares for $52.20086194373154
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.22360359554581635 shares for $53.08796565448772
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.48033358033170875 shares for $110.03481658238785
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 234th day, sold 0.21190930281839374 shares for $49.26679381224836
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 125th day, sold 0.23955538520505942 shares for $53.74664622460713
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44572709621218687 shares for $105.8245271826974
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 205th day, sold 0.4491279499535765 shares for $106.63195787797814
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 126th day, sold 0.2400729821865847 shares for $53.867575743025874
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 205th day, sold 0.22700444928720603 shares for $53.895396349768454
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 126th day, sold 0.23940627244433804 shares for $53.71797941106057

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 115.61788808317326, Final Money: 115.61788808317326, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 62th day, sold 0.23819732266209329 shares for $48.05869182030394
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.4279497485115096 shares for $100.23439009636577
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4446063536548852 shares for $99.55180864686534
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.429830156314737 shares for $99.9312130416132
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22693232877955793 shares for $50.81241773703081
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 77th day, sold 0.23978515250335697 shares for $48.97851525033569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 111th day, sold 0.24077819512664933 shares for $54.473658865453146
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.21711754744018413 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44412199672739017 shares for $105.44344446301697
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 111th day, sold 0.23955538520505942 shares for $54.197010348792645
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 111th day, sold 0.23955538520505942 shares for $54.197010348792645

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 105.6525857240085, Final Money: 105.6525857240085, Final Shares: 0.0
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 62th day, sold 0.24315518163692068 shares for $49.058989447065116
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 84th day, sold 0.23999232024575212 shares for $50.947969664970714
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.23137436372049977 shares for $50.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.46372716821885007 shares for $105.18259629539958
On the 109th day, Bought 0.22479992806402302 shares for $50.0
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4441558989335501 shares for $99.65970060270998
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44934504106442896 shares for $100.61284814473629
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 63th day, sold 0.24315518163692068 shares for $48.351407868501674
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 123th day, Bought 0.2134745111433695 shares for $50.0
On the 126th day, sold 0.2134745111433695 shares for $47.899410810349245
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 63th day, sold 0.24315518163692068 shares for $48.351407868501674
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 64th day, sold 0.23955538520505942 shares for $47.09179762361058
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 64th day, sold 0.23955538520505942 shares for $47.09179762361058
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 64th day, sold 0.2400729821865847 shares for $47.193546838238824

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 107.4332936300973, Final Money: 5.462104154881672, Final Shares: 0.4325395099691013
read  1258  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.23819732266209329 shares for $48.00152446286504
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.223254152527237 shares for $49.98883729237363
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 234th day, sold 0.21791239921551536 shares for $50.66245369361517
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44873755024886464 shares for $100.47682487622328
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 205th day, sold 0.22360359554581635 shares for $53.08796565448772
XLK Final Value: 103.08796565448772, Final Money: 103.08796565448772, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 134th day, sold 0.6484243288808196 shares for $50.57061340941512
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 155th day, Bought 0.6077549532028687 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2129352969453038 shares for $96.8528834610825
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 218th day, sold 0.6201165819174005 shares for $51.2402331638348
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 230th day, sold 0.6039376736320812 shares for $49.54704674477594
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 187th day, Bought 0.6099792607051361 shares for $50.00000000000001
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6099792607051361 shares for $48.70684396730511
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.3424622931916024 shares for $98.50988307439978
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.606134076857801 shares for $48.98775609164747
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 68th day, sold 1.3403048587263708 shares for $101.76934792309335
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 1.2949284414746003 shares for $100.81017916879763
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.229964395011263 shares for $99.06133237420714
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 70th day, sold 0.6693440428380187 shares for $50.595716198125835
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 70th day, sold 0.6637461834594451 shares for $50.17257400769946
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 208th day, sold 1.2459530007464696 shares for $100.46119045018784
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 70th day, sold 0.6637461834594451 shares for $50.17257400769946
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 208th day, sold 1.2459530007464696 shares for $100.46119045018784

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.68729852490586, Final Money: 102.68729852490586, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 73th day, sold 0.6600660066006601 shares for $49.51815181518152
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3015780808355715 shares for $101.64023233244978
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 205th day, sold 1.233140578938254 shares for $98.46627522821957
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3424622931916024 shares for $100.05371471157012
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 87th day, sold 0.6600660066006601 shares for $51.570957095709566
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.3015780808355715 shares for $101.70531123649155
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2417076485953324 shares for $100.81424398945504
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 238th day, sold 1.2116114701196075 shares for $96.55331805383152
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.3403048587263708 shares for $99.46402356608397
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.6518055012384305 shares for $50.70394994133751
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2354125741558495 shares for $100.30314689571341
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 239th day, sold 0.6069434328720563 shares for $48.13061422675406
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.3403048587263708 shares for $99.46402356608397
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.649772579597141 shares for $50.5458089668616
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 1.2222774287555604 shares for $97.5988526861315
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 139th day, sold 0.6459113809585325 shares for $50.53610644619558
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 0.60960741282614 shares for $48.67715191416727
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 139th day, sold 0.6459113809585325 shares for $50.53610644619558

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.53610644619559, Final Money: 100.53610644619559, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 62th day, sold 0.6813845734532571 shares for $49.81602616516763
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 98th day, sold 0.6377551020408163 shares for $49.77678571428571
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6455777921239509 shares for $50.58102001291155
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 186th day, Bought 0.6124448799608035 shares for $50.0
On the 189th day, sold 0.6124448799608035 shares for $50.48383145516904
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.606354596167839 shares for $48.302207130730054
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6377551020408163 shares for $48.8329081632653
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 126th day, sold 0.6431695394906097 shares for $50.39233341908927
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 54th day, sold 0.6637461834594451 shares for $49.25660427452542
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.595734540688669 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.1956865445283618 shares for $97.41258278272564
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 150th day, sold 0.6446621970087674 shares for $52.68824136152656
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 181th day, sold 1.2056191664391671 shares for $98.22179348979894
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 181th day, sold 0.6446621970087674 shares for $52.52062919030428

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.52062919030428, Final Money: 102.52062919030428, Final Shares: 0.0
read  1258  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 42th day, sold 1.342552488151616 shares for $101.30901075592094
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3027624078912101 shares for $102.0714346582763
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.2778882724426772 shares for $99.29191876879602
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 169th day, sold 1.2417076485953324 shares for $103.23557390421594
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 238th day, sold 1.2062079794997167 shares for $96.12271388633242
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 53th day, sold 0.6693440428380187 shares for $49.88621151271754
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, sold 1.227685713783603 shares for $102.06979024396875
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 54th day, sold 0.6637461834594451 shares for $49.25660427452542
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 170th day, sold 1.227685713783603 shares for $101.4682242442148
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 171th day, sold 0.6117704637220115 shares for $50.80753701211305
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
XLP Final Value: 102.92949059481009, Final Money: 102.92949059481009, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6867669549229583 shares for $97.48656925131391
On the 79th day, Bought 0.34891835310537334 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.34891835310537334 shares for $50.491974877878576
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.34220792553555535 shares for $49.03839572924508
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 112th day, Bought 0.34277096044423117 shares for $50.0
On the 117th day, sold 0.34277096044423117 shares for $49.499554397751425
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6880421586636769 shares for $97.66758442230893
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.32379225488926305 shares for $47.87268488537754
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.32379225488926305 shares for $47.87268488537754
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 83th day, Bought 0.34199726402188785 shares for $50.0
On the 95th day, sold 0.34199726402188785 shares for $49.49042407660739
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 83th day, Bought 0.34199726402188785 shares for $50.0
On the 96th day, sold 0.34199726402188785 shares for $49.63406292749658
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.30459928394382, Final Money: 99.30459928394382, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 52th day, sold 0.6890405585234674 shares for $99.35275813349875
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6839719051540245 shares for $101.1389256151256
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.33978933061501865 shares for $47.339449541284395
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6850020195559079 shares for $101.2912486317321
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.64628714820769 shares for $99.06289407727472
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 109th day, Bought 0.33992793527772114 shares for $50.0
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 127th day, sold 0.6809222747716855 shares for $100.68797677048914
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 212th day, sold 0.34043712126370257 shares for $48.321644992169944

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 98.32164499216995, Final Money: 98.32164499216995, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 35th day, Bought 0.3408316291751875 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, sold 0.6846160076130312 shares for $100.27570663508068
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7088950308199609 shares for $100.35118056287367
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6853774917644311 shares for $101.6209207039122
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 183th day, sold 0.6431285584952722 shares for $97.62048389399736
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 207th day, sold 0.33532291596807723 shares for $50.063711354033934
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 234th day, sold 0.34458993797381116 shares for $46.96071674707098
On the 238th day, Bought 0.35816618911174786 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.3408316291751875 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, sold 0.6846160076130312 shares for $100.27570663508068
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7086447783151835 shares for $100.31575481829738
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.6858477175629567 shares for $101.33400026992685
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6412113233688959 shares for $98.00915077693573
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6838510315018442 shares for $98.49506406721062
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 123th day, sold 0.34057625502349975 shares for $50.32014167972209
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.32094486167276465 shares for $49.05642210668208
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6838510315018442 shares for $97.07265392168678
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 125th day, sold 0.34057625502349975 shares for $51.27034943123765
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.32094486167276465 shares for $49.05642210668208
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 54th day, sold 0.3439735828288387 shares for $48.827050082553654
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 54th day, sold 0.3439735828288387 shares for $48.827050082553654

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  1258  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.32379225488926305 shares for $49.50783577256832
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.34234851078397804 shares for $50.44505306401916
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2807411566535654 shares for $51.26614261650759
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.27156202476645663 shares for $54.37486421898761
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2798298634430266 shares for $51.099731363331095
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.24895439155546703 shares for $49.84813782115116
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21929824561403508 shares for $50.19956140350877
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.49849274560048373 shares for $107.23575943357606
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.2794076557697681 shares for $52.89186923721711
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 123th day, sold 0.28123066539175434 shares for $53.790989369480855
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 207th day, sold 0.500089566712886 shares for $109.74965631080995
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 208th day, sold 0.2505512126678693 shares for $54.251854078973736

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 113.54064568029082, Final Money: 113.54064568029082, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 109th day, sold 0.2807411566535654 shares for $50.93767546322291
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 125th day, sold 0.26452227277536766 shares for $50.642789122844135
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5404948991210178 shares for $108.53678069249158
On the 216th day, Bought 0.22925263640531868 shares for $50.0
On the 217th day, Bought 0.22693232877955793 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4561849651848766 shares for $104.16071310066289
On the 38th day, Bought 0.2756795500909742 shares for $49.99999999999999
On the 55th day, sold 0.2756795500909742 shares for $49.30253073826983
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2807411566535654 shares for $52.71476698483998
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44423674848696104 shares for $101.43257678202782
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619718220453198 shares for $107.58950533057647
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5130302364012908 shares for $103.02160177174319
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.2594033722438392 shares for $59.22957198443581

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 115.40097128016419, Final Money: 115.40097128016419, Final Shares: 0.0
read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 50th day, Bought 0.2719016803523846 shares for $50.0
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.5458442619872739 shares for $97.61878781380406
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.26822595354326484 shares for $53.6317794109758
On the 240th day, Bought 0.22119000221190002 shares for $50.0
On the 242th day, sold 0.22119000221190002 shares for $48.971466489714665
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5427999546785756 shares for $115.13329838687267
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 205th day, sold 0.5042888059092354 shares for $106.96469862140793
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5609340406510999 shares for $105.32658481305702
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 205th day, sold 0.5042888059092354 shares for $106.96469862140793
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 63th day, sold 0.27625835681529365 shares for $47.60760262997956

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 115.87651856649931, Final Money: 115.87651856649931, Final Shares: 0.0

read  1258  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.2897878752752985 shares for $51.53877361771183
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5022116493566033 shares for $106.52411294502915
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 211th day, sold 0.2309148847734725 shares for $49.28647300604997
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 68th day, Bought 0.2870428842069005 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2870428842069005 shares for $52.94505999196279
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 211th day, sold 0.2309148847734725 shares for $49.28647300604997
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 186th day, sold 0.5199806235127767 shares for $102.21779097014166
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5626111386085259 shares for $106.61481076631564
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077
XLY Final Value: 116.90790081961075, Final Money: 116.90790081961075, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 60th day, sold 0.7907638779060573 shares for $50.76704096156888
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.4012495930161712 shares for $100.69379575414206
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4603163717416159 shares for $102.32436816793502
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3360068701989094 shares for $106.55990796706502
On the 220th day, Bought 0.6029181237187989 shares for $50.0
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2190610688820769 shares for $93.23379054810124
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 62th day, sold 0.7907638779060573 shares for $49.63624861616322
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.7015574575557738 shares for $49.1861933492353
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.7265329845975008 shares for $50.90816623074688
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.6648052120728627 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 174th day, sold 1.3288158362428495 shares for $106.54445374995169
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2601408843698723 shares for $96.37557483660784
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 43th day, Bought 0.7838219156607619 shares for $50.0
On the 62th day, sold 0.7838219156607619 shares for $49.20050164602603
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.6923289947382997 shares for $48.42148989199668
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.7265329845975008 shares for $50.89363557105493
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.6439979392065945 shares for $49.137042761463164
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6923289947382997 shares for $50.027693159789536
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 238th day, sold 0.6676458806249166 shares for $50.94138069168113
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 138th day, sold 0.7197351374694113 shares for $52.00806103353967
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 65th day, sold 0.7793017456359103 shares for $50.98971321695761

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 106.76314661921313, Final Money: 56.232138359084644, Final Shares: 0.6555657532450505
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 51th day, sold 0.7862871520679352 shares for $51.30523667243277
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7115411982353779 shares for $50.8467340259001
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4688613054034505 shares for $102.92311166961977
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2350687215757445 shares for $93.93932696305113
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7115411982353779 shares for $51.74327593567668
On the 116th day, Bought 0.7306736811340054 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4572066657315061 shares for $102.10647106780662
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 217th day, Bought 0.6127450980392157 shares for $50.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2266186400895533 shares for $93.81179359404905
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4024265352120677 shares for $100.82044361639555
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.346354675156112 shares for $107.38524889045149
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2884938363724394 shares for $98.31207971521712
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 96th day, sold 0.7843137254901961 shares for $56.36078431372549
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 96th day, sold 0.7843137254901961 shares for $56.36078431372549
On the 147th day, Bought 0.6716818914562064 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 113.15714011720405, Final Money: 113.15714011720405, Final Shares: 0.0
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 50th day, sold 0.7878978884336589 shares for $51.725496375669714
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 101th day, sold 0.7063144511936713 shares for $49.73160050854639
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.7148984844152131 shares for $48.62739490992279
On the 117th day, Bought 0.7293946024799417 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7293946024799417 shares for $51.97665937272065
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 157th day, Bought 0.655393891728929 shares for $50.0
On the 167th day, sold 1.3270757831851354 shares for $105.02477748127161
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 183th day, sold 0.6140243153628884 shares for $48.802652585042374
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 199th day, sold 1.2216852740530135 shares for $96.62308832485284
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 216th day, sold 0.6403688524590164 shares for $52.15804303278689
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 1.3195363630238734 shares for $99.26872059028601
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 50th day, sold 0.7878978884336589 shares for $51.725496375669714
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7148984844152131 shares for $50.94366599942809
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 184th day, sold 0.6140243153628884 shares for $48.3851160505956
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2216852740530135 shares for $97.6248702495763
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 0.6676458806249166 shares for $50.22699959941248
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 184th day, sold 0.6140243153628884 shares for $48.3851160505956
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 200th day, sold 1.2309103603960099 shares for $98.36204689924514
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 185th day, sold 0.6140243153628884 shares for $48.23775021490851
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 234th day, sold 0.6220452848967405 shares for $46.79646678278179
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 63th day, sold 0.7623113279463333 shares for $48.84890989480103
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 63th day, sold 0.7623113279463333 shares for $48.84890989480103
On the 242th day, Bought 0.6555657532450505 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 105.08875955619209, Final Money: 3.920416376012014, Final Shares: 1.3125109390267264
read  1258  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.439698010984607 shares for $102.92401080528954
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.3487087648370697 shares for $103.90452324304786
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 189th day, sold 1.270973978310089 shares for $104.48677075687242
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.439698010984607 shares for $102.92401080528954
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 164th day, sold 1.3487087648370697 shares for $104.22821334660875
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 189th day, sold 1.270973978310089 shares for $104.48677075687242
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7008690776562938 shares for $50.96719932716569
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3487087648370697 shares for $108.34177507936181
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 189th day, sold 1.270973978310089 shares for $104.48677075687242
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 62th day, sold 0.7793017456359103 shares for $48.91677057356609
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 67th day, sold 0.7793017456359103 shares for $51.69887780548629
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
XLU Final Value: 110.9457839117806, Final Money: 14.820335847376967, Final Shares: 1.2470867678308721

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 57th day, sold 0.09557122923715046 shares for $49.63205076743698
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1791071512121006 shares for $102.27734762815793
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1656259923094319 shares for $97.07339409255803
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 57th day, sold 0.09575609008732956 shares for $49.72805270415199
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.174860422392223 shares for $99.63721728331258
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.16507664932143729 shares for $96.7514241672944
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17463810735127167 shares for $100.71379650947837
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 58th day, sold 0.09575609008732956 shares for $49.23012103569788
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 203th day, sold 0.17582727512007773 shares for $101.39958956174884
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 102.0303438885868, Final Money: 102.0303438885868, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 59th day, sold 0.09858432903505658 shares for $51.06668244015931
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.19198464209553492 shares for $106.92392656868724
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.09599877121572843 shares for $53.4655556408878
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1791071512121006 shares for $102.27734762815793
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09599877121572843 shares for $53.05468090008447
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 202th day, sold 0.17228911804900965 shares for $98.17206235550618
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 60th day, sold 0.09557122923715046 shares for $48.82256245579831
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.54771191435394, Final Money: 107.54771191435394, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.19116072968642112 shares for $96.25516221900362
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.09554748710108925 shares for $53.05560863749284
On the 124th day, Bought 0.08851750876323336 shares for $50.0
On the 128th day, sold 0.08851750876323336 shares for $49.09623623552738
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.08894739650970417 shares for $50.79252130290146
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.08230994633391499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1652561971633775 shares for $96.85665715745556
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.19116072968642112 shares for $96.25516221900362
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.09437879874664956 shares for $52.40665936803956
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.08915993509156726 shares for $50.91388933468857
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 62th day, sold 0.19132731932448002 shares for $96.33904509945542
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.09437879874664956 shares for $52.40665936803956
On the 194th day, Bought 0.08650668696690254 shares for $50.0
On the 201th day, sold 0.08650668696690254 shares for $49.39877852558003
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 62th day, sold 0.09575609008732956 shares for $48.21606404167305
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 100.44531857349833, Final Money: 100.44531857349833, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 60th day, sold 0.09626306771144183 shares for $49.17598814039006
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.09598587087980649 shares for $50.66134265036186
On the 102th day, Bought 0.0923599822668834 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.0923599822668834 shares for $51.043667799615775
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17798507725619608 shares for $102.54254255961224
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17243352818983582 shares for $102.7031337251481
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.166739304078092 shares for $97.72590612016972
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.1784969621943106 shares for $102.83745482900817
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17202832508608146 shares for $102.46179070452098
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.166739304078092 shares for $97.72590612016972
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.08594461728861921 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17202832508608146 shares for $102.46179070452098
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 235th day, sold 0.1664768163323842 shares for $98.41276997488892
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 236th day, sold 0.08349615082744685 shares for $49.65432593557437
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.09409816320385425 shares for $52.00429087624209
SPY Final Value: 105.31241689450377, Final Money: 105.31241689450377, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.5710370031978073 shares for $52.97510278666058
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 122th day, Bought 0.5524861878453039 shares for $50.0
On the 125th day, sold 0.5524861878453039 shares for $50.73480662983425
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.0966471303772733 shares for $103.15062908328633
On the 212th day, Bought 0.5435373410153278 shares for $50.0
On the 213th day, Bought 0.5453157378121932 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 1.088853078827521 shares for $98.68275453413823
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, sold 0.5685048322910744 shares for $48.055713473564516
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.0890283040146238 shares for $100.0054691576629
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.5391998274560552 shares for $50.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0843966435066497 shares for $100.5018809201963
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, sold 0.5397236614853195 shares for $50.107944732297064
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0890283040146238 shares for $99.0144534010096
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5260389268805892 shares for $47.6749079431878
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.524824183898394 shares for $44.91445365802456
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.524824183898394 shares for $44.91445365802456
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 136th day, sold 0.5433010974682169 shares for $49.85874171465826

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 102.26497085120882, Final Money: 102.26497085120882, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0862543025393099 shares for $98.8382789880518
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1184689967049135 shares for $100.25956086462845
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.1009008637772286 shares for $106.699311717289
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0938814610365155 shares for $92.46579990141666
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0862543025393099 shares for $98.8382789880518
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 121th day, sold 0.5619240278714318 shares for $50.370869858395146
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5514503143266791 shares for $51.108415131796626
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1014463109828538 shares for $93.10525666738063
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0808309389958162 shares for $92.49751175926194
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 236th day, sold 1.1201985319490242 shares for $95.29528911290348
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 236th day, sold 1.1201985319490242 shares for $95.29528911290348

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 43th day, Bought 0.5515719801434087 shares for $50.0
On the 61th day, sold 0.5515719801434087 shares for $49.36017650303364
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 69th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.5663797009515179 shares for $51.38196647032171
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.089819163774012 shares for $98.73761623792548
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 106th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5567308762943993 shares for $48.496826634005124
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 166th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.052751541094044 shares for $98.91653480119636
On the 202th day, Bought 0.5345306820611503 shares for $50.0
On the 203th day, Bought 0.533731853116994 shares for $50.0
On the 209th day, sold 1.0682625351781443 shares for $99.00657176031042
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 227th day, sold 1.0643081826903797 shares for $96.79882921569003
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 241th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.5515719801434087 shares for $50.0
On the 61th day, sold 0.5515719801434087 shares for $49.36017650303364
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 78th day, sold 0.5663797009515179 shares for $51.38196647032171
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 115th day, sold 1.0890547818097573 shares for $94.86756204344796
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 166th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5443065534509035 shares for $51.14304376224689
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5295488244016098 shares for $48.16246557932641
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 78th day, sold 0.5663797009515179 shares for $51.38196647032171
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 196th day, sold 0.5443065534509035 shares for $51.14304376224689
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 1.0643081826903797 shares for $96.45825059722911
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 228th day, sold 0.5343593031954686 shares for $48.428983648605325
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 234th day, sold 0.5343593031954686 shares for $45.169391899112966
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 98.86959370904324, Final Money: 98.86959370904324, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 61th day, sold 1.0871888974428363 shares for $97.29253443215941
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5619871866921434 shares for $49.80892435652467
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5472255663784612 shares for $49.80299879610376
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5567308762943993 shares for $50.61797127268679
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 163th day, sold 0.5514503143266791 shares for $50.07168854086246
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.5253756435851634 shares for $47.956288746453716
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5441288497116117 shares for $46.218304494504295
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 175th day, sold 0.5357334190506804 shares for $52.01435765563056
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0563065388855981 shares for $96.4196608694774
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5497526113249038 shares for $46.69598680593733
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.0554195515497262 shares for $99.30442560531374
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 1.1338598752580578 shares for $95.01745754662524
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 127th day, sold 0.5619240278714318 shares for $50.63497415149472
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.529380624669137 shares for $50.32292218104817
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 242th day, sold 1.1600108065014139 shares for $96.52449920898265
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.529380624669137 shares for $44.04976177871889
XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.579979120751653 shares for $55.753392877856406
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 151th day, Bought 0.5614192679092747 shares for $50.0
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.1145778031454734 shares for $94.8951541598056
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.5757052389176742 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5757052389176742 shares for $55.34254461715602
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.067180811577654 shares for $95.91821134459954
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 151th day, Bought 0.5614192679092747 shares for $50.0
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.1145778031454734 shares for $101.11449830135734
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108588481558596 shares for $100.05011046066329
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0829689411473016 shares for $97.83541414324723
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108588481558596 shares for $100.05011046066329
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 136th day, sold 0.548666739822232 shares for $49.78601997146933
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108588481558596 shares for $100.05011046066329
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 103.79324763015684, Final Money: 103.79324763015684, Final Shares: 0.0
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.1428764887239757 shares for $108.83612802118421
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 95th day, sold 0.5343022013250694 shares for $48.4932677922633
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.1099668407952938 shares for $100.27440439744684
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 157th day, Bought 0.5477651183172656 shares for $50.00000000000001
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1115901070407657 shares for $97.59761139817923
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.117517062787762 shares for $104.07436405742426
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0451065062759581 shares for $87.71578907174117
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 95th day, sold 0.5343022013250694 shares for $48.4932677922633
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 127th day, Bought 0.5413012882970661 shares for $50.0
On the 132th day, sold 1.0962402450118276 shares for $101.06238818764038
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 171th day, Bought 0.5633168093735916 shares for $49.99999999999999
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.127141798097092 shares for $98.96304987292467
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.117517062787762 shares for $104.07436405742426
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 236th day, sold 1.0938878216576393 shares for $91.81000487172568
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5569789461958338 shares for $46.74724295421633
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 99.88169644784287, Final Money: 48.82519399629021, Final Shares: 0.5837030119075415
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0548281001756075 shares for $97.07583005916116
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5299417064122947 shares for $48.91891891891892
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 110th day, sold 0.5585344057193924 shares for $51.100312779267206
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 187th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5420641803989593 shares for $50.482437120555076
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 238th day, Bought 0.5912262031453235 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0548281001756075 shares for $97.07583005916116
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5299417064122947 shares for $48.484366719660834
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5420641803989593 shares for $50.482437120555076
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5299417064122947 shares for $48.484366719660834
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.546268982847154 shares for $50.92319458101169
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5299417064122947 shares for $49.40116587175411
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5299417064122947 shares for $49.491255961844196
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 101.85412026726058, Final Money: 101.85412026726058, Final Shares: 0.0
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5612932195779076 shares for $53.99079479119893
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 94th day, sold 0.5339028296849972 shares for $49.759743726641744
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.094935722669386 shares for $98.91649318595235
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.104728573913182 shares for $96.99516878957738
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5534646889528448 shares for $51.24529555014391
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.545732372844357 shares for $50.52936040165902
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
XLE Final Value: 101.22526125254817, Final Money: 50.16875880099552, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 46th day, sold 1.2330456226880395 shares for $51.0727496917386
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 120th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.276626291211212 shares for $100.80901217483246
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 201th day, sold 1.072271070126528 shares for $50.01072271070126
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 237th day, sold 2.015524105733302 shares for $98.74052593987447
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 98th day, sold 1.200192030724916 shares for $49.55592894863178
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 165th day, sold 2.247196571777908 shares for $99.73058385550355
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 237th day, sold 1.0062386798148522 shares for $49.295632924129606
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.391777228919281 shares for $104.8076781712429
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.2379022564825797 shares for $104.53241440030129
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.3830007126571893 shares for $104.42309122863803
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 1.1976047904191616 shares for $52.47904191616766

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 109.3400925715442, Final Money: 109.3400925715442, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 47th day, sold 2.2330456226880395 shares for $92.13546239210851
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 89th day, sold 2.4688340557083066 shares for $102.11097654409556
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.418830948492971 shares for $103.64690614292381
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 59th day, sold 1.2330456226880395 shares for $50.06165228113441
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.4688340557083066 shares for $100.77780615401308
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 2.3972209132598525 shares for $102.72091613318469
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2379022564825797 shares for $103.57011643001378
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 127th day, sold 1.2357884330202669 shares for $52.95353435491844
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 127th day, sold 1.2357884330202669 shares for $52.95353435491844
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 127th day, sold 1.2357884330202669 shares for $52.95353435491844
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 127th day, sold 1.2357884330202669 shares for $52.95353435491844
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 127th day, sold 1.2330456226880395 shares for $52.8360049321825

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 109.09930126887829, Final Money: 11.164984971297137, Final Shares: 2.015524105733302
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 31th day, Bought 1.2410027302060065 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 46th day, sold 2.2410027302060067 shares for $92.8223330851328
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4562839967441796 shares for $105.62021185999973
On the 167th day, Bought 1.1088933244621866 shares for $50.0
On the 173th day, Bought 1.1096316023080337 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.21852492677022 shares for $103.82696657284629
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 199th day, Bought 1.0608953957139826 shares for $50.0
On the 205th day, sold 2.1331664658405103 shares for $103.99186520972488
On the 233th day, Bought 1.0497585555322275 shares for $50.0
On the 234th day, sold 1.0497585555322275 shares for $50.17845895444047
On the 242th day, Bought 1.0371292263015972 shares for $50.0
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 35th day, Bought 1.0 shares for $40.55
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4028295721041095 shares for $103.3216716004767
On the 167th day, Bought 1.1088933244621866 shares for $50.0
On the 173th day, Bought 1.1096316023080337 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.21852492677022 shares for $103.82696657284629
On the 199th day, Bought 1.0608953957139826 shares for $50.0
On the 205th day, sold 1.0608953957139826 shares for $51.718650541056654
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 46th day, sold 1.2379301807378065 shares for $51.27506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.434057971873108 shares for $104.66449279054363
On the 173th day, Bought 1.1096316023080337 shares for $50.0
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.225952209586444 shares for $104.17456340864558
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 59th day, sold 1.2379301807378065 shares for $50.259965337954945
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 123th day, sold 1.2100677637947725 shares for $52.03291384317522
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 178th day, Bought 1.109139307897072 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2254599151754824 shares for $104.15152403021257
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 124th day, sold 1.2100677637947725 shares for $52.62584704743466
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.224231088111559 shares for $104.09401492362096
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 189th day, sold 1.1163206072784104 shares for $53.002902433578925

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 116.44394478813877, Final Money: 66.04983568214416, Final Shares: 1.0371292263015972
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 73th day, Bought 1.2388503468780971 shares for $50.0
On the 90th day, sold 1.2388503468780971 shares for $51.54856293359762
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.422873949388438 shares for $104.4016384791478
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2784403631861974 shares for $106.63100899711402
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.201076809935687 shares for $101.8658347638236
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 128th day, sold 1.2357884330202669 shares for $53.2501235788433
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 1.0604453870625663 shares for $52.54506892895016
XLF Final Value: 109.01058338529, Final Money: 11.544050742822641, Final Shares: 2.0058969467476304

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7959566428887224 shares for $97.10671043242412
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39142007202129325 shares for $52.383748238609684
On the 222th day, Bought 0.3520383017672323 shares for $50.0
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7025465387108004 shares for $93.52299523318176
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 236th day, sold 0.7105312176540179 shares for $94.58591569410287
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.39013732833957554 shares for $52.2120786516854
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7966308196124732 shares for $99.47529044500953

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 101.6270731220483, Final Money: 101.6270731220483, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 52th day, sold 0.4132231404958678 shares for $51.40909090909091
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.8250044961264706 shares for $104.40431898480486
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7303689539425081 shares for $97.22671514882668
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 52th day, sold 0.4132231404958678 shares for $51.40909090909091
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 126th day, sold 0.8272044433900118 shares for $103.86378991204988
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39013732833957554 shares for $55.177122347066174
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.390625 shares for $55.24609375
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.3995205753096284 shares for $48.741510187774665

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 114.97297404214282, Final Money: 114.97297404214282, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 100th day, Bought 0.4074647542987532 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.4074647542987532 shares for $50.96161682014505
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.38675742574257427 shares for $49.43533415841584
On the 165th day, Bought 0.38681726752282225 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.38681726752282225 shares for $53.45041002630358
On the 193th day, Bought 0.36469730123997085 shares for $50.0
On the 197th day, sold 0.36469730123997085 shares for $49.525893508388044
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 235th day, sold 0.35050823694356814 shares for $46.90501226778829
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.38675742574257427 shares for $53.442141089108915
On the 193th day, Bought 0.36469730123997085 shares for $50.0
On the 205th day, sold 0.36469730123997085 shares for $51.269146608315104
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.37947783849423194 shares for $50.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 193th day, Bought 0.36469730123997085 shares for $50.0
On the 205th day, sold 0.36469730123997085 shares for $51.269146608315104
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 46th day, sold 0.40970173713536545 shares for $51.298754506719106
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7976729342068497 shares for $97.34002816126187
On the 42th day, Bought 0.4102395799146702 shares for $50.0
On the 46th day, sold 0.4102395799146702 shares for $51.36609780111585
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 93th day, sold 0.7976729342068497 shares for $97.34002816126187
On the 42th day, Bought 0.4102395799146702 shares for $50.0
On the 46th day, sold 0.4102395799146702 shares for $51.36609780111585
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 93th day, sold 0.3981842796846381 shares for $48.590427649916386

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 103.84235367808542, Final Money: 3.1748408839981437, Final Shares: 0.7584954249102417
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 70th day, sold 0.4062728528479727 shares for $49.83342813033233
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.8002117420331725 shares for $97.64983888030804
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 228th day, Bought 0.3605422555523507 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 241th day, sold 0.7110504924959189 shares for $93.68801289126226
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.4062728528479727 shares for $49.24839522223125
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959566428887224 shares for $97.13058913171079
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 151th day, Bought 0.390625 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.390625 shares for $54.91406250000001
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 56th day, sold 0.41145490454246214 shares for $51.617017774851874
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7965350266356567 shares for $97.20116930034918
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 205th day, sold 0.3681885125184094 shares for $51.759941089837994
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 93th day, sold 0.39939292275740873 shares for $48.73791836408659
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 205th day, sold 0.3681885125184094 shares for $51.759941089837994
XLI Final Value: 104.78451070265994, Final Money: 104.78451070265994, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22472920131241853 shares for $50.31911546586363
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 65th day, sold 0.48033358033170875 shares for $92.47862422126389
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21190930281839374 shares for $49.26679381224836
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.47962836739164416 shares for $109.55191539592545
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.47962836739164416 shares for $111.96444608390541
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44301649220077255 shares for $105.18097557830741
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 125th day, sold 0.2400729821865847 shares for $53.86277428338215
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.44301649220077255 shares for $104.5341714996943
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 126th day, sold 0.23940627244433804 shares for $53.71797941106057
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 236th day, sold 0.4470555011312338 shares for $106.43050315431283

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 118.28072377244247, Final Money: 118.28072377244247, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 62th day, sold 0.24321432045918862 shares for $49.07092129584589
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22472920131241853 shares for $50.31911546586363
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.21590810950859313 shares for $50.94567751964764
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22693232877955793 shares for $50.7738392411383
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.21590810950859313 shares for $51.401243630710766
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 77th day, sold 0.24321432045918862 shares for $49.67895709699386
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.22700444928720603 shares for $51.505039498774174
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 111th day, sold 0.23978515250335697 shares for $54.24899290235948
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.21036687983843824 shares for $50.0
On the 126th day, sold 0.42378671934671897 shares for $95.0892640870168
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 111th day, sold 0.23955538520505942 shares for $54.197010348792645
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 131th day, sold 0.2134198395082807 shares for $45.58007512378351

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 101.48951479667204, Final Money: 101.48951479667204, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 32th day, Bought 0.2372366672992978 shares for $50.0
On the 62th day, sold 0.2372366672992978 shares for $47.86486999430632
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, sold 0.23999232024575212 shares for $50.835173274455215
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, sold 0.2323528044983503 shares for $52.28867512430875
On the 109th day, Bought 0.22479992806402302 shares for $50.0
On the 123th day, Bought 0.2134745111433695 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4382744392073925 shares for $98.34001866935473
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 160th day, sold 0.22609088853719195 shares for $47.332127515261135
On the 170th day, Bought 0.22359359627940256 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22359359627940256 shares for $50.06484214292103
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 225th day, sold 0.21861746316295744 shares for $52.65182982816667
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.20888164765843673 shares for $49.28771358148473
On the 40th day, Bought 0.23948654085640386 shares for $50.0
On the 62th day, sold 0.23948654085640386 shares for $48.31880448318804
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 85th day, sold 0.23999232024575212 shares for $50.835173274455215
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 123th day, Bought 0.2134745111433695 shares for $50.0
On the 124th day, Bought 0.2141877998629198 shares for $50.0
On the 126th day, sold 0.42766231100628926 shares for $95.95886934359119
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 160th day, sold 0.22609088853719195 shares for $47.332127515261135
On the 170th day, Bought 0.22359359627940256 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22359359627940256 shares for $50.06484214292103
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 235th day, sold 0.21861746316295744 shares for $51.58497660793144
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 63th day, sold 0.24315518163692068 shares for $48.351407868501674
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 160th day, sold 0.4508200898496105 shares for $94.37918581001595
On the 171th day, Bought 0.2246888060036849 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.2246888060036849 shares for $50.27187345526446
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 63th day, sold 0.24315518163692068 shares for $48.351407868501674
On the 171th day, Bought 0.2246888060036849 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.2246888060036849 shares for $50.27187345526446
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 63th day, sold 0.24315518163692068 shares for $48.351407868501674
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 64th day, sold 0.2400729821865847 shares for $47.193546838238824

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 38th day, sold 0.2415692337423906 shares for $50.975939704319266
On the 46th day, Bought 0.23819732266209329 shares for $50.0
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4779824751654502 shares for $96.32302839534154
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 116th day, Bought 0.21535943489684284 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4336237966918489 shares for $97.29650750171706
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.223254152527237 shares for $49.98883729237363
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.21614144296027318 shares for $50.678684130895256
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2302343785974122 shares for $51.55177971174656
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 40th day, sold 0.2415692337423906 shares for $50.43482462073631
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44656903590256103 shares for $99.915356092839
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 127th day, sold 0.23470872647045016 shares for $51.84011641552833
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44656903590256103 shares for $101.32204855593207
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 204th day, sold 0.2229654403567447 shares for $52.028985507246375
XLK Final Value: 103.1621649714604, Final Money: 103.1621649714604, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6377551020408163 shares for $49.30484693877551
On the 113th day, Bought 0.6529119874640898 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6529119874640898 shares for $50.82919822407939
On the 155th day, Bought 0.6077549532028687 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6077549532028687 shares for $48.52923301324906
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 218th day, sold 0.6232859636000997 shares for $51.50211917227624
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 231th day, sold 0.6039376736320812 shares for $49.287353545114144
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 96th day, sold 0.6399590426212722 shares for $49.904006143606814
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6455777921239509 shares for $50.25823111684958
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.606134076857801 shares for $48.98775609164747
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 237th day, sold 0.6069434328720563 shares for $48.215586307356155
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 198th day, Bought 0.6218132073125233 shares for $50.0
On the 200th day, Bought 0.6240639041437843 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2458771114563076 shares for $100.34294255669103
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.3424622931916024 shares for $99.63755140068072
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 70th day, sold 0.6715014773032502 shares for $50.758796669352684
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 70th day, sold 0.6693440428380187 shares for $50.595716198125835
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 136th day, sold 0.6455777921239509 shares for $50.72304712717882
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 102.85037899613269, Final Money: 102.85037899613269, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 70th day, Bought 0.6614631565021828 shares for $50.0
On the 87th day, sold 0.6614631565021828 shares for $51.680116417515535
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 120th day, sold 1.3027624078912101 shares for $100.83381037077967
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 191th day, Bought 0.6079766536964981 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2172869144812897 shares for $97.20036012133097
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2279540008476508 shares for $97.3767522672187
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3403048587263708 shares for $101.0053741536193
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3027624078912101 shares for $101.7327164322246
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 239th day, sold 0.6069434328720563 shares for $48.13061422675406
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 53th day, sold 0.6637461834594451 shares for $49.46900305323245
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6518055012384305 shares for $50.93208186677096
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 1.2222774287555604 shares for $97.5988526861315
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 139th day, sold 0.649772579597141 shares for $50.83820662768031
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 139th day, sold 0.649772579597141 shares for $50.83820662768031
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 139th day, sold 0.649772579597141 shares for $50.83820662768031

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.83820662768031, Final Money: 100.83820662768031, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 62th day, sold 0.6813845734532571 shares for $49.81602616516763
On the 73th day, Bought 0.6664889362836577 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.6664889362836577 shares for $50.75313249800054
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 1.2964676982471979 shares for $99.27053165478793
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6455777921239509 shares for $50.58102001291155
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6069434328720563 shares for $48.349113862588005
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 73th day, Bought 0.6664889362836577 shares for $50.0
On the 99th day, sold 0.6664889362836577 shares for $51.759530791788855
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 1.2964676982471979 shares for $99.27053165478793
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 125th day, Bought 0.63500127000254 shares for $50.0
On the 126th day, sold 1.2781708094931497 shares for $100.14468292378827
On the 164th day, Bought 0.6036460219727152 shares for $50.0
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2035980258124082 shares for $98.0571311629369
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.3424622931916024 shares for $99.6241267777488
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.595734540688669 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.1956865445283618 shares for $97.41258278272564
On the 214th day, Bought 0.6232859636000997 shares for $50.0
On the 217th day, sold 0.6232859636000997 shares for $51.29020194465221
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2056191664391671 shares for $98.22179348979894
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 178th day, Bought 0.6044487427466151 shares for $50.0
On the 181th day, sold 1.2067132573214163 shares for $98.31092907397579

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 95th day, sold 1.2824673952298562 shares for $99.14755432522018
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6443298969072165 shares for $50.73453608247423
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6227425582264291 shares for $51.46967243741437
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 183th day, sold 0.6033546518643659 shares for $48.9079280801255
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6065752759917505 shares for $49.91507946136115
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 54th day, sold 0.6715916722632639 shares for $49.83881799865681
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.642508352608584 shares for $50.34052942688255
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6159152500615914 shares for $51.151761517615164
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 238th day, sold 1.2062079794997167 shares for $96.12271388633242
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 217th day, sold 0.6093102607847916 shares for $50.140141359980504
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 0.6015399422521656 shares for $47.936717998075075
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 127th day, sold 0.6518055012384305 shares for $50.899491591709044
XLP Final Value: 101.35133812381514, Final Money: 101.35133812381514, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 30th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6890405585234674 shares for $97.80930728240618
On the 78th day, Bought 0.3519144144144144 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3519144144144144 shares for $50.57010135135135
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.3409943394939644 shares for $48.864488849485106
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 233th day, sold 0.34055305816646236 shares for $46.76474594741861
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6838510315018442 shares for $97.07265392168678
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6851745190905817 shares for $97.26052298490806
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32303915234526426 shares for $47.82271611319292
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.30459928394382, Final Money: 99.30459928394382, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 52th day, sold 0.6851745190905817 shares for $98.79531390767097
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6818288784824503 shares for $100.46748524438905
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.3391900142459806 shares for $47.06261447662981
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6877579612666824 shares for $99.05777916124028
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6839719051540245 shares for $101.1389256151256
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.64543908666797 shares for $98.93290320446644
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 109th day, Bought 0.33992793527772114 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6822764460616992 shares for $100.88821807914347
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 97.68738177119462, Final Money: 97.68738177119462, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 34th day, Bought 0.3424188467333242 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, sold 0.6862032251711679 shares for $100.50818639082097
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7086447783151835 shares for $100.31575481829738
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.6858477175629567 shares for $101.33400026992685
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6469099769642548 shares for $98.88018997898634
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.3381805884342239 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.6788496624956806 shares for $101.35225461060512
On the 238th day, Bought 0.35816618911174786 shares for $50.0
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 35th day, Bought 0.3408316291751875 shares for $50.0
On the 53th day, sold 0.3408316291751875 shares for $49.08997955010226
On the 90th day, Bought 0.3462124359506994 shares for $50.0
On the 92th day, sold 0.3462124359506994 shares for $49.009832433181
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 123th day, sold 0.34057625502349975 shares for $50.32014167972209
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.32094486167276465 shares for $49.05642210668208
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.3406690740614567 shares for $50.861892757375486
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 53th day, sold 0.3400666530640005 shares for $48.979800040807994
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 123th day, sold 0.34057625502349975 shares for $50.32014167972209
On the 169th day, Bought 0.3218331616889804 shares for $50.0
On the 188th day, sold 0.3218331616889804 shares for $49.19219876416065
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.3406690740614567 shares for $50.861892757375486

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 102.65167638517217, Final Money: 2.3903860686366585, Final Shares: 0.721511876198442
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6890405585234674 shares for $98.684388791731
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3402054841124039 shares for $50.12927808396272
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3359989248034406 shares for $49.74128082790135
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32324799586242564 shares for $49.01732609257822
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 238th day, sold 0.33978933061501865 shares for $47.4345905538566
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 200th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3359989248034406 shares for $47.65808749412002
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 211th day, sold 0.3359989248034406 shares for $47.65808749412002
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 211th day, sold 0.3359989248034406 shares for $47.65808749412002
XLV Final Value: 98.45668673308728, Final Money: 98.45668673308728, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.26893287435456115 shares for $53.84842943201377
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 175th day, Bought 0.24932681759250025 shares for $50.0
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.49828120914796725 shares for $105.69042727237535
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 116th day, sold 0.2794076557697681 shares for $52.46437552388936
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 207th day, sold 0.5021488577139117 shares for $110.20158831389507
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 207th day, sold 0.2505512126678693 shares for $54.985969132090595

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 110.20158831389509, Final Money: 110.20158831389509, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.2756795500909742 shares for $49.99999999999999
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5468145210795323 shares for $98.72189363569876
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2807411566535654 shares for $52.71476698483998
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 125th day, sold 0.26452227277536766 shares for $50.642789122844135
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5404948991210178 shares for $108.53678069249158
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.45037596551192016 shares for $102.83434420533673
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 59th day, sold 0.2808199943836001 shares for $50.556023588879526
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.561060528834781 shares for $105.35033549930682
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2671939293539251 shares for $53.6552129535617
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 114.02435463425628, Final Money: 114.02435463425628, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 52th day, Bought 0.2780403714619363 shares for $50.00000000000001
On the 55th day, sold 0.5519829530968257 shares for $98.7166313318363
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.537158827897826 shares for $107.4049076381703
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 52th day, Bought 0.2780403714619363 shares for $50.00000000000001
On the 55th day, sold 0.5519829530968257 shares for $98.7166313318363
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.5387702334026259 shares for $106.078471254643
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5242531856296496 shares for $111.19934320390499
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 62th day, sold 0.2739425816348893 shares for $47.43863686171378
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5042888059092354 shares for $106.96469862140793
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5606383211615225 shares for $105.27105756449907
On the 40th day, Bought 0.2780249110320285 shares for $50.0
On the 62th day, sold 0.2780249110320285 shares for $48.145573843416365
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 116th day, sold 0.28123066539175434 shares for $52.806682040609715

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 113.452092815139, Final Money: 113.452092815139, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2897878752752985 shares for $53.4513735945288
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5022116493566033 shares for $106.52411294502915
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.21510927551196007 shares for $50.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2702410550210788 shares for $49.019024970273485
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5242949918070232 shares for $99.3539009474309
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.2176373291546966 shares for $50.0
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2702410550210788 shares for $48.26235001621447
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.282326369282891 shares for $53.50084697910785
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5626111386085259 shares for $106.61481076631564
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 186th day, sold 0.5199806235127767 shares for $102.21779097014166
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077
XLY Final Value: 110.1084138122571, Final Money: 12.851082844395364, Final Shares: 0.43057079408474297

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5786617663397162 shares for $100.41867495686935
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, sold 1.4012495930161712 shares for $96.92443434892857
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.7265329845975008 shares for $50.90816623074688
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3389713616283672 shares for $106.79635580347858
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, sold 1.2348654834504846 shares for $97.66551108609883
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2426992193016655 shares for $94.51970262008469
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 61th day, sold 0.7907638779060573 shares for $50.300490273604304
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, sold 1.390927373452644 shares for $96.21044642171938
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 124th day, sold 0.7197351374694113 shares for $50.43184108248165
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 184th day, sold 0.6672894701721607 shares for $52.58241024956626
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, sold 1.2348654834504846 shares for $97.66551108609883
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.6491820306413919 shares for $49.649441703453654
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 61th day, sold 0.7907638779060573 shares for $50.300490273604304
On the 85th day, Bought 0.6911805363560962 shares for $50.0
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.383509531094396 shares for $96.9978532250281
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 185th day, sold 0.6640106241699868 shares for $52.16467463479417
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.6128201985537443 shares for $48.467949503615635
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6923289947382997 shares for $48.53918582110219
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.6923289947382997 shares for $48.53918582110219
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 65th day, sold 0.7829627309740056 shares for $51.22925148762919
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 137th day, sold 1.3805014311268045 shares for $102.46081621823143
On the 48th day, Bought 0.7882705344474223 shares for $50.0
On the 138th day, sold 0.7882705344474223 shares for $56.960428819170744

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 106.96042881917074, Final Money: 106.96042881917074, Final Shares: 0.0
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 118th day, Bought 0.728650539201399 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4637284574607345 shares for $102.56345301427366
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 139th day, sold 0.7094211123723042 shares for $51.69551645856981
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2426992193016655 shares for $94.51970262008469
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 52th day, sold 0.7843137254901961 shares for $51.26274509803921
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7115411982353779 shares for $51.74327593567668
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 139th day, sold 0.7094211123723042 shares for $51.69551645856981
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2426992193016655 shares for $94.51970262008469
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 65th day, sold 0.7843137254901961 shares for $51.31764705882353
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 95th day, sold 0.7015574575557738 shares for $50.43496562368458
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.265276076086015 shares for $96.76831429905842
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 124th day, sold 0.7843137254901961 shares for $54.956862745098036
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 172th day, sold 0.6746727836999056 shares for $54.19646471461341
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 125th day, sold 0.7803964413922273 shares for $54.71359450600906

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 112.09005861929498, Final Money: 14.536984780780664, Final Shares: 1.2656081193372382
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 50th day, sold 0.7827175954915466 shares for $51.38541014402004
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.7063144511936713 shares for $48.04350897019352
On the 117th day, Bought 0.7293946024799417 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7293946024799417 shares for $51.97665937272065
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 157th day, Bought 0.0 shares for $0.0
On the 168th day, sold 1.3389713616283672 shares for $105.88585527757127
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 183th day, sold 0.6140243153628884 shares for $48.802652585042374
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, sold 1.2216852740530135 shares for $95.73125807479414
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 211th day, Bought 0.6309148264984227 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.271283678957439 shares for $103.54605565108342
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 0.6676458806249166 shares for $50.22699959941248
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 51th day, sold 0.7827175954915466 shares for $51.072323105823415
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.7063144511936713 shares for $48.04350897019352
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 137th day, sold 0.7035317292809906 shares for $52.21612494723512
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.6220452848967405 shares for $48.59417765613337
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 235th day, sold 0.6676458806249166 shares for $51.02817465616238
On the 240th day, Bought 0.6599788806758183 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 106.74872604993067, Final Money: 5.5803828697505935, Final Shares: 1.3125109390267264
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.428063510802319 shares for $102.09226038725778
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.352185047296217 shares for $108.28297858748105
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 189th day, sold 0.6345177664974619 shares for $52.16370558375634
On the 220th day, Bought 0.6029181237187989 shares for $50.0
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 62th day, sold 0.7880220646178092 shares for $49.464144996059886
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.446268122066912 shares for $103.39370804656353
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.352185047296217 shares for $108.28297858748105
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 62th day, sold 0.7880220646178092 shares for $49.464144996059886
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 62th day, sold 0.7827175954915466 shares for $49.131183469004384
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6741270055278414 shares for $53.98409060266954
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
XLU Final Value: 110.74047297818248, Final Money: 15.336687942520633, Final Shares: 1.2377242479976887

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 37th day, sold 0.09858432903505658 shares for $50.40419574904372
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.19116072968642112 shares for $99.15889370294036
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 173th day, Bought 0.08751969193068442 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17523283486802216 shares for $100.06495802303537
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 49th day, Bought 0.09557122923715046 shares for $50.0
On the 56th day, sold 0.09557122923715046 shares for $49.57470802989469
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17463810735127167 shares for $99.72534482187017
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 58th day, sold 0.09558950044927064 shares for $49.14447397097902
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17507663733900194 shares for $99.76041872213669
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17507663733900194 shares for $99.76041872213669
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1647013436594728 shares for $97.36319930429735
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 59th day, sold 0.09575609008732956 shares for $49.601654665236715
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 62th day, sold 0.09575609008732956 shares for $48.21606404167305
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.1647013436594728 shares for $99.034917942441

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 100.58540422917395, Final Money: 100.58540422917395, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 59th day, sold 0.09858432903505658 shares for $51.06668244015931
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.19198464209553492 shares for $107.5094797270786
On the 149th day, Bought 0.08949346697691068 shares for $50.00000000000001
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17853114772340262 shares for $101.94842659597182
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 59th day, sold 0.09858432903505658 shares for $51.06668244015931
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.19198464209553492 shares for $107.5094797270786
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17858724643109836 shares for $101.9804612020144
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19198464209553492 shares for $106.10223230051832
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17699524334172284 shares for $101.0713637578574
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 61th day, sold 0.09858432903505658 shares for $49.73086478173429
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 201th day, sold 0.08793218669761879 shares for $50.212795891808234
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 234th day, sold 0.08349615082744685 shares for $48.9370939999666
On the 52th day, Bought 0.09636882275846118 shares for $50.0
On the 61th day, sold 0.09636882275846118 shares for $48.61325264050574
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 234th day, sold 0.08349615082744685 shares for $48.9370939999666
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 126th day, sold 0.09598587087980649 shares for $53.04755140043385

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.1286854216627, Final Money: 108.1286854216627, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.19134559053660022 shares for $96.52428314618798
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.09554748710108925 shares for $53.05560863749284
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 211th day, Bought 0.08536064874093043 shares for $50.0
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.16830689957039294 shares for $98.64467383820731
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09554748710108925 shares for $53.107204280527434
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 211th day, Bought 0.08536064874093043 shares for $50.0
On the 234th day, sold 0.08536064874093043 shares for $50.029876227059326
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 120th day, sold 0.09506426344208685 shares for $53.361472355312195
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17871752061906143 shares for $102.05485297430883
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 121th day, sold 0.09443940767603505 shares for $52.55364158355999
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 201th day, sold 0.17670203616887734 shares for $100.90393073387571
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 128th day, sold 0.09443940767603505 shares for $52.38081746751284
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 104.56038154668136, Final Money: 104.56038154668136, Final Shares: 0.0
read  2517  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1899262858477388 shares for $104.96466113661131
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.17798507725619608 shares for $102.54254255961224
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17243352818983582 shares for $102.7031337251481
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.166739304078092 shares for $97.72590612016972
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 152th day, Bought 0.08894739650970417 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.1784969621943106 shares for $102.83745482900817
On the 196th day, Bought 0.08634982039237359 shares for $50.0
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17243352818983582 shares for $102.7031337251481
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.166739304078092 shares for $97.72590612016972
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.1737968507348 shares for $103.51514226615423
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.166739304078092 shares for $98.56793960576408
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 205th day, sold 0.08608370779746224 shares for $51.27231720124649
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 240th day, sold 0.166739304078092 shares for $98.07939344481528
On the 53th day, Bought 0.09626306771144183 shares for $50.0
On the 61th day, sold 0.09626306771144183 shares for $48.55990450703683
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09409816320385425 shares for $52.00429087624209
On the 197th day, Bought 0.08608370779746224 shares for $50.0
On the 206th day, sold 0.08608370779746224 shares for $51.494413167363945
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 240th day, sold 0.08349615082744685 shares for $49.11410583972079
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.09409816320385425 shares for $52.00429087624209
SPY Final Value: 108.20883840849149, Final Money: 108.20883840849149, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 122th day, Bought 0.5524861878453039 shares for $50.0
On the 125th day, sold 0.5524861878453039 shares for $50.73480662983425
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.1009008637772286 shares for $104.00210460103479
On the 212th day, Bought 0.5435373410153278 shares for $50.0
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 1.0782966993040979 shares for $97.72602985793038
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.0890283040146238 shares for $99.0144534010096
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0508631107789832 shares for $97.39399310699618
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5214308061320263 shares for $48.326207112316204
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5184570717544588 shares for $46.987764413106596
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 136th day, sold 0.5433010974682169 shares for $49.85874171465826

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 104.14398080940875, Final Money: 104.14398080940875, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.5710370031978073 shares for $52.97510278666058
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0877261845762307 shares for $98.97220553459123
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1143316711984972 shares for $102.32907736615799
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, sold 1.1009008637772286 shares for $101.01866326019851
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.5277601857715855 shares for $50.0
On the 176th day, sold 1.0634936048222658 shares for $103.073800179374
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.0554195515497262 shares for $99.27276301876725
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1014463109828538 shares for $93.10525666738063
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0862543025393099 shares for $98.8382789880518
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 125th day, sold 0.5577867023650156 shares for $51.22155287817938
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.1009008637772286 shares for $103.55073524688612
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 126th day, sold 0.541829215431296 shares for $49.26311226701343
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5514503143266791 shares for $51.108415131796626
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0966471303772733 shares for $92.69958193079091
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 228th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0478710816543884 shares for $88.57654253224545
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 234th day, sold 0.5357334190506804 shares for $45.28554591235402

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 101.23880353996609, Final Money: 101.23880353996609, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, Bought 0.0 shares for $0.0
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0913564946715506 shares for $97.66549270815706
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.0 shares for $0.0
On the 78th day, sold 0.5663797009515179 shares for $51.38196647032171
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.541829215431296 shares for $49.003034243606415
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.5567308762943993 shares for $49.16490368555841
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 173th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.052751541094044 shares for $98.91653480119636
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, sold 1.0643081826903797 shares for $97.799278907419
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 241th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0901937982874808 shares for $97.56144300874665
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.052751541094044 shares for $98.91653480119636
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5295488244016098 shares for $48.16246557932641
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0901937982874808 shares for $97.56144300874665
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 196th day, sold 0.5214308061320263 shares for $48.99363854416519
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5295488244016098 shares for $47.99300995551789
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 197th day, sold 0.5214308061320263 shares for $49.40035457294817
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 228th day, sold 0.5295488244016098 shares for $47.99300995551789
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 98.86959370904324, Final Money: 98.86959370904324, Final Shares: 0.0
read  2517  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, sold 1.0871888974428363 shares for $100.93461723859292
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.5538938739337543 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.1124282796531468 shares for $101.2420977312329
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.119772962379967 shares for $102.82875113535238
On the 135th day, Bought 0.5426524853483828 shares for $49.99999999999999
On the 139th day, sold 0.5426524853483828 shares for $48.013891903624916
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 154th day, Bought 0.5367686527106816 shares for $50.0
On the 163th day, sold 1.0882189670373608 shares for $98.81028220699235
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0691805544395634 shares for $103.62497933628248
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.5851375073142189 shares for $50.00000000000001
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.1536423396052933 shares for $98.52105580229205
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5585344057193924 shares for $50.832216264521904
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0691805544395634 shares for $103.62497933628248
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0547562682543004 shares for $97.75481094180856
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 238th day, sold 0.5915059742103396 shares for $50.514610197563
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0547562682543004 shares for $97.75481094180856
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 128th day, sold 0.5619240278714318 shares for $50.80355135985615
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0547562682543004 shares for $97.75481094180856
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 95th day, sold 0.5425935973955507 shares for $49.370591427021154
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5253756435851634 shares for $44.86707996217296
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5253756435851634 shares for $44.86707996217296
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
XLB Final Value: 104.53637447976251, Final Money: 104.53637447976251, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.579979120751653 shares for $55.753392877856406
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 151th day, Bought 0.5614192679092747 shares for $50.0
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 1.1145778031454734 shares for $94.01463769532067
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5389673385792821 shares for $48.641802306780214
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 34th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.579979120751653 shares for $55.753392877856406
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0679201308875026 shares for $95.98466136416873
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 128th day, sold 1.103184570749849 shares for $101.26131174912865
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 156th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.1014041492712865 shares for $99.91938442189111
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.1103815969501716 shares for $93.42750756738744
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 97th day, sold 0.5324246619103397 shares for $47.85432861250133
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 128th day, sold 0.5549389567147615 shares for $50.93784683684796
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 100.5661822489001, Final Money: 3.451953300404135, Final Shares: 1.1102575620040698
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 33th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 95th day, sold 0.5336179295624333 shares for $48.43116328708645
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 105th day, Bought 0.5664438654129376 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.1343675364715473 shares for $102.47876324483958
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 157th day, Bought 0.5477651183172656 shares for $50.00000000000001
On the 165th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1115901070407657 shares for $97.59761139817923
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 185th day, sold 0.5490282200505107 shares for $50.642363017459104
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 73th day, sold 0.5187260089220873 shares for $47.738354601099694
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 127th day, Bought 0.5413012882970661 shares for $50.0
On the 132th day, sold 1.0962402450118276 shares for $101.06238818764038
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.5874750323111267 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.151300021034627 shares for $101.08414184684024
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 185th day, sold 0.5490282200505107 shares for $50.642363017459104
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.117517062787762 shares for $94.58664419435617
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 179th day, sold 0.5610412926391383 shares for $50.89766606822262
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 197th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 100.60836885354888, Final Money: 49.55186640199622, Final Shares: 0.5837030119075415
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 59th day, Bought 0.511665984445354 shares for $50.0
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 62th day, sold 1.0317949764353676 shares for $97.4014457754987
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5201831044527674 shares for $48.14814814814815
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5299417064122947 shares for $48.91891891891892
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 110th day, sold 0.5585344057193924 shares for $51.100312779267206
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 134th day, Bought 0.5386770092652446 shares for $50.00000000000001
On the 136th day, sold 0.5386770092652446 shares for $48.879551820728295
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 176th day, sold 0.5736576411197798 shares for $50.0172097292336
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5420641803989593 shares for $50.482437120555076
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 74th day, sold 0.5201831044527674 shares for $48.14814814814815
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5299417064122947 shares for $48.484366719660834
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5420641803989593 shares for $50.482437120555076
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.5299417064122947 shares for $48.00741918388977
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5299417064122947 shares for $49.491255961844196
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 181th day, sold 0.5489679402722881 shares for $51.15283267457181
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 234th day, sold 0.5567928730512249 shares for $46.391982182628055
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 234th day, sold 0.5567928730512249 shares for $46.391982182628055

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 102.87018057535627, Final Money: 102.87018057535627, Final Shares: 0.0
read  2517  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 55th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.5612932195779076 shares for $52.986079928154474
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0533710046449274 shares for $96.94173355747267
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5328786102525844 shares for $49.66428647554087
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 219th day, sold 0.5534646889528448 shares for $52.645561213194604
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5152514427040396 shares for $47.41859027205276
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.545732372844357 shares for $50.52936040165902
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 224th day, sold 0.5389673385792821 shares for $49.902985879055734
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
XLE Final Value: 101.10603492416953, Final Money: 50.049532472616875, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 46th day, sold 2.2330456226880395 shares for $92.4927496917386
On the 53th day, Bought 1.2004801920768309 shares for $50.00000000000001
On the 55th day, sold 1.2004801920768309 shares for $49.90396158463386
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.4105140597728463 shares for $104.8332564595211
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2812835348939844 shares for $101.01523492510563
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 201th day, sold 2.132716457189094 shares for $99.46989556329935
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 237th day, sold 1.0062386798148522 shares for $49.295632924129606
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 96th day, sold 1.200192030724916 shares for $49.43590974555929
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.0 shares for $41.75
On the 124th day, sold 2.2068549360366885 shares for $95.97612116823558
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 165th day, sold 2.2812835348939844 shares for $101.24336327859503
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 124th day, sold 2.391777228919281 shares for $104.01839168569954
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2379022564825797 shares for $103.57011643001378
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 125th day, sold 2.3830007126571893 shares for $104.42309122863803

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 107.58850811571332, Final Money: 107.58850811571332, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.237623762376238 shares for $93.0180198019802
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 114th day, Bought 1.2135922330097086 shares for $50.0
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.4132083558504 shares for $103.40597804818964
On the 146th day, Bought 1.1507479861910241 shares for $50.0
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.293082918793263 shares for $107.3162805995247
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 215th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2330456226880395 shares for $92.8277065351418
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.4688340557083066 shares for $100.77780615401308
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.406471058877379 shares for $103.11728487289571
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2569046077068378 shares for $105.62313564068
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 38th day, Bought 1.2236906510034264 shares for $50.00000000000001
On the 39th day, Bought 1.0 shares for $41.16
On the 56th day, sold 2.2236906510034267 shares for $92.83908467939307
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 2.4688340557083066 shares for $102.16035322520973
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 2.4044597264558503 shares for $103.03109927863319
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 202th day, sold 2.119543035865786 shares for $98.09245169986858
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 96th day, sold 1.2357884330202669 shares for $50.90212555610479
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 127th day, sold 1.1976047904191616 shares for $51.31736526946108
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 127th day, sold 1.2330456226880395 shares for $52.8360049321825
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 127th day, sold 1.2330456226880395 shares for $52.8360049321825
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 127th day, sold 1.2330456226880395 shares for $52.8360049321825

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.50562013826152, Final Money: 14.571303840680365, Final Shares: 2.015524105733302
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 40th day, sold 2.2379301807378065 shares for $91.37468927952463
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4562839967441796 shares for $105.62021185999973
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 199th day, Bought 1.0608953957139826 shares for $50.0
On the 205th day, sold 1.0608953957139826 shares for $51.718650541056654
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4562839967441796 shares for $105.62021185999973
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2416863511451672 shares for $104.91092123359383
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 46th day, sold 1.2379301807378065 shares for $51.27506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.434057971873108 shares for $104.66449279054363
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.224231088111559 shares for $104.09401492362096
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 124th day, sold 1.2239902080783354 shares for $53.231334149326806
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.224231088111559 shares for $104.09401492362096
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 188th day, sold 2.230154423273064 shares for $104.59424245150669
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 188th day, sold 1.1138338159946535 shares for $52.238805970149244

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.8262011797535, Final Money: 112.8262011797535, Final Shares: 0.0
read  2517  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 73th day, Bought 1.2388503468780971 shares for $50.0
On the 90th day, sold 1.2388503468780971 shares for $51.54856293359762
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4260697616889684 shares for $104.53934603117766
On the 147th day, Bought 1.142334932602239 shares for $50.0
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2784403631861974 shares for $106.63100899711402
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.25 shares for $11.6575
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 229th day, Bought 1.008471157724889 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.0050826785540696 shares for $96.80539172059048
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 240th day, sold 2.029452284704046 shares for $97.98195630551135
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 1.0604453870625663 shares for $52.54506892895016
XLF Final Value: 108.48715001544299, Final Money: 108.48715001544299, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 53th day, Bought 0.39984006397441024 shares for $50.0
On the 55th day, sold 0.39984006397441024 shares for $50.24790083966413
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.7839155583232007 shares for $104.91141917039396
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7053194773636646 shares for $93.89212882665103
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7216760140645313 shares for $96.06951099227041
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 127th day, sold 0.40264132710581413 shares for $50.277822515703015
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39013732833957554 shares for $55.177122347066174
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 127th day, sold 0.7983397032568902 shares for $99.68867874568788

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 104.42296456596354, Final Money: 104.42296456596354, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 63th day, Bought 0.412847824291966 shares for $50.0
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.8271323549075928 shares for $100.98458921066802
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959566428887224 shares for $97.13058913171079
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.8250044961264706 shares for $104.40431898480486
On the 146th day, Bought 0.39323633503735744 shares for $50.0
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7846564070586507 shares for $110.97395565030497
On the 219th day, Bought 0.34921078362899843 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.704022024049095 shares for $93.1209931209738
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 68th day, sold 0.8262140082890491 shares for $100.87246827201001
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959566428887224 shares for $97.13058913171079
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4102732419791581 shares for $51.92007877246245
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 68th day, sold 0.4142845306156268 shares for $50.57999834286188
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 73th day, sold 0.4142845306156268 shares for $50.21957080122628
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 126th day, sold 0.39783577339274345 shares for $49.952259707192866

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 112.5406472170439, Final Money: 112.5406472170439, Final Shares: 0.0
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 102th day, Bought 0.40594300560201346 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.40594300560201346 shares for $50.77129171064382
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.390625 shares for $52.0234375
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 179th day, Bought 0.36965843560550055 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.7388255944950457 shares for $102.09092064732542
On the 193th day, Bought 0.36469730123997085 shares for $50.0
On the 196th day, sold 0.36469730123997085 shares for $49.380014587892056
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 235th day, sold 0.7053194773636646 shares for $94.3858524608056
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.796407374083437 shares for $97.18559185940181
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7951987310106663 shares for $97.03810114523161
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 205th day, sold 0.3691671588895452 shares for $51.89751919669227
On the 42th day, Bought 0.4102395799146702 shares for $50.0
On the 46th day, sold 0.4102395799146702 shares for $51.36609780111585
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 93th day, sold 0.3981842796846381 shares for $48.590427649916386

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 103.19156890633292, Final Money: 52.8883548372001, Final Shares: 0.37901758641600974
read  2517  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8002117420331725 shares for $96.9856631344205
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.4102732419791581 shares for $51.751866743251
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 206th day, sold 0.3924954863019075 shares for $55.769683648638036
On the 215th day, Bought 0.35539128580567203 shares for $50.0
On the 216th day, Bought 0 shares for $0.0
On the 221th day, Bought 0.3498215909885958 shares for $50.0
On the 232th day, Bought 0 shares for $0.0
On the 236th day, sold 0.7052128767942678 shares for $93.87793815885293
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 74th day, sold 0.4062728528479727 shares for $49.53278621922483
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8002117420331725 shares for $96.9856631344205
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.41473125414731254 shares for $52.314200398142006
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 206th day, sold 0.7773824257425743 shares for $110.45826887376239
On the 216th day, Bought 0 shares for $0.0
On the 232th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 74th day, sold 0.4062728528479727 shares for $49.53278621922483
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.8002117420331725 shares for $97.64983888030804
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 206th day, sold 0.3844083954793573 shares for $54.62058891366188
On the 216th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.8041086262407162 shares for $98.1253756601546
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 216th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 93th day, sold 0.7973244279149551 shares for $97.29749993846197
On the 197th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 93th day, sold 0.41145490454246214 shares for $50.20984200131666
On the 204th day, Bought 0 shares for $0.0
On the 204th day, Bought 0 shares for $0.0
XLI Final Value: 111.12976160075635, Final Money: 111.12976160075635, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.4805633476300063 shares for $96.84312581439887
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22687054766550208 shares for $50.79858432778257
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21791239921551536 shares for $50.66245369361517
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 36th day, sold 0.24321432045918862 shares for $50.430489347212756
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.24077819512664933 shares for $50.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 65th day, sold 0.4805633476300063 shares for $92.52286131920512
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 99th day, sold 0.24211902571304053 shares for $52.20086194373154
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 107th day, sold 0.47962836739164416 shares for $109.7437667428821
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 234th day, sold 0.21190930281839374 shares for $49.26679381224836
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.47962836739164416 shares for $107.60942050798928
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 234th day, sold 0.21190930281839374 shares for $49.26679381224836
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 37th day, sold 0.24321432045918862 shares for $50.29185718455102
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 52th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4794792546309228 shares for $107.58555515408645
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 205th day, sold 0.4506080448330224 shares for $106.98336200425618
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 126th day, sold 0.2400729821865847 shares for $53.867575743025874
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 205th day, sold 0.22700444928720603 shares for $53.895396349768454
On the 51th day, Bought 0.23940627244433804 shares for $50.0
On the 126th day, sold 0.23940627244433804 shares for $53.71797941106057

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 115.32683824366751, Final Money: 115.32683824366751, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 61th day, sold 0.24321432045918862 shares for $49.01254985893569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.4279497485115096 shares for $100.23439009636577
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4446063536548852 shares for $99.55180864686534
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.429830156314737 shares for $99.9312130416132
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2302343785974122 shares for $51.55177971174656
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 234th day, sold 0.429830156314737 shares for $99.9312130416132
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 110th day, sold 0.24321432045918862 shares for $55.08804358400622
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.2166283956501018 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4436328449373078 shares for $99.33383030991259
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 111th day, sold 0.24321432045918862 shares for $55.024807860686835
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.21711754744018413 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.44412199672739017 shares for $99.36785554778628
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 111th day, sold 0.24321432045918862 shares for $55.024807860686835
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 196th day, Bought 0.21711754744018413 shares for $50.0
On the 205th day, sold 0.21711754744018413 shares for $51.54804811324851
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 111th day, sold 0.23955538520505942 shares for $54.197010348792645
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 131th day, sold 0.4266667367659256 shares for $91.12321497109872

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 102.37761604503322, Final Money: 102.37761604503322, Final Shares: 0.0
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 40th day, Bought 0.23948654085640386 shares for $50.0
On the 62th day, sold 0.23948654085640386 shares for $48.31880448318804
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 84th day, sold 0.23999232024575212 shares for $50.947969664970714
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 109th day, Bought 0.22479992806402302 shares for $50.0
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4441558989335501 shares for $99.65970060270998
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 167th day, sold 0.44934504106442896 shares for $98.6761710177486
On the 170th day, Bought 0.22359359627940256 shares for $50.0
On the 171th day, Bought 0.2246888060036849 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44828240228308747 shares for $100.3749126952061
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.4325395099691013 shares for $102.72380822256187
On the 40th day, Bought 0.23948654085640386 shares for $50.0
On the 62th day, sold 0.23948654085640386 shares for $48.31880448318804
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 84th day, sold 0.23999232024575212 shares for $50.947969664970714
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 123th day, Bought 0.2134745111433695 shares for $50.0
On the 124th day, Bought 0.2141877998629198 shares for $50.0
On the 126th day, sold 0.42766231100628926 shares for $95.95886934359119
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 62th day, sold 0.24315518163692068 shares for $49.058989447065116
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 63th day, sold 0.24315518163692068 shares for $48.351407868501674
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 50th day, Bought 0.2400729821865847 shares for $50.0
On the 64th day, sold 0.2400729821865847 shares for $47.193546838238824

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 105.9762407841001, Final Money: 54.43717384343289, Final Shares: 0.21861746316295744
read  2517  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 114th day, Bought 0.21935597086952707 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.43277581037780777 shares for $97.10623633257251
On the 161th day, Bought 0.2451941938014908 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.2451941938014908 shares for $54.901431934091804
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 240th day, sold 0.4340538421757886 shares for $101.77260437495714
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 37th day, sold 0.2415692337423906 shares for $49.95168615325153
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 161th day, Bought 0.2451941938014908 shares for $50.0
On the 167th day, Bought 0.22768670309653916 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4728808968980299 shares for $105.88276162443788
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23999232024575212 shares for $54.295862532398964
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 62th day, sold 0.23978515250335697 shares for $48.3790523690773
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 101th day, Bought 0.22709724303946952 shares for $50.0
On the 126th day, sold 0.22709724303946952 shares for $50.95607939319617
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
XLK Final Value: 106.98049989718221, Final Money: 106.98049989718221, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 120th day, Bought 0.6459948320413437 shares for $50.00000000000001
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6459948320413437 shares for $50.2906976744186
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6051803437424352 shares for $48.32365044783345
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 232th day, sold 0.606354596167839 shares for $49.39970894979385
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 233th day, sold 0.6069434328720563 shares for $48.695071619325084
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.342552488151616 shares for $98.51650158056557
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 98th day, sold 0.6377551020408163 shares for $49.77678571428571
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 67th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 135th day, sold 1.2949284414746003 shares for $100.81017916879763
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2459530007464696 shares for $99.48934710960559
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 70th day, sold 0.6715014773032502 shares for $50.758796669352684
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2459530007464696 shares for $100.69792152032967
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 70th day, sold 0.6637461834594451 shares for $50.17257400769946
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 1.2459530007464696 shares for $100.34905468012067
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 70th day, sold 0.6637461834594451 shares for $50.17257400769946
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 103.19924583634169, Final Money: 103.19924583634169, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 52th day, sold 1.3424622931916024 shares for $101.16795841491916
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 79th day, sold 0.6600660066006601 shares for $50.943894389438945
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3015780808355715 shares for $101.97864263346702
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 137th day, sold 0.6411078343377357 shares for $50.81420694960893
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3403048587263708 shares for $99.89292112087642
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 239th day, sold 0.6046680372475511 shares for $47.950175353730806
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 53th day, sold 0.6693440428380187 shares for $49.88621151271754
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2348803404304947 shares for $100.25993483955186
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 54th day, sold 0.6637461834594451 shares for $49.25660427452542
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.649772579597141 shares for $50.487329434697855
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 205th day, sold 0.6126700159294204 shares for $48.92170077196421
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 138th day, sold 0.6459113809585325 shares for $50.18731430047798
On the 113th day, Bought 0.6529119874640898 shares for $50.0
On the 139th day, sold 0.6529119874640898 shares for $51.08383389919039

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.08383389919038, Final Money: 101.08383389919038, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 73th day, Bought 0.6664889362836577 shares for $50.0
On the 75th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 97th day, sold 0.6664889362836577 shares for $51.85950413223141
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 1.2964676982471979 shares for $99.27053165478793
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.2887473316145606 shares for $100.9733534320008
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.6036460219727152 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2096331750450702 shares for $98.54881477092187
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.2108811065041376 shares for $96.4587889441196
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.3403048587263708 shares for $99.46402356608397
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 228th day, Bought 0.6096817461285209 shares for $50.0
On the 234th day, sold 0.6096817461285209 shares for $48.56724789659797
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.3403048587263708 shares for $99.46402356608397
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 166th day, Bought 0.595734540688669 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.595734540688669 shares for $48.53449302990587
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2056191664391671 shares for $98.22179348979894
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 149th day, sold 0.6446621970087674 shares for $52.33367715317174
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 178th day, Bought 0.0 shares for $0.0
On the 183th day, sold 1.2056191664391671 shares for $97.72748963155888
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 183th day, sold 0.6033546518643659 shares for $48.9079280801255

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.06116678473063, Final Money: 100.06116678473063, Final Shares: 0.0
read  2517  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 37th day, Bought 0 shares for $0.0
On the 42th day, sold 1.342552488151616 shares for $101.30901075592094
On the 45th day, Bought 0.6578081831337982 shares for $50.0
On the 46th day, Bought 0.6610259122157589 shares for $50.00000000000001
On the 53th day, sold 1.318834095349557 shares for $98.29270512640248
On the 78th day, Bought 0.6534239414532149 shares for $50.0
On the 80th day, sold 0.6534239414532149 shares for $50.718766335598545
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.2824673952298562 shares for $98.108755735084
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6443298969072165 shares for $50.483247422680414
On the 132th day, Bought 0.6370238246910435 shares for $50.0
On the 133th day, Bought 0.0 shares for $0.0
On the 134th day, Bought 0.0 shares for $0.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6370238246910435 shares for $49.49675117849408
On the 143th day, Bought 0.6349206349206349 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0 shares for $0.0
On the 150th day, Bought 0 shares for $0.0
On the 151th day, Bought 0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 170th day, sold 0.6349206349206349 shares for $52.476190476190474
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0 shares for $0.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 217th day, sold 1.2234023176892586 shares for $100.6737767226491
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 236th day, sold 0.600817111271329 shares for $47.416486421533286
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 37th day, Bought 0 shares for $0.0
On the 42th day, sold 1.3403048587263708 shares for $101.13940463949193
On the 78th day, Bought 0.6534239414532149 shares for $50.0
On the 85th day, sold 0.6534239414532149 shares for $51.104286461055935
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.2824673952298562 shares for $98.108755735084
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.2961353981456472 shares for $101.55220844471145
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 135th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.2778882724426772 shares for $99.29191876879602
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0 shares for $0.0
On the 150th day, Bought 0 shares for $0.0
On the 151th day, Bought 0 shares for $0.0
On the 171th day, sold 0.6189650903689032 shares for $51.40505075513741
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0 shares for $0.0
On the 217th day, sold 0.6065752759917505 shares for $49.91507946136115
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 238th day, sold 0.600817111271329 shares for $47.879115597212206
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 37th day, Bought 0 shares for $0.0
On the 54th day, sold 1.3403048587263708 shares for $99.46402356608397
On the 87th day, Bought 0.6399590426212722 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.6399590426212722 shares for $48.956866760527326
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0 shares for $0.0
On the 150th day, Bought 0 shares for $0.0
On the 151th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 189th day, Bought 0.6065752759917505 shares for $50.0
On the 190th day, Bought 0 shares for $0.0
On the 217th day, sold 0.6065752759917505 shares for $49.91507946136115
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 238th day, sold 0.600817111271329 shares for $47.879115597212206
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 37th day, Bought 0 shares for $0.0
On the 54th day, sold 0.6637461834594451 shares for $49.25660427452542
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.642508352608584 shares for $50.34052942688255
On the 150th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.642508352608584 shares for $50.34052942688255
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 127th day, sold 0.642508352608584 shares for $50.173477255204325
On the 221th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
XLP Final Value: 100.39581986285012, Final Money: 100.39581986285012, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6838510315018442 shares for $97.07265392168678
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3485535029627048 shares for $50.08713837574068
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.3409943394939644 shares for $48.864488849485106
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6838510315018442 shares for $97.07265392168678
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 117th day, sold 0.34220792553555535 shares for $49.41824652658955
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6867669549229583 shares for $97.48656925131391
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 98.54139796381182, Final Money: 98.54139796381182, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 52th day, sold 0.6851745190905817 shares for $98.79531390767097
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6839719051540245 shares for $100.78326022444551
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.6470402507516887 shares for $98.84833910733549
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.33978933061501865 shares for $47.14576962283384
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6877579612666824 shares for $99.05777916124028
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.685095974452747 shares for $101.30514174232769
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 110th day, Bought 0.3409943394939644 shares for $50.0
On the 127th day, sold 0.3409943394939644 shares for $50.422832980972515
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 189th day, sold 0.321646831778707 shares for $49.302026375040214
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 209th day, sold 0.6788695024739367 shares for $99.67840904824814
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 53th day, sold 0.34298257648511454 shares for $49.39978049115105
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.15616518810998, Final Money: 100.15616518810998, Final Shares: 0.0
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, sold 0.6838510315018442 shares for $101.02531288376744
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 73th day, Bought 0.35566936975387675 shares for $50.0
On the 74th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7095264115090076 shares for $100.44055881321512
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6853774917644311 shares for $101.6209207039122
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 183th day, sold 0.6422609724625596 shares for $97.48879301009192
On the 191th day, Bought 0.3265199503689675 shares for $49.99999999999999
On the 194th day, sold 0.3265199503689675 shares for $49.10860053549272
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.3406690740614567 shares for $50.861892757375486
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 238th day, Bought 0.35816618911174786 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, sold 0.6838510315018442 shares for $101.02531288376744
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7088950308199609 shares for $100.35118056287367
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6858477175629567 shares for $101.6906410830596
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6412113233688959 shares for $98.00915077693573
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 207th day, sold 0.6759919900295339 shares for $100.92560411140943
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 51th day, sold 0.6838510315018442 shares for $100.16366058407512
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 93th day, sold 0.3538570417551309 shares for $50.116772823779186
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 123th day, sold 0.6833237186922686 shares for $100.96107943678268
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 188th day, sold 0.32026646169613116 shares for $48.95272867025365
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 207th day, sold 0.33532291596807723 shares for $50.063711354033934
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 211th day, sold 0.33532291596807723 shares for $47.56220240091208
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.37662387645369, Final Money: 2.001889418045863, Final Shares: 0.7079356250605053
read  2517  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 67th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 99th day, Bought 0.3414600833162603 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3414600833162603 shares for $50.31414327665096
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.32379225488926305 shares for $49.608211371584
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 107th day, sold 0.2811041772080733 shares for $50.90234440883791
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 107th day, sold 0.2811041772080733 shares for $50.90234440883791
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.26893287435456115 shares for $54.13080895008607
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.49849274560048373 shares for $99.67362448281672
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.49849274560048373 shares for $105.73529626931861
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.21477663230240548 shares for $49.16451890034364
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2794076557697681 shares for $52.46437552388936
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.500089566712886 shares for $106.07399799547025
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 116th day, sold 0.2794076557697681 shares for $52.46437552388936
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.500089566712886 shares for $107.57926759127604
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 208th day, sold 0.500089566712886 shares for $108.2843938803412

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 110.0436431151654, Final Money: 110.0436431151654, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 33th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 80th day, Bought 0.2807411566535654 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2807411566535654 shares for $52.71476698483998
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5404948991210178 shares for $108.53678069249158
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2702410550210788 shares for $48.32991027996974
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 73th day, sold 0.2897878752752985 shares for $50.57377999304509
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.2672082086361693 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5384461385482882 shares for $108.12536908188174
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4483236079159607 shares for $102.36572939545131
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 56th day, sold 0.2808199943836001 shares for $50.699241786015165
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5592375192127947 shares for $105.00802898258648
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5130302364012908 shares for $103.02160177174319
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.2594033722438392 shares for $52.212710765239954

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 113.44903305296457, Final Money: 113.44903305296457, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 52th day, Bought 0.2780403714619363 shares for $50.00000000000001
On the 55th day, sold 0.5519829530968257 shares for $98.7166313318363
On the 59th day, Bought 0.2777314891962451 shares for $50.0
On the 62th day, sold 0.2777314891962451 shares for $48.09476198411376
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 144th day, Bought 0.2808988764044944 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.2808988764044944 shares for $56.16573033707865
On the 202th day, Bought 0.25075225677031093 shares for $50.0
On the 205th day, sold 0.25075225677031093 shares for $53.187061183550654
On the 240th day, Bought 0.22119000221190002 shares for $50.0
On the 242th day, sold 0.22119000221190002 shares for $48.971466489714665
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5397879783097215 shares for $114.49442807927502
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5242531856296496 shares for $111.19934320390499
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5609340406510999 shares for $105.32658481305702
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 205th day, sold 0.5042888059092354 shares for $106.96469862140793
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.252691160863193 shares for $53.59832213069187
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 63th day, sold 0.27625835681529365 shares for $47.60760262997956
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 63th day, sold 0.27625835681529365 shares for $47.60760262997956

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 115.23764825890167, Final Money: 115.23764825890167, Final Shares: 0.0
read  2517  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 78th day, sold 0.2897878752752985 shares for $51.53877361771183
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 86th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5610292104393202 shares for $103.4818378655326
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5022116493566033 shares for $106.52411294502915
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 211th day, sold 0.2309148847734725 shares for $49.28647300604997
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 58th day, sold 0.2739425816348893 shares for $48.923405654174886
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2897878752752985 shares for $53.4513735945288
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5615154347173892 shares for $103.57152193362244
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5617212209748524 shares for $103.60947920881152
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 126th day, sold 0.26116479498563594 shares for $49.49072864977801
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.2602133749674733 shares for $55.19385896435077
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
XLY Final Value: 113.39329791188464, Final Money: 113.39329791188464, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 31th day, Bought 0.8101101749837978 shares for $50.0
On the 33th day, sold 0.8101101749837978 shares for $50.69669475048607
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.5797807628673954 shares for $101.42192497608679
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.4012495930161712 shares for $100.11928342100543
On the 110th day, Bought 0.7237984944991315 shares for $50.0
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4575818816432466 shares for $102.13276244674228
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3327280241967356 shares for $106.29838720993165
On the 213th day, Bought 0.6215040397762586 shares for $50.0
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2426992193016655 shares for $94.81795043271707
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 31th day, Bought 0.8101101749837978 shares for $50.0
On the 62th day, sold 0.8101101749837978 shares for $50.85061568373299
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 104th day, sold 1.38169891063517 shares for $96.63602180982379
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.7265329845975008 shares for $50.90816623074688
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 153th day, Bought 0.6586747464102226 shares for $49.99999999999999
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.3226853705802095 shares for $105.49738515747752
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.6923289947382997 shares for $48.42148989199668
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7197351374694113 shares for $50.47502519072981
On the 153th day, Bought 0.6586747464102226 shares for $49.99999999999999
On the 154th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.6586747464102226 shares for $52.450270056646026
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6923289947382997 shares for $48.553032400996955
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 63th day, sold 0.7829627309740056 shares for $50.17225180081428
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 138th day, sold 1.3805014311268045 shares for $99.7550334132229
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 63th day, sold 0.7793017456359103 shares for $49.937655860349125
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6861534239055852 shares for $49.58144641141759
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 63th day, sold 0.7793017456359103 shares for $49.937655860349125
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 138th day, sold 0.6861534239055852 shares for $49.58144641141759

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 108.67124645737019, Final Money: 58.140238197241686, Final Shares: 0.6555657532450505
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 51th day, sold 0.7862871520679352 shares for $51.30523667243277
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 71th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7554011179936546 shares for $54.93276930049856
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4688613054034505 shares for $102.92311166961977
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2317703413278247 shares for $93.68845216139435
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 51th day, sold 0.7862871520679352 shares for $51.30523667243277
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7115411982353779 shares for $51.15269674114131
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 124th day, sold 0.7068136839129207 shares for $49.526434831778346
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2317703413278247 shares for $93.68845216139435
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 95th day, sold 0.7862871520679352 shares for $56.52618336216386
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 124th day, sold 0.7068136839129207 shares for $49.526434831778346
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 95th day, sold 0.7843137254901961 shares for $56.384313725490195
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 173th day, sold 1.346354675156112 shares for $107.38524889045149
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 96th day, sold 0.7843137254901961 shares for $56.36078431372549
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 202th day, sold 1.3389713616283672 shares for $103.36858911770994
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 125th day, sold 0.7843137254901961 shares for $54.98823529411764
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 204th day, sold 0.6716818914562064 shares for $52.0889306824288

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 114.20833418147663, Final Money: 64.53698478078067, Final Shares: 0.6444129398118313
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 50th day, sold 0.7827175954915466 shares for $51.38541014402004
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 62th day, sold 1.5204614416688504 shares for $95.43936469355374
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7063144511936713 shares for $50.33196779206102
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 168th day, sold 0.6716818914562064 shares for $53.1166039763568
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 184th day, sold 0.6140243153628884 shares for $48.3851160505956
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2216852740530135 shares for $97.6248702495763
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 216th day, sold 0.6403688524590164 shares for $52.15804303278689
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 1.3195363630238734 shares for $99.26872059028601
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7063144511936713 shares for $50.33196779206102
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 184th day, sold 0.6140243153628884 shares for $48.3851160505956
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 1.2216852740530135 shares for $94.31410315689264
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 0.6676458806249166 shares for $50.22699959941248
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 109th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.2309103603960099 shares for $92.60138641259182
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 1.2896911655216572 shares for $97.02346638219427
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 63th day, sold 0.7623113279463333 shares for $48.84890989480103
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0

[*********************100%***********************]  1 of 1 completed

On the 242th day, Bought 0.6555657532450505 shares for $50.0
XLU Final Value: 100.53100826012849, Final Money: 50.0, Final Shares: 0.6555657532450505
read  2517  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.428063510802319 shares for $102.09226038725778
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 164th day, sold 1.352185047296217 shares for $104.49686045505165
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 189th day, sold 0.6345177664974619 shares for $52.16370558375634
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.439698010984607 shares for $102.92401080528954
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.352185047296217 shares for $108.28297858748105
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 189th day, sold 0.6345177664974619 shares for $52.16370558375634
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 62th day, sold 0.7880220646178092 shares for $49.464144996059886
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6741270055278414 shares for $53.98409060266954
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 66th day, sold 0.7827175954915466 shares for $51.682842830306825
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 172th day, sold 1.3487087648370697 shares for $108.34177507936181
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 66th day, sold 0.7793017456359103 shares for $51.457294264339154
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
XLU Final Value: 112.00883206196528, Final Money: 13.714780054160485, Final Shares: 1.2752212248028645

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 58th day, sold 0.09840969925995907 shares for $50.59439458353016
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1899262858477388 shares for $104.96466113661131
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.1750799086196722 shares for $103.47922919057106
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.16507664932143729 shares for $98.16943258496555
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 58th day, sold 0.09840969925995907 shares for $50.59439458353016
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18895217823179206 shares for $103.73285632747152
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.174860422392223 shares for $104.14861618103194
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.16507664932143729 shares for $98.16943258496555
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 59th day, sold 0.09749439407234084 shares for $50.502096129472555
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18895217823179206 shares for $103.73285632747152
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17463810735127167 shares for $104.01620311949092
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.1647013436594728 shares for $99.034917942441
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 59th day, sold 0.09858432903505658 shares for $51.06668244015931
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18895217823179206 shares for $103.73285632747152
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17507663733900194 shares for $104.27739596548295
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.1647013436594728 shares for $99.034917942441
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 61th day, sold 0.09858432903505658 shares for $49.73086478173429
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17507663733900194 shares for $104.27739596548295
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.1647013436594728 shares for $99.04150599618738
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 127th day, sold 0.18867154268899677 shares for $103.57879022083235
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.1647013436594728 shares for $99.04150599618738
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 206th day, sold 0.08793218669761879 shares for $52.60015476064859
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.08226254915187313 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 108.11185267555479, Final Money: 108.11185267555479, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.19198464209553492 shares for $106.92392656868724
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 33th day, Bought 0.09858432903505658 shares for $50.0
On the 60th day, sold 0.09858432903505658 shares for $50.36180448755866
On the 80th day, Bought 0.09599877121572843 shares for $50.0
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19198464209553492 shares for $106.10223230051832
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.1785952662739861 shares for $102.99589006020778
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.1664768163323842 shares for $97.57206205241039
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17825237578963055 shares for $102.79814511787994
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 234th day, sold 0.1662899446046653 shares for $97.46253653279435
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.19008403408366076 shares for $105.05184227667594
On the 199th day, Bought 0.08620541025154739 shares for $50.0
On the 204th day, sold 0.08620541025154739 shares for $50.95084567507457
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 126th day, sold 0.09554748710108925 shares for $52.80527422128798
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.03198890069515, Final Money: 107.03198890069515, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 46th day, sold 0.09759906304899474 shares for $50.86960765176655
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.19134559053660022 shares for $96.52428314618798
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 106th day, sold 0.09437879874664956 shares for $51.76582732454982
On the 110th day, Bought 0.09177174531505239 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09177174531505239 shares for $51.008571481012424
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.08230994633391499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1652561971633775 shares for $97.6912009531306
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 61th day, sold 0.09759906304899474 shares for $49.23384735506539
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 120th day, sold 0.09506426344208685 shares for $53.361472355312195
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.08230994633391499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1652561971633775 shares for $97.6912009531306
On the 38th day, Bought 0.09675297031618871 shares for $50.0
On the 61th day, sold 0.09675297031618871 shares for $48.80703587600139
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.09506426344208685 shares for $52.72739371815347
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1791071512121006 shares for $102.05704583216703
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.08230994633391499 shares for $50.0
On the 235th day, sold 0.1652561971633775 shares for $97.6912009531306
On the 38th day, Bought 0.09675297031618871 shares for $50.0
On the 62th day, sold 0.09675297031618871 shares for $48.718023143310496
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 131th day, sold 0.09506426344208685 shares for $51.18355007985398
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.08955758552749418 shares for $51.030807809421454
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 131th day, sold 0.09506426344208685 shares for $51.18355007985398
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17507663733900194 shares for $99.76041872213669
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 139th day, sold 0.09443940767603505 shares for $49.3115367180417
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 202th day, sold 0.08714445064138315 shares for $49.65577941996653
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 139th day, sold 0.09443940767603505 shares for $49.3115367180417
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 202th day, sold 0.08714445064138315 shares for $49.65577941996653

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 102.04448721167351, Final Money: 102.04448721167351, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 160th day, Bought 0.0909735994614363 shares for $50.0
On the 161th day, Bought 0.09253090532237768 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.18350450478381397 shares for $109.77055971662969
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.166739304078092 shares for $98.56793960576408
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 161th day, Bought 0.09253090532237768 shares for $50.0
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.1815939619664817 shares for $108.6276921087297
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.1664768163323842 shares for $100.10916873331593
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.18867154268899677 shares for $104.27121478250095
On the 173th day, Bought 0.08751969193068442 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.17523283486802216 shares for $104.82252948970219
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.08298066550493735 shares for $50.0
On the 239th day, sold 0.1664768163323842 shares for $99.05537048593192
On the 85th day, Bought 0.09443762394938142 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18853578715323566 shares for $103.50426178925484
On the 173th day, Bought 0.08751969193068442 shares for $50.0
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.17523283486802216 shares for $103.075458126068
On the 86th day, Bought 0.09432894389314418 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18842710709699845 shares for $103.44459752518118
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 240th day, sold 0.1750799086196722 shares for $102.98550384826359
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.09436989222958307 shares for $50.0
On the 127th day, sold 0.1884680554334373 shares for $103.46707775240274
SPY Final Value: 112.90053863361108, Final Money: 112.90053863361108, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.5418879375745096 shares for $50.0
On the 228th day, sold 1.0766472958632796 shares for $97.57654442408902
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0915254873792657 shares for $101.16258217031036
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0905266638466782 shares for $98.26735767922418
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.039887877886485 shares for $96.37680852251944
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0905266638466782 shares for $98.26735767922418
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.039887877886485 shares for $96.37680852251944
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 128th day, sold 1.089819163774012 shares for $98.53055059680842
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 192th day, Bought 0.5161023947151115 shares for $50.00000000000001
On the 209th day, sold 1.0345594664695703 shares for $95.88297135239978
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 133th day, sold 0.5425935973955507 shares for $49.64188822571893

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.89484018806405, Final Money: 100.89484018806405, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 66th day, Bought 0.5614823133071308 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5614823133071308 shares for $50.02245929253229
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.0844228128268467 shares for $99.25722005804128
On the 102th day, Bought 0.5565449688334817 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5565449688334817 shares for $51.10752448797862
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.0966471303772733 shares for $106.47346988832948
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0788882080003819 shares for $91.78101985459247
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 94th day, sold 1.0844228128268467 shares for $99.25722005804128
On the 103th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5567308762943993 shares for $51.12459637011469
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1014463109828538 shares for $93.70003767531136
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.5463286713286714 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0915254873792657 shares for $105.79065023679843
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0508631107789832 shares for $97.39399310699618
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1014463109828538 shares for $93.70003767531136
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.5161023947151115 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0282400573188193 shares for $87.47238167611195
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 74th day, sold 0.5659950192438307 shares for $50.164138555580706
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.5161023947151115 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0282400573188193 shares for $87.47238167611195
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 237th day, sold 1.12406038784663 shares for $96.14088497252226
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 238th day, sold 0.5555555555555556 shares for $47.44444444444445
XLB Final Value: 98.6096742816942, Final Money: 98.6096742816942, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 81th day, sold 0.5619871866921434 shares for $51.579183994604925
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.541829215431296 shares for $47.198742956220194
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5279273571956499 shares for $50.015837820715866
On the 203th day, Bought 0.533731853116994 shares for $50.0
On the 210th day, sold 0.533731853116994 shares for $49.06063193851409
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5295488244016098 shares for $48.16246557932641
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.541829215431296 shares for $47.198742956220194
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.524824183898394 shares for $49.721843182533846
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5295488244016098 shares for $47.99300995551789
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 109th day, Bought 0.5568548836173293 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5568548836173293 shares for $48.50762891190555
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.524824183898394 shares for $49.721843182533846
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 109th day, Bought 0.5568548836173293 shares for $50.0
On the 115th day, sold 0.5568548836173293 shares for $48.50762891190555
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.524824183898394 shares for $49.721843182533846
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 109th day, Bought 0.5568548836173293 shares for $50.0
On the 115th day, sold 0.5568548836173293 shares for $48.50762891190555
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 211th day, sold 0.5214308061320263 shares for $47.596203983731364
On the 109th day, Bought 0.5568548836173293 shares for $50.0
On the 115th day, sold 0.5568548836173293 shares for $48.50762891190555
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 211th day, sold 0.5214308061320263 shares for $47.596203983731364

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5619871866921434 shares for $50.06743846240306
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.0844228128268467 shares for $98.69332019537133
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5619240278714318 shares for $51.60148347943358
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 163th day, sold 0.5514503143266791 shares for $50.07168854086246
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.0691805544395634 shares for $103.80674003053721
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.0938814610365155 shares for $92.91429130044162
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 73th day, sold 0.5585344057193924 shares for $49.75983020554067
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5425935973955507 shares for $49.38144329896907
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 163th day, sold 0.5514503143266791 shares for $50.07168854086246
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 175th day, sold 0.5334471353888829 shares for $51.792382374906644
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5653550429669832 shares for $48.02125734961555
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5685048322910744 shares for $47.3052870949403
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0547562682543004 shares for $98.69354402055488
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 242th day, sold 1.1600108065014139 shares for $96.52449920898265
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, sold 0.5253756435851634 shares for $43.716507302721446
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 242th day, sold 0.529380624669137 shares for $44.04976177871889
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
XLB Final Value: 97.43082999910408, Final Money: 97.43082999910408, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 33th day, Bought 0.5757052389176742 shares for $50.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.144792423074287 shares for $110.0488956301312
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 151th day, Bought 0.5614192679092747 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 1.125244256632775 shares for $101.04693424562319
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 190th day, Bought 0.5516328331862312 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 226th day, sold 1.108549741183558 shares for $100.73391498134993
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0679201308875026 shares for $95.98466136416873
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.1036056965369934 shares for $101.29996688513063
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 155th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 156th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.1101374814320324 shares for $100.71167231551398
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.108588481558596 shares for $100.05011046066329
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 38th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.0679201308875026 shares for $96.475904624377
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 108.18029834864997, Final Money: 6.656452255278708, Final Shares: 1.160670470942852
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 32th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.1428764887239757 shares for $108.83612802118421
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 95th day, sold 0.5343022013250694 shares for $48.4932677922633
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.1316215290067495 shares for $102.23068893046975
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 157th day, Bought 0.5477651183172656 shares for $50.00000000000001
On the 165th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1115901070407657 shares for $97.59761139817923
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.117517062787762 shares for $104.07436405742426
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0451065062759581 shares for $87.71578907174117
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 0.5346449957228401 shares for $49.20337895637297
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1248662813626384 shares for $98.76325950363965
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.117517062787762 shares for $94.58664419435617
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.5610412926391383 shares for $50.381508078994614
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.117517062787762 shares for $94.50841799996103
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.5610412926391383 shares for $50.89766606822262
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 100.67513356242216, Final Money: 49.6186311108695, Final Shares: 0.5837030119075415
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 47th day, Bought 0.536135535063264 shares for $50.0
On the 52th day, sold 0.536135535063264 shares for $51.70491100150117
On the 59th day, Bought 0.511665984445354 shares for $50.0
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 62th day, sold 1.0317949764353676 shares for $97.4014457754987
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0548281001756075 shares for $97.07583005916116
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5299417064122947 shares for $48.91891891891892
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 103th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5585344057193924 shares for $51.100312779267206
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 134th day, Bought 0.5386770092652446 shares for $50.00000000000001
On the 136th day, sold 0.5386770092652446 shares for $48.879551820728295
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 161th day, sold 0.5489679402722881 shares for $47.21673254281951
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5420641803989593 shares for $50.482437120555076
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 40th day, sold 0.5737893045673629 shares for $52.38122561395456
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 110th day, sold 1.063559635974728 shares for $97.30507109532785
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5389673385792821 shares for $50.194028241888546
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 110th day, sold 0.5585344057193924 shares for $51.100312779267206
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 125th day, sold 1.1012079395619154 shares for $102.65460412596175
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 205th day, sold 1.1137718192470587 shares for $103.72556952647857
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 125th day, sold 0.546268982847154 shares for $50.92319458101169
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 108.69401611813176, Final Money: 56.967227235813596, Final Shares: 0.5913660555884093
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5152514427040396 shares for $50.35037098103874
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0533710046449274 shares for $97.50002018993447
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5336179295624333 shares for $49.73319103521878
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5520591807441758 shares for $48.13403996908469
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 218th day, sold 0.5534646889528448 shares for $52.700907682089884
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 237th day, sold 0.5948839976204641 shares for $50.35098155859608
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.5152514427040396 shares for $48.639736191261335
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 0.5339028296849972 shares for $48.45702082221035
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 185th day, Bought 0.5420641803989593 shares for $50.00000000000001
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.5420641803989593 shares for $49.132697311361675
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5551237926057512 shares for $51.3989119573665
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 237th day, sold 0.5948839976204641 shares for $50.35098155859608
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
XLE Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 2.4044597264558503 shares for $104.08906155827376
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, sold 2.2812835348939844 shares for $101.24336327859503
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 236th day, sold 0.9966115208291807 shares for $48.25592983854893
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.3943644692250357 shares for $102.59851750629278
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.276626291211212 shares for $105.36226475725489
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 55th day, sold 1.2376237623762376 shares for $51.448019801980195
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.379568360738147 shares for $101.9645042576296
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 203th day, sold 1.1133377866844802 shares for $52.004008016032074
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 55th day, sold 1.2376237623762376 shares for $51.448019801980195
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 85th day, Bought 1.1767474699929394 shares for $50.0
On the 127th day, sold 2.362143392230967 shares for $101.21784435709694

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 110.19532366166368, Final Money: 110.19532366166368, Final Shares: 0.0
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.237623762376238 shares for $93.0180198019802
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 91th day, sold 2.4688340557083066 shares for $101.59252139239682
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.403275246576849 shares for $103.55713037499643
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2812835348939844 shares for $106.76406943303846
On the 191th day, Bought 1.0499790004199916 shares for $50.0
On the 192th day, Bought 1.0584250635055037 shares for $50.0
On the 194th day, Bought 0.25 shares for $11.7775
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.3584040639254953 shares for $109.14694007847193
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 216th day, Bought 0.9856100926473488 shares for $50.0
On the 240th day, sold 1.9822216134765296 shares for $95.70165949864685
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.237623762376238 shares for $93.42079207920793
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.4688340557083066 shares for $100.77780615401308
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.2379022564825797 shares for $110.88805680871182
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 35th day, Bought 1.2330456226880395 shares for $50.0
On the 59th day, sold 1.2330456226880395 shares for $50.06165228113441
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, sold 2.4688340557083066 shares for $100.77780615401308
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 126th day, Bought 1.155001155001155 shares for $50.0
On the 128th day, sold 2.3526059454203168 shares for $101.37379018816145
On the 157th day, Bought 1.0931351114997814 shares for $50.0
On the 158th day, Bought 1.1013215859030838 shares for $50.00000000000001
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.194456697402865 shares for $108.73532935631195
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 80th day, Bought 1.1953143676786995 shares for $50.0
On the 128th day, sold 1.1953143676786995 shares for $51.50609610327516
On the 80th day, Bought 1.1953143676786995 shares for $50.0
On the 129th day, sold 1.1953143676786995 shares for $51.60172125268946
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 129th day, sold 1.200192030724916 shares for $51.81228996639463

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 116.2601784520053, Final Money: 67.83482465491542, Final Shares: 0.9966115208291807
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 87th day, Bought 1.1853959222380275 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4028295721041095 shares for $103.3216716004767
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 199th day, Bought 1.0608953957139826 shares for $50.0
On the 205th day, sold 1.0608953957139826 shares for $51.718650541056654
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 89th day, Bought 1.2088974854932302 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4263311353593124 shares for $104.33223882045044
On the 167th day, Bought 1.1088933244621866 shares for $50.0
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.225213931740597 shares for $104.14001200545992
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 123th day, sold 1.2100677637947725 shares for $52.03291384317522
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 178th day, Bought 1.109139307897072 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2254599151754824 shares for $104.15152403021257
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 123th day, sold 1.2100677637947725 shares for $52.03291384317522
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.224231088111559 shares for $104.09401492362096
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 187th day, sold 2.221744296827802 shares for $103.97763309154114
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 187th day, sold 1.1138338159946535 shares for $52.12742258854978

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.50418978689936, Final Money: 112.50418978689936, Final Shares: 0.0
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.255802452049888 shares for $105.57155475593474
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.0058969467476304 shares for $97.78747615394698
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 240th day, sold 2.029452284704046 shares for $97.98195630551135
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0 shares for $49.1
On the 240th day, sold 2.0111223458038423 shares for $97.09698685540951
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 203th day, sold 2.132716457189094 shares for $99.61918571530258
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 90th day, sold 1.2330456226880395 shares for $51.30702836004932
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 91th day, sold 1.2330456226880395 shares for $50.739827373612826
XLF Final Value: 107.0972571516929, Final Money: 107.0972571516929, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7959566428887224 shares for $96.86792343955752
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4049566696363489 shares for $50.84635943953997
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39142007202129325 shares for $55.358540785971506
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7105312176540179 shares for $94.58591569410287
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39142007202129325 shares for $55.358540785971506
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7216760140645313 shares for $96.06951099227041
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3924954863019075 shares for $55.51063662767878
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7966308196124732 shares for $99.47529044500953
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 127th day, sold 0.39939292275740873 shares for $49.87219426471763

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 104.6953547294366, Final Money: 104.6953547294366, Final Shares: 0.0
read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 33th day, Bought 0.41335978835978837 shares for $50.0
On the 48th day, sold 0.41335978835978837 shares for $51.23594576719577
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8293256196834445 shares for $100.53085161802714
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.8250044961264706 shares for $104.40431898480486
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.7303689539425081 shares for $98.05933575632113
On the 33th day, Bought 0.41335978835978837 shares for $50.0
On the 49th day, sold 0.41335978835978837 shares for $52.05853174603175
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.82697056674124 shares for $100.24537210037312
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 126th day, sold 0.8272044433900118 shares for $103.86378991204988
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7807623283395755 shares for $110.42321609706616
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 33th day, Bought 0.41335978835978837 shares for $50.0
On the 50th day, sold 0.41335978835978837 shares for $52.06679894179894
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7773824257425743 shares for $109.9451964727723
On the 33th day, Bought 0.41335978835978837 shares for $50.0
On the 50th day, sold 0.41335978835978837 shares for $52.06679894179894
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.8097652510661657 shares for $98.79136063007222
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.7739341331918541 shares for $109.45750445732394
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3869370066553165 shares for $54.3956043956044
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 154th day, Bought 0.3869370066553165 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3869370066553165 shares for $54.3956043956044
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 113.76268524184022, Final Money: 65.07239248375085, Final Shares: 0.3668647736444347
read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 45th day, sold 0.40997048212528703 shares for $51.508691374221065
On the 73th day, Bought 0.4124731892426992 shares for $50.0
On the 78th day, sold 0.4124731892426992 shares for $51.29104108232964
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 102th day, Bought 0.40594300560201346 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.40594300560201346 shares for $50.410002435658036
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.7773824257425743 shares for $99.36502165841584
On the 165th day, Bought 0.38681726752282225 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.38681726752282225 shares for $53.45041002630358
On the 193th day, Bought 0.36469730123997085 shares for $50.0
On the 200th day, Bought 0.3736083090487932 shares for $50.0
On the 205th day, sold 0.7383056102887641 shares for $103.79100269439446
On the 211th day, Bought 0.3594277909567967 shares for $50.0
On the 222th day, Bought 0.3520383017672323 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.711466092724029 shares for $94.10562008460732
On the 239th day, Bought 0.375206363499925 shares for $50.0
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 45th day, sold 0.40997048212528703 shares for $51.508691374221065
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7951987310106663 shares for $97.03810114523161
On the 102th day, Bought 0.40594300560201346 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.40594300560201346 shares for $50.77129171064382
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.38675742574257427 shares for $49.43533415841584
On the 165th day, Bought 0.38681726752282225 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.38681726752282225 shares for $53.45041002630358
On the 193th day, Bought 0.36469730123997085 shares for $50.0
On the 205th day, sold 0.36469730123997085 shares for $51.269146608315104
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 234th day, sold 0.35050823694356814 shares for $46.36172450052576
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 45th day, sold 0.40997048212528703 shares for $51.508691374221065
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7976729342068497 shares for $97.34002816126187
On the 153th day, Bought 0.3871767074492799 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.3871767074492799 shares for $53.5000774353415
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 45th day, sold 0.40970173713536545 shares for $51.474926253687315
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7976729342068497 shares for $97.34002816126187
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3691671588895452 shares for $51.89751919669227
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 46th day, sold 0.40970173713536545 shares for $51.298754506719106
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 93th day, sold 0.7976729342068497 shares for $97.34002816126187
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 46th day, sold 0.40970173713536545 shares for $51.298754506719106
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 93th day, sold 0.3981842796846381 shares for $48.590427649916386

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 102.65201103995724, Final Money: 52.348796970824424, Final Shares: 0.37901758641600974
read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 76th day, Bought 0.40319329086364003 shares for $50.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8052841634008334 shares for $97.60044060418102
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.41044163519947463 shares for $51.77310786406173
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 230th day, Bought 0.3638215818962381 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.7143298188398062 shares for $94.23438970134723
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7988815772796203 shares for $96.82444716628999
On the 119th day, Bought 0.4137702747434624 shares for $50.0
On the 128th day, sold 0.4137702747434624 shares for $52.19298245614035
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7773824257425743 shares for $109.28442141089111
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 242th day, sold 0.3668647736444347 shares for $48.16934477951428
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.4062728528479727 shares for $49.24839522223125
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7988815772796203 shares for $96.82444716628999
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3681885125184094 shares for $52.31590574374079
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 92th day, sold 0.3994886545222116 shares for $48.418024928092045
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 206th day, sold 0.3681885125184094 shares for $52.31590574374079
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 92th day, sold 0.41145490454246214 shares for $49.86833443054641
XLI Final Value: 107.49252529384583, Final Money: 107.49252529384583, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 151th day, Bought 0.22687054766550208 shares for $50.0
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.4501247001927391 shares for $100.71090042112345
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4365298623784728 shares for $101.48882770437115
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 108th day, sold 0.2415692337423906 shares for $55.17682867909944
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.4508200898496105 shares for $100.86648690295185
On the 212th day, Bought 0.21791239921551536 shares for $50.0
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.4340538421757886 shares for $102.41934459979908
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 115th day, sold 0.2415692337423906 shares for $55.33868006570684
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.44873755024886464 shares for $101.81406277596489
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.20735702732965622 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.4234984702899294 shares for $99.92869904961174
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 116th day, sold 0.2415692337423906 shares for $56.08512899797082
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 125th day, sold 0.2415692337423906 shares for $54.198473282442755
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 125th day, sold 0.2415692337423906 shares for $54.198473282442755
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 176th day, Bought 0.22212350066637052 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.44572709621218687 shares for $107.21073845191731
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 126th day, sold 0.2415692337423906 shares for $54.2033046671176
On the 178th day, Bought 0.22700444928720603 shares for $50.0

[*********************100%***********************]  1 of 1 completed

On the 237th day, sold 0.22700444928720603 shares for $54.60138018705167
XLK Final Value: 112.10954950195686, Final Money: 112.10954950195686, Final Shares: 0.0

read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 62th day, sold 0.24321432045918862 shares for $49.07092129584589
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 157th day, Bought 0.22693232877955793 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22693232877955793 shares for $50.81241773703081
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.21590810950859313 shares for $51.401243630710766
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 76th day, sold 0.23955538520505942 shares for $49.09208509007283
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 237th day, sold 0.21590810950859313 shares for $51.93237758010191
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22700444928720603 shares for $50.78997548351948
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.2134198395082807 shares for $47.88714358886802
On the 197th day, Bought 0.21718356354791069 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.21718356354791069 shares for $48.59265050820954

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 101.55833773583441, Final Money: 101.55833773583441, Final Shares: 0.0
read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 62th day, sold 0.2415692337423906 shares for $48.739008599864725
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 123th day, Bought 0.2134745111433695 shares for $50.0
On the 124th day, Bought 0.2141877998629198 shares for $50.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42766231100628926 shares for $95.95886934359119
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 62th day, sold 0.2415692337423906 shares for $48.739008599864725
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.2323528044983503 shares for $52.70226311631581
On the 124th day, Bought 0.2141877998629198 shares for $50.0
On the 125th day, Bought 0.22285612408628988 shares for $50.0
On the 126th day, sold 0.43704392394920966 shares for $98.06391565572366
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.22609088853719195 shares for $50.58557540131133
On the 229th day, Bought 0.21005755577028107 shares for $50.0
On the 32th day, Bought 0.2372366672992978 shares for $50.0
On the 62th day, sold 0.2372366672992978 shares for $47.86486999430632
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.2323528044983503 shares for $52.89976300013941
On the 155th day, Bought 0.22787348464132715 shares for $50.0
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.45782197617922266 shares for $102.43308895033928
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 62th day, sold 0.24315518163692068 shares for $49.058989447065116
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 105th day, sold 0.2323528044983503 shares for $53.70138017565872
On the 155th day, Bought 0.22787348464132715 shares for $50.0
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.45782197617922266 shares for $102.43308895033928
On the 91th day, Bought 0.23137436372049977 shares for $50.0
On the 105th day, sold 0.23137436372049977 shares for $53.47524294308191
On the 155th day, Bought 0.22787348464132715 shares for $50.0
On the 156th day, Bought 0.2299484915378955 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.45782197617922266 shares for $103.87522817530382
On the 158th day, Bought 0.23785738071452356 shares for $50.0
On the 205th day, sold 0.23785738071452356 shares for $56.472099329242184
On the 158th day, Bought 0.23785738071452356 shares for $50.0
On the 206th day, sold 0.23785738071452356 shares for $56.41025641025641

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 107.35047111838573, Final Money: 107.35047111838573, Final Shares: 0.0
read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 109th day, sold 0.23999232024575212 shares for $53.37909186906018
On the 168th day, Bought 0.228133412419583 shares for $50.0
On the 169th day, Bought 0.2302343785974122 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.4583677910169952 shares for $103.99906810384604
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.44656903590256103 shares for $104.20688452786261
On the 84th day, Bought 0.23552687361627964 shares for $50.0
On the 111th day, sold 0.23552687361627964 shares for $53.285599886947104
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.44656903590256103 shares for $104.20688452786261
On the 85th day, Bought 0.23604947597016335 shares for $50.0
On the 111th day, sold 0.23604947597016335 shares for $53.40383344348976
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44301649220077255 shares for $105.18097557830741
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 205th day, sold 0.2229654403567447 shares for $52.936454849498325
On the 175th day, Bought 0.22005105184402782 shares for $50.0
On the 205th day, sold 0.22005105184402782 shares for $52.24452072880908
XLK Final Value: 108.58480902179717, Final Money: 108.58480902179717, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.6377551020408163 shares for $49.73214285714286
On the 113th day, Bought 0.6529119874640898 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6529119874640898 shares for $51.01854270044398
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 155th day, Bought 0.6077549532028687 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2129352969453038 shares for $96.8528834610825
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.606354596167839 shares for $48.302207130730054
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 98th day, sold 0.6377551020408163 shares for $49.77678571428571
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 56th day, sold 1.342552488151616 shares for $99.64424567061293
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 92th day, Bought 0.0 shares for $0.0
On the 98th day, sold 0.6377551020408163 shares for $49.77678571428571
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 62th day, sold 1.342552488151616 shares for $98.15401240876464
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6377551020408163 shares for $49.649234693877546
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 70th day, sold 1.342552488151616 shares for $101.48354257938065
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 204th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.2403224847690706 shares for $100.24286321903628
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 70th day, sold 0.6715014773032502 shares for $50.758796669352684
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 1.2403224847690706 shares for $99.89557292330095
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 70th day, sold 0.6715014773032502 shares for $50.758796669352684
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 136th day, sold 1.2949284414746003 shares for $101.74252764665934
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 0.6181998021760633 shares for $49.789812067260144

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 103.46893344507629, Final Money: 103.46893344507629, Final Shares: 0.0
read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 75th day, sold 0.6600660066006601 shares for $50.085808580858085
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3015780808355715 shares for $101.64023233244978
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2400059548577866 shares for $100.67608347490369
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.3424622931916024 shares for $100.05371471157012
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 87th day, sold 0.6600660066006601 shares for $51.570957095709566
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 105th day, Bought 0.6436663233779608 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.2954718246163912 shares for $101.163394784294
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 152th day, Bought 0.6109481915933529 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2236182075227733 shares for $99.34556226877396
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2116114701196075 shares for $96.08078958048486
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.3424622931916024 shares for $99.6241267777488
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6459113809585325 shares for $50.47151530809973
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 152th day, Bought 0.6109481915933529 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2236182075227733 shares for $99.34556226877396
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 54th day, sold 0.6693440428380187 shares for $49.67202141900937
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 139th day, sold 0.6459113809585325 shares for $50.53610644619558
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 205th day, sold 0.6126700159294204 shares for $48.92170077196421
On the 110th day, Bought 0.6459113809585325 shares for $50.0
On the 139th day, sold 0.6459113809585325 shares for $50.53610644619558

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.53610644619559, Final Money: 100.53610644619559, Final Shares: 0.0
read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 36th day, sold 1.342552488151616 shares for $100.90624500947546
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 62th day, sold 0.6813845734532571 shares for $49.81602616516763
On the 73th day, Bought 0.6664889362836577 shares for $50.0
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 94th day, sold 1.304244038324474 shares for $100.87023392401483
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 115th day, sold 1.2964676982471979 shares for $99.27053165478793
On the 123th day, Bought 0.6493506493506493 shares for $50.0
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.2925201888412592 shares for $101.26895679571265
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 158th day, Bought 0.6017571308220002 shares for $50.0
On the 161th day, sold 1.207744283894355 shares for $100.23069812039252
On the 164th day, Bought 0.6036460219727152 shares for $50.0
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2035980258124082 shares for $98.0571311629369
On the 187th day, Bought 0.6099792607051361 shares for $50.00000000000001
On the 200th day, sold 0.6099792607051361 shares for $48.87153836769551
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6039376736320812 shares for $48.109675081531584
On the 240th day, Bought 0.6379992344009187 shares for $50.0
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 126th day, sold 0.6431695394906097 shares for $50.39233341908927
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 234th day, sold 0.6069434328720563 shares for $48.349113862588005
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 126th day, sold 0.6431695394906097 shares for $50.39233341908927
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.5999520038396928 shares for $48.878089752819776
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 54th day, sold 0.6715014773032502 shares for $49.83212463067419
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6518055012384305 shares for $49.908747229826616
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 126th day, sold 0.6431695394906097 shares for $50.39233341908927
On the 165th day, Bought 0.5999520038396928 shares for $50.0
On the 166th day, Bought 0.595734540688669 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.1956865445283618 shares for $97.41258278272564
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 181th day, sold 0.6022645145748012 shares for $49.066490002409054
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 181th day, sold 0.6022645145748012 shares for $49.066490002409054

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 88th day, Bought 0.642508352608584 shares for $50.0
On the 94th day, sold 0.642508352608584 shares for $49.691595990747885
On the 100th day, Bought 0.6443298969072165 shares for $50.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6443298969072165 shares for $50.483247422680414
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 138th day, sold 0.6411078343377357 shares for $49.81407872804206
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, sold 1.227685713783603 shares for $102.06979024396875
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 185th day, sold 0.6033546518643659 shares for $48.98636418486787
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 210th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2023570535234946 shares for $95.81583359528729
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 54th day, sold 0.6693440428380187 shares for $49.67202141900937
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 169th day, sold 1.227685713783603 shares for $102.06979024396875
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 217th day, sold 0.616827041697508 shares for $50.758697261287935
On the 220th day, Bought 0.600817111271329 shares for $50.0
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 238th day, sold 1.2023570535234946 shares for $95.81583359528729
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
XLP Final Value: 101.35133812381514, Final Money: 101.35133812381514, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6851745190905817 shares for $97.26052298490806
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.34220792553555535 shares for $49.41824652658955
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6851745190905817 shares for $98.13069462415311
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32379225488926305 shares for $47.9342054138065
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.34073872154831675 shares for $47.02194357366771
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.32324799586242564 shares for $47.85363330747349
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.321646831778707 shares for $47.61659697651978
On the 226th day, Bought 0.34554250172771256 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 50th day, Bought 0.3384552900561836 shares for $49.99999999999999
On the 55th day, sold 0.6827130702820167 shares for $97.77816592579043
On the 83th day, Bought 0.34199726402188785 shares for $50.0
On the 127th day, sold 0.34199726402188785 shares for $50.571135430916556
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.30459928394382, Final Money: 99.30459928394382, Final Shares: 0.0
read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6838510315018442 shares for $98.49506406721062
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.34234851078397804 shares for $50.623074289626835
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.6470402507516887 shares for $100.12300840131631
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.6735630619895059 shares for $101.15570064958399
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.680342388781481 shares for $94.39750644343049
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6838510315018442 shares for $98.49506406721062
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.34234851078397804 shares for $50.623074289626835
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3375641371860653 shares for $49.56454226302998
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6838510315018442 shares for $98.49506406721062
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.32303915234526426 shares for $49.5154412714821
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3375641371860653 shares for $49.56454226302998
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.34043712126370257 shares for $49.98638251514945
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 54th day, sold 0.34139014065273793 shares for $48.46033046565614
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.42257702189542, Final Money: 99.42257702189542, Final Shares: 0.0
read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 35th day, Bought 0.3408316291751875 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6846160076130312 shares for $98.60524357650489
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3550379890648299 shares for $50.25917773201732
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.34234851078397804 shares for $50.76001369394043
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.32094486167276465 shares for $49.05642210668208
On the 191th day, Bought 0.3265199503689675 shares for $49.99999999999999
On the 194th day, sold 0.3265199503689675 shares for $49.10860053549272
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 207th day, sold 0.33532291596807723 shares for $50.063711354033934
On the 238th day, Bought 0.35816618911174786 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.3408316291751875 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6846160076130312 shares for $98.60524357650489
On the 89th day, Bought 0.34504175005175625 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.34504175005175625 shares for $48.868263059830234
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.3426300280956623 shares for $50.623586651134104
On the 167th day, Bought 0.3179852454846095 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.3179852454846095 shares for $48.60404477232256
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6838510315018442 shares for $97.07265392168678
On the 90th day, Bought 0.3462124359506994 shares for $50.0
On the 93th day, sold 0.3462124359506994 shares for $49.034067303697555
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.34274746366876885 shares for $50.6409377570606
On the 167th day, Bought 0.3179852454846095 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.3179852454846095 shares for $48.60404477232256
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 54th day, sold 0.3439735828288387 shares for $48.827050082553654
On the 179th day, Bought 0.3270111183780248 shares for $50.0
On the 188th day, sold 0.3270111183780248 shares for $49.983649444081095

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6867669549229583 shares for $98.35876328406609
On the 66th day, Bought 0.3584743332377402 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3584743332377402 shares for $50.745626613134505
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3402054841124039 shares for $50.12927808396272
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.32379225488926305 shares for $49.608211371584
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3359989248034406 shares for $49.74128082790135
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3391900142459806 shares for $47.350925988738894
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 89th day, Bought 0.34504175005175625 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.34504175005175625 shares for $48.844110137326616
On the 101th day, Bought 0.3416233943700464 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3416233943700464 shares for $50.338207160426336
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.32379225488926305 shares for $49.608211371584
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.32379225488926305 shares for $49.09985753140784
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 206th day, sold 0.3359989248034406 shares for $50.460318526980714
XLV Final Value: 100.46031852698071, Final Money: 100.46031852698071, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 150th day, Bought 0.26659557451346305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.26659557451346305 shares for $53.380431884830706
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.43407487791644056 shares for $99.3640803038524
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 109th day, sold 0.2798298634430266 shares for $50.77233042310275
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.26893287435456115 shares for $53.7731282271945
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.43407487791644056 shares for $99.3640803038524
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5205164163219237 shares for $111.97349147917222
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 236th day, sold 0.43023815087518835 shares for $98.59767703606691
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.500089566712886 shares for $109.74965631080995
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 237th day, sold 0.43023815087518835 shares for $100.87793923570541
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.2711349709885581 shares for $48.950707662274276
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 117th day, sold 0.2794076557697681 shares for $52.89186923721711
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 208th day, sold 0.500089566712886 shares for $108.2843938803412
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 56th day, sold 0.2702410550210788 shares for $48.789320073505564
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.2794076557697681 shares for $54.40067057837385
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 124th day, sold 0.2794076557697681 shares for $54.40067057837385
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 191th day, Bought 0.2506140043105609 shares for $50.00000000000001

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 117.60386978946165, Final Money: 4.400670578373848, Final Shares: 0.5011652169784302
read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 55th day, sold 0.2808199943836001 shares for $50.22184779556304
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5609340406510999 shares for $103.46428379809537
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 162th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5404948991210178 shares for $108.53678069249158
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 221th day, Bought 0.22297538351765964 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4478966610705161 shares for $102.26824462223095
On the 41th day, Bought 0.2808199943836001 shares for $50.0
On the 55th day, sold 0.2808199943836001 shares for $50.22184779556304
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.5592375192127947 shares for $105.00802898258648
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5427999546785756 shares for $108.99965889900476
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.28009635314548204 shares for $49.99999999999999
On the 116th day, sold 0.5599262165885086 shares for $105.13734568882427
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.538431859266044 shares for $108.1225016592143
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 196th day, sold 0.5277496711749954 shares for $105.97741146865083
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 196th day, sold 0.25362686415745156 shares for $50.93081059145785
On the 170th day, Bought 0.25362686415745156 shares for $50.0
On the 196th day, sold 0.25362686415745156 shares for $50.93081059145785

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 114.49115690838093, Final Money: 114.49115690838093, Final Shares: 0.0
read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 37th day, sold 0.2739425816348893 shares for $49.260355029585796
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 50th day, Bought 0.2719016803523846 shares for $50.0
On the 51th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2719016803523846 shares for $48.62689651422046
On the 59th day, Bought 0.2777314891962451 shares for $50.0
On the 62th day, sold 0.2777314891962451 shares for $48.09476198411376
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.26822595354326484 shares for $53.66933104447186
On the 240th day, Bought 0.22119000221190002 shares for $50.0
On the 241th day, sold 0.22119000221190002 shares for $49.62397699623977
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 96th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5397879783097215 shares for $114.49442807927502
On the 240th day, Bought 0.22119000221190002 shares for $50.0
On the 241th day, sold 0.22119000221190002 shares for $49.62397699623977
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5387559541203817 shares for $114.27552542847417
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.5242531856296496 shares for $111.19934320390499
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.252691160863193 shares for $53.59832213069187
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 63th day, sold 0.27625835681529365 shares for $47.60760262997956
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 63th day, sold 0.27625835681529365 shares for $47.60760262997956

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 116.46450131568122, Final Money: 116.46450131568122, Final Shares: 0.0
read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 32th day, Bought 0.2739425816348893 shares for $50.0
On the 45th day, sold 0.2739425816348893 shares for $50.495836072759154
On the 66th day, Bought 0.2932379332590464 shares for $50.0
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5830258085343449 shares for $107.53911038415991
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.537158827897826 shares for $106.0458958035888
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.21510927551196007 shares for $50.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 67th day, Bought 0.2897878752752985 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5721142445581895 shares for $105.52647240875804
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5242949918070232 shares for $99.3539009474309
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5401708042666801 shares for $106.64052017832798
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 239th day, Bought 0.2176373291546966 shares for $50.0
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.5617212209748524 shares for $103.60947920881152
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.26116479498563594 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5242949918070232 shares for $99.3539009474309
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5199806235127767 shares for $102.65457469389237
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 185th day, sold 0.2602133749674733 shares for $51.37132448607858
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
XLY Final Value: 111.23038613006706, Final Money: 13.973055162205327, Final Shares: 0.43057079408474297

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.5786617663397162 shares for $101.35008539900979
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 104th day, sold 1.4012495930161712 shares for $98.00339653555102
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.7197351374694113 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.446268122066912 shares for $101.34000731322851
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 174th day, sold 1.3327280241967356 shares for $106.85813298009427
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 197th day, Bought 0.6172077521293667 shares for $50.0
On the 199th day, sold 1.2392530370261072 shares for $98.01252269839482
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2317703413278247 shares for $94.20579570475203
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 44th day, Bought 0.7828401440425865 shares for $50.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.5736040219486438 shares for $100.09695183615322
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 105th day, sold 1.3890620513572678 shares for $96.08142209238221
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.7265329845975008 shares for $50.937227550130785
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.6640106241699868 shares for $52.875166002656044
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 231th day, Bought 0.6491820306413919 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2653249758046696 shares for $96.77205414954113
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 61th day, sold 0.8051529790660226 shares for $51.2157809983897
On the 83th day, Bought 0.6893699158968702 shares for $50.0
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.38169891063517 shares for $96.87091062463178
On the 151th day, Bought 0.6648052120728627 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.6648052120728627 shares for $52.93843903736205
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 238th day, sold 0.6676458806249166 shares for $50.94138069168113
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6923289947382997 shares for $48.49764608141789
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6861534239055852 shares for $49.58144641141759
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 138th day, sold 0.7793017456359103 shares for $56.31234413965088
On the 48th day, Bought 0.7882705344474223 shares for $50.0
On the 138th day, sold 0.7882705344474223 shares for $56.960428819170744

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 106.96042881917074, Final Money: 106.96042881917074, Final Shares: 0.0
read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 53th day, sold 0.7862871520679352 shares for $51.18729359962258
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 58th day, Bought 0.7713668620796051 shares for $50.0
On the 64th day, sold 1.5295169758021223 shares for $98.56207392068876
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7554011179936546 shares for $54.93276930049856
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4688613054034505 shares for $102.92311166961977
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2317703413278247 shares for $93.68845216139435
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 64th day, sold 0.7862871520679352 shares for $50.66834407925774
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.4669423162290325 shares for $105.41447484421828
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 115th day, Bought 0.7350779182593355 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4688613054034505 shares for $102.92311166961977
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 218th day, Bought 0.6031363088057901 shares for $50.0
On the 219th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.224331488331197 shares for $93.63687222756995
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 64th day, sold 0.7862871520679352 shares for $50.66834407925774
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 98th day, sold 0.7015574575557738 shares for $49.607127823768764
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3389713616283672 shares for $107.55956947960674
On the 219th day, Bought 0.6031363088057901 shares for $50.0
On the 227th day, Bought 0.6400409626216077 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2431772714273976 shares for $95.07819771876737
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 125th day, sold 0.7862871520679352 shares for $55.12659223148294
On the 228th day, Bought 0.6440808965606081 shares for $50.0
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2884938363724394 shares for $98.31207971521712
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 125th day, sold 0.7862871520679352 shares for $55.12659223148294
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 125th day, sold 0.7862871520679352 shares for $55.12659223148294
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 125th day, sold 0.7862871520679352 shares for $55.12659223148294

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 112.24470118747855, Final Money: 10.795473875956205, Final Shares: 1.3161549988521322
read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 51th day, sold 0.7862871520679352 shares for $51.30523667243277
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 57th day, Bought 0.7581501137225171 shares for $50.0
On the 62th day, sold 1.5204614416688504 shares for $95.43936469355374
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7063144511936713 shares for $50.33196779206102
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 168th day, sold 0.6746727836999056 shares for $53.35312373498853
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 184th day, sold 0.6140243153628884 shares for $48.3851160505956
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2216852740530135 shares for $97.6248702495763
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 216th day, sold 0.6403688524590164 shares for $52.15804303278689
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 1.3195363630238734 shares for $99.26872059028601
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 51th day, sold 0.7827175954915466 shares for $51.072323105823415
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7063144511936713 shares for $50.33196779206102
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 200th day, sold 1.2348654834504846 shares for $98.67810078252822
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 234th day, sold 0.6676458806249166 shares for $50.22699959941248
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7063144511936713 shares for $50.33196779206102
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6220452848967405 shares for $46.79646678278179
On the 240th day, Bought 0.6599788806758183 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.6605892456070815 shares for $50.0

[*********************100%***********************]  1 of 1 completed

On the 241th day, Bought 0.6605892456070815 shares for $50.0
XLU Final Value: 102.33050282397951, Final Money: 2.921107785570193, Final Shares: 1.2896911655216572

read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 104th day, Bought 0.7148984844152131 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.428063510802319 shares for $102.09226038725778
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 164th day, sold 1.352185047296217 shares for $104.49686045505165
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 189th day, sold 0.6345177664974619 shares for $52.16370558375634
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.3487087648370697 shares for $108.00459788815255
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 189th day, sold 0.6345177664974619 shares for $52.16370558375634
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.6215813028344107 shares for $49.99999999999999
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 62th day, sold 0.7803964413922273 shares for $48.98548462619011
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7452675510508272 shares for $54.195856312416154
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3487087648370697 shares for $108.34177507936181
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.7880220646178092 shares for $50.0
On the 63th day, sold 0.7880220646178092 shares for $50.49645390070921
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.6745817593092283 shares for $50.0
On the 146th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.3487087648370697 shares for $108.34177507936181
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
XLU Final Value: 110.17740530977338, Final Money: 14.05195724536975, Final Shares: 1.2470867678308721

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 58th day, sold 0.09840969925995907 shares for $50.59439458353016
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.1785952662739861 shares for $101.985040853097
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 59th day, sold 0.09840969925995907 shares for $50.9762242166588
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 174th day, Bought 0.08771314293733774 shares for $50.00000000000001
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1750799086196722 shares for $99.76228273057541
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 59th day, sold 0.09840969925995907 shares for $50.9762242166588
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1899262858477388 shares for $104.26763166755012
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17507663733900194 shares for $100.96669675340243
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.16507664932143729 shares for $98.16943258496555
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 59th day, sold 0.09840969925995907 shares for $50.9762242166588
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1899262858477388 shares for $104.26763166755012
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17507663733900194 shares for $100.96669675340243
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18895217823179206 shares for $103.73285632747152
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 205th day, sold 0.08793218669761879 shares for $52.37328971896873
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.1647013436594728 shares for $97.9462420608519
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 205th day, sold 0.08793218669761879 shares for $52.37328971896873
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 225th day, Bought 0.08226254915187313 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.16454540469609194 shares for $98.94115184376008
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 106.34206641206967, Final Money: 106.34206641206967, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 37th day, Bought 0 shares for $0.0
On the 38th day, Bought 0 shares for $0.0
On the 39th day, Bought 0 shares for $0.0
On the 40th day, Bought 0 shares for $0.0
On the 41th day, Bought 0 shares for $0.0
On the 42th day, Bought 0 shares for $0.0
On the 43th day, Bought 0 shares for $0.0
On the 44th day, Bought 0 shares for $0.0
On the 45th day, Bought 0 shares for $0.0
On the 46th day, Bought 0 shares for $0.0
On the 49th day, Bought 0 shares for $0.0
On the 50th day, Bought 0 shares for $0.0
On the 80th day, Bought 0 shares for $0.0
On the 81th day, Bought 0 shares for $0.0
On the 82th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 91th day, Bought 0 shares for $0.0
On the 92th day, Bought 0 shares for $0.0
On the 102th day, Bought 0 shares for $0.0
On the 103th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 106th day, Bought 0 shares for $0.0
On the 107th day, Bought 0 shares for $0.0
On the 108th day, Bought 0 shares for $0.0
On the 113th day, Bought 0 shares for $0.0
On the 114th day, Bought 0 shares for $0.0
On the 115th day, Bought 0 shares for $0.0
On the 116th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 118th day, Bought 0 shares for $0.0
On the 119th day, Bought 0 shares for $0.0
On the 120th day, Bought 0 shares for $0.0
On the 121th day, Bought 0 shares for $0.0
On the 154th day, Bought 0 shares for $0.0
On the 155th day, Bought 0 shares for $0.0
On the 156th day, Bought 0 shares for $0.0
On the 157th day, Bought 0 shares for $0.0
On the 158th day, Bought 0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 200th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 37th day, Bought 0 shares for $0.0
On the 38th day, Bought 0 shares for $0.0
On the 39th day, Bought 0 shares for $0.0
On the 40th day, Bought 0 shares for $0.0
On the 41th day, Bought 0 shares for $0.0
On the 80th day, Bought 0 shares for $0.0
On the 81th day, Bought 0 shares for $0.0
On the 82th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 91th day, Bought 0 shares for $0.0
On the 92th day, Bought 0 shares for $0.0
On the 102th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 106th day, Bought 0 shares for $0.0
On the 107th day, Bought 0 shares for $0.0
On the 113th day, Bought 0 shares for $0.0
On the 114th day, Bought 0 shares for $0.0
On the 115th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 118th day, Bought 0 shares for $0.0
On the 121th day, Bought 0 shares for $0.0
On the 155th day, Bought 0 shares for $0.0
On the 156th day, Bought 0 shares for $0.0
On the 157th day, Bought 0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 37th day, Bought 0 shares for $0.0
On the 81th day, Bought 0 shares for $0.0
On the 82th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 106th day, Bought 0 shares for $0.0
On the 107th day, Bought 0 shares for $0.0
On the 113th day, Bought 0 shares for $0.0
On the 114th day, Bought 0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0 shares for $0.0
On the 81th day, Bought 0 shares for $0.0
On the 82th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 107th day, Bought 0 shares for $0.0
On the 113th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 81th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 100.0, Final Money: 100.0, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 47th day, sold 0.09759906304899474 shares for $50.72906500097599
On the 50th day, Bought 0.09558950044927064 shares for $50.0
On the 51th day, Bought 0.09575609008732956 shares for $50.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 62th day, sold 0.19134559053660022 shares for $96.3482452028943
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.09437879874664956 shares for $52.40665936803956
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.08915993509156726 shares for $50.91388933468857
On the 211th day, Bought 0.08536064874093043 shares for $50.0
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.16830689957039294 shares for $98.64467383820731
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 118th day, sold 0.09437879874664956 shares for $52.40665936803956
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 227th day, Bought 0.08294625082946251 shares for $50.0
On the 234th day, sold 0.08294625082946251 shares for $48.61479761114798
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09506426344208685 shares for $52.83861890638072
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.09443940767603505 shares for $52.55364158355999
On the 153th day, Bought 0.08915993509156726 shares for $50.0
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.17819761583805918 shares for $101.75796654816531
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 131th day, sold 0.09443940767603505 shares for $50.84712148685403
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.08955758552749418 shares for $51.6478595737059
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 103.74064167160635, Final Money: 103.74064167160635, Final Shares: 0.0
read  5035  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 36th day, Bought 0.0977096849839756 shares for $50.0
On the 52th day, Bought 0 shares for $0.0
On the 53th day, Bought 0 shares for $0.0
On the 54th day, Bought 0 shares for $0.0
On the 60th day, sold 0.0977096849839756 shares for $49.91499257406394
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 90th day, Bought 0 shares for $0.0
On the 91th day, Bought 0 shares for $0.0
On the 92th day, Bought 0 shares for $0.0
On the 102th day, Bought 0 shares for $0.0
On the 103th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 106th day, Bought 0 shares for $0.0
On the 107th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 118th day, Bought 0 shares for $0.0
On the 119th day, Bought 0 shares for $0.0
On the 120th day, Bought 0 shares for $0.0
On the 152th day, Bought 0 shares for $0.0
On the 155th day, Bought 0 shares for $0.0
On the 156th day, Bought 0 shares for $0.0
On the 157th day, Bought 0 shares for $0.0
On the 160th day, Bought 0 shares for $0.0
On the 161th day, Bought 0 shares for $0.0
On the 168th day, Bought 0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 177th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 200th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 53th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 90th day, Bought 0 shares for $0.0
On the 91th day, Bought 0 shares for $0.0
On the 92th day, Bought 0 shares for $0.0
On the 102th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 118th day, Bought 0 shares for $0.0
On the 156th day, Bought 0 shares for $0.0
On the 157th day, Bought 0 shares for $0.0
On the 160th day, Bought 0 shares for $0.0
On the 161th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 53th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 102th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 32th day, Bought 0 shares for $0.0
On the 33th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 218th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 30th day, Bought 0 shares for $0.0
On the 31th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
SPY Final Value: 100.0, Final Money: 100.0, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, sold 1.0890283040146238 shares for $98.77486717412638
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.0890283040146238 shares for $100.0054691576629
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0462549900304203 shares for $96.96691247601936
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 127th day, sold 0.5442473059758354 shares for $49.042124741482525
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5214308061320263 shares for $48.326207112316204
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 133th day, sold 0.5433010974682169 shares for $49.706617407367155
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5121376626037079 shares for $47.46491857011165
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 133th day, sold 0.5425935973955507 shares for $49.64188822571893

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 103.12304121962426, Final Money: 103.12304121962426, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 80th day, Bought 0.544425087108014 shares for $50.00000000000001
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0886723930838493 shares for $99.05830104669944
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 117th day, sold 1.1197107302364473 shares for $98.42257318778373
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 207th day, sold 1.1009008637772286 shares for $103.55073524688612
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 73th day, sold 1.1245294249632232 shares for $100.18432646997356
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0875484034440523 shares for $98.95602922937432
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 209th day, sold 1.1009008637772286 shares for $102.03149205487355
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5710370031978073 shares for $52.27272727272728
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 211th day, sold 1.0966471303772733 shares for $100.10195006083751
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.1072492552135054 shares for $93.59577954319761
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 60th day, sold 0.5710370031978073 shares for $51.34764732754683
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 126th day, sold 0.541829215431296 shares for $49.26311226701343
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0966471303772733 shares for $92.69958193079091
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 234th day, sold 0.5685048322910744 shares for $48.055713473564516

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, Bought 0.0 shares for $0.0
On the 57th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0913564946715506 shares for $97.66549270815706
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 80th day, sold 0.5663797009515179 shares for $52.016311735387404
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 114th day, sold 0.541829215431296 shares for $47.112050281751195
On the 144th day, Bought 0.5614823133071308 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 166th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.052751541094044 shares for $98.91653480119636
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 217th day, sold 0.5343593031954686 shares for $50.79619536176125
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, sold 1.0643081826903797 shares for $97.799278907419
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0901937982874808 shares for $97.56144300874665
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 173th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 185th day, Bought 0.524824183898394 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 1.052751541094044 shares for $98.91653480119636
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5295488244016098 shares for $47.99300995551789
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0901937982874808 shares for $97.56144300874665
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5663797009515179 shares for $49.337335749886726
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5443065534509035 shares for $51.5676028739386
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5295488244016098 shares for $47.99300995551789
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 106th day, Bought 0.5584096493187402 shares for $50.0
On the 115th day, sold 0.5584096493187402 shares for $48.64306455215545
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 186th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5443065534509035 shares for $51.5676028739386
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 234th day, sold 0.5295488244016098 shares for $44.76276212666807
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 197th day, sold 0.5214308061320263 shares for $49.40035457294817
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 234th day, sold 0.5295488244016098 shares for $44.76276212666807
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 98.86959370904324, Final Money: 98.86959370904324, Final Shares: 0.0
read  5035  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 31th day, Bought 0.5684402000909504 shares for $49.99999999999999
On the 32th day, Bought 0.5643340857787811 shares for $50.0
On the 33th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 59th day, sold 1.1327742858697314 shares for $103.69415812851521
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.5538938739337543 shares for $50.0
On the 73th day, sold 1.1124282796531468 shares for $99.10623543429885
On the 84th day, Bought 0.5472255663784612 shares for $50.0
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, sold 1.089819163774012 shares for $99.18444209507284
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.1197107302364473 shares for $102.82303635761295
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.0691805544395634 shares for $103.80674003053721
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0523015578016246 shares for $97.52730837705458
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.0938814610365155 shares for $93.41747677251843
On the 48th day, Bought 0.5474652359575167 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 61th day, sold 1.0871888974428363 shares for $97.29253443215941
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5585344057193924 shares for $49.50290437890975
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 176th day, sold 0.5357334190506804 shares for $51.923282974391945
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.5253756435851634 shares for $47.956288746453716
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5441288497116117 shares for $46.218304494504295
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 215th day, sold 1.0523015578016246 shares for $98.463856763498
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.5851375073142189 shares for $50.00000000000001
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.1536423396052933 shares for $97.9903803260736
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 128th day, sold 0.5619240278714318 shares for $50.80355135985615
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.0547562682543004 shares for $99.24201728004712
On the 233th day, Bought 0.5851375073142189 shares for $50.00000000000001
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 235th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 0.5253756435851634 shares for $49.43259430492803
On the 234th day, Bought 0.5915059742103396 shares for $50.00000000000001
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
XLB Final Value: 99.30104031209362, Final Money: 99.30104031209362, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 34th day, Bought 0.573921028466483 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.573921028466483 shares for $55.171028466483
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.067180811577654 shares for $95.92888315271531
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.0969123538573196 shares for $100.68558496056338
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 1.1014041492712865 shares for $92.90343999103301
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.5389673385792821 shares for $50.5281879918077
On the 217th day, Bought 0.5243838489774515 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5243838489774515 shares for $44.12165705296277
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.103184570749849 shares for $101.26131174912865
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 156th day, Bought 0.5498130635583902 shares for $50.00000000000001
On the 179th day, sold 1.0980586775934777 shares for $99.6158832312803
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 190th day, Bought 0.5516328331862312 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.108549741183558 shares for $93.27337522318457
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 97th day, sold 1.066042591472773 shares for $95.81590812157282
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 128th day, sold 0.5549389567147615 shares for $50.93784683684796
On the 156th day, Bought 0.5498130635583902 shares for $50.00000000000001
On the 179th day, sold 0.5498130635583902 shares for $49.87904112601716
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.1103815969501716 shares for $93.98269836586252
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 97th day, sold 0.5324246619103397 shares for $47.85432861250133
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.108588481558596 shares for $93.83092907911957
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5534646889528448 shares for $46.84525127296879
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 195th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 98.41155634270532, Final Money: 49.99999999999999, Final Shares: 0.5534646889528448
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 63th day, Bought 0.5311802825879104 shares for $50.0
On the 66th day, sold 0.5311802825879104 shares for $50.775523212578356
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0679201308875026 shares for $96.92443107934974
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 105th day, Bought 0.5664438654129376 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.1343675364715473 shares for $102.47876324483958
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.5874750323111267 shares for $50.0
On the 169th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.151300021034627 shares for $101.08414184684024
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 184th day, sold 0.5490282200505107 shares for $50.30196552102779
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.117517062787762 shares for $104.07436405742426
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0451065062759581 shares for $87.71578907174117
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 63th day, Bought 0.5311802825879104 shares for $50.0
On the 66th day, sold 0.5311802825879104 shares for $50.775523212578356
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 104th day, Bought 0.5679236710586096 shares for $49.99999999999999
On the 105th day, Bought 0.5664438654129376 shares for $50.0
On the 117th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.1343675364715473 shares for $104.57734318731194
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 165th day, Bought 0.5874750323111267 shares for $50.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.151300021034627 shares for $101.08414184684024
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.117517062787762 shares for $94.58664419435617
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 73th day, sold 0.5222477543346564 shares for $48.062460831418434
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.562429696287964 shares for $50.00000000000001
On the 177th day, sold 1.1234709889271022 shares for $98.64075282779957
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 133th day, sold 0.5549389567147615 shares for $50.7214206437292
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 197th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.5605381165919282 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 105.3692067658129, Final Money: 3.845360672441643, Final Shares: 1.160670470942852
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 50th day, Bought 0.5296049147336087 shares for $50.0
On the 53th day, sold 0.5296049147336087 shares for $51.4246372206334
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 63th day, sold 0.5201289919900135 shares for $48.959742016019966
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0548281001756075 shares for $97.63488895225423
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 91th day, sold 0.5299417064122947 shares for $48.91891891891892
On the 102th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 103th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5585344057193924 shares for $51.100312779267206
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 134th day, Bought 0.5386770092652446 shares for $50.00000000000001
On the 138th day, sold 0.5386770092652446 shares for $46.5686274509804
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 161th day, sold 0.5489679402722881 shares for $47.21673254281951
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 176th day, sold 0.5736576411197798 shares for $50.0172097292336
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5389673385792821 shares for $50.194028241888546
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0548281001756075 shares for $97.63488895225423
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5299417064122947 shares for $48.484366719660834
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.5299417064122947 shares for $48.00741918388977
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5299417064122947 shares for $49.491255961844196
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 181th day, sold 0.5489679402722881 shares for $51.15283267457181
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 205th day, sold 1.1137718192470587 shares for $103.72556952647857
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 234th day, sold 0.5567928730512249 shares for $46.391982182628055

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 104.36965816289458, Final Money: 104.36965816289458, Final Shares: 0.0
read  5035  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 54th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5612932195779076 shares for $54.888863942523585
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0533710046449274 shares for $96.94173355747267
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.0675207592474305 shares for $99.49293476186052
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 1.094935722669386 shares for $98.91649318595235
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.5526693931690063 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.104728573913182 shares for $96.99516878957738
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5534646889528448 shares for $51.24529555014391
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5187260089220873 shares for $48.013279385828405
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.545732372844357 shares for $50.52936040165902
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 238th day, sold 0.5948839976204641 shares for $50.30933967876264
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5387350501023597 shares for $49.88147828897748
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 137th day, sold 0.546268982847154 shares for $48.29017808368842
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 138th day, sold 0.546268982847154 shares for $47.22495356713646
XLE Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.4105140597728463 shares for $105.62872609924612
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 164th day, sold 2.2812835348939844 shares for $101.01523492510563
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 1.072271070126528 shares for $49.62470512545571
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 236th day, sold 2.0058969467476304 shares for $97.12553016152027
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 126th day, sold 2.3943644692250357 shares for $103.65203787275179
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2812835348939844 shares for $105.5778019948936
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.379568360738147 shares for $101.9645042576296
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2379022564825797 shares for $103.57011643001378
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 55th day, sold 1.2312238364934744 shares for $51.18197488303373
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.370791844476055 shares for $101.58843053579896
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 56th day, sold 1.2312238364934744 shares for $51.40359517360256
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 85th day, Bought 1.1767474699929394 shares for $50.0
On the 127th day, sold 2.362143392230967 shares for $101.21784435709694

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 111.9343812657614, Final Money: 111.9343812657614, Final Shares: 0.0
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, sold 2.2394645513138323 shares for $93.4976450173525
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 109th day, Bought 1.2022120702091847 shares for $50.0
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.4090670062458734 shares for $103.22852121763567
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0 shares for $0.0
On the 187th day, sold 2.274804803274146 shares for $106.46086479323002
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.25 shares for $11.7875
On the 197th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.3615453243694313 shares for $109.29231761181728
On the 215th day, Bought 0 shares for $0.0
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.2394645513138323 shares for $90.9222607833416
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.4688340557083066 shares for $102.72818505802263
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 123th day, Bought 1.1627906976744187 shares for $50.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.369645633711107 shares for $101.53931540452093
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0 shares for $0.0
On the 187th day, sold 2.2615618513896103 shares for $105.84109464503375
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 2.121791173519794 shares for $103.43731970908996
On the 215th day, Bought 0 shares for $0.0
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.2394645513138323 shares for $90.9222607833416
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.450479272554122 shares for $101.96444253097701
On the 123th day, Bought 1.1627906976744187 shares for $50.0
On the 126th day, Bought 1.155001155001155 shares for $50.0
On the 127th day, sold 2.3177918526755734 shares for $99.31738088714832
On the 158th day, Bought 0 shares for $0.0
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 205th day, sold 1.0590976488032195 shares for $51.631010379156955
On the 31th day, Bought 1.2410027302060065 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 59th day, sold 2.2410027302060067 shares for $90.98471084636388
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 2.450479272554122 shares for $101.40083229828957
On the 126th day, Bought 1.155001155001155 shares for $50.0
On the 127th day, sold 1.155001155001155 shares for $49.49179949179949
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 205th day, sold 1.0590976488032195 shares for $51.631010379156955
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 34th day, Bought 1.0 shares for $40.61
On the 60th day, sold 2.2379301807378065 shares for $89.65148304035654
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 76th day, Bought 1.0 shares for $41.07
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 95th day, sold 2.2330456226880395 shares for $92.40342786683108
On the 126th day, Bought 1.155001155001155 shares for $50.0
On the 128th day, sold 1.155001155001155 shares for $49.76899976899977
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 205th day, sold 1.0590976488032195 shares for $51.631010379156955
On the 34th day, Bought 1.2312238364934744 shares for $50.0
On the 128th day, sold 1.2312238364934744 shares for $53.05343511450382
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 128th day, sold 1.2330456226880395 shares for $53.131935881627626

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 114.07817560000888, Final Money: 114.07817560000888, Final Shares: 0.0
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4562839967441796 shares for $105.62021185999973
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 154th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 199th day, Bought 1.0608953957139826 shares for $50.0
On the 205th day, sold 2.1331664658405103 shares for $103.99186520972488
On the 211th day, Bought 1.0026067776218168 shares for $50.0
On the 213th day, Bought 1.0062386798148522 shares for $50.0
On the 214th day, Bought 0.25 shares for $12.385
On the 215th day, Bought 0.0 shares for $0.0
On the 234th day, sold 2.258845457436669 shares for $107.97281286547278
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 33th day, Bought 1.0 shares for $40.4
On the 46th day, sold 2.2379301807378065 shares for $92.69506808615995
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.4562839967441796 shares for $105.62021185999973
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 1.121830827911151 shares for $50.00000000000001
On the 167th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.247196571777908 shares for $105.16879955920608
On the 214th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 46th day, sold 1.2379301807378065 shares for $51.27506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.434057971873108 shares for $105.85718119676147
On the 167th day, Bought 1.1088933244621866 shares for $50.0
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.225213931740597 shares for $104.14001200545992
On the 32th day, Bought 1.2379301807378065 shares for $50.00000000000001
On the 46th day, sold 1.2379301807378065 shares for $51.27506808615995
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 124th day, sold 2.434057971873108 shares for $105.85718119676147
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 179th day, Bought 1.1079104808331486 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 189th day, sold 2.224231088111559 shares for $105.60649206353682
On the 174th day, Bought 1.1163206072784104 shares for $50.0
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 189th day, sold 2.230154423273064 shares for $105.88773201700506
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 189th day, sold 1.1138338159946535 shares for $52.884829583426146

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.73874134645823, Final Money: 112.73874134645823, Final Shares: 0.0
read  5035  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 73th day, Bought 1.2388503468780971 shares for $50.0
On the 90th day, sold 1.2388503468780971 shares for $51.54856293359762
On the 105th day, Bought 1.21921482565228 shares for $49.99999999999999
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 2.4260697616889684 shares for $104.53934603117766
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 163th day, sold 2.2758364540624174 shares for $101.25196384123696
On the 190th day, Bought 1.0501995379122033 shares for $50.0
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.1115453243694313 shares for $98.48247392859028
On the 215th day, Bought 0.9966115208291807 shares for $50.0
On the 229th day, Bought 1.008471157724889 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.0050826785540696 shares for $97.74778057951089
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 148th day, Bought 1.1361054305839582 shares for $50.0
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 187th day, sold 2.2758364540624174 shares for $106.50914605012113
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.121791173519794 shares for $98.9603403329632
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 0.0 shares for $0.0
On the 239th day, sold 2.020407771722292 shares for $98.49487887146174
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.121791173519794 shares for $98.19649551049608
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 240th day, sold 1.0111223458038423 shares for $48.81698685540951
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 202th day, sold 2.132716457189094 shares for $98.70211763871127
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 204th day, sold 1.0604453870625663 shares for $52.54506892895016
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 92th day, sold 1.2357884330202669 shares for $50.444883835887296
XLF Final Value: 108.99369156550195, Final Money: 108.99369156550195, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39142007202129325 shares for $55.358540785971506
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7053194773636646 shares for $93.89212882665103
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7973563487023718 shares for $97.03826763707865
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 127th day, sold 0.4049566696363489 shares for $50.56693933749089
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.39142007202129325 shares for $55.358540785971506
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7216760140645313 shares for $96.06951099227041
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7991369435960733 shares for $99.78823014684168
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7966308196124732 shares for $99.47529044500953
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 58th day, sold 0.4132231404958678 shares for $51.27685950413223
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 127th day, sold 0.796407374083437 shares for $99.44738880179878

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 106.89499767727955, Final Money: 106.89499767727955, Final Shares: 0.0
read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 63th day, Bought 0.412847824291966 shares for $50.0
On the 64th day, Bought 0.4142845306156268 shares for $50.0
On the 65th day, Bought 0.0 shares for $0.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8271323549075928 shares for $100.2649840618984
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4102732419791581 shares for $51.92007877246245
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7303689539425081 shares for $97.22671514882668
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 63th day, Bought 0.412847824291966 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 66th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.8278889133597838 shares for $100.35669407747298
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7973563487023718 shares for $97.30139523215044
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.4102732419791581 shares for $51.92007877246245
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 63th day, Bought 0.412847824291966 shares for $50.0
On the 65th day, Bought 0.4150410890678177 shares for $50.0
On the 73th day, sold 0.8278889133597838 shares for $100.35669407747298
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 113th day, Bought 0.4102732419791581 shares for $50.0
On the 114th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4102732419791581 shares for $51.513908262903094
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7831204863019074 shares for $110.09107796432215
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 95th day, sold 0.7973563487023718 shares for $97.27747454168936
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3924954863019075 shares for $55.17701546432216
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 151th day, Bought 0.390625 shares for $50.0
On the 205th day, sold 0.390625 shares for $54.91406250000001
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 73th day, sold 0.4132231404958678 shares for $50.09090909090909
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 126th day, sold 0.39783577339274345 shares for $49.952259707192866

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 112.10477003203744, Final Money: 112.10477003203744, Final Shares: 0.0
read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 45th day, sold 0.40997048212528703 shares for $51.508691374221065
On the 75th day, Bought 0.4072656186364747 shares for $50.0
On the 78th day, sold 0.4072656186364747 shares for $50.643479677445626
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.796407374083437 shares for $96.52457373891257
On the 100th day, Bought 0.4074647542987532 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.4074647542987532 shares for $50.96161682014505
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 162th day, sold 0.38675742574257427 shares for $49.43533415841584
On the 165th day, Bought 0.38681726752282225 shares for $50.0
On the 171th day, sold 0.38681726752282225 shares for $51.51632368868947
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 179th day, Bought 0.36965843560550055 shares for $50.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 0.7388255944950457 shares for $102.88146403343511
On the 193th day, Bought 0.36469730123997085 shares for $50.0
On the 196th day, sold 0.36469730123997085 shares for $49.380014587892056
On the 222th day, Bought 0.3520383017672323 shares for $50.0
On the 223th day, Bought 0.35050823694356814 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.7025465387108004 shares for $92.92583067527758
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 32th day, Bought 0.40997048212528703 shares for $50.0
On the 46th day, sold 0.40997048212528703 shares for $51.33240406690719
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 102th day, Bought 0.40594300560201346 shares for $50.0
On the 123th day, sold 0.40594300560201346 shares for $50.77129171064382
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 46th day, sold 0.40970173713536545 shares for $51.298754506719106
On the 83th day, Bought 0.39701445132602825 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7959612318255096 shares for $97.13114911966694
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.38675742574257427 shares for $54.3703589108911
On the 240th day, Bought 0.37901758641600974 shares for $50.0
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 46th day, sold 0.40970173713536545 shares for $51.298754506719106
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7971310601841195 shares for $97.27390327426811
On the 177th day, Bought 0.3691671588895452 shares for $50.0
On the 193th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.3691671588895452 shares for $51.89751919669227
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 46th day, sold 0.40970173713536545 shares for $51.298754506719106
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 93th day, sold 0.3981842796846381 shares for $48.590427649916386
On the 41th day, Bought 0.40970173713536545 shares for $50.0
On the 46th day, sold 0.40970173713536545 shares for $51.298754506719106
On the 86th day, Bought 0.3981842796846381 shares for $50.0
On the 93th day, sold 0.3981842796846381 shares for $48.590427649916386

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 103.90841787724187, Final Money: 53.60520380810905, Final Shares: 0.37901758641600974
read  5035  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 53th day, Bought 0.39984006397441024 shares for $50.0
On the 56th day, sold 0.39984006397441024 shares for $50.159936025589765
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 76th day, Bought 0.40319329086364003 shares for $50.0
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8052841634008334 shares for $97.60044060418102
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.41044163519947463 shares for $51.77310786406173
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.782632814641483 shares for $110.02252108229969
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 228th day, Bought 0.3605422555523507 shares for $50.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.7110504924959189 shares for $95.46563912250207
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 73th day, sold 0.818202330521395 shares for $99.1824865058035
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7988815772796203 shares for $96.82444716628999
On the 112th day, Bought 0.41044163519947463 shares for $50.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.41044163519947463 shares for $51.77310786406173
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.390625 shares for $54.91406250000001
On the 216th day, Bought 0.35050823694356814 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 238th day, sold 0.7173730105880028 shares for $96.31450040154526
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 67th day, Bought 0.4062728528479727 shares for $50.0
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.8056657756053814 shares for $97.64669200337224
On the 151th day, Bought 0.390625 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.390625 shares for $55.50390625
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 89th day, Bought 0.4037793749495276 shares for $50.0
On the 92th day, sold 0.8032680294717391 shares for $97.35608517197478
On the 156th day, Bought 0.3844083954793573 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.3844083954793573 shares for $55.04343814868917
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 87th day, Bought 0.3994886545222116 shares for $50.0
On the 92th day, sold 0.3994886545222116 shares for $48.418024928092045
On the 197th day, Bought 0.3681885125184094 shares for $50.0
On the 207th day, sold 0.3681885125184094 shares for $52.72091310751104
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 92th day, sold 0.41145490454246214 shares for $49.86833443054641
XLI Final Value: 106.25371798129727, Final Money: 106.25371798129727, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.24211902571304053 shares for $51.11858989879425
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22472920131241853 shares for $50.31911546586363
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.20735702732965622 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4234984702899294 shares for $98.45915935770569
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 81th day, Bought 0.24211902571304053 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.24211902571304053 shares for $55.30240666311559
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44986315601546684 shares for $106.80651050119214
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 223th day, Bought 0.20735702732965622 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4234984702899294 shares for $98.45915935770569
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 125th day, sold 0.2415692337423906 shares for $54.198473282442755
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44873755024886464 shares for $106.53926918008544
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 228th day, Bought 0.20888164765843673 shares for $50.0
On the 234th day, sold 0.42079095047683046 shares for $97.82968807635832
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 125th day, sold 0.2415692337423906 shares for $54.198473282442755
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.44656903590256103 shares for $106.02442050398604
On the 227th day, Bought 0.21190930281839374 shares for $50.0
On the 234th day, sold 0.21190930281839374 shares for $49.26679381224836
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 126th day, sold 0.2415692337423906 shares for $54.2033046671176
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 206th day, sold 0.44656903590256103 shares for $105.90831255465137
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 126th day, sold 0.2415692337423906 shares for $54.2033046671176
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 236th day, sold 0.4506080448330224 shares for $107.27625723339764
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 126th day, sold 0.2415692337423906 shares for $54.2033046671176
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 178th day, Bought 0.22700444928720603 shares for $50.0

[*********************100%***********************]  1 of 1 completed

On the 237th day, sold 0.4506080448330224 shares for $108.38475302368688
XLK Final Value: 112.58805769080449, Final Money: 112.58805769080449, Final Shares: 0.0

read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 61th day, sold 0.24321432045918862 shares for $49.01254985893569
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.4279497485115096 shares for $100.05465120199095
On the 149th day, Bought 0.22295549808258272 shares for $50.0
On the 150th day, Bought 0.2216508555723025 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4446063536548852 shares for $99.55180864686534
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.429830156314737 shares for $99.9312130416132
On the 33th day, Bought 0.24321432045918862 shares for $50.0
On the 76th day, sold 0.24321432045918862 shares for $49.84191069170152
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22360359554581635 shares for $50.06708107866374
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 234th day, sold 0.21590810950859313 shares for $50.196476379652815
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 76th day, sold 0.23978515250335697 shares for $49.13917130251294
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.23470872647045016 shares for $53.16152654555696
On the 117th day, Bought 0.21470285125386465 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4279497485115096 shares for $96.02336457101252
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22700444928720603 shares for $50.8285662398983
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 234th day, sold 0.21590810950859313 shares for $50.196476379652815
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 110th day, sold 0.23978515250335697 shares for $54.31133704201035
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 186th day, Bought 0.2166283956501018 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4436328449373078 shares for $99.33383030991259
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 238th day, sold 0.21590810950859313 shares for $51.966922877623276
On the 49th day, Bought 0.23955538520505942 shares for $50.0
On the 111th day, sold 0.23955538520505942 shares for $54.197010348792645
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.2134198395082807 shares for $50.0
On the 126th day, sold 0.4266667367659256 shares for $95.73548239553838
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.22700444928720603 shares for $53.895396349768454
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 126th day, sold 0.2132468972576449 shares for $47.84833880667036
On the 178th day, Bought 0.22700444928720603 shares for $50.0
On the 196th day, Bought 0.21711754744018413 shares for $50.0
On the 205th day, sold 0.44412199672739017 shares for $105.44344446301697
On the 219th day, Bought 0.21590810950859313 shares for $50.0
On the 219th day, Bought 0.21590810950859313 shares for $50.0
XLK Final Value: 107.29262236301281, Final Money: 56.392285546361975, Final Shares: 0.21590810950859313

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 32th day, Bought 0.2372366672992978 shares for $50.0
On the 62th day, sold 0.2372366672992978 shares for $47.86486999430632
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 123th day, Bought 0.2134745111433695 shares for $50.0
On the 124th day, Bought 0.2141877998629198 shares for $50.0
On the 125th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.42766231100628926 shares for $95.95886934359119
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.22609088853719195 shares for $50.624010852362645
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.21861746316295744 shares for $52.61903720869223
On the 40th day, Bought 0.23948654085640386 shares for $50.0
On the 62th day, sold 0.23948654085640386 shares for $48.31880448318804
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.23999232024575212 shares for $53.00710377267927
On the 153th day, Bought 0.22609088853719195 shares for $50.0
On the 154th day, Bought 0.22472920131241853 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.4508200898496105 shares for $100.94312631822628
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 220th day, Bought 0.21392204680614385 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.23948654085640386 shares for $50.0
On the 63th day, sold 0.23948654085640386 shares for $47.62189864929591
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.23999232024575212 shares for $53.73668042622636
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 63th day, sold 0.24315518163692068 shares for $48.351407868501674
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.23999232024575212 shares for $54.4518575405587
On the 211th day, Bought 0.21861746316295744 shares for $50.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 93th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.24315518163692068 shares for $50.0
On the 64th day, sold 0.24315518163692068 shares for $47.79944560618587
On the 90th day, Bought 0.2323528044983503 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

XLK Final Value: 104.3423323497276, Final Money: 52.80326540906037, Final Shares: 0.21861746316295744
read  5035  lines of data for ticker:  XLK

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLK
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.23999232024575212 shares for $54.435058078141495
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 118th day, Bought 0.2132468972576449 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.431511259052651 shares for $96.82249630623383
On the 152th day, Bought 0.223254152527237 shares for $50.0
On the 161th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.223254152527237 shares for $49.98883729237363
On the 213th day, Bought 0.21614144296027318 shares for $50.0
On the 234th day, sold 0.21614144296027318 shares for $50.250724073833915
On the 30th day, Bought 0.2415692337423906 shares for $50.0
On the 61th day, sold 0.2415692337423906 shares for $48.68103198376655
On the 82th day, Bought 0.23999232024575212 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 104th day, sold 0.23999232024575212 shares for $54.63905155035038
On the 115th day, Bought 0.2182643617950061 shares for $50.0
On the 126th day, sold 0.2182643617950061 shares for $48.97415749956347
On the 172th day, Bought 0.2251339547030483 shares for $50.0
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44873755024886464 shares for $100.47682487622328
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.23470872647045016 shares for $53.100502276674646
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 47th day, Bought 0.23978515250335697 shares for $50.0
On the 61th day, sold 0.23978515250335697 shares for $48.321503932476496
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 83th day, Bought 0.23470872647045016 shares for $50.0
On the 126th day, sold 0.23470872647045016 shares for $52.66394404543961
On the 173th day, Bought 0.22360359554581635 shares for $50.0
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 175th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.44656903590256103 shares for $99.99127282894244
On the 174th day, Bought 0.2229654403567447 shares for $50.0
On the 205th day, sold 0.2229654403567447 shares for $52.936454849498325
XLK Final Value: 102.93645484949832, Final Money: 102.93645484949832, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6377551020408163 shares for $49.30484693877551
On the 120th day, Bought 0.6459948320413437 shares for $50.00000000000001
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 128th day, sold 0.6459948320413437 shares for $50.47803617571059
On the 154th day, Bought 0.6051803437424352 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.6051803437424352 shares for $48.32365044783345
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 231th day, sold 0.606354596167839 shares for $49.484598593257346
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.342552488151616 shares for $99.79192644430961
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.6377551020408163 shares for $49.30484693877551
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 59th day, sold 1.342552488151616 shares for $99.5234159466793
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 95th day, sold 0.6377551020408163 shares for $49.30484693877551
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 0.6484243288808196 shares for $50.4798340033718
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.606134076857801 shares for $48.3998060370954
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 67th day, sold 1.342552488151616 shares for $101.17475550710579
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 98th day, sold 0.6377551020408163 shares for $49.77678571428571
On the 121th day, Bought 0.6484243288808196 shares for $50.0
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 125th day, Bought 0.0 shares for $0.0
On the 135th day, sold 1.2940021210047705 shares for $100.73806512022138
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 200th day, Bought 0.6240639041437843 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 203th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2301979810015853 shares for $98.23130878297658
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 67th day, sold 0.6715916722632639 shares for $50.611148421759566
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 125th day, Bought 0.63500127000254 shares for $50.0
On the 135th day, sold 1.280579062126491 shares for $99.69307998654732
On the 201th day, Bought 0.6238303181534622 shares for $50.0
On the 202th day, Bought 0.6221226825930073 shares for $50.0
On the 203th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2459530007464696 shares for $99.48934710960559
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 70th day, sold 0.6693440428380187 shares for $50.595716198125835
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 137th day, sold 0.6455777921239509 shares for $51.16849580374436
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 0.6181998021760633 shares for $49.789812067260144
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 137th day, sold 0.6455777921239509 shares for $51.16849580374436
On the 203th day, Bought 0.6181998021760633 shares for $50.0
On the 207th day, sold 0.6181998021760633 shares for $49.789812067260144

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.55402406913034, Final Money: 101.55402406913034, Final Shares: 0.0
read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 69th day, Bought 0.6600660066006601 shares for $50.0
On the 75th day, sold 0.6600660066006601 shares for $50.085808580858085
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3015780808355715 shares for $101.97864263346702
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2437834227153124 shares for $100.98277609025621
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 205th day, sold 0.6093102607847916 shares for $48.653424323665604
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2086057108796324 shares for $96.3137890999979
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 53th day, sold 1.342552488151616 shares for $100.06043694193994
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.649772579597141 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.3015780808355715 shares for $101.64023233244978
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 148th day, Bought 0.6189650903689032 shares for $50.00000000000001
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 185th day, sold 1.2417076485953324 shares for $100.81424398945504
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 224th day, Bought 0.6039376736320812 shares for $50.00000000000001
On the 225th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 239th day, sold 1.2086057108796324 shares for $95.84243287275484
On the 31th day, Bought 0.6715014773032502 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.3424622931916024 shares for $99.6241267777488
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 138th day, sold 0.6518055012384305 shares for $50.64528744622605
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 1.2285852659910117 shares for $98.10253348938228
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 34th day, Bought 0.6637461834594451 shares for $50.0
On the 54th day, sold 1.3347069993477971 shares for $99.04860642160001
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 205th day, sold 1.2222774287555604 shares for $97.5988526861315
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 205th day, sold 0.6126700159294204 shares for $48.92170077196421
On the 113th day, Bought 0.6529119874640898 shares for $50.0
On the 139th day, sold 0.6529119874640898 shares for $51.08383389919039
On the 151th day, Bought 0.6126700159294204 shares for $50.0
On the 205th day, sold 0.6126700159294204 shares for $48.92170077196421

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 100.00553467115459, Final Money: 100.00553467115459, Final Shares: 0.0
read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 60th day, Bought 0.6813845734532571 shares for $50.0
On the 62th day, sold 0.6813845734532571 shares for $49.81602616516763
On the 84th day, Bought 0.6377551020408163 shares for $50.0
On the 93th day, sold 0.6377551020408163 shares for $48.56505102040816
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 122th day, Bought 0.6455777921239509 shares for $50.0
On the 124th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6455777921239509 shares for $50.58102001291155
On the 133th day, Bought 0.6367804381049414 shares for $50.0
On the 138th day, sold 0.6367804381049414 shares for $49.477840040753954
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 215th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 225th day, Bought 0.6069434328720563 shares for $50.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.6069434328720563 shares for $48.349113862588005
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 126th day, sold 0.6431695394906097 shares for $50.39233341908927
On the 157th day, Bought 0.6059871530723548 shares for $50.0
On the 164th day, Bought 0.0 shares for $0.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6059871530723548 shares for $49.36977336080475
On the 213th day, Bought 0.6201165819174005 shares for $50.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 0.6201165819174005 shares for $51.02939352598289
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 54th day, sold 1.342552488151616 shares for $99.63082014573142
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.6446621970087674 shares for $49.361784424961314
On the 124th day, Bought 0.6431695394906097 shares for $50.0
On the 126th day, sold 0.6431695394906097 shares for $50.39233341908927
On the 164th day, Bought 0.6036460219727152 shares for $50.0
On the 165th day, Bought 0.0 shares for $0.0
On the 166th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, sold 0.6036460219727152 shares for $49.17904141011711
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 126th day, sold 0.6446621970087674 shares for $50.50928313563692
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 181th day, sold 1.2056191664391671 shares for $98.22179348979894
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 149th day, sold 0.6446621970087674 shares for $52.33367715317174
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 176th day, Bought 0.6022645145748012 shares for $49.99999999999999
On the 181th day, sold 1.2056191664391671 shares for $98.22179348979894
On the 101th day, Bought 0.6446621970087674 shares for $50.0
On the 149th day, sold 0.6446621970087674 shares for $52.33367715317174
On the 175th day, Bought 0.6033546518643659 shares for $50.0
On the 181th day, sold 0.6033546518643659 shares for $49.15530348738989

[*********************100%***********************]  1 of 1 completed

XLP Final Value: 101.48898064056164, Final Money: 101.48898064056164, Final Shares: 0.0
read  5035  lines of data for ticker:  XLP

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLP
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 32th day, Bought 0.6709608158883521 shares for $49.99999999999999
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 41th day, sold 1.342552488151616 shares for $101.40298943009155
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.6509569066527796 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 1.3027624078912101 shares for $102.57951199735388
On the 132th day, Bought 0.6370238246910435 shares for $50.0
On the 134th day, Bought 0.6411078343377357 shares for $50.0
On the 136th day, Bought 0.0 shares for $0.0
On the 138th day, sold 1.2781316590287792 shares for $99.31082990653616
On the 146th day, Bought 0.6227425582264291 shares for $49.99999999999999
On the 147th day, Bought 0.6210408644888833 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 161th day, sold 1.2437834227153124 shares for $103.22158625114376
On the 178th day, Bought 0.6044487427466151 shares for $50.0
On the 179th day, Bought 0.60960741282614 shares for $49.99999999999999
On the 183th day, sold 1.214056155572755 shares for $98.41139197072752
On the 188th day, Bought 0.606134076857801 shares for $50.0
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 204th day, Bought 0.0 shares for $0.0
On the 214th day, Bought 0.0 shares for $0.0
On the 217th day, sold 1.2154443376425925 shares for $100.01891454460895
On the 221th day, Bought 0.6015399422521656 shares for $50.00000000000001
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2062079794997167 shares for $96.12271388633242
On the 30th day, Bought 0.6715916722632639 shares for $50.0
On the 54th day, sold 0.6715916722632639 shares for $49.83881799865681
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 169th day, sold 1.227685713783603 shares for $102.06979024396875
On the 190th day, Bought 0.6093102607847916 shares for $50.0
On the 196th day, Bought 0.616827041697508 shares for $50.0
On the 217th day, sold 1.2261373024822997 shares for $100.89883862126845
On the 222th day, Bought 0.6046680372475511 shares for $50.0
On the 223th day, Bought 0.606354596167839 shares for $50.00000000000001
On the 238th day, sold 1.2110226334153902 shares for $96.50639365687245
On the 33th day, Bought 0.6693440428380187 shares for $50.0
On the 54th day, sold 0.6693440428380187 shares for $49.67202141900937
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 103th day, Bought 0.0 shares for $0.0
On the 104th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6518055012384305 shares for $51.068961022031026
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.227685713783603 shares for $101.95929852972823
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 149th day, Bought 0.6159152500615914 shares for $49.99999999999999
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 185th day, sold 1.227685713783603 shares for $99.67580310209073
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.6417661404184315 shares for $49.99999999999999
On the 126th day, sold 1.293571641656862 shares for $101.35133812381513
On the 150th day, Bought 0.6117704637220115 shares for $50.0
On the 185th day, sold 0.6117704637220115 shares for $49.66964394959011
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 139th day, sold 0.6518055012384305 shares for $50.9972624168948
On the 102th day, Bought 0.6518055012384305 shares for $50.0
On the 217th day, sold 0.6518055012384305 shares for $53.63707469691045
XLP Final Value: 103.63707469691045, Final Money: 103.63707469691045, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 30th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 54th day, sold 0.6890405585234674 shares for $97.80930728240618
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.3485535029627048 shares for $50.08713837574068
On the 111th day, Bought 0.34220792553555535 shares for $49.99999999999999
On the 112th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.34220792553555535 shares for $49.41482444733419
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34055305816646236 shares for $46.41057076692549
On the 30th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6890405585234674 shares for $98.684388791731
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 148th day, Bought 0.3250975292587776 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.3250975292587776 shares for $47.71456436931079
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 30th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6890405585234674 shares for $98.684388791731
On the 81th day, Bought 0.3485535029627048 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3485535029627048 shares for $50.43917741373302
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.34073872154831675 shares for $46.435872972604606
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6838510315018442 shares for $97.94114473169412
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.32379225488926305 shares for $47.52298925009714
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3470776065528252 shares for $50.22560044425934
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 236th day, sold 0.34073872154831675 shares for $47.277497614828945
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6880421586636769 shares for $98.5413979638118
On the 82th day, Bought 0.3470776065528252 shares for $50.0
On the 96th day, sold 0.3470776065528252 shares for $50.37137303901152
On the 223th day, Bought 0.34073872154831675 shares for $50.0
On the 47th day, Bought 0.3442577802258331 shares for $50.0
On the 55th day, sold 0.3442577802258331 shares for $49.304599283943816

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.30459928394382, Final Money: 99.30459928394382, Final Shares: 0.0
read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 102th day, Bought 0.34234851078397804 shares for $50.0
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.6849785388796403 shares for $100.931587703915
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6735630619895059 shares for $98.89926439191916
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.33978933061501865 shares for $47.339449541284395
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6851745190905817 shares for $98.68568598461648
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3550379890648299 shares for $51.37754739757154
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6853774917644311 shares for $101.34676970720642
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6470402507516887 shares for $99.17832963521884
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.6780012584497679 shares for $99.55092477817942
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.34055305816646236 shares for $50.0
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6877579612666824 shares for $99.05777916124028
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 109th day, Bought 0.33992793527772114 shares for $50.0
On the 110th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.6825814440496509 shares for $100.93331813162189
On the 151th day, Bought 0.32303915234526426 shares for $50.0
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6446859841239713 shares for $98.81746764652232
On the 199th day, Bought 0.3375641371860653 shares for $49.99999999999999
On the 200th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3375641371860653 shares for $49.56454226302998
On the 221th day, Bought 0.33978933061501865 shares for $49.99999999999999
On the 222th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6890405585234674 shares for $99.242511644135
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.3536067892503536 shares for $51.170438472418674
On the 152th day, Bought 0.321646831778707 shares for $50.0
On the 153th day, Bought 0.32181244770547723 shares for $50.0
On the 154th day, Bought 0.0 shares for $0.0
On the 189th day, sold 0.6434592794841842 shares for $98.62943835933577
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.34043712126370257 shares for $49.98638251514945
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 53th day, sold 0.34525618008562353 shares for $49.72724761773236
On the 77th day, Bought 0.3507049168829347 shares for $50.0
On the 95th day, sold 0.3507049168829347 shares for $50.750508522129486
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 201th day, Bought 0.33843238121023417 shares for $50.0
On the 211th day, sold 0.6788695024739367 shares for $96.29085023090319
On the 42th day, Bought 0.34525618008562353 shares for $50.0
On the 54th day, sold 0.34525618008562353 shares for $49.00911476315426
On the 200th day, Bought 0.34043712126370257 shares for $50.0
On the 211th day, sold 0.34043712126370257 shares for $48.287601280043575

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 99.02877099103893, Final Money: 99.02877099103893, Final Shares: 0.0
read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, sold 0.6838510315018442 shares for $101.02531288376744
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 73th day, Bought 0.35566936975387675 shares for $50.0
On the 74th day, Bought 0.0 shares for $0.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7095264115090076 shares for $100.44055881321512
On the 103th day, Bought 0.3426300280956623 shares for $50.0
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.6853774917644311 shares for $101.6209207039122
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 183th day, sold 0.6422609724625596 shares for $97.48879301009192
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 207th day, sold 0.6759919900295339 shares for $100.92560411140943
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 232th day, sold 0.34458993797381116 shares for $47.97036526533425
On the 238th day, Bought 0.35816618911174786 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, sold 0.6838510315018442 shares for $101.02531288376744
On the 67th day, Bought 0.3538570417551309 shares for $50.0
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 76th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.7088950308199609 shares for $100.35118056287367
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 105th day, Bought 0.3431002538941879 shares for $50.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.6858477175629567 shares for $101.33400026992685
On the 154th day, Bought 0.321316110789795 shares for $50.00000000000001
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.6422609724625596 shares for $98.16958964090223
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 207th day, sold 0.6759919900295339 shares for $100.92560411140943
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 242th day, Bought 0.36334568708669424 shares for $50.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6838510315018442 shares for $98.49506406721062
On the 75th day, Bought 0.3550379890648299 shares for $50.0
On the 93th day, sold 0.3550379890648299 shares for $50.28403039125186
On the 104th day, Bought 0.34274746366876885 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.34274746366876885 shares for $50.6409377570606
On the 155th day, Bought 0.32094486167276465 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 188th day, sold 0.32094486167276465 shares for $49.05642210668208
On the 202th day, Bought 0.3406690740614567 shares for $50.0
On the 205th day, Bought 0.0 shares for $0.0
On the 211th day, sold 0.3406690740614567 shares for $48.32050146487702
On the 224th day, Bought 0.34458993797381116 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.3400666530640005 shares for $50.0
On the 46th day, Bought 0.34378437843784376 shares for $49.99999999999999
On the 47th day, Bought 0.0 shares for $0.0
On the 53th day, sold 0.6838510315018442 shares for $98.49506406721062
On the 108th day, Bought 0.34057625502349975 shares for $50.0
On the 125th day, sold 0.34057625502349975 shares for $51.27034943123765
On the 156th day, Bought 0.32026646169613116 shares for $50.0
On the 188th day, sold 0.32026646169613116 shares for $48.95272867025365
On the 205th day, Bought 0.33532291596807723 shares for $50.0
On the 211th day, sold 0.33532291596807723 shares for $47.56220240091208
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764
On the 41th day, Bought 0.3439735828288387 shares for $50.0
On the 53th day, sold 0.3439735828288387 shares for $49.54251513483764

[*********************100%***********************]  1 of 1 completed

XLV Final Value: 100.18042192728743, Final Money: 1.8056874688795972, Final Shares: 0.7079356250605053
read  5035  lines of data for ticker:  XLV

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLV
On the 34th day, Bought 0.3424188467333242 shares for $50.0
On the 36th day, sold 0.3424188467333242 shares for $50.14039172716066
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 40th day, Bought 0.3426065506372482 shares for $50.0
On the 42th day, sold 0.6839966912899862 shares for $99.0564008326158
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.34298257648511454 shares for $49.121964604198105
On the 68th day, Bought 0.3549623739883572 shares for $50.00000000000001
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3549623739883572 shares for $50.24847366179185
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3402054841124039 shares for $50.12927808396272
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.32379225488926305 shares for $49.608211371584
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3359989248034406 shares for $49.74128082790135
On the 219th day, Bought 0.3402517863218782 shares for $49.99999999999999
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3402517863218782 shares for $47.49914937053419
On the 34th day, Bought 0.3424188467333242 shares for $50.0
On the 36th day, sold 0.3424188467333242 shares for $50.14039172716066
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 40th day, Bought 0.3426065506372482 shares for $50.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6839966912899862 shares for $97.96200612655183
On the 76th day, Bought 0.3536067892503536 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 92th day, sold 0.3536067892503536 shares for $50.05657708628006
On the 100th day, Bought 0.3402054841124039 shares for $50.00000000000001
On the 101th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.3402054841124039 shares for $50.12927808396272
On the 149th day, Bought 0.32379225488926305 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 178th day, sold 0.32379225488926305 shares for $49.608211371584
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.3359989248034406 shares for $49.74128082790135
On the 219th day, Bought 0.3402517863218782 shares for $49.99999999999999
On the 220th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.3402517863218782 shares for $47.49914937053419
On the 34th day, Bought 0.3424188467333242 shares for $50.0
On the 36th day, sold 0.3424188467333242 shares for $50.14039172716066
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 43th day, Bought 0.34298257648511454 shares for $50.0
On the 44th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.6843727171378524 shares for $98.01586054848322
On the 106th day, Bought 0.34265350877192985 shares for $50.0
On the 121th day, sold 0.34265350877192985 shares for $50.48999451754386
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 179th day, sold 0.32324799586242564 shares for $49.42461856736488
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 55th day, sold 0.34139014065273793 shares for $48.89389594428513
On the 150th day, Bought 0.32324799586242564 shares for $50.0
On the 179th day, sold 0.32324799586242564 shares for $49.42461856736488
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 220th day, Bought 0.3391900142459806 shares for $50.0
On the 39th day, Bought 0.34139014065273793 shares for $50.0
On the 55th day, sold 0.34139014065273793 shares for $48.89389594428513
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 201th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
On the 197th day, Bought 0.3359989248034406 shares for $50.0
On the 209th day, sold 0.3359989248034406 shares for $49.33472212888919
XLV Final Value: 100.0, Final Money: 100, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 108th day, sold 0.2811041772080733 shares for $51.33243379996627
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.26893287435456115 shares for $53.84842943201377
On the 223th day, Bought 0.22109219544550077 shares for $50.0
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.44039044105953584 shares for $100.55434940712382
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 199th day, sold 0.5404948991210178 shares for $108.0719550792475
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.43407487791644056 shares for $99.11231687466088
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 154th day, Bought 0.26893287435456115 shares for $50.00000000000001
On the 176th day, Bought 0.24895439155546703 shares for $50.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.5178872659100282 shares for $103.26672082245963
On the 224th day, Bought 0.21929824561403508 shares for $50.0
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 235th day, sold 0.43407487791644056 shares for $99.3640803038524
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 55th day, sold 0.2711349709885581 shares for $48.48977821159373
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.500089566712886 shares for $109.74965631080995
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 236th day, sold 0.21477663230240548 shares for $49.220360824742265
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2711349709885581 shares for $49.18117238761455
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 207th day, sold 0.500089566712886 shares for $109.74965631080995
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 238th day, sold 0.21477663230240548 shares for $50.17182130584192
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 57th day, sold 0.2711349709885581 shares for $49.18117238761455
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 123th day, sold 0.2794076557697681 shares for $53.44230231908355
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.2794076557697681 shares for $50.0
On the 124th day, sold 0.2794076557697681 shares for $54.40067057837385
On the 177th day, Bought 0.2495383540450167 shares for $50.0
On the 178th day, Bought 0.2505512126678693 shares for $49.99999999999999

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 117.36090190748052, Final Money: 4.400670578373855, Final Shares: 0.500089566712886
read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.2756795500909742 shares for $49.99999999999999
On the 39th day, Bought 0.0 shares for $0.0
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.5468145210795323 shares for $97.65560531959368
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 121th day, Bought 0.26452227277536766 shares for $50.0
On the 125th day, sold 0.26452227277536766 shares for $50.642789122844135
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5427999546785756 shares for $108.99965889900476
On the 218th day, Bought 0.22611133722244833 shares for $50.0
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4533427496929082 shares for $103.51175003738174
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.2756795500909742 shares for $49.99999999999999
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5468145210795323 shares for $98.44301822994821
On the 82th day, Bought 0.2798298634430266 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2798298634430266 shares for $52.543653458697115
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 220th day, Bought 0.22492127755285649 shares for $50.0
On the 222th day, Bought 0.0 shares for $0.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.4521526900233164 shares for $103.24002371302383
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.2756795500909742 shares for $49.99999999999999
On the 41th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5468145210795323 shares for $98.44301822994821
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.28123066539175434 shares for $52.806682040609715
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 161th day, Bought 0.2741228070175438 shares for $49.99999999999999
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5413167363714689 shares for $108.70181383075467
On the 219th day, Bought 0.22723141247045991 shares for $50.0
On the 222th day, Bought 0.22314455304146028 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 234th day, sold 0.45037596551192016 shares for $102.83434420533673
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.2711349709885581 shares for $48.812428827070114
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5265973015977643 shares for $105.74600413384705
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 234th day, sold 0.21477663230240548 shares for $49.03994845360825
On the 31th day, Bought 0.2702410550210788 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.2702410550210788 shares for $48.65149713544482
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 126th day, sold 0.28123066539175434 shares for $53.29321109173745
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.5265973015977643 shares for $105.74600413384705
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 170th day, Bought 0.0 shares for $0.0
On the 196th day, sold 0.2594033722438392 shares for $52.09079118028535
On the 169th day, Bought 0.2594033722438392 shares for $50.00000000000001
On the 234th day, sold 0.2594033722438392 shares for $59.22957198443581

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 113.35345683752145, Final Money: 113.35345683752145, Final Shares: 0.0
read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 106th day, sold 0.2811041772080733 shares for $50.83769044808005
On the 144th day, Bought 0.2808988764044944 shares for $50.0
On the 147th day, sold 0.2808988764044944 shares for $51.44101123595506
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 198th day, sold 0.5397879783097215 shares for $108.08174689695552
On the 202th day, Bought 0.25075225677031093 shares for $50.0
On the 205th day, sold 0.25075225677031093 shares for $53.187061183550654
On the 240th day, Bought 0.22119000221190002 shares for $50.0
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 113th day, sold 0.2811041772080733 shares for $51.27340192275257
On the 144th day, Bought 0.2808988764044944 shares for $50.0
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5491248299477592 shares for $116.47486768021922
On the 240th day, Bought 0.22119000221190002 shares for $50.0
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 46th day, sold 0.27625835681529365 shares for $50.47792695729046
On the 51th day, Bought 0.2739425816348893 shares for $50.0
On the 55th day, sold 0.2739425816348893 shares for $48.99189129958361
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 144th day, Bought 0.2808988764044944 shares for $50.0
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5491248299477592 shares for $116.47486768021922
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 153th day, Bought 0.26822595354326484 shares for $50.0
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 160th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5397879783097215 shares for $114.49442807927502
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 55th day, sold 0.27625835681529365 shares for $49.40604453284712
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.5242531856296496 shares for $111.19934320390499
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 63th day, sold 0.27625835681529365 shares for $47.60760262997956
On the 81th day, Bought 0.2811041772080733 shares for $50.0
On the 116th day, sold 0.2811041772080733 shares for $52.782931354359924
On the 155th day, Bought 0.27156202476645663 shares for $50.0
On the 179th day, Bought 0.252691160863193 shares for $50.0
On the 205th day, sold 0.5242531856296496 shares for $111.19934320390499
On the 39th day, Bought 0.27625835681529365 shares for $50.0
On the 63th day, sold 0.27625835681529365 shares for $47.60760262997956

[*********************100%***********************]  1 of 1 completed

XLY Final Value: 118.72761729145323, Final Money: 118.72761729145323, Final Shares: 0.0
read  5035  lines of data for ticker:  XLY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLY
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.28123066539175434 shares for $49.48816018898701
On the 97th day, Bought 0.282326369282891 shares for $49.99999999999999
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.282326369282891 shares for $52.07509881422924
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.26400549131421935 shares for $50.02904060404457
On the 156th day, Bought 0.2712379299121189 shares for $50.0
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.0 shares for $0.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.538431859266044 shares for $106.2972176563024
On the 190th day, Bought 0.2515976450460424 shares for $50.0
On the 192th day, Bought 0.25257627803596683 shares for $49.99999999999999
On the 193th day, Bought 0.0 shares for $0.0
On the 201th day, sold 0.5041739230820093 shares for $100.88016026947923
On the 203th day, Bought 0.2463903809195289 shares for $50.0
On the 205th day, sold 0.2463903809195289 shares for $52.261863696841274
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 211th day, sold 0.2309148847734725 shares for $49.28647300604997
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 84th day, Bought 0.28123066539175434 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 97th day, Bought 0.0 shares for $0.0
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.28123066539175434 shares for $51.872996231509084
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 160th day, Bought 0.2671939293539251 shares for $50.00000000000001
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 168th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 185th day, sold 0.5269611778992285 shares for $104.03267574086568
On the 203th day, Bought 0.2463903809195289 shares for $50.0
On the 205th day, sold 0.2463903809195289 shares for $52.261863696841274
On the 208th day, Bought 0.2309148847734725 shares for $50.0
On the 211th day, sold 0.2309148847734725 shares for $49.28647300604997
On the 225th day, Bought 0.21477663230240548 shares for $50.0
On the 226th day, Bought 0.2154615185727829 shares for $50.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 30th day, Bought 0.2711349709885581 shares for $50.0
On the 31th day, Bought 0.0 shares for $0.0
On the 58th day, sold 0.2711349709885581 shares for $48.42199446884659
On the 85th day, Bought 0.2797985450475658 shares for $50.00000000000001
On the 98th day, Bought 0.0 shares for $0.0
On the 99th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 112th day, sold 0.2797985450475658 shares for $51.608841634023506
On the 118th day, Bought 0.26400549131421935 shares for $50.0
On the 119th day, Bought 0.2631301968213872 shares for $50.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5271356881356066 shares for $99.89221290169746
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.2597672485453034 shares for $55.099231088944315
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 98th day, Bought 0.28028476932563484 shares for $49.99999999999999
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 100th day, Bought 0.0 shares for $0.0
On the 101th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5617212209748524 shares for $106.44617137473453
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
On the 237th day, Bought 0.2132468972576449 shares for $50.0
On the 99th day, Bought 0.2814364516492176 shares for $50.0
On the 126th day, sold 0.2814364516492176 shares for $53.33220758752674
On the 166th day, Bought 0.2597672485453034 shares for $50.0
On the 167th day, Bought 0.2602133749674733 shares for $50.0
On the 205th day, sold 0.5199806235127767 shares for $110.29309005329509
XLY Final Value: 114.90747058058646, Final Money: 66.73926142802964, Final Shares: 0.2132468972576449

[*********************100%***********************]  1 of 1 completed

read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 34th day, sold 0.8051529790660226 shares for $50.869565217391305
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 42th day, Bought 0.7907638779060573 shares for $50.0
On the 43th day, Bought 0.0 shares for $0.0
On the 44th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 51th day, Bought 0.0 shares for $0.0
On the 57th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 62th day, sold 1.5786617663397162 shares for $99.09259907314399
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 103th day, sold 0.7015574575557738 shares for $49.1861933492353
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.7337833871441151 shares for $51.416201937188134
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, sold 1.3360068701989094 shares for $107.12103085254857
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 220th day, Bought 0.6029181237187989 shares for $50.0
On the 221th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 1.2241133032442058 shares for $93.62018543211686
On the 242th day, Bought 0.6555657532450505 shares for $50.0
On the 30th day, Bought 0.8051529790660226 shares for $50.0
On the 62th day, sold 0.8051529790660226 shares for $50.53945249597424
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 82th day, Bought 0.6996921354603974 shares for $49.99999999999999
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4012495930161712 shares for $98.18555898264312
On the 131th day, Bought 0.7094211123723042 shares for $50.0
On the 137th day, sold 0.7094211123723042 shares for $52.65323496027242
On the 149th day, Bought 0.6687174000267487 shares for $50.0
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 175th day, sold 1.3327280241967356 shares for $106.12513256678605
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.2601408843698723 shares for $96.14874947742125
On the 45th day, Bought 0.7840677434530343 shares for $50.0
On the 62th day, sold 0.7840677434530343 shares for $49.215932256546964
On the 81th day, Bought 0.7015574575557738 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 124th day, sold 0.7015574575557738 shares for $49.158131050933065
On the 150th day, Bought 0.6640106241699868 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 175th day, sold 0.6640106241699868 shares for $52.875166002656044
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 230th day, Bought 0.6439979392065945 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 62th day, sold 0.7829627309740056 shares for $49.14657062323833
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.6923289947382997 shares for $48.49764608141789
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 63th day, sold 0.7829627309740056 shares for $50.17225180081428
On the 86th day, Bought 0.6923289947382997 shares for $50.0
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.3784824186438849 shares for $96.56269342600413
On the 46th day, Bought 0.7829627309740056 shares for $50.0
On the 64th day, sold 0.7829627309740056 shares for $50.45411838396492
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 88th day, Bought 0.6943480072212193 shares for $50.0
On the 138th day, sold 1.3805014311268045 shares for $99.7550334132229
On the 47th day, Bought 0.7793017456359103 shares for $50.0
On the 138th day, sold 0.7793017456359103 shares for $56.31234413965088

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 106.31234413965089, Final Money: 106.31234413965089, Final Shares: 0.0
read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 64th day, sold 0.7862871520679352 shares for $50.66834407925774
On the 70th day, Bought 0.7554011179936546 shares for $50.0
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4669423162290325 shares for $106.67604523617524
On the 112th day, Bought 0.7255840951966334 shares for $50.0
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 1.4593674823407485 shares for $102.25787948761624
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 197th day, Bought 0.6172077521293667 shares for $50.0
On the 200th day, sold 0.6172077521293667 shares for $49.32107147265769
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 215th day, Bought 0.6105751618024179 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 217th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 220th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.2317703413278247 shares for $93.68845216139435
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 64th day, sold 0.7862871520679352 shares for $50.66834407925774
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 79th day, Bought 0.7008690776562938 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 94th day, sold 1.4124102758916717 shares for $102.71047526284237
On the 113th day, Bought 0.7337833871441151 shares for $50.0
On the 124th day, sold 0.7337833871441151 shares for $51.416201937188134
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 216th day, Bought 0.6138735420503376 shares for $50.0
On the 218th day, Bought 0.0 shares for $0.0
On the 219th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 240th day, sold 1.2350687215757445 shares for $93.56880634657841
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 64th day, sold 0.7862871520679352 shares for $50.66834407925774
On the 78th day, Bought 0.7115411982353779 shares for $50.0
On the 80th day, Bought 0.7015574575557738 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.4130986557911518 shares for $101.5876623648259
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 150th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 214th day, Bought 0.6211951795254069 shares for $50.0
On the 218th day, Bought 0.6031363088057901 shares for $50.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 95th day, sold 0.7862871520679352 shares for $56.52618336216386
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 229th day, Bought 0.6444129398118313 shares for $49.99999999999999
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 96th day, sold 0.7862871520679352 shares for $56.502594747601826
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 172th day, sold 1.346354675156112 shares for $108.15267105529047
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 139th day, sold 0.7862871520679352 shares for $57.29674477119044
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 202th day, sold 0.6672894701721607 shares for $51.51474709729081
On the 35th day, Bought 0.7862871520679352 shares for $50.0
On the 139th day, sold 0.7862871520679352 shares for $57.29674477119044

[*********************100%***********************]  1 of 1 completed

XLU Final Value: 114.65526580289229, Final Money: 114.65526580289229, Final Shares: 0.0
read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 50th day, sold 0.7827175954915466 shares for $51.38541014402004
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.7063144511936713 shares for $48.04350897019352
On the 117th day, Bought 0.7293946024799417 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7293946024799417 shares for $51.97665937272065
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 146th day, Bought 0.6746727836999056 shares for $50.0
On the 147th day, Bought 0.6716818914562064 shares for $50.0
On the 148th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 167th day, sold 1.346354675156112 shares for $106.5505089918547
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 184th day, sold 0.6140243153628884 shares for $48.3851160505956
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2216852740530135 shares for $97.6248702495763
On the 210th day, Bought 0.6403688524590164 shares for $50.0
On the 212th day, Bought 0.6254691018263698 shares for $50.0
On the 216th day, sold 1.2658379542853861 shares for $103.10250137654471
On the 232th day, Bought 0.651890482398957 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 235th day, sold 1.3195363630238734 shares for $100.85216422591466
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 89th day, Bought 0.7063144511936713 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 111th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 122th day, sold 0.7063144511936713 shares for $50.33196779206102
On the 130th day, Bought 0.7035317292809906 shares for $50.0
On the 136th day, sold 0.7035317292809906 shares for $52.1317011397214
On the 157th day, Bought 0.655393891728929 shares for $50.0
On the 168th day, sold 0.655393891728929 shares for $51.82854895792371
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 184th day, sold 0.6140243153628884 shares for $48.3851160505956
On the 194th day, Bought 0.6088650754992694 shares for $50.00000000000001
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 200th day, sold 1.2216852740530135 shares for $97.6248702495763
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 235th day, sold 0.6676458806249166 shares for $51.02817465616238
On the 238th day, Bought 0.6553079947575361 shares for $50.0
On the 239th day, Bought 0.6572029442691903 shares for $50.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 178th day, Bought 0.6140243153628884 shares for $50.00000000000001
On the 185th day, sold 0.6140243153628884 shares for $48.23775021490851
On the 195th day, Bought 0.6128201985537443 shares for $49.99999999999999
On the 196th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 239th day, Bought 0.0 shares for $0.0
On the 240th day, Bought 0.0 shares for $0.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.7878978884336589 shares for $50.0
On the 51th day, sold 0.7878978884336589 shares for $51.41033722029624
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 62th day, sold 0.7623113279463333 shares for $47.85028205519134
On the 105th day, Bought 0.7228567297961543 shares for $50.0
On the 122th day, sold 0.7228567297961543 shares for $51.510770565273965
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 233th day, Bought 0.6676458806249166 shares for $50.00000000000001
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 63th day, sold 0.7623113279463333 shares for $48.84890989480103
On the 196th day, Bought 0.6220452848967405 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.7623113279463333 shares for $50.0
On the 63th day, sold 0.7623113279463333 shares for $48.84890989480103
On the 241th day, Bought 0.6605892456070815 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

On the 242th day, Bought 0.6555657532450505 shares for $50.0
XLU Final Value: 109.07106575651298, Final Money: 7.902722576332906, Final Shares: 1.3125109390267264

read  5035  lines of data for ticker:  XLU

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLU
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 103th day, Bought 0.713165026387106 shares for $50.0
On the 119th day, Bought 0.7265329845975008 shares for $50.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 133th day, sold 1.439698010984607 shares for $102.92401080528954
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.352185047296217 shares for $108.28297858748105
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 185th day, Bought 0.6364562118126272 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 189th day, sold 1.270973978310089 shares for $104.48677075687242
On the 218th day, Bought 0.6031363088057901 shares for $50.0
On the 221th day, Bought 0.6161429451632778 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 71th day, Bought 0.7452675510508272 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 93th day, sold 0.7452675510508272 shares for $53.25681919809211
On the 121th day, Bought 0.7068136839129207 shares for $50.0
On the 133th day, sold 0.7068136839129207 shares for $50.53011026293469
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 146th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.352185047296217 shares for $108.28297858748105
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 225th day, Bought 0.6274312962730582 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.7843137254901961 shares for $50.0
On the 62th day, sold 0.7843137254901961 shares for $49.23137254901961
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.0 shares for $0.0
On the 145th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 171th day, sold 0.6780580417683755 shares for $54.29888798481151
On the 184th day, Bought 0.6345177664974619 shares for $50.0
On the 191th day, sold 0.6345177664974619 shares for $51.99873096446701
On the 224th day, Bought 0.6196554715578139 shares for $50.0
On the 37th day, Bought 0.7803964413922273 shares for $50.0
On the 66th day, sold 0.7803964413922273 shares for $51.529577025128766
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 143th day, Bought 0.6780580417683755 shares for $50.00000000000001
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 145th day, Bought 0.0 shares for $0.0
On the 147th day, Bought 0.0 shares for $0.0
On the 148th day, Bought 0.0 shares for $0.0
On the 171th day, sold 1.352185047296217 shares for $108.28297858748105
On the 39th day, Bought 0.7827175954915466 shares for $50.0
On the 66th day, sold 0.7827175954915466 shares for $51.682842830306825
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 148th day, Bought 0.6672894701721607 shares for $50.00000000000001
On the 172th day, sold 1.3414164757000022 shares for $107.75598549298118
On the 40th day, Bought 0.7890168849613381 shares for $50.0
On the 66th day, sold 0.7890168849613381 shares for $52.09878491399716
On the 87th day, Bought 0.6861534239055852 shares for $50.0
On the 94th day, sold 0.6861534239055852 shares for $49.897076986414156
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
On the 144th day, Bought 0.6741270055278414 shares for $50.0
On the 172th day, sold 0.6741270055278414 shares for $54.1526223540515
XLU Final Value: 112.16399679269048, Final Money: 18.18195189675474, Final Shares: 1.2192792539690678

[*********************100%***********************]  1 of 1 completed

read  7553  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 59th day, sold 0.09840969925995907 shares for $50.9762242166588
On the 81th day, Bought 0.09598587087980649 shares for $50.0
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.19153335798089574 shares for $105.85282562172183
On the 154th day, Bought 0.08903768074649192 shares for $50.0
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 156th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.1785952662739861 shares for $101.76536867558
On the 221th day, Bought 0.08283219853221344 shares for $49.99999999999999
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.0 shares for $0.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.1656259923094319 shares for $97.90980535372066
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 59th day, sold 0.09840969925995907 shares for $50.9762242166588
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1899262858477388 shares for $104.96466113661131
On the 155th day, Bought 0.08955758552749418 shares for $50.0
On the 175th day, Bought 0.08736676568233445 shares for $50.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 203th day, sold 0.17692435120982863 shares for $102.03227334270818
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.16507664932143729 shares for $97.58506124636764
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 82th day, Bought 0.09554748710108925 shares for $50.0
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.1899262858477388 shares for $104.26763166755012
On the 176th day, Bought 0.08749365670988853 shares for $50.0
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.17463810735127167 shares for $103.2181069688956
On the 222th day, Bought 0.08279379377721846 shares for $50.0
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.0 shares for $0.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.16507664932143729 shares for $98.16943258496555
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.09457337948514251 shares for $50.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.18895217823179206 shares for $103.73285632747152
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17507663733900194 shares for $104.27739596548295
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.1647013436594728 shares for $99.034917942441
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 177th day, Bought 0.08714445064138315 shares for $50.0
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17507663733900194 shares for $104.27739596548295
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.1647013436594728 shares for $99.034917942441
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.09437879874664956 shares for $51.81301672392314
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 179th day, Bought 0.08789508842245895 shares for $50.0
On the 205th day, sold 0.17582727512007773 shares for $104.7244833342695
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.1647013436594728 shares for $99.04150599618738
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 178th day, Bought 0.08793218669761879 shares for $50.0
On the 205th day, sold 0.08793218669761879 shares for $52.37328971896873
On the 223th day, Bought 0.08228285554421881 shares for $50.0
On the 224th day, Bought 0.08241848811525401 shares for $50.0
On the 225th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 107.31776510234558, Final Money: 107.31776510234558, Final Shares: 0.0
read  7553  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 47th day, Bought 0 shares for $0.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 81th day, Bought 0 shares for $0.0
On the 82th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 90th day, Bought 0 shares for $0.0
On the 91th day, Bought 0 shares for $0.0
On the 92th day, Bought 0 shares for $0.0
On the 93th day, Bought 0 shares for $0.0
On the 104th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 106th day, Bought 0 shares for $0.0
On the 107th day, Bought 0 shares for $0.0
On the 108th day, Bought 0 shares for $0.0
On the 109th day, Bought 0 shares for $0.0
On the 110th day, Bought 0 shares for $0.0
On the 111th day, Bought 0 shares for $0.0
On the 112th day, Bought 0 shares for $0.0
On the 113th day, Bought 0 shares for $0.0
On the 114th day, Bought 0 shares for $0.0
On the 115th day, Bought 0 shares for $0.0
On the 116th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 118th day, Bought 0 shares for $0.0
On the 119th day, Bought 0 shares for $0.0
On the 120th day, Bought 0 shares for $0.0
On the 121th day, Bought 0 shares for $0.0
On the 156th day, Bought 0 shares for $0.0
On the 157th day, Bought 0 shares for $0.0
On the 158th day, Bought 0 shares for $0.0
On the 169th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 171th day, Bought 0 shares for $0.0
On the 173th day, Bought 0 shares for $0.0
On the 174th day, Bought 0 shares for $0.0
On the 175th day, Bought 0 shares for $0.0
On the 176th day, Bought 0 shares for $0.0
On the 177th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 184th day, Bought 0 shares for $0.0
On the 191th day, Bought 0 shares for $0.0
On the 192th day, Bought 0 shares for $0.0
On the 193th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 200th day, Bought 0 shares for $0.0
On the 219th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 229th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 60th day, sold 0.09840969925995907 shares for $50.272594866950094
On the 81th day, Bought 0 shares for $0.0
On the 82th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 90th day, Bought 0 shares for $0.0
On the 91th day, Bought 0 shares for $0.0
On the 92th day, Bought 0 shares for $0.0
On the 105th day, Bought 0 shares for $0.0
On the 106th day, Bought 0 shares for $0.0
On the 107th day, Bought 0 shares for $0.0
On the 110th day, Bought 0 shares for $0.0
On the 114th day, Bought 0 shares for $0.0
On the 115th day, Bought 0 shares for $0.0
On the 116th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 118th day, Bought 0 shares for $0.0
On the 119th day, Bought 0 shares for $0.0
On the 120th day, Bought 0 shares for $0.0
On the 121th day, Bought 0 shares for $0.0
On the 170th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 194th day, Bought 0 shares for $0.0
On the 195th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 200th day, Bought 0 shares for $0.0
On the 220th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 226th day, Bought 0 shares for $0.0
On the 227th day, Bought 0 shares for $0.0
On the 228th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 82th day, Bought 0 shares for $0.0
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 89th day, Bought 0 shares for $0.0
On the 91th day, Bought 0 shares for $0.0
On the 92th day, Bought 0 shares for $0.0
On the 115th day, Bought 0 shares for $0.0
On the 116th day, Bought 0 shares for $0.0
On the 117th day, Bought 0 shares for $0.0
On the 118th day, Bought 0 shares for $0.0
On the 119th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 183th day, Bought 0 shares for $0.0
On the 196th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 200th day, Bought 0 shares for $0.0
On the 221th day, Bought 0 shares for $0.0
On the 222th day, Bought 0 shares for $0.0
On the 223th day, Bought 0 shares for $0.0
On the 224th day, Bought 0 shares for $0.0
On the 225th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 182th day, Bought 0 shares for $0.0
On the 197th day, Bought 0 shares for $0.0
On the 198th day, Bought 0 shares for $0.0
On the 199th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 35th day, Bought 0 shares for $0.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 88th day, Bought 0 shares for $0.0
On the 178th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 34th day, Bought 0 shares for $0.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0 shares for $0.0
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0
On the 86th day, Bought 0 shares for $0.0
On the 87th day, Bought 0 shares for $0.0
On the 179th day, Bought 0 shares for $0.0
On the 180th day, Bought 0 shares for $0.0
On the 181th day, Bought 0 shares for $0.0
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 33th day, Bought 0 shares for $0.0
On the 62th day, sold 0.09840969925995907 shares for $49.55223586836719
On the 84th day, Bought 0 shares for $0.0
On the 85th day, Bought 0 shares for $0.0

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 100.2725948669501, Final Money: 100.2725948669501, Final Shares: 0.0
read  7553  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 62th day, sold 0.09749439407234084 shares for $49.09135224724578
On the 89th day, Bought 0.09506426344208685 shares for $50.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09506426344208685 shares for $52.83861890638072
On the 156th day, Bought 0.08954956568460642 shares for $50.0
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.0 shares for $0.0
On the 159th day, Bought 0.0 shares for $0.0
On the 160th day, Bought 0.0 shares for $0.0
On the 161th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17825237578963055 shares for $101.56998624868937
On the 31th day, Bought 0.09749439407234084 shares for $50.0
On the 62th day, sold 0.09749439407234084 shares for $49.09135224724578
On the 90th day, Bought 0.09443940767603505 shares for $50.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 113th day, Bought 0.0 shares for $0.0
On the 114th day, Bought 0.0 shares for $0.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09443940767603505 shares for $52.49131157449381
On the 157th day, Bought 0.08870281010502414 shares for $50.0
On the 158th day, Bought 0.09056658455296333 shares for $50.0
On the 159th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 202th day, sold 0.17926939465798747 shares for $102.14949377006783
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 114th day, Bought 0.09168592071001576 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 119th day, sold 0.09168592071001576 shares for $50.960868449040966
On the 32th day, Bought 0.09759906304899474 shares for $50.0
On the 62th day, sold 0.09759906304899474 shares for $49.14405621706032
On the 115th day, Bought 0.09107302234931969 shares for $50.0
On the 121th day, sold 0.09107302234931969 shares for $50.680315476949424

[*********************100%***********************]  1 of 1 completed

SPY Final Value: 103.73215759180742, Final Money: 103.73215759180742, Final Shares: 0.0
read  7553  lines of data for ticker:  SPY

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  SPY
On the 30th day, Bought 0.09840969925995907 shares for $50.0
On the 61th day, sold 0.09840969925995907 shares for $49.642772791686355
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 93th day, Bought 0.0 shares for $0.0
On the 100th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 105th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.09437879874664956 shares for $52.159386915323346
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 202th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17663179810615176 shares for $105.20366527000505
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 220th day, Bought 0.0 shares for $0.0
On the 221th day, Bought 0.0 shares for $0.0
On the 222th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17663179810615176 shares for $105.20366527000505
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 83th day, Bought 0.09437879874664956 shares for $50.0
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 91th day, Bought 0.0 shares for $0.0
On the 92th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884769619505038 shares for $104.16367779156543
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.17663179810615176 shares for $105.20366527000505
On the 218th day, Bought 0.08324315325064514 shares for $50.00000000000001
On the 219th day, Bought 0.08349615082744685 shares for $50.0
On the 238th day, sold 0.166739304078092 shares for $100.26701311431985
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 88th day, Bought 0.09436989222958307 shares for $50.0
On the 92th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.1884680554334373 shares for $104.15875551584345
On the 169th day, Bought 0.08906305664410404 shares for $50.0
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 218th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.17663179810615176 shares for $103.89835628200059
On the 87th day, Bought 0.09409816320385425 shares for $49.99999999999999
On the 126th day, sold 0.09409816320385425 shares for $52.00429087624209
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 172th day, Bought 0.08777011252128426 shares for $50.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.175338853983332 shares for $103.13782069007554
On the 170th day, Bought 0.08756874146204771 shares for $50.00000000000001
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 175th day, Bought 0.0 shares for $0.0
On the 176th day, Bought 0.0 shares for $0.0
On the 177th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.08756874146204771 shares for $51.509685102805705
On the 173th day, Bought 0.08751969193068442 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 240th day, sold 0.08751969193068442 shares for $51.48083318746719
SPY Final Value: 109.63435617589033, Final Money: 109.63435617589033, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  6299  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 32th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0890283040146238 shares for $97.99076679523586
On the 122th day, Bought 0.5524861878453039 shares for $50.0
On the 125th day, sold 0.5524861878453039 shares for $50.73480662983425
On the 148th day, Bought 0.5494505494505495 shares for $50.00000000000001
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 206th day, sold 1.1009008637772286 shares for $104.00210460103479
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 52th day, Bought 0.0 shares for $0.0
On the 56th day, sold 0.5710370031978073 shares for $53.015075376884425
On the 81th day, Bought 0.5447809980387884 shares for $50.0
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 97th day, sold 1.0890283040146238 shares for $98.66596434372491
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0966471303772733 shares for $101.6372560433657
On the 30th day, Bought 0.5710370031978073 shares for $50.00000000000001
On the 58th day, sold 0.5710370031978073 shares for $52.31269986295112
On the 82th day, Bought 0.5442473059758354 shares for $50.0
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.0875484034440523 shares for $97.99898663434355
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.039887877886485 shares for $96.37680852251944
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 127th day, sold 0.5433010974682169 shares for $48.95686189286102
On the 187th day, Bought 0.5184570717544588 shares for $50.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 209th day, sold 0.5184570717544588 shares for $48.05060141020324
On the 83th day, Bought 0.5433010974682169 shares for $50.0
On the 133th day, sold 0.5433010974682169 shares for $49.706617407367155
On the 192th day, Bought 0.5161023947151115 shares for $50.00000000000001
On the 228th day, sold 0.5161023947151115 shares for $46.774360033030554

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 104.20799404470054, Final Money: 104.20799404470054, Final Shares: 0.0
read  6299  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 32th day, Bought 0.5643340857787811 shares for $50.0
On the 33th day, Bought 0.5673436968115284 shares for $49.99999999999999
On the 35th day, Bought 0.0 shares for $0.0
On the 55th day, sold 1.1316777825903095 shares for $104.98574789090301
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 71th day, Bought 0.0 shares for $0.0
On the 73th day, sold 1.127982205935974 shares for $100.49193472683594
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 1.0844228128268467 shares for $98.67163173911477
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 121th day, sold 1.1197107302364473 shares for $100.37086985839514
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0966471303772733 shares for $106.28703987616534
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 209th day, sold 1.0554195515497262 shares for $97.81628403762863
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 225th day, Bought 0.5440104450005441 shares for $50.00000000000001
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.078769803289314 shares for $91.18841147204571
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 88th day, Bought 0.5471656817684395 shares for $50.0
On the 95th day, sold 1.0889948971997354 shares for $99.08764569620392
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 121th day, sold 0.5619240278714318 shares for $50.370869858395146
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 210th day, sold 1.0554195515497262 shares for $97.01416517845084
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, sold 1.0938814610365155 shares for $92.46579990141666
On the 68th day, Bought 0.5659950192438307 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 73th day, sold 0.5659950192438307 shares for $50.424496264432875
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 105th day, Bought 0.5577867023650156 shares for $50.0
On the 121th day, sold 0.5577867023650156 shares for $50.0
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 169th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 189th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 226th day, Bought 0.0 shares for $0.0
On the 227th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 0.5514503143266791 shares for $47.1931179000772
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 191th day, Bought 0.5121376626037079 shares for $49.99999999999999
On the 192th day, Bought 0.0 shares for $0.0
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 235th day, sold 1.0635879769303869 shares for $91.0218590657025
On the 192th day, Bought 0.5161023947151115 shares for $50.00000000000001
On the 228th day, Bought 0.0 shares for $0.0
On the 229th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.5161023947151115 shares for $43.90483071841454
On the 228th day, Bought 0.5516936996579499 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 236th day, sold 1.1201985319490242 shares for $95.29528911290348
On the 229th day, Bought 0.5555555555555556 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 236th day, sold 1.12406038784663 shares for $95.6238171941128
XLB Final Value: 99.81191960108856, Final Money: 99.81191960108856, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  6299  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 49th day, Bought 0.5397236614853195 shares for $49.99999999999999
On the 56th day, Bought 0.0 shares for $0.0
On the 57th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0913564946715506 shares for $97.66549270815706
On the 67th day, Bought 0.5663797009515179 shares for $50.0
On the 68th day, Bought 0.0 shares for $0.0
On the 81th day, sold 0.5663797009515179 shares for $51.98232895333032
On the 86th day, Bought 0.541829215431296 shares for $50.0
On the 87th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 106th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.541829215431296 shares for $47.198742956220194
On the 145th day, Bought 0.5614823133071308 shares for $50.0
On the 162th day, sold 0.5614823133071308 shares for $50.9601347557552
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 173th day, Bought 0.0 shares for $0.0
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 184th day, Bought 0.5260389268805892 shares for $50.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 197th day, sold 1.053966284076239 shares for $99.85276575338287
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 217th day, sold 0.5343593031954686 shares for $50.79619536176125
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 226th day, sold 1.0643081826903797 shares for $97.799278907419
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 42th day, Bought 0.5516328331862312 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 58th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0901937982874808 shares for $97.56144300874665
On the 106th day, Bought 0.5584096493187402 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5584096493187402 shares for $48.64306455215545
On the 165th day, Bought 0.5443065534509035 shares for $49.99999999999999
On the 176th day, sold 0.5443065534509035 shares for $52.754191160461566
On the 180th day, Bought 0.5279273571956499 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 197th day, sold 0.5279273571956499 shares for $50.015837820715866
On the 215th day, Bought 0.5343593031954686 shares for $50.0
On the 218th day, sold 0.5343593031954686 shares for $50.416800256492465
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 227th day, sold 0.5295488244016098 shares for $48.16246557932641
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 56th day, Bought 0.5385609651012494 shares for $49.99999999999999
On the 57th day, Bought 0.0 shares for $0.0
On the 61th day, sold 1.0846509607325294 shares for $97.06541447595406
On the 106th day, Bought 0.5584096493187402 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5584096493187402 shares for $48.64306455215545
On the 186th day, Bought 0.5214308061320263 shares for $50.0
On the 197th day, sold 0.5214308061320263 shares for $49.40035457294817
On the 222th day, Bought 0.5295488244016098 shares for $49.99999999999999
On the 223th day, Bought 0.0 shares for $0.0
On the 228th day, sold 0.5295488244016098 shares for $47.99300995551789
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 44th day, Bought 0.54608999563128 shares for $50.0
On the 61th day, sold 0.54608999563128 shares for $48.869593709043244
On the 106th day, Bought 0.5584096493187402 shares for $50.0
On the 107th day, Bought 0.0 shares for $0.0
On the 115th day, sold 0.5584096493187402 shares for $48.64306455215545
On the 223th day, Bought 0.5347593582887701 shares for $50.0
On the 228th day, sold 0.5347593582887701 shares for $48.46524064171123
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001
On the 240th day, Bought 0.5966587112171838 shares for $50.00000000000001

[*********************100%***********************]  1 of 1 completed

XLB Final Value: 100.0, Final Money: 100, Final Shares: 0.0
read  6299  lines of data for ticker:  XLB

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLB
On the 69th day, Bought 0.5619871866921434 shares for $50.0
On the 70th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5619871866921434 shares for $49.80892435652467
On the 85th day, Bought 0.5425935973955507 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5425935973955507 shares for $49.66359196961476
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 105th day, Bought 0.0 shares for $0.0
On the 107th day, Bought 0.0 shares for $0.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 112th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.5619240278714318 shares for $51.09013261407058
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 150th day, Bought 0.5451968160505943 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 163th day, sold 1.0966471303772733 shares for $99.57555943825642
On the 168th day, Bought 0.5334471353888829 shares for $49.99999999999999
On the 169th day, Bought 0.5357334190506804 shares for $50.0
On the 171th day, Bought 0.0 shares for $0.0
On the 176th day, sold 1.0691805544395634 shares for $103.62497933628248
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 190th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.0 shares for $0.0
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.5441288497116117 shares for $46.218304494504295
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5585344057193924 shares for $51.12265415549599
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 110th day, Bought 0.0 shares for $0.0
On the 126th day, sold 1.119772962379967 shares for $101.8097577395866
On the 149th day, Bought 0.5514503143266791 shares for $50.0
On the 176th day, sold 0.5514503143266791 shares for $53.446564464541744
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 182th day, Bought 0.5269259142164612 shares for $50.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0523015578016246 shares for $96.05408619613229
On the 226th day, Bought 0.5441288497116117 shares for $50.0
On the 227th day, Bought 0.5497526113249038 shares for $50.00000000000001
On the 230th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 237th day, Bought 0.0 shares for $0.0
On the 240th day, sold 1.0938814610365155 shares for $91.66726643486
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 71th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 107th day, Bought 0.5578489345085351 shares for $50.0
On the 108th day, Bought 0.0 shares for $0.0
On the 109th day, Bought 0.0 shares for $0.0
On the 127th day, sold 1.119772962379967 shares for $100.90274164005884
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 211th day, sold 1.0547562682543004 shares for $96.27815216625254
On the 230th day, Bought 0.5603496581867085 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 236th day, Bought 0.0 shares for $0.0
On the 70th day, Bought 0.5585344057193924 shares for $50.00000000000001
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.5585344057193924 shares for $50.82104557640751
On the 104th day, Bought 0.5619240278714318 shares for $50.00000000000001
On the 128th day, sold 0.5619240278714318 shares for $50.80355135985615
On the 181th day, Bought 0.5253756435851634 shares for $50.00000000000001
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 216th day, sold 1.0547562682543004 shares for $99.24201728004712
On the 231th day, Bought 0.5653550429669832 shares for $50.0
On the 232th day, Bought 0.5685048322910744 shares for $49.99999999999999
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 235th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
On the 184th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.541829215431296 shares for $50.0
On the 95th day, sold 0.541829215431296 shares for $49.301040312093626
On the 183th day, Bought 0.529380624669137 shares for $49.99999999999999
XLB Final Value: 96.0355784053855, Final Money: 96.0355784053855, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  6299  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 33th day, Bought 0.5757052389176742 shares for $50.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 42th day, Bought 0.0 shares for $0.0
On the 43th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.144792423074287 shares for $110.0488956301312
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.094935722669386 shares for $100.50414998382296
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 179th day, sold 1.1014041492712865 shares for $99.91938442189111
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.0 shares for $0.0
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 227th day, sold 1.0958842465766088 shares for $98.90355325353895
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 235th day, sold 0.5730002292000916 shares for $48.21223928489571
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 33th day, Bought 0.5757052389176742 shares for $50.0
On the 35th day, Bought 0.5690871841566127 shares for $49.99999999999999
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 45th day, Bought 0.0 shares for $0.0
On the 46th day, Bought 0.0 shares for $0.0
On the 47th day, Bought 0.0 shares for $0.0
On the 48th day, Bought 0.0 shares for $0.0
On the 49th day, Bought 0.0 shares for $0.0
On the 50th day, Bought 0.0 shares for $0.0
On the 60th day, sold 1.144792423074287 shares for $110.0488956301312
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 82th day, Bought 0.5336179295624333 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 96th day, sold 1.0679201308875026 shares for $95.9953405654776
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 128th day, sold 1.1036056965369934 shares for $101.29996688513063
On the 152th day, Bought 0.5531585352361987 shares for $50.00000000000001
On the 153th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 179th day, sold 1.1014041492712865 shares for $99.91938442189111
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1103815969501716 shares for $93.1943274320279
On the 242th day, Bought 0.5769674590353104 shares for $50.0
On the 36th day, Bought 0.5670863105364636 shares for $50.0
On the 37th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5670863105364636 shares for $54.51400703187025
On the 83th day, Bought 0.5324246619103397 shares for $49.99999999999999
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 117th day, Bought 0.0 shares for $0.0
On the 129th day, sold 1.066327491595337 shares for $96.32136231580678
On the 188th day, Bought 0.5569169079973267 shares for $49.99999999999999
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.1103815969501716 shares for $93.1943274320279
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 47th day, Bought 0.0 shares for $0.0
On the 60th day, sold 0.5612932195779076 shares for $53.95711719802425
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.108588481558596 shares for $93.04383125721297
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.5612932195779076 shares for $50.00000000000001
On the 61th day, sold 0.5612932195779076 shares for $53.45195330040414
On the 192th day, Bought 0.5551237926057512 shares for $50.00000000000001
On the 193th day, Bought 0.5538325210456357 shares for $49.99999999999999
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 105.10740923312879, Final Money: 3.58356313975753, Final Shares: 1.160670470942852
read  6299  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 40th day, Bought 0.0 shares for $0.0
On the 41th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 70th day, Bought 0.5222477543346564 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 73th day, sold 1.0568927500574965 shares for $97.2658397877914
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 84th day, Bought 0.5339028296849972 shares for $49.99999999999999
On the 95th day, sold 1.0682050310100668 shares for $96.95028861447366
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 104th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 120th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.5636978579481398 shares for $50.924464487034946
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 157th day, Bought 0.5477651183172656 shares for $50.00000000000001
On the 171th day, Bought 0.0 shares for $0.0
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1115901070407657 shares for $97.59761139817923
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 184th day, sold 0.5490282200505107 shares for $50.30196552102779
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 200th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5569789461958338 shares for $51.871449259218
On the 212th day, Bought 0.5208875924575477 shares for $50.0
On the 213th day, Bought 0.5242189138184106 shares for $50.0
On the 216th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.0451065062759581 shares for $87.71578907174117
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 40th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 81th day, Bought 0.5343022013250694 shares for $50.0
On the 95th day, sold 0.5343022013250694 shares for $48.4932677922633
On the 103th day, Bought 0.5636978579481398 shares for $50.0
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 127th day, Bought 0.0 shares for $0.0
On the 132th day, sold 1.118636814662901 shares for $103.12712794377285
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 171th day, Bought 0.5633168093735916 shares for $49.99999999999999
On the 172th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.127141798097092 shares for $98.96304987292467
On the 183th day, Bought 0.5490282200505107 shares for $50.0
On the 189th day, sold 0.5490282200505107 shares for $49.527835730756564
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 213th day, Bought 0.0 shares for $0.0
On the 231th day, Bought 0.0 shares for $0.0
On the 236th day, sold 1.117517062787762 shares for $93.79320707977686
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 32th day, Bought 0.579979120751653 shares for $50.00000000000001
On the 56th day, Bought 0.0 shares for $0.0
On the 61th day, sold 0.579979120751653 shares for $55.23141166917992
On the 117th day, Bought 0.5549389567147615 shares for $50.00000000000001
On the 132th day, sold 0.5549389567147615 shares for $51.15982241953386
On the 149th day, Bought 0.5638249887235002 shares for $50.0
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 177th day, sold 1.1248662813626384 shares for $98.76325950363965
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 212th day, Bought 0.0 shares for $0.0
On the 238th day, sold 1.117517062787762 shares for $94.50841799996103
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 242th day, Bought 0.0 shares for $0.0
On the 56th day, Bought 0.5130309870716192 shares for $50.00000000000001
On the 61th day, sold 0.5130309870716192 shares for $48.8559408988303
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 173th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5610412926391383 shares for $49.259425493716336
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 238th day, sold 0.5569789461958338 shares for $47.10370947978166
On the 172th day, Bought 0.5610412926391383 shares for $50.00000000000001
On the 179th day, sold 0.5610412926391383 shares for $50.89766606822262
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 198th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 197th day, Bought 0.5605381165919282 shares for $50.0

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 100.71941404386712, Final Money: 49.66291159231446, Final Shares: 0.5837030119075415
read  6299  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 59th day, Bought 0.511665984445354 shares for $50.0
On the 60th day, Bought 0.5201289919900135 shares for $49.99999999999999
On the 63th day, sold 1.0317949764353676 shares for $97.12286113186114
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.0 shares for $0.0
On the 74th day, sold 0.5201831044527674 shares for $48.14814814814815
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 103th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5299417064122947 shares for $48.484366719660834
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 149th day, Bought 0.0 shares for $0.0
On the 160th day, sold 0.5489679402722881 shares for $47.81510759771629
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 176th day, sold 0.5736576411197798 shares for $50.0172097292336
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5387350501023597 shares for $50.172395216032754
On the 211th day, Bought 0.5278158978148422 shares for $50.0
On the 226th day, sold 0.5278158978148422 shares for $47.96263063443471
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 31th day, Bought 0.5737893045673629 shares for $50.0
On the 39th day, sold 0.5737893045673629 shares for $51.84760156070691
On the 67th day, Bought 0.5201831044527674 shares for $50.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0548281001756075 shares for $97.63488895225423
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 102th day, Bought 0.0 shares for $0.0
On the 110th day, sold 0.5299417064122947 shares for $48.484366719660834
On the 114th day, Bought 0.5482456140350876 shares for $49.99999999999999
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.5482456140350876 shares for $51.10745614035087
On the 148th day, Bought 0.5489679402722881 shares for $50.0
On the 162th day, sold 0.5489679402722881 shares for $47.55709266578832
On the 174th day, Bought 0.5736576411197798 shares for $50.00000000000001
On the 176th day, sold 0.5736576411197798 shares for $50.0172097292336
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5387350501023597 shares for $50.172395216032754
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 241th day, Bought 0.0 shares for $0.0
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 79th day, Bought 0.5299417064122947 shares for $50.0
On the 102th day, Bought 0.0 shares for $0.0
On the 111th day, sold 0.5299417064122947 shares for $48.00741918388977
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 125th day, sold 0.546268982847154 shares for $50.92319458101169
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 240th day, Bought 0.5913660555884093 shares for $50.0
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 196th day, Bought 0.5569789461958338 shares for $49.99999999999999
On the 205th day, sold 1.1137718192470587 shares for $103.72556952647857
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571
On the 195th day, Bought 0.5567928730512249 shares for $50.0
On the 205th day, sold 0.5567928730512249 shares for $51.854120267260576
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 126th day, sold 0.546268982847154 shares for $51.01606030809571

[*********************100%***********************]  1 of 1 completed

XLE Final Value: 104.74162983457427, Final Money: 104.74162983457427, Final Shares: 0.0
read  6299  lines of data for ticker:  XLE

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLE
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 59th day, sold 0.5152514427040396 shares for $50.35037098103874
On the 71th day, Bought 0.5187260089220873 shares for $49.99999999999999
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 1.0533710046449274 shares for $97.50002018993447
On the 80th day, Bought 0.5328786102525844 shares for $49.99999999999999
On the 82th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.5328786102525844 shares for $49.66428647554087
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, Bought 0.0 shares for $0.0
On the 127th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 146th day, Bought 0.5520591807441758 shares for $50.0
On the 147th day, Bought 0.0 shares for $0.0
On the 149th day, Bought 0.0 shares for $0.0
On the 177th day, sold 0.5520591807441758 shares for $48.47079606933863
On the 184th day, Bought 0.545732372844357 shares for $49.99999999999999
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.545732372844357 shares for $49.46518227461252
On the 191th day, Bought 0.5534646889528448 shares for $50.00000000000001
On the 192th day, Bought 0.0 shares for $0.0
On the 193th day, Bought 0.0 shares for $0.0
On the 194th day, Bought 0.0 shares for $0.0
On the 195th day, Bought 0.0 shares for $0.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 224th day, sold 0.5534646889528448 shares for $51.24529555014391
On the 231th day, Bought 0.5730002292000916 shares for $50.0
On the 233th day, Bought 0.0 shares for $0.0
On the 237th day, sold 0.5730002292000916 shares for $48.498739399495754
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 115th day, Bought 0.548666739822232 shares for $50.0
On the 116th day, Bought 0.0 shares for $0.0
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.548666739822232 shares for $49.56655327554044
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 188th day, Bought 0.0 shares for $0.0
On the 190th day, sold 0.5387350501023597 shares for $48.83094494127788
On the 194th day, Bought 0.5567308762943993 shares for $50.00000000000001
On the 224th day, sold 0.5567308762943993 shares for $51.547711836098436
On the 233th day, Bought 0.5948839976204641 shares for $50.0
On the 237th day, sold 0.5948839976204641 shares for $50.35098155859608
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 56th day, Bought 0.0 shares for $0.0
On the 68th day, sold 0.5152514427040396 shares for $49.562036273701565
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 186th day, Bought 0.5387350501023597 shares for $50.0
On the 187th day, Bought 0.0 shares for $0.0
On the 226th day, sold 0.5387350501023597 shares for $48.954854002801426
On the 241th day, Bought 0.5837030119075415 shares for $50.0
On the 54th day, Bought 0.5152514427040396 shares for $50.0
On the 74th day, sold 0.5152514427040396 shares for $47.691673536685904
On the 116th day, Bought 0.546268982847154 shares for $50.00000000000001
On the 117th day, Bought 0.0 shares for $0.0
On the 130th day, sold 0.546268982847154 shares for $49.34993991041189
On the 187th day, Bought 0.5389673385792821 shares for $50.0
On the 226th day, sold 0.5389673385792821 shares for $48.97596205669937
On the 72th day, Bought 0.5346449957228401 shares for $50.0
On the 74th day, sold 0.5346449957228401 shares for $49.48674080410608
XLE Final Value: 100.40147114087313, Final Money: 49.34496868932047, Final Shares: 0.5837030119075415

[*********************100%***********************]  1 of 1 completed

read  6299  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 52th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 81th day, Bought 1.200192030724916 shares for $50.0
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.3943644692250357 shares for $98.62387248737922
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 121th day, Bought 0.0 shares for $0.0
On the 122th day, Bought 0.0 shares for $0.0
On the 124th day, sold 2.4044597264558503 shares for $104.56995350356493
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 165th day, sold 2.2812835348939844 shares for $101.24336327859503
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 201th day, sold 2.132716457189094 shares for $99.46989556329935
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 32th day, Bought 1.0 shares for $40.39
On the 33th day, Bought 0.0 shares for $0.0
On the 34th day, Bought 0.0 shares for $0.0
On the 35th day, Bought 0.0 shares for $0.0
On the 36th day, Bought 0.0 shares for $0.0
On the 37th day, Bought 0.0 shares for $0.0
On the 38th day, Bought 0.0 shares for $0.0
On the 39th day, Bought 0.0 shares for $0.0
On the 53th day, Bought 0.0 shares for $0.0
On the 55th day, sold 2.2394645513138323 shares for $93.09454139811601
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 96th day, sold 2.379568360738147 shares for $98.01442077880426
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 120th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.4044597264558503 shares for $105.36342521329536
On the 151th day, Bought 1.1350737797956867 shares for $49.99999999999999
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 202th day, sold 2.2604395236624435 shares for $104.61314115509789
On the 30th day, Bought 1.2394645513138323 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 56th day, sold 2.2394645513138323 shares for $93.4976450173525
On the 82th day, Bought 1.1941724385001196 shares for $50.0
On the 83th day, Bought 1.1853959222380275 shares for $50.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.379568360738147 shares for $104.2726855675456
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 1.1133377866844802 shares for $50.00000000000001
On the 202th day, sold 2.2294092152559086 shares for $103.17705848204345
On the 33th day, Bought 1.2376237623762376 shares for $50.0
On the 56th day, sold 1.2376237623762376 shares for $51.67079207920792
On the 84th day, Bought 1.1853959222380275 shares for $50.0
On the 85th day, Bought 1.1767474699929394 shares for $50.0
On the 119th day, Bought 0.0 shares for $0.0
On the 125th day, sold 2.362143392230967 shares for $103.50912344756097

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 110.69552854531354, Final Money: 110.69552854531354, Final Shares: 0.0
read  6299  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 37th day, Bought 1.228803145736053 shares for $50.0
On the 38th day, Bought 1.0 shares for $40.86
On the 39th day, Bought 0.0 shares for $0.0
On the 53th day, sold 2.228803145736053 shares for $92.8296510199066
On the 71th day, Bought 1.2266928361138372 shares for $50.0
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 75th day, Bought 0.0 shares for $0.0
On the 76th day, Bought 0.0 shares for $0.0
On the 77th day, Bought 0.0 shares for $0.0
On the 78th day, Bought 0.0 shares for $0.0
On the 79th day, Bought 0.0 shares for $0.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 90th day, sold 2.462481269134104 shares for $102.46384560867006
On the 115th day, Bought 1.199616122840691 shares for $50.0
On the 117th day, Bought 1.203659123736158 shares for $50.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 127th day, sold 2.403275246576849 shares for $102.98034431581799
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 150th day, Bought 1.1415525114155252 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 186th day, sold 2.2812835348939844 shares for $106.10249720791921
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 197th day, Bought 0.25 shares for $11.8025
On the 201th day, sold 2.371791173519794 shares for $110.6203403329632
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 91th day, sold 1.2330456226880395 shares for $50.739827373612826
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 127th day, sold 1.2068549360366885 shares for $51.7137340091721
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.255802452049888 shares for $105.57155475593474
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 202th day, sold 1.0590976488032195 shares for $49.015039186613
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 197th day, Bought 1.0590976488032195 shares for $49.99999999999999
On the 204th day, sold 1.0590976488032195 shares for $52.478288498199525
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 95th day, sold 1.2330456226880395 shares for $51.02342786683108
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 95th day, sold 1.2330456226880395 shares for $51.02342786683108
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 128th day, sold 1.2174336498660823 shares for $52.45921597272949

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 112.33417848527706, Final Money: 112.33417848527706, Final Shares: 0.0
read  6299  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 94th day, sold 1.2388503468780971 shares for $51.58572844400397
On the 100th day, Bought 1.2100677637947725 shares for $50.0
On the 101th day, Bought 1.2239902080783354 shares for $50.0
On the 112th day, Bought 0.0 shares for $0.0
On the 123th day, sold 2.434057971873108 shares for $104.66449279054363
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 173th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2414371724381854 shares for $104.89925967010707
On the 72th day, Bought 1.2388503468780971 shares for $50.0
On the 123th day, sold 1.2388503468780971 shares for $53.27056491575818
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 167th day, Bought 0.0 shares for $0.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.2414371724381854 shares for $104.89925967010707
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 123th day, sold 1.2174336498660823 shares for $52.349646944241535
On the 152th day, Bought 1.1253657438667568 shares for $50.00000000000001
On the 167th day, Bought 1.1088933244621866 shares for $50.0
On the 174th day, Bought 0.0 shares for $0.0
On the 178th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.234259068328943 shares for $104.56332439779453
On the 76th day, Bought 1.2174336498660823 shares for $50.0
On the 123th day, sold 1.2174336498660823 shares for $52.349646944241535
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 187th day, sold 1.1138338159946535 shares for $52.12742258854978
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 187th day, sold 1.1138338159946535 shares for $52.12742258854978
On the 180th day, Bought 1.1138338159946535 shares for $49.99999999999999
On the 187th day, sold 1.1138338159946535 shares for $52.12742258854978

[*********************100%***********************]  1 of 1 completed

XLF Final Value: 111.14948090465467, Final Money: 111.14948090465467, Final Shares: 0.0
read  6299  lines of data for ticker:  XLF

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLF
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 118th day, Bought 1.2068549360366885 shares for $50.0
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 2.4044597264558503 shares for $103.60816961298259
On the 149th day, Bought 1.1397310234784592 shares for $50.0
On the 154th day, Bought 1.1160714285714286 shares for $50.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 187th day, sold 2.255802452049888 shares for $105.57155475593474
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 199th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.121791173519794 shares for $99.10886571510959
On the 230th day, Bought 1.0092854259184498 shares for $50.00000000000001
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 234th day, Bought 0.0 shares for $0.0
On the 240th day, sold 2.020407771722292 shares for $97.54528721875225
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 119th day, Bought 1.1976047904191616 shares for $49.99999999999999
On the 128th day, sold 1.1976047904191616 shares for $51.604790419161674
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 203th day, sold 2.121791173519794 shares for $99.10886571510959
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 241th day, sold 2.029452284704046 shares for $98.08342891974655
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 194th day, Bought 1.0613457864572278 shares for $50.0
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 0.0 shares for $0.0
On the 197th day, Bought 0.0 shares for $0.0
On the 198th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.121791173519794 shares for $105.13475264790578
On the 231th day, Bought 1.0111223458038423 shares for $50.00000000000001
On the 232th day, Bought 1.0183299389002036 shares for $50.0
On the 242th day, sold 2.029452284704046 shares for $97.83989464558206
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 90th day, sold 1.2357884330202669 shares for $51.4211566979733
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 197th day, Bought 0.0 shares for $0.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 74th day, Bought 1.2357884330202669 shares for $50.0
On the 91th day, sold 1.2357884330202669 shares for $50.85269401878398
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
On the 195th day, Bought 1.0604453870625663 shares for $50.0
On the 196th day, Bought 1.072271070126528 shares for $50.0
On the 204th day, sold 2.132716457189094 shares for $105.6761004537196
On the 75th day, Bought 1.2330456226880395 shares for $50.0
On the 92th day, sold 1.2330456226880395 shares for $50.332922318125775
XLF Final Value: 107.25503400075246, Final Money: 107.25503400075246, Final Shares: 0.0

[*********************100%***********************]  1 of 1 completed

read  6299  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 50th day, sold 0.4132231404958678 shares for $52.049586776859506
On the 78th day, Bought 0.40209087253719344 shares for $50.0
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.0 shares for $0.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 90th day, Bought 0.0 shares for $0.0
On the 95th day, sold 0.8002117420331725 shares for $97.62583252804704
On the 121th day, Bought 0.4049566696363489 shares for $50.0
On the 122th day, Bought 0.0 shares for $0.0
On the 123th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.4049566696363489 shares for $50.84635943953997
On the 148th day, Bought 0.39142007202129325 shares for $50.0
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.7839155583232007 shares for $104.91141917039396
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 225th day, Bought 0.35571997723392146 shares for $50.0
On the 231th day, Bought 0.0 shares for $0.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 236th day, sold 0.7105312176540179 shares for $94.58591569410287
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 55th day, sold 0.4132231404958678 shares for $51.929752066115704
On the 79th day, Bought 0.39812086949597897 shares for $50.0
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.0 shares for $0.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7959566428887224 shares for $96.86792343955752
On the 122th day, Bought 0.40264132710581413 shares for $50.0
On the 126th day, sold 0.40264132710581413 shares for $50.55564503140602
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 186th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 224th day, Bought 0.35481124042009654 shares for $50.0
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 236th day, sold 0.7216760140645313 shares for $96.06951099227041
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.0 shares for $0.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 200th day, sold 0.3924954863019075 shares for $52.527670931784286
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.399616368286445 shares for $50.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 96th day, sold 0.7991369435960733 shares for $97.25496603564213
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 205th day, sold 0.39013732833957554 shares for $54.84550561797754
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662
On the 84th day, Bought 0.39939292275740873 shares for $50.0
On the 85th day, Bought 0.3989467804994814 shares for $50.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 127th day, sold 0.7983397032568902 shares for $99.68867874568788
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 56th day, sold 0.4132231404958678 shares for $51.83884297520662

[*********************100%***********************]  1 of 1 completed

XLI Final Value: 103.93931462882628, Final Money: 103.93931462882628, Final Shares: 0.0
read  6299  lines of data for ticker:  XLI

[*********************100%***********************]  1 of 1 completed

read  251  lines of data for ticker:  XLI
On the 30th day, Bought 0.4132231404958678 shares for $50.0
On the 52th day, sold 0.4132231404958678 shares for $51.40909090909091
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 114th day, Bought 0.41473125414731254 shares for $50.0
On the 115th day, Bought 0.0 shares for $0.0
On the 116th day, Bought 0.0 shares for $0.0
On the 118th day, Bought 0.0 shares for $0.0
On the 119th day, Bought 0.0 shares for $0.0
On the 126th day, sold 0.41473125414731254 shares for $52.073656270736564
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 150th day, Bought 0.39013732833957554 shares for $50.0
On the 151th day, Bought 0.0 shares for $0.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 170th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 180th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 184th day, Bought 0.0 shares for $0.0
On the 185th day, Bought 0.0 shares for $0.0
On the 201th day, Bought 0.0 shares for $0.0
On the 204th day, sold 0.782632814641483 shares for $110.68775897474495
On the 228th day, Bought 0.3605422555523507 shares for $50.0
On the 231th day, Bought 0.3635041802980734 shares for $50.0
On the 232th day, Bought 0.0 shares for $0.0
On the 233th day, Bought 0.0 shares for $0.0
On the 239th day, sold 0.7240464358504242 shares for $96.48642804142752
On the 31th day, Bought 0.41145490454246214 shares for $50.0
On the 52th day, sold 0.41145490454246214 shares for $51.18910467412771
On the 66th day, Bought 0.4119294776734223 shares for $50.0
On the 73th day, sold 0.4119294776734223 shares for $49.93409128357225
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 81th day, Bought 0.3995205753096284 shares for $50.0
On the 82th day, Bought 0.0 shares for $0.0
On the 83th day, Bought 0.0 shares for $0.0
On the 84th day, Bought 0.0 shares for $0.0
On the 85th day, Bought 0.0 shares for $0.0
On the 86th day, Bought 0.0 shares for $0.0
On the 87th day, Bought 0.0 shares for $0.0
On the 88th day, Bought 0.0 shares for $0.0
On the 89th day, Bought 0.0 shares for $0.0
On the 94th day, sold 0.7973563487023718 shares for $98.48148262822994
On the 115th day, Bought 0.4124731892426992 shares for $50.0
On the 126th day, sold 0.4124731892426992 shares for $51.79013364131331
On the 149th day, Bought 0.3924954863019075 shares for $50.0
On the 151th day, Bought 0.390625 shares for $50.0
On the 152th day, Bought 0.0 shares for $0.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0
On the 179th day, Bought 0.0 shares for $0.0
On the 181th day, Bought 0.0 shares for $0.0
On the 182th day, Bought 0.0 shares for $0.0
On the 183th day, Bought 0.0 shares for $0.0
On the 205th day, sold 0.7831204863019074 shares for $110.09107796432215
On the 232th day, Bought 0.3668647736444347 shares for $50.0
On the 240th day, sold 0.3668647736444347 shares for $48.39680093917382
On the 80th day, Bought 0.39783577339274345 shares for $50.0
On the 95th day, sold 0.39783577339274345 shares for $48.5359643539147
On the 152th day, Bought 0.38675742574257427 shares for $50.0
On the 153th day, Bought 0.0 shares for $0.0
On the 154th day, Bought 0.0 shares for $0.0
On the 155th day, Bought 0.0 shares for $0.0
On the 156th day, Bought 0.0 shares for $0.0
On the 157th day, Bought 0.0 shares for $0.0
On the 158th day, Bought 0.0 shares for $0.0

In [14]:
runtest_num = 50000 
for file in os.listdir('../output'):
    if "runtest_bollinger" in file:
        runtest_num+=1
#get stock
#loop over "metrics"
#loop over "thresholds"
#call bollinger bands method with metric as parameter
#for each point (vertical:m, horizontal:t) -> final portfolio value
os.mkdir(f'../output/runtest_bollinger_{runtest_num}')
root0 = f'../output/runtest_bollinger_{runtest_num}'
start, end = '2019-01-05', '2024-01-05'
metrics = ["sd","atr","mad","iqr","mad_med","iqr_med"]
periods = [14,50]
stocks = ['NVDA', 'LIN', 'XOM', 'JPM', 'GE', 'AAPL', 'WMT', 'LLY', 'AMZN', 'NEE']

for etf in stocks:
    root1=os.path.join(root0,f"{etf}")
    os.mkdir(root1)
    df = get_cleaned_df(etf,start,end)
    for T in periods:
        root2 = os.path.join(root1, f"{T}_period")
        os.mkdir(root2)
        results_df = pd.DataFrame({"metric":[],"1":[],"1.25":[],"1.5":[],"1.75":[],"2":[],"2.25":[],"2.5":[]})
        trades_df = pd.DataFrame({"metric":[],"1":[],"1.25":[],"1.5":[],"1.75":[],"2":[],"2.25":[],"2.5":[]})
        sharpe_df = pd.DataFrame({"metric":[],"1":[],"1.25":[],"1.5":[],"1.75":[],"2":[],"2.25":[],"2.5":[]})
        for metric in metrics:
            final_values = [metric]
            trades = [metric]
            sharpes = [metric]
            for buy,sell in factors:
                results = bollinger_bands_backtest(df,metric,buy, sell,T)
                #print(results)
                print(etf,buy,sell)
                final_value = results["final_value"]
                num_trades = len(results["trades"])
                sharpe=0
                if num_trades>0:
                    sharpe = int(results["sharpe"]*1000000)/1000000
                #print(results)
                final_values.append(int(final_value)) # should have n+1 values for metric and number of factors
                trades.append(num_trades)
                sharpes.append(sharpe)
            #print(final_values)
            results_df.loc[len(results_df)] =  final_values # table has n+1 columns
            trades_df.loc[len(trades_df)] = trades
            sharpe_df.loc[len(sharpe_df)] = sharpes
        results_df.to_csv(os.path.join(root2,f"results_{etf}_{T}.csv"))
        trades_df.to_csv(os.path.join(root2,f"trades_{etf}_{T}.csv"))
        sharpe_df.to_csv(os.path.join(root2,f"sharpes_{etf}_{T}.csv"))
df

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  NVDA
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25
NVDA 2.5 2.5
NVDA 1.0 1.0
NVDA 1.25 1.25
NVDA 1.5 1.5
NVDA 1.75 1.75
NVDA 2.0 2.0
NVDA 2.25 2.25

[*********************100%***********************]  1 of 1 completed

NVDA 2.5 2.5
read  1258  lines of data for ticker:  LIN

LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25
LIN 2.5 2.5
LIN 1.0 1.0
LIN 1.25 1.25
LIN 1.5 1.5
LIN 1.75 1.75
LIN 2.0 2.0
LIN 2.25 2.25

[*********************100%***********************]  1 of 1 completed

LIN 2.5 2.5
read  1258  lines of data for ticker:  XOM

XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5
XOM 1.0 1.0
XOM 1.25 1.25
XOM 1.5 1.5
XOM 1.75 1.75
XOM 2.0 2.0
XOM 2.25 2.25
XOM 2.5 2.5

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  JPM
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5
JPM 1.0 1.0
JPM 1.25 1.25
JPM 1.5 1.5
JPM 1.75 1.75
JPM 2.0 2.0
JPM 2.25 2.25
JPM 2.5 2.5

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  GE
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5
GE 1.0 1.0
GE 1.25 1.25
GE 1.5 1.5
GE 1.75 1.75
GE 2.0 2.0
GE 2.25 2.25
GE 2.5 2.5

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  AAPL
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5
AAPL 1.0 1.0
AAPL 1.25 1.25
AAPL 1.5 1.5
AAPL 1.75 1.75
AAPL 2.0 2.0
AAPL 2.25 2.25
AAPL 2.5 2.5

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  WMT
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5
WMT 1.0 1.0
WMT 1.25 1.25
WMT 1.5 1.5
WMT 1.75 1.75
WMT 2.0 2.0
WMT 2.25 2.25
WMT 2.5 2.5

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  LLY
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5
LLY 1.0 1.0
LLY 1.25 1.25
LLY 1.5 1.5
LLY 1.75 1.75
LLY 2.0 2.0
LLY 2.25 2.25
LLY 2.5 2.5

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  AMZN
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5
AMZN 1.0 1.0
AMZN 1.25 1.25
AMZN 1.5 1.5
AMZN 1.75 1.75
AMZN 2.0 2.0
AMZN 2.25 2.25
AMZN 2.5 2.5

[*********************100%***********************]  1 of 1 completed

read  1258  lines of data for ticker:  NEE
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5
NEE 1.0 1.0
NEE 1.25 1.25
NEE 1.5 1.5
NEE 1.75 1.75
NEE 2.0 2.0
NEE 2.25 2.25
NEE 2.5 2.5

Price,index,Date,Open,High,Low,Close,Volume,Adj Close,TR,ATR,Returns,SD_Returns,SR,SD_Squared_Returns,SD_Prices,IQR
0,0,2019-01-16,43.51,43.73,43.21,43.67,7059200,37.01,0.011905,0.828571,-0.000229,0.014898,5.242449e-08,0.000256,0.397732,0.013311
1,1,2019-01-17,43.78,43.98,43.61,43.87,8200800,37.18,0.008473,0.801429,0.004580,0.014780,2.087894e-05,0.000260,0.415239,0.012002
2,2,2019-01-18,44.10,44.15,43.78,44.02,7414400,37.31,0.008434,0.784286,0.003419,0.014556,1.165103e-05,0.000260,0.408126,0.009015
3,3,2019-01-22,43.86,44.49,43.81,44.35,8654400,37.58,0.015448,0.772857,0.007497,0.013753,5.578047e-05,0.000264,0.478485,0.005240
4,4,2019-01-23,44.49,44.87,44.05,44.85,9089200,38.01,0.018489,0.801429,0.011274,0.014223,1.256838e-04,0.000256,0.633685,0.007790
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1246,0,2023-12-28,60.12,61.10,60.12,61.02,5981900,57.89,0.016177,1.242857,0.007263,0.013222,5.237234e-05,0.000292,0.729194,0.008228
1247,1,2023-12-29,60.80,61.06,60.27,60.74,6814600,57.62,0.012947,1.218571,-0.004589,0.012638,2.115282e-05,0.000296,0.545296,0.011004
1248,2,2024-01-02,60.55,62.15,60.18,61.57,10064300,58.41,0.032433,1.222857,0.013665,0.006613,1.842068e-04,0.000061,0.699496,0.008228
1249,3,2024-01-03,61.11,62.12,60.46,61.99,10306300,58.81,0.026961,1.232857,0.006822,0.005587,4.621746e-05,0.000059,0.769236,0.003150
1250,4,2024-01-04,62.17,62.76,61.73,61.80,10568100,58.63,0.016616,1.198571,-0.003065,0.006441,9.423164e-06,0.000058,0.670224,0.005941

In [14]:
results["signals"].iloc[30:40]

     price        ma  metric_value  lower_band  upper_band
30  253.64  249.1820        2.2335    246.9485    251.4155
31  252.72  249.6045        2.3840    247.2205    251.9885
32  252.37  249.9235        2.3180    247.6055    252.2415
33  250.84  250.1145        2.3495    247.7650    252.4640
34  248.74  250.2170        2.4415    247.7755    252.6585
35  248.25  250.4125        2.3485    248.0640    252.7610
36  251.85  250.7730        2.4190    248.3540    253.1920
37  252.80  251.1745        2.4275    248.7470    253.6020
38  254.47  251.5020        2.3770    249.1250    253.8790
39  254.31  251.7810        2.3440    249.4370    254.1250